{
  "hash": "b0c59cb3646d4858b60c5d4d3a6206fc",
  "result": {
    "engine": "knitr",
    "markdown": "# Networks and Graph Data {#sec-network-graph}\n\nMost of the data structures the preceding chapters relied on are *rectangular*: a\ncustomer is a row, an attribute is a column, and rows are treated as exchangeable draws\nfrom a population. Network data violate that convenience at the root. The unit of\nanalysis is not the isolated individual but the *relation* between individuals, and the\ninformative quantity is the pattern of relations across the whole system. A customer\nwho buys, adopts, churns, or recommends does so embedded in a web of friends,\nco-purchasers, followers, and referrers, and that embedding carries marketing signal\nthat no amount of demographic enrichment recovers. The object that encodes this\nstructure is a **graph**: a set of *nodes* (consumers, products, brands, sellers) and a\nset of *edges* (friendships, co-purchases, referrals, co-mentions) connecting them.\n\nThis chapter treats the graph as a first-class marketing data type, parallel to text\n(@sec-text-as-data) and images (@sec-image-processing) in the unstructured-and-\nmultimodal family. As with those modalities, the analytic arc is the same: an\nunstructured artifact (here, a relational structure rather than a document or a photo)\nis turned into machine-readable features, and those features are then used for\ndescription, prediction, or causal claims. And as with those modalities, the central\neconometric caution recurs in a network-specific and unusually severe form: a feature\nextracted from the graph, such as a node's centrality or its neighbors' behavior, is a\n*generated regressor* whose error is correlated with the outcome in ways that mimic the\nvery effect the analyst wants to measure. The identification of social influence is the\nhardest version of this problem in all of empirical marketing, and it earns its own\nsection below.\n\nThe chapter proceeds from use to method to practice. It opens with the marketing\n*applications* that motivate graph thinking. It then develops the formal\n*representation* of a graph and the *centrality* measures that summarize a node's\nposition, with a runnable `igraph` demonstration on simulated data, and the\nego-network measures of *brokerage and structural holes*. It treats\n*community detection*, the unsupervised discovery of cohesive subgroups. It then\nconfronts the *contagion-versus-homophily* identification problem head on, because no\nhonest account of network marketing can avoid it. It develops *diffusion* models and\nsimulates an independent-cascade process over a graph. It surveys the learned-\nrepresentation frontier, *graph embeddings* and *graph neural networks*, keeping the\ndeep-learning specifics conceptual but clearly labeled. It closes with *industry and\nproduction* practice (recommendation, fraud, influencer selection) and a *frontier*\nsection on where the field is moving. @fig-net-workflow previews the shared analytic\narc these sections instantiate: relational data become a graph, the graph yields\nfeatures, and those features serve description, prediction, or causal claims.\n\n```{mermaid}\n%%| label: fig-net-workflow\n%%| fig-cap: \"The shared analytic arc of network data. Relational records become a graph of nodes and edges, the graph yields features such as centrality, community, and embeddings, and those features serve description, prediction, or causal claims.\"\nflowchart LR\n  RD[\"Relational data<br/>(friendships, co-purchases, referrals, co-mentions)\"]\n  RD --> GR[\"Graph<br/>(nodes and edges)\"]\n  GR --> FE[\"Network features<br/>(centrality, community, embeddings)\"]\n  FE --> US[\"Uses<br/>(description, prediction, causal claims)\"]\n```\n\n## Why Networks Matter in Marketing {#sec-graph-applications}\n\nThe marketing relevance of graph structure is not a single idea but a family of them,\nunified by the premise that a consumer's value, behavior, and reachability depend on\nthe consumers around them.\n\n**Social networks, word of mouth, and contagion.** The oldest motivation is that\nproducts spread through social ties. A consumer is more likely to adopt when adopters\nsit nearby in the social graph, whether because of genuine influence, shared exposure,\nor similarity. The word-of-mouth literature in marketing has long modeled this spread\nformally; @goldenberg2001 used a complex-systems simulation of the underlying\nperson-to-person process to show how the structure of \"weak\" and \"strong\" ties governs\nthe macro-level diffusion curve, and a large empirical literature, surveyed below,\nestimates contagion from observed adoption sequences over real ties. The contagion\npremise is also what makes *misinformation* a network phenomenon: @vosoughi2018 showed\nthat false news diffuses faster, farther, and more broadly than true news through the\nTwitter retweet graph, a finding that is fundamentally about diffusion structure rather\nthan content alone.\n\n**Co-purchase and recommendation graphs.** A second, entirely different graph arises\nwithout any social tie at all. Connect two products when they are frequently bought\ntogether, or connect a customer to every product they purchased, and the resulting\nco-purchase (or bipartite customer-product) graph is the substrate of modern\nrecommendation. \"Customers who bought this also bought that\" is a statement about the\nneighborhood of a node in a co-purchase graph, and item-to-item collaborative\nfiltering, the algorithm that powered Amazon's recommendations, is literally a\ncomputation over this graph (Linden, Smith and York 2003, *IEEE Internet Computing*\n7(1), 76--80, doi:10.1109/MIC.2003.1167344). The graph here is a tool for *prediction\nand retrieval*, and the identification anxieties of the social-contagion literature are\nlargely absent.\n\n**Customer-referral networks and seeding.** Referral programs make the graph a managed\nasset: a firm rewards existing customers for recruiting new ones, and the chain of\nwho-referred-whom is a directed network whose structure determines program value. The\nadjacent question, *whom to seed* with free product or early access to maximize spread,\nturns network position into a targeting variable. @hinz2011 compared seeding strategies\nempirically and found that seeding well-connected \"hubs\" outperforms seeding random or\n\"fringe\" customers, a result that operationalizes centrality as a marketing decision\nvariable. The structure of referral and affiliate networks on the commercial web has\nitself been modeled as an outcome of strategic link formation by @katona2008.\n\n**Influencer identification.** Closely related is the problem of finding the\nindividuals whose activity moves the system. The naive answer, \"the most connected\nperson,\" is both intuitive and contested. @trusov2010 developed a method to identify\ngenuinely influential users in an internet social network by modeling whose activity\npredicts others' subsequent activity, distinguishing influence from mere connectedness.\n@watts2007influentials (Watts and Dodds 2007, *Journal of Consumer Research* 34(4),\n441--458, doi:10.1086/518527) challenged the \"influentials hypothesis\" itself,\narguing through simulation that large cascades are often driven by a critical mass of\neasily influenced ordinary people rather than by rare special individuals, a caution\nthat remains central to how marketers should read centrality.\n\n**Customer value, retention, and CRM spillovers.** A consumer's economic value to a\nfirm is partly a network quantity. Social ties shape churn—a customer whose connections\ndefect is more likely to defect [@nitzan2011social]—and the value of participation in a\nfirm-sponsored community spills over into the spending of those who merely observe it,\nthe \"social dollars\" quantified by @manchanda2015social. CRM actions, too, propagate\nalong ties: @ascarza2017beyond show that a retention campaign aimed at target customers\nalso moves the behavior of their untreated social neighbors, so the campaign's true\nreturn is a network effect that target-only accounting misses. The classic statement of\nthis logic is @hill2006networkbased, who show that consumers linked (by communication\nties) to existing customers are far likelier to adopt, making explicit consumer networks\na powerful targeting variable. Firm-generated content on social platforms engages users\nthrough the same network substrate [@lee2018advertising].\n\n**Referral economics and social-commerce value.** Referral programs turn the graph into\na managed asset whose returns can be measured: referred customers are more valuable and\nloyal than others [@schmitt2011referral], and @vandenbulte2018customer decompose *why*,\nseparating the selection (homophily) and influence channels through which referral\nprograms convert social capital into economic capital. In social commerce, a seller's\nposition in the network generates value directly [@stephen2010deriving], and the motives\nfor contributing the content that builds these networks—intrinsic versus\nstatus/image—are themselves measurable [@toubia2013]. Whether observed\nclustering reflects genuine word of mouth or mere observational learning is itself an\nidentification question [@chen2011online], and the interplay of social influence with the\nfirm's own direct marketing unfolds dynamically over the adoption process\n[@risselada2014dynamic]. The diffusion consequences of network position are not uniformly\npositive: hubs play a distinctive role in adoption [@goldenberg2009role], yet network\nexternalities can also *chill* diffusion when consumers wait for others to commit first\n[@goldenberg2010chilling].\n\n**Brand co-mention and semantic networks.** Finally, graphs need not connect people or\nproducts at all. Connect two brands when they are mentioned together in reviews, social\nposts, or search sessions, and the resulting co-mention network is a map of *market\nstructure*: tightly connected brand clusters are competitive sets, and a brand's\nposition reveals its substitutes and complements. This is the network-analytic cousin\nof the text-mining market-structure maps discussed in @sec-text-as-data, and it lets an\nanalyst recover perceptual structure from unstructured co-occurrence rather than from\nsurveys.\n\nAcross these applications the same primitive recurs: a position in a graph is a\nfeature, and the configuration of the graph is information. @fig-net-types sorts these\napplications by the kind of graph each builds, since the nodes and edges differ sharply\nacross them.\n\n```{mermaid}\n%%| label: fig-net-types\n%%| fig-cap: \"A taxonomy of marketing networks by what their nodes and edges represent, with the marketing use each structure supports.\"\nflowchart TB\n  G[\"Marketing networks\"]\n  G --> SO[\"Social / word-of-mouth<br/>(people to people)\"]\n  G --> CP[\"Co-purchase / recommendation<br/>(product to product, customer to product)\"]\n  G --> RE[\"Referral / seeding<br/>(directed: who referred whom)\"]\n  G --> BC[\"Brand co-mention / semantic<br/>(brand to brand)\"]\n  SO --> SOu[\"Contagion, influence,<br/>churn spillover\"]\n  CP --> CPu[\"Recommendation, retrieval\"]\n  RE --> REu[\"Seeding, referral value\"]\n  BC --> BCu[\"Market-structure maps\"]\n```\n\nThe rest of the chapter develops the methods that turn that information into measures.\n\n## Graph Representation and Centrality {#sec-graph-centrality}\n\nA graph $G = (V, E)$ is a set of nodes $V$ and a set of edges $E \\subseteq V \\times V$.\nEdges may be **undirected** (a Facebook friendship is mutual) or **directed** (a\nTwitter follow is one-way; an A-referred-B link has an arrow), and they may be\n**weighted** (the number of co-purchases, the strength of a tie). The workhorse\nalgebraic representation is the **adjacency matrix** $A$, an $n \\times n$ matrix with\n$A_{ij} = 1$ (or the edge weight) when an edge runs from $i$ to $j$ and $0$ otherwise.\nAlmost every structural quantity in this chapter is a function of $A$. For sparse\nreal-world graphs, where each node connects to a tiny fraction of all others, $A$ is\nstored as an edge list rather than a dense matrix, but the mathematics is unchanged.\n\nThe most basic summary of a node is its **degree**, the number of edges incident to it\n($d_i = \\sum_j A_{ij}$). In a directed graph this splits into *in-degree* (how many\npoint to $i$; a proxy for received attention or popularity) and *out-degree* (how many\n$i$ points to; a proxy for activity). Degree is the crudest notion of importance, and\nits crudeness is exactly the point of the richer **centrality** measures, each of which\nformalizes a different theory of what makes a node matter.\n\n**Betweenness centrality** measures how often a node lies on shortest paths between\nother pairs of nodes:\n$$\nC_B(i) = \\sum_{s \\ne i \\ne t} \\frac{\\sigma_{st}(i)}{\\sigma_{st}},\n$$ {#eq-graph-betweenness}\nwhere $\\sigma_{st}$ is the number of shortest paths from $s$ to $t$ and\n$\\sigma_{st}(i)$ the number passing through $i$. A high-betweenness node is a *broker*\nsitting on the bridges between otherwise separated regions; in marketing terms, a\nbroker controls the flow of information across communities and is a candidate \"weak tie\"\nconnector in the sense of the word-of-mouth literature.\n\nBrokerage need not be defined on the graph of who knows whom. @mell2021brokerage\nintroduce **temporal brokerage**, a position in a team's *temporal* structure that\nbridges subgroups sharing little or no overlap in working hours. It is not a formal\nrole and need not coincide with high betweenness in the communication graph, yet it\nattracts the same coordination work, because the temporal broker is the only member\nwho can relay between subgroups that cannot speak to each other directly. The\nconsequences are two-sided, greater integrative complexity on one hand and a heavier\nworkload on the other, and they spill beyond the focal team into the broker's other\ncommitments. For measurement the lesson is that the adjacency matrix behind\n@eq-graph-betweenness encodes one relation at a time, and the bridge that matters\nsubstantively may be defined on a different one, such as overlap in working hours,\nshared language, or shift schedule. Choosing the edge is choosing the theory.\n\n**Eigenvector centrality** formalizes the recursive idea that a node is important if its\nneighbors are important. It is the leading eigenvector of the adjacency matrix:\n$$\nA\\,\\mathbf{x} = \\lambda_{\\max}\\,\\mathbf{x},\n$$ {#eq-graph-eigenvector}\nso a node's score is proportional to the sum of its neighbors' scores. PageRank is a\ndirected, damped variant of the same idea. Eigenvector centrality captures *prestige*:\nbeing connected to other well-connected nodes, not merely to many nodes. The three\nmeasures can disagree sharply, and the disagreement is informative. A node can have\nhigh degree but low betweenness (a popular member buried inside one tight cluster), or\nmodest degree but high betweenness (a lone bridge between two cliques). Choosing a\ncentrality measure is therefore choosing a theory of influence, not a neutral\npreprocessing step.\n\nThe runnable demonstration below builds a simulated graph and computes all three. The\npackage is the maintained `igraph`, the standard for network analysis in R. The graph\nis generated by *preferential attachment* (the Barabási-Albert model), which produces\nthe heavy-tailed degree distribution characteristic of real social and co-purchase\nnetworks: a few hubs and a long tail of sparsely connected nodes.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(igraph)\nset.seed(20260622)\n\n# --- Build a simulated scale-free network (Barabasi-Albert) ---\n# Interpretable as a social graph (who-follows-whom) or, with edges read as\n# \"frequently bought together,\" a product co-purchase graph.\ng <- sample_pa(n = 80, power = 1.1, m = 2, directed = FALSE)\nV(g)$name <- paste0(\"u\", seq_len(vcount(g)))\n\n# --- Centrality measures (all functions of the adjacency structure) ---\ndeg  <- degree(g)\nbtw  <- betweenness(g, normalized = TRUE)\neig  <- eigen_centrality(g)$vector\n\ncent <- data.frame(\n  node       = V(g)$name,\n  degree     = deg,\n  betweenness = round(btw, 3),\n  eigenvector = round(eig, 3)\n)\n\n# Show the five highest-degree nodes and how they rank on the other measures\ntop_deg <- head(cent[order(-cent$degree), ], 5)\ncat(\"Top-5 nodes by degree:\\n\")\n#> Top-5 nodes by degree:\nprint(top_deg, row.names = FALSE)\n#>  node degree betweenness eigenvector\n#>    u1     34       0.538       1.000\n#>    u3     21       0.218       0.656\n#>    u7     13       0.124       0.387\n#>    u9      9       0.039       0.191\n#>   u10      9       0.051       0.216\n\n# The top node by EACH measure can differ:\ncat(\"\\nMost central node by measure:\\n\")\n#> \n#> Most central node by measure:\ncat(\"  degree     :\", cent$node[which.max(cent$degree)], \"\\n\")\n#>   degree     : u1\ncat(\"  betweenness:\", cent$node[which.max(cent$betweenness)], \"\\n\")\n#>   betweenness: u1\ncat(\"  eigenvector:\", cent$node[which.max(cent$eigenvector)], \"\\n\")\n#>   eigenvector: u1\n\n# Rank correlation between degree and betweenness: high but not 1,\n# which is exactly why brokers and hubs are distinct managerial targets.\ncat(\"\\nSpearman corr(degree, betweenness):\",\n    round(cor(deg, btw, method = \"spearman\"), 3), \"\\n\")\n#> \n#> Spearman corr(degree, betweenness): 0.869\n\n# --- Visualize ---\nnode_col <- colorRampPalette(c(\"#d9e3f0\", \"#1f3b73\"))(100)[\n  as.integer(cut(btw, breaks = 100, include.lowest = TRUE))]\nplot(g,\n     vertex.size   = 4 + 14 * (deg / max(deg)),\n     vertex.color  = node_col,\n     vertex.label  = NA,\n     edge.color    = \"grey75\",\n     layout        = layout_with_fr(g))\n```\n\n::: {.cell-output-display}\n![A simulated scale-free social/co-purchase graph of 80 nodes generated by preferential attachment. Node size is proportional to degree; color encodes betweenness (darker = higher). The hubs (large nodes) and the brokers (dark nodes) are not always the same vertices, which is the practical point of distinguishing centrality measures.](54-network-graph_files/figure-html/graph-centrality-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nThe output makes the conceptual point operational. The Spearman correlation between\ndegree and betweenness is high but well below one, and the single most central node\ndiffers across measures. A seeding or influencer program that targets \"the most\nconnected user\" is implicitly committing to the degree theory of influence; if the real\nmechanism is brokerage across communities, betweenness is the right target, and the two\nwill recommend different people.\n\n## Brokerage and Structural Holes {#sec-graph-brokerage}\n\nBetweenness (@eq-graph-betweenness) finds brokers by counting shortest paths across the\nwhole graph. A second tradition, older in sociology and now central in strategy and\norganization research, asks a more local question: are a node's own contacts connected\nto one another? Its starting point is @granovetter1973, who argued that the overlap of\ntwo people's friendship networks rises with the strength of the tie between them, so\nthat weak ties are the ones that link otherwise separate groups and carry information\nbetween them. @burt1992structural moved the argument from the tie to the position. A\n**structural hole** is a disconnection between two of ego's nonredundant contacts, and\nbridging such holes yields information benefits (access to nonredundant information) and\ncontrol benefits (the ability to deal with parties who cannot easily deal with each\nother) [@burt1997contingent]. The control benefit is the *tertius gaudens* strategy of a\nbroker who plays contacts off against one another for his or her own benefit\n[@obstfeld2005tertius]. The opposing view locates advantage in *closure*, a network in\nwhich contacts are tied to one another: @coleman1988social describes how closure\nfacilitates two of the forms social capital takes, obligations and expectations on the\none hand and effective social norms on the other. Much of the subsequent literature is\nan argument about when each view holds, and @burt2013advantage review it with network\nadvantage as the organizing lens, tracing advantage to information breadth, timing, and\narbitrage.\n\n### Burt's measures\n\nBurt's measures are computed on the ego network. Let $N(i)$ be ego $i$'s set of\ncontacts, $N_i = |N(i)|$, and let\n$p_{ij} = (a_{ij} + a_{ji}) / \\sum_{k}(a_{ik} + a_{ki})$ be the proportion of $i$'s\nrelational investment directed to $j$, which reduces to $p_{ij} = 1/N_i$ in a binary\nnetwork. **Constraint** measures how far ego's investment is concentrated, directly or\nthrough mutual contacts, on contacts who are themselves connected:\n$$\nc_i = \\sum_{j \\in N(i)} \\Big( p_{ij} + \\sum_{q \\ne i, j} p_{iq}\\, p_{qj} \\Big)^2 .\n$$ {#eq-graph-constraint}\nThe first term inside the parentheses is ego's direct investment in $j$; the second is\nthe investment that reaches $j$ indirectly through a third contact $q$. Constraint is\ntherefore high when ego has few contacts, when tie strength is concentrated on a few of\nthem, and when those contacts are tied to one another, and lower constraint is read as\nmore structural holes [@borgatti2026beyond]. Burt's general formula also weights each\nterm by an exogenous concentration factor, which virtually all studies set to one\n[@borgatti2026beyond]. In `igraph::constraint()` the proportions $p_{qj}$ are computed\nover all of $q$'s ties (the \"whole network\" convention) rather than over $q$'s ties\ninside ego's network; the two conventions coincide when a network contains only ego and\nits contacts.\n\nThe second measure, *effective size*, is the number of contacts discounted for their\nredundancy with one another:\n$$\n\\mathrm{ES}_i = \\sum_{j \\in N(i)} \\Big( 1 - \\sum_{q \\ne i, j} p_{iq}\\, m_{jq} \\Big)\n\\;=\\; N_i - \\frac{2\\,t_i}{N_i} \\quad \\text{(binary data)},\n$$ {#eq-graph-effsize}\nwhere $m_{jq}$ is $j$'s tie to $q$ divided by $j$'s strongest tie to anyone and $t_i$\nis the number of ties among ego's contacts. The binary simplification, due to Borgatti\n(1997, *Connections* 20(1): 35--38), shows that effective size is\nnetwork size minus the average degree of the alters within the ego network\n[@everett2020unpacking]. It equals $N_i$ when no contacts are tied and 1 when every\ncontact is tied to every other, and *efficiency* is effective size divided by $N_i$\n[@burt1992structural].\n\nA different formalization ties brokerage to group membership rather than to ego-network\ndensity. @gould1989structures partition actors into mutually exclusive groups and\nclassify every open two-path $a \\to b \\to c$ (one in which $a$ has no direct tie to\n$c$) by the group memberships of the three actors. The partition yields five distinct\nroles for the broker $b$: a *coordinator* mediates between two members of its own\ngroup; an *itinerant* broker mediates between two members of a single group to which it\ndoes not belong; a *gatekeeper* passes a contact from an outsider into its own group; a\n*representative* passes a contact from its own group to an outsider; and a *liaison*\nconnects two different groups, neither of them its own. Gould and Fernandez give\nquantitative measures of each role and a test of whether occupancy of a role exceeds\nwhat a random distribution of exchange relations would produce; the `sna` package's\n`brokerage()` function implements the counts. The roles read naturally onto marketing\nstructures. A distributor that carries a manufacturer's offer into its own retail\nnetwork occupies the gatekeeper position, and a key-account manager who carries the\nfirm's offer to a customer's buying center acts as a representative.\n\n### What the evidence shows\n\nThe canonical positive evidence is @burt2004goodideas. Among managers in a large\nAmerican electronics company, compensation, positive performance evaluations,\npromotions, and good ideas were disproportionately held by people whose networks\nspanned structural holes, and between-group brokers were more likely to express ideas,\nless likely to have them dismissed, and more likely to have them judged valuable. The\nmechanism is that opinion and behavior are more homogeneous within than between\ngroups, so a person connected across groups sees options that others do not. The value\nof that position is contingent. @burt1997contingent shows that it is especially high for\nmanagers with few peers doing the same work, and @burt2007secondhand finds that\nbrokerage benefits are concentrated in the immediate network, with secondhand brokerage\nacross indirect contacts often worth little. The content of ties matters too:\n@podolny1997resources find that mobility is enhanced by a large, sparse network of\ninformal ties for acquiring information and resources, whereas well-defined performance\nexpectations are more likely to arise from a small, dense network.\n\nThe record is mixed once the outcome and the setting change. In the international\nchemicals industry, @ahuja2000collaboration finds that direct and indirect collaborative\nties raise a firm's subsequent innovation output but that more structural holes in the\ninterfirm collaboration network lower it. Among Canadian mutual fund companies, by\ncontrast, innovative firms that also bridge structural holes earn a further performance\nboost [@zaheer2005benefiting]. For investment banks advising on U.K. mergers and\nacquisitions, structural holes increase status accumulation but dampen market\nperformance, because open networks supply information about new opportunities while\nlimiting information about partners' cooperativeness [@shipilov2008cake]. Cohesion and\nbrokerage are not simple opposites. @reagans2003network find that both social cohesion\naround a tie and network range ease knowledge transfer, @fleming2007collaborative show\nacross 35,400 inventors that collaborative brokerage helps generate an idea but hampers\nits diffusion and use by others, and @tortoriello2010activating find no advantage to\nbridging per se among 276 R&D scientists and engineers, only to bridging ties that are\nSimmelian, that is, embedded in a three-person clique. @aral2011diversity add a\ndiversity-bandwidth trade-off. A structurally diverse network raises novelty at the cost\nof thinner information flow, so in e-mail and network data from an executive recruiting\nfirm bridging ties sometimes delivered less novel information, depending on how much\ncontacts' information overlaps, how deep their topical knowledge is, and how fast it\nrefreshes.\n\nHow brokers broker is a separate question. @obstfeld2005tertius contrasts the *tertius\ngaudens* with the *tertius iungens* (\"third who joins\"), who introduces disconnected\npeople or coordinates connected ones, and finds that a tertius iungens orientation,\ndense networks, and diverse social knowledge predict involvement in innovation in an\nautomotive engineering division. @quintane2016brokers reconcile the two strategies over\ntime with e-mail relational-event data. When brokering through short-term interactions\noutside their long-term relationships, brokers are more likely than densely embedded\nactors to intermediate the information flow themselves; when brokering through their\nlong-term ties, they are more likely to facilitate a direct exchange between the\nbrokered parties. Brokers also affect the people around them. In the French television\ngame show industry, hubs, the brokers who act as the main interface between their own\nnetwork community and others, generate positive externalities for neighbors in\ncreativity-focused roles and negative ones for neighbors in efficiency-focused roles\n[@clement2018brokerage]. @stovel2012brokerage stress the same duality at the societal\nlevel: brokerage eases interaction and economic activity, but it also breeds\nexploitation, corruption, and the accumulation of power.\n\nFinally, brokerage positions are contested and endogenous. In Italian television\nproduction, the structural holes a team spans originate in the prior status and\ncentrality of the teams its members came from, and spanning holes is associated with\nlarger audiences [@zaheer2009origins]. In a game-theoretic model of network formation\nin which every actor strives for structural holes, the predominant stable networks\ndistribute benefits evenly, so no one keeps a structural advantage in the long run\n[@buskens2008dynamics]. @ryall2007brokers reach a parallel conclusion with a biform game:\na broker earns an advantage only if no substitutes exist for the connections it offers\nor the value it creates, if it intermediates more than two parties, and if\ninterdependence does not lock it into a fixed pattern of exchange, and when actors form\nrelations strategically, profitable intermediation survives only under strict\nassumptions of unilateral action. Substitutability is exactly what the next development\nputs at the center of measurement.\n\n### Opportunity versus exclusivity\n\nConstraint has been the workhorse operationalization of structural holes, and\n@johnson2026reassessing argue that it does not measure what it is usually taken to\nmeasure.\nUsing formal, computational, and empirical analyses, they conclude that constraint\nalmost exclusively operationalizes dyadic constructs, namely available alternatives,\nexchange-partner diversity, and concentration, rather than the broader network\nstructure that structural-hole theory invokes. As @borgatti2026beyond summarize the\nevidence, in large unweighted simulated networks the variance of inverse degree alone\naverages about 110 percent of the variance of constraint (possible because inverse\ndegree covaries negatively with the closure terms), and in replications of two earlier\nstudies, one of them the investment-bank study of @shipilov2008cake, constraint\ncorrelates .94 and .99 with the Herfindahl index of ego's tie distribution.\n\n@borgatti2026beyond accept that constraint has a measurement problem but locate it\nelsewhere. Degree belongs in a brokerage measure by design, because contacts create the\npairs across which brokerage can occur: an ego with eight mutually disconnected contacts\nhas more brokerage occasions than one with three. The real failure is substitutability.\nTheir diagnostic holds degree fixed at eight. With no ties among the alters, ego's\nconstraint is .125. Tying one alter to every other alter creates a competing broker,\nwhat @everett2020unpacking call a *shadow ego*, and constraint correctly rises to .455.\nAdding a second, third, and fourth competitor, each of which weakens ego further,\nlowers constraint to .452, .441, and .436, and even the fully closed ego network scores\n.439, below the single-competitor case. This is the general pattern\n@everett2020unpacking derived: with more than seven alters, maximum constraint occurs in\na sparse shadow-ego network rather than in a closed one, and constraint can exceed one\nin small ego networks but cannot reach one in large ones.\n\nThe remedy is to take the brokered pair, not the individual alter, as the unit of\nmeasurement. A *gap* is an unordered pair $\\{j, k\\}$ of ego's contacts that are not tied\nto each other; let $\\mathcal{G}_i$ be ego's set of gaps and $c_{jk}$ the number of\ncommon neighbors of $j$ and $k$ in the whole network, which is at least one because ego\nis among them. Then\n$$\nP_i = |\\mathcal{G}_i|, \\qquad\nQ_i = \\frac{1}{P_i} \\sum_{\\{j,k\\} \\in \\mathcal{G}_i} \\frac{1}{c_{jk}}, \\qquad\nP_i Q_i = \\sum_{\\{j,k\\} \\in \\mathcal{G}_i} \\frac{1}{c_{jk}} .\n$$ {#eq-graph-pq}\n$P$ is **opportunity volume**, the number of occasions on which ego can connect two\notherwise unconnected contacts. $Q$ is average *exclusivity*: $1/c_{jk}$ is ego's share\nof the length-two brokerage between $j$ and $k$, equal to one when ego is the only\nintermediary and to one half when a single competitor can make the same connection,\nwhich can be read as ego's expected share of brokerage occasions when competing brokers\nare equally capable. Their product $PQ$ is total exclusivity-weighted brokerage, and it\nequals ego's betweenness restricted to geodesics of length two. An indicator version\nscores a gap one only if $c_{jk} = 1$, so that $PQ_e$ counts the pairs ego connects\nexclusively; it follows the value-capture logic that a broker with a substitute for a\ngiven connection adds no value to it [@ryall2007brokers]. $P$ is closely tied to Burt's\nmeasure: for fixed degree it is a monotone transformation of ego-network density, and\nfor binary data effective size equals $1 + 2P/N$ [@borgatti2026beyond].\n\nTwo refinements matter in practice. First, a gap with a single intermediary can still\nbe shallow if the two contacts are joined by a short path that avoids ego. Removing ego\nand letting $d_{jk}$ be the length of the shortest remaining path between $j$ and $k$,\nor letting $A_{-i}$ be the adjacency matrix with ego deleted, two distance-sensitive\npair scores are\n$$\nq^{\\text{geo}}_{jk} = 1 - \\rho^{\\,d_{jk} - 1}, \\qquad\nq^{\\text{walk}}_{jk} = \\frac{1}{1 + r_{jk}}, \\quad\nr_{jk} = \\Big[ A_{-i}^{2} \\,(I - \\beta A_{-i})^{-1} \\Big]_{jk},\n$$ {#eq-graph-hole-depth}\nwith $0 < \\rho < 1$, $q^{\\text{geo}}_{jk} = 1$ when no bypass exists, and\n$0 < \\beta < 1/\\lambda_1$ for the largest eigenvalue $\\lambda_1$ of $A_{-i}$. The\nshortest-bypass score ignores how many bypasses there are, whereas the walk-discounted\nscore, which applies Katz-style walk counting to a single pair, penalizes both the\nnumber and the length of ego-avoiding routes and approaches $1/c_{jk}$ as\n$\\beta \\to 0$ [@borgatti2026beyond]. Second, the common-neighbor count must come from\nthe whole network. A rival need not be one of ego's contacts to weaken ego's position,\nso with egocentric survey data $Q$ can only be computed locally and will overstate\nexclusivity.\n\nThese measures share a monotonicity property that constraint lacks: a tie that does not\ninvolve ego can close a gap, create a bypass, or add a competitor, but it can never\nraise $P$ or $PQ$. $Q$ alone is not monotone, because closing a low-quality gap removes\nit from the average, which is why it should be reported with $P$ rather than on its own.\nThe components also carry different strategic meaning. An ego spanning ten gaps, each\nshared with four other brokers ($P = 10$, $Q = .20$), and an ego spanning two gaps\nexclusively ($P = 2$, $Q = 1$) have the same $PQ = 2$; the first has more occasions for\ntransfer and recombination, the second more leverage over timing and bargaining. Hence\n@borgatti2026beyond recommend specifying the structural-hole mechanism first.\nInformation access depends on $P$ (the diversity of what those contacts know has to be\nmeasured separately, for instance from alter attributes), timing on exclusivity ($Q$ or\n$PQ$), control on the absence of substitutes (the indicator or base $Q$, or $PQ$),\nsynthesis on $P$ and $Q$ jointly, and referral, which depends on contacts' ties beyond\nego's network, is captured by none of $P$, $Q$, or constraint. For empirical work they\nsuggest entering $P$ and $Q$ separately while controlling for a function of degree,\nwith $PQ$ acting as their interaction; in their reconstruction of a published industry\nnetwork the two components correlate only .201. All of these are measures of\nopportunity, not of whether or how an actor actually brokers.\n\n@fig-graph-brokerage contrasts three ego networks with the same three contacts. Closure\nleaves no gaps, the open network gives ego three exclusive gaps, and in the contested\nnetwork a rival outside ego's network reaches the same contacts, which halves $Q$ and\n$PQ$ while leaving constraint exactly where it was in the open case.\n\n```{mermaid}\n%%| label: fig-graph-brokerage\n%%| fig-cap: \"Three ego networks with the same three contacts. Under closure every pair of contacts is tied, so ego spans no gaps. In the open network ego spans all three gaps alone. In the contested network a rival broker outside ego's network (dashed ties) reaches the same contacts, so every gap is shared and exclusivity halves, yet constraint is identical to the open case because the rival is not one of ego's contacts.\"\nflowchart TB\n  subgraph CO[\"Contested: shared gaps\"]\n    direction TB\n    E3[\"Ego<br/>P = 3, Q = 0.5, PQ = 1.5<br/>constraint = 0.333\"]\n    A3[\"A\"]\n    B3[\"B\"]\n    C3[\"C\"]\n    R3[\"Rival broker\"]\n    E3 --- A3\n    E3 --- B3\n    E3 --- C3\n    R3 -.- A3\n    R3 -.- B3\n    R3 -.- C3\n  end\n  subgraph OP[\"Open: exclusive gaps\"]\n    direction TB\n    E2[\"Ego<br/>P = 3, Q = 1, PQ = 3<br/>constraint = 0.333\"]\n    A2[\"A\"]\n    B2[\"B\"]\n    C2[\"C\"]\n    E2 --- A2\n    E2 --- B2\n    E2 --- C2\n  end\n  subgraph CL[\"Closure: no gaps\"]\n    direction TB\n    E1[\"Ego<br/>P = 0, PQ = 0<br/>constraint = 0.926\"]\n    A1[\"A\"]\n    B1[\"B\"]\n    C1[\"C\"]\n    E1 --- A1\n    E1 --- B1\n    E1 --- C1\n    A1 --- B1\n    B1 --- C1\n    A1 --- C1\n  end\n```\n\nThe first demonstration implements @eq-graph-effsize and @eq-graph-pq alongside\n`igraph::constraint()` (@eq-graph-constraint) and reproduces the eight-alter shadow-ego\nsequence of @borgatti2026beyond.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(igraph)\n\n# --- Pair-based brokerage measures (Borgatti and Everett 2026) ---\n# For ego i, a brokered pair (a \"gap\") is an unordered pair {j, k} of i's\n# alters that are not tied to each other. c_jk is the number of common\n# neighbors of j and k in the WHOLE network; ego is always one, so c_jk >= 1.\n#   P   = number of brokered pairs                  (opportunity volume)\n#   Q   = mean of 1 / c_jk over brokered pairs      (base exclusivity)\n#   PQ  = sum of 1 / c_jk                           (= two-step betweenness)\n#   PQe = number of pairs with c_jk == 1            (indicator version)\nbrokerage_pq <- function(g, ego) {\n  alters <- as.integer(neighbors(g, ego))\n  none <- c(P = 0, Q = NA, PQ = 0, PQe = 0)\n  if (length(alters) < 2) return(none)\n  prs  <- combn(alters, 2)\n  open <- !apply(prs, 2, function(p) are_adjacent(g, p[1], p[2]))\n  if (!any(open)) return(none)\n  prs  <- prs[, open, drop = FALSE]\n  c_jk <- apply(prs, 2, function(p)\n    length(intersect(neighbors(g, p[1]), neighbors(g, p[2]))))\n  c(P = ncol(prs), Q = mean(1 / c_jk), PQ = sum(1 / c_jk),\n    PQe = sum(c_jk == 1))\n}\n\n# Burt's effective size for binary data, N - 2t/N, where t is the number of\n# ties among ego's N alters; efficiency is effective size divided by N.\neffective_size <- function(g, ego) {\n  alters <- as.integer(neighbors(g, ego))\n  N <- length(alters)\n  t <- ecount(induced_subgraph(g, alters))\n  c(N = N, ES = N - 2 * t / N, eff = (N - 2 * t / N) / N)\n}\n\n# --- The eight-alter shadow-ego sequence ---\n# Ego (vertex 1) has 8 alters (2..9), initially unconnected. Step k makes k\n# alters competing brokers (\"shadow egos\") tied to every other alter. By\n# structural-hole theory ego's position worsens monotonically in k.\nshadow_net <- function(k, n_alters = 8) {\n  g <- make_star(n_alters + 1, mode = \"undirected\", center = 1)\n  alters <- 2:(n_alters + 1)\n  for (s in alters[seq_len(k)]) {\n    others <- setdiff(alters, s)\n    new <- others[!sapply(others, function(o) are_adjacent(g, s, o))]\n    if (length(new) > 0) g <- add_edges(g, as.vector(rbind(s, new)))\n  }\n  g\n}\n\nshadow <- do.call(rbind, lapply(0:7, function(k) {\n  g <- shadow_net(k)\n  m <- brokerage_pq(g, 1)\n  data.frame(k          = k,\n             constraint = round(constraint(g, nodes = 1), 3),\n             eff_size   = effective_size(g, 1)[[\"ES\"]],\n             P          = m[[\"P\"]],\n             Q          = round(m[[\"Q\"]], 3),\n             PQ         = round(m[[\"PQ\"]], 2),\n             PQe        = m[[\"PQe\"]],\n             btw2       = round(betweenness(g, v = 1, cutoff = 2), 2))\n}))\nprint(shadow, row.names = FALSE)\n#>  k constraint eff_size  P     Q    PQ PQe  btw2\n#>  0      0.125     8.00 28 1.000 28.00  28 28.00\n#>  1      0.455     6.25 21 0.500 10.50   0 10.50\n#>  2      0.452     4.75 15 0.333  5.00   0  5.00\n#>  3      0.441     3.50 10 0.250  2.50   0  2.50\n#>  4      0.436     2.50  6 0.200  1.20   0  1.20\n#>  5      0.436     1.75  3 0.167  0.50   0  0.50\n#>  6      0.438     1.25  1 0.143  0.14   0  0.14\n#>  7      0.439     1.00  0    NA  0.00   0  0.00\n\n# --- Identities stated in the paper ---\ncat(\"\\nPQ equals two-step betweenness in every row:\",\n    isTRUE(all.equal(shadow$PQ, shadow$btw2)), \"\\n\")\n#> \n#> PQ equals two-step betweenness in every row: TRUE\ncat(\"Effective size equals 1 + 2P/N in every row:\",\n    isTRUE(all.equal(shadow$eff_size, 1 + 2 * shadow$P / 8)), \"\\n\")\n#> Effective size equals 1 + 2P/N in every row: TRUE\n\n# --- Figure: constraint versus P and PQ along the sequence ---\nop <- par(mfrow = c(1, 2), mar = c(4.2, 4.4, 2.2, 1))\ns1 <- shadow[shadow$k >= 1, ]\nplot(s1$k, s1$constraint, type = \"b\", pch = 19, col = \"#1f3b73\",\n     xlab = \"Competing brokers (k)\", ylab = \"Burt's constraint\",\n     main = \"Constraint (k = 0: 0.125)\", cex.main = 0.95)\nplot(shadow$k, shadow$P, type = \"b\", pch = 1, col = \"grey40\",\n     ylim = c(0, 28), xlab = \"Competing brokers (k)\",\n     ylab = \"Count of gaps\", main = \"P and PQ\", cex.main = 0.95)\nlines(shadow$k, shadow$PQ, type = \"b\", pch = 19, col = \"#b0413e\")\nlegend(\"topright\", c(\"P (gaps spanned)\", \"PQ (exclusivity-weighted)\"),\n       pch = c(1, 19), col = c(\"grey40\", \"#b0413e\"), bty = \"n\", cex = 0.85)\npar(op)\n```\n\n::: {.cell-output-display}\n![Burt's constraint and the pair-based measures along the eight-alter shadow-ego sequence, in which k of ego's alters become competing brokers tied to every other alter. Ego's position worsens with every added competitor. Constraint (left, plotted from k = 1 on a narrow vertical scale; it is 0.125 at k = 0) peaks at 0.455 with the first competitor and then falls, signalling an improvement that has not occurred; P and PQ (right) decline monotonically.](54-network-graph_files/figure-html/fig-graph-brokerage-shadow-1.png){#fig-graph-brokerage-shadow fig-align='center' width=85%}\n:::\n:::\n\n\nThe printed table reproduces the published values: constraint runs .125, .455, .452,\n.441, .436, .436, .438, .439, while $P$ falls from 28 to 0, $Q$ from 1 to 1/7, and\n$PQ$ from 28 to 0. The indicator count $PQ_e$ drops from 28 to 0 at the very\nfirst competitor, since from then on no remaining gap is ego's alone. The two printed\nchecks confirm the identities stated above, that $PQ$ is two-step betweenness\n(`betweenness(g, cutoff = 2)` in `igraph`) and that effective size equals $1 + 2P/N$.\n\nThe second demonstration applies the same functions, plus the distance-sensitive scores\nof @eq-graph-hole-depth, to the three toy networks of @fig-graph-brokerage and to a\nsimulated business-to-business referral network of 36 firms in three regional clusters,\nwith ties far more likely within clusters than across them.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(igraph)\n\n# --- Three toy ego networks with the same three contacts A, B, C ---\n# In the contested case the rival broker is tied to A, B, and C but is NOT\n# one of ego's contacts.\ntoy <- list(\n  closure   = graph_from_literal(Ego-A, Ego-B, Ego-C, A-B, B-C, A-C),\n  open      = graph_from_literal(Ego-A, Ego-B, Ego-C),\n  contested = graph_from_literal(Ego-A, Ego-B, Ego-C, Rival-A, Rival-B, Rival-C)\n)\ntoy_tab <- do.call(rbind, lapply(names(toy), function(nm) {\n  g <- toy[[nm]]; m <- brokerage_pq(g, \"Ego\")\n  data.frame(case = nm,\n             constraint = round(constraint(g, nodes = \"Ego\"), 3),\n             P = m[[\"P\"]], Q = round(m[[\"Q\"]], 3), PQ = round(m[[\"PQ\"]], 2))\n}))\nprint(toy_tab, row.names = FALSE)\n#>       case constraint P   Q  PQ\n#>    closure      0.926 0  NA 0.0\n#>       open      0.333 3 1.0 3.0\n#>  contested      0.333 3 0.5 1.5\n\n# --- Distance-sensitive quality scores (Borgatti and Everett 2026, App. B) ---\n# Shortest bypass: 1 - rho^(d_jk - 1), with d_jk the j-k distance once ego is\n# removed (no bypass: score 1). Walk-discounted: 1 / (1 + r_jk), where\n# r = A^2 (I - beta A)^{-1} on the ego-deleted adjacency matrix A and\n# beta < 1 / lambda_1 (here beta = 0.5 / lambda_1).\ndeep_quality <- function(g, ego, rho = 0.5, beta_frac = 0.5) {\n  alters <- as.integer(neighbors(g, ego))\n  if (length(alters) < 2) return(c(Qgeo = NA, Qwalk = NA))\n  prs  <- combn(alters, 2)\n  open <- !apply(prs, 2, function(p) are_adjacent(g, p[1], p[2]))\n  if (!any(open)) return(c(Qgeo = NA, Qwalk = NA))\n  prs  <- prs[, open, drop = FALSE]\n  keep <- setdiff(seq_len(vcount(g)), ego)\n  h    <- induced_subgraph(g, keep)\n  idx  <- matrix(match(prs, keep), nrow = 2)      # pair ids inside h\n  d    <- distances(h)[cbind(idx[1, ], idx[2, ])]\n  geo  <- ifelse(is.finite(d), 1 - rho^(d - 1), 1)\n  A    <- as_adjacency_matrix(h, sparse = FALSE)\n  lam  <- max(abs(eigen(A, symmetric = TRUE, only.values = TRUE)$values))\n  beta <- if (lam > 0) beta_frac / lam else 0\n  R    <- A %*% A %*% solve(diag(nrow(A)) - beta * A)\n  walk <- 1 / (1 + R[cbind(idx[1, ], idx[2, ])])\n  c(Qgeo = mean(geo), Qwalk = mean(walk))\n}\n\n# --- A simulated B2B referral network: 36 firms in three regional clusters ---\nset.seed(20261001)\npm  <- matrix(0.02, 3, 3); diag(pm) <- 0.30\ng   <- sample_sbm(36, pref.matrix = pm, block.sizes = c(12, 12, 12))\nblk <- rep(1:3, each = 12)                 # regional cluster of each firm\nV(g)$name <- paste0(\"f\", seq_len(vcount(g)))\n\nmeas <- do.call(rbind, lapply(seq_len(vcount(g)), function(i) {\n  pq <- brokerage_pq(g, i); es <- effective_size(g, i); dq <- deep_quality(g, i)\n  data.frame(firm = V(g)$name[i], degree = es[[\"N\"]],\n             clusters = length(unique(blk[as.integer(neighbors(g, i))])),\n             eff_size   = round(es[[\"ES\"]], 2),\n             constraint = round(constraint(g, nodes = i), 3),\n             P = pq[[\"P\"]], Q = round(pq[[\"Q\"]], 3), PQ = round(pq[[\"PQ\"]], 2),\n             Qgeo = round(dq[[\"Qgeo\"]], 3), Qwalk = round(dq[[\"Qwalk\"]], 3))\n}))\n\ncat(\"\\nSix firms with the largest PQ:\\n\")\n#> \n#> Six firms with the largest PQ:\nprint(head(meas[order(-meas$PQ), ], 6), row.names = FALSE)\n#>  firm degree clusters eff_size constraint  P     Q    PQ  Qgeo Qwalk\n#>   f13      6        1     5.33      0.252 13 0.872 11.33 0.832 0.827\n#>   f27      5        2     5.00      0.200 10 0.950  9.50 0.825 0.861\n#>   f33      5        3     4.60      0.262  9 1.000  9.00 0.916 0.948\n#>   f21      5        1     4.60      0.262  9 0.815  7.33 0.729 0.737\n#>   f28      5        1     4.20      0.305  8 0.875  7.00 0.734 0.786\n#>    f6      4        1     4.00      0.250  6 1.000  6.00 0.958 0.974\ncat(\"\\nLowest-constraint firm:\", meas$firm[which.min(meas$constraint)],\n    \"| highest-PQ firm:\", meas$firm[which.max(meas$PQ)], \"\\n\")\n#> \n#> Lowest-constraint firm: f27 | highest-PQ firm: f13\n\ncat(\"\\nSpearman correlations across the 36 firms:\\n\")\n#> \n#> Spearman correlations across the 36 firms:\nprint(round(cor(meas[, c(\"degree\", \"constraint\", \"P\", \"Q\", \"PQ\")],\n                method = \"spearman\", use = \"pairwise.complete.obs\"), 2))\n#>            degree constraint     P     Q    PQ\n#> degree       1.00      -0.91  0.97 -0.32  0.93\n#> constraint  -0.91       1.00 -0.96  0.14 -0.94\n#> P            0.97      -0.96  1.00 -0.17  0.97\n#> Q           -0.32       0.14 -0.17  1.00  0.05\n#> PQ           0.93      -0.94  0.97  0.05  1.00\n```\n:::\n\n\nThe toy table confirms the figure: closure scores a constraint of .926 with no gaps,\nand the open and contested networks share a constraint of .333 even though the rival\nhalves ego's exclusivity ($Q$ from 1 to .5, $PQ$ from 3 to 1.5). Constraint cannot see\nthe rival because the rival is not one of ego's contacts, whereas $Q$ counts common\nneighbors over the whole network. The simulated network shows the same separation at\nscale. Firms f33 and f21 have identical degree (5), effective size (4.60), number of\ngaps ($P = 9$), and constraint (.262), yet f33, whose contacts lie in all three\nclusters, spans every one of its gaps alone ($Q = 1$), while f21, whose contacts all\nlie in its own cluster, shares some of its gaps with other firms in that cluster\n($Q = .815$). Burt's measures cannot tell the two positions apart; $Q$, $PQ$, and both\ndistance-sensitive scores can. The correlation matrix makes the @johnson2026reassessing\npoint concrete, since constraint correlates $-.91$ with degree, and it shows why\nseparating $P$ from $Q$ is useful: $Q$ is nearly uncorrelated with constraint ($.14$),\nso it carries information that constraint does not. The lowest-constraint firm (f27)\nand the highest-$PQ$ firm (f13) also differ, so a program that targets \"the firm with\nthe most structural holes\" will choose different partners depending on the measure.\nNote, too, that f13's contacts all sit in its own cluster. Structural measures count\ngaps without knowing which group boundaries they cross, which is exactly the information\nthe Gould-Fernandez roles add.\n\n### Implications for marketing\n\nSeeding and opinion-leader programs have mostly targeted degree. @hinz2011 find that\nseeding well-connected people is the most successful strategy because they are more\nlikely to participate in a campaign; they use their greater reach but are not more\ninfluential on their peers than less-connected people. @goldenberg2009role show that\nhubs tend to adopt early, with innovative hubs speeding adoption and follower hubs\nenlarging the market, and @iyengar2011opinion find that sociometric and self-reported\nopinion leadership are weakly correlated and capture different constructs. Structure\naround the target matters as well: in an online social network, the density of\nconnections among a consumer's already-adopted contacts strongly raises the consumer's\nadoption probability, and the average influence of adopters declines with their total\nnumber of contacts [@katona2011network]. That clustering effect is a closure result, and\ntogether with the finding that brokered ideas diffuse less [@fleming2007collaborative] it\ncautions against equating \"broker\" with \"best seed.\" The measurement lesson of this\nsection applies directly: if a campaign needs novel information to cross community\nboundaries, the relevant quantity is opportunity volume ($P$, or betweenness); if the\nfirm needs a partner whose position cannot be bypassed, it is exclusivity ($Q$).\n\nIn business-to-business markets the evidence again favors balance over either pure\nposition. In an event study of 230 marketing-alliance announcements in the software\nindustry, the efficiency and density of a firm's alliance network had their strongest\npositive effects on abnormal returns at moderate levels, while network centrality and\nreputation had none [@swaminathan2009a]. What a firm gains from an alliance also\ndepends on the firm itself: in onshore drilling, slow firms gain the most speed from\npartnering and keep the gain only with prior partnering experience [@li2026speed], so a\npartner's network position and the focal firm's own capabilities jointly set the return\n(@sec-ms-corpdev). In new product alliances, knowledge redundancy\ndiminishes information acquisition but enhances information utilization\n[@rindfleisch2001b]. Inside the selling organization, relationship managers perform\nbest when wide-reaching, nonoverlapping ties in their informal network are combined\nwith a densely interconnected formal network, and the effects grow with the overlap\nbetween the two networks [@gonzalez2014synergistic]. Salespeople's relational and\npositional centrality in the intraorganizational network both contribute to objective\nsales performance, but political skill predicts only the former\n[@bolander2015socialnetworks].\n\nFor channel intermediaries, distributors, agencies, and platforms, @ryall2007brokers\nsupply the economic logic and $Q$ supplies the measure. An intermediary earns rents from\nits position only while the parties it connects lack substitutes for the connection,\nand the arrival of a rival intermediary, or of a direct route between buyer and seller,\nerodes those rents without any change in the intermediary's own ties\n[@borgatti2026beyond]. Because interorganizational networks such as alliances,\nsyndicates, and buyer-supplier relations are usually observed sociocentrically, the\ncommon-neighbor counts that $Q$ requires can be computed on the full network rather than\napproximated from ego-network surveys [@borgatti2026beyond]. The usual caution applies\nwith special force. Positions are not randomly assigned [@zaheer2009origins], so a\nbrokerage measure entered as a regressor is a generated feature subject to the\nselection and identification problems of @sec-graph-identification, and the temporal\nbrokerage of @mell2021brokerage is a reminder that the relation on which a gap is\ndefined is itself a theoretical choice.\n\n## Community Detection {#sec-graph-communities}\n\nReal marketing graphs are not homogeneous. They decompose into **communities**:\nsubgroups of nodes more densely connected to one another than to the rest of the graph.\nIn a social network communities are friend groups, demographic clusters, or interest\ntribes; in a co-purchase graph they are product categories or use-occasion bundles; in\na brand co-mention graph they are competitive sets. Detecting communities is an\nunsupervised problem analogous to clustering or topic modeling, and it serves the same\nends: segmentation, market-structure mapping, and the construction of group-level\nfeatures.\n\nThe dominant family of methods maximizes **modularity**, a score that compares the\nfraction of edges falling within proposed communities to the fraction expected if edges\nwere placed at random while preserving the degree sequence:\n$$\nQ = \\frac{1}{2m} \\sum_{i,j} \\left( A_{ij} - \\frac{d_i d_j}{2m} \\right) \\delta(c_i, c_j),\n$$ {#eq-graph-modularity}\nwhere $m$ is the number of edges, $d_i$ is node $i$'s degree, $c_i$ is its assigned\ncommunity, and $\\delta$ is one when two nodes share a community and zero otherwise.\nHigh modularity means communities capture far more internal edge density than chance.\nThe **Louvain** algorithm (Blondel, Guillaume, Lambiotte and Lefebvre 2008, *Journal of\nStatistical Mechanics* P10008, doi:10.1088/1742-5468/2008/10/P10008) greedily and\nhierarchically optimizes modularity and scales to graphs with millions of nodes, which\nmade it the field standard. Its successor, the **Leiden** algorithm (Traag, Waltman and\nvan Eck 2019, *Scientific Reports* 9, 5233, doi:10.1038/s41598-019-41695-z), repairs a\nknown defect in Louvain, that it can produce internally disconnected communities, and is\nnow the recommended default. Both are exposed in `igraph` through the `cluster_*`\nfamily.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(igraph)\nset.seed(20260622)\n\n# --- Simulate a graph with PLANTED community structure ---\n# Stochastic block model: 4 blocks (think 4 customer tribes / 4 product\n# categories) with high within-block and low between-block edge probability.\nblock_sizes <- c(25, 25, 25, 25)\np_within  <- 0.18\np_between <- 0.01\npref <- matrix(p_between, nrow = 4, ncol = 4)\ndiag(pref) <- p_within\ngsbm <- sample_sbm(n = sum(block_sizes),\n                   pref.matrix = pref,\n                   block.sizes = block_sizes)\n\n# --- Louvain community detection (modularity maximization) ---\ncomm_louvain <- cluster_louvain(gsbm)\n\ncat(\"Number of communities found:\", length(comm_louvain), \"\\n\")\n#> Number of communities found: 4\ncat(\"Community sizes:\", paste(sizes(comm_louvain), collapse = \", \"), \"\\n\")\n#> Community sizes: 27, 25, 24, 24\ncat(\"Modularity Q:\", round(modularity(comm_louvain), 3), \"\\n\")\n#> Modularity Q: 0.632\n\n# Leiden is available in recent igraph; fall back to Louvain if not present,\n# so the chapter renders across versions.\nleiden_ok <- \"cluster_leiden\" %in% ls(\"package:igraph\")\nif (leiden_ok) {\n  comm_leiden <- cluster_leiden(gsbm, objective_function = \"modularity\")\n  cat(\"Leiden communities:\", length(unique(membership(comm_leiden))), \"\\n\")\n}\n#> Leiden communities: 4\n\n# --- Visualize the Louvain partition ---\nplot(comm_louvain, gsbm,\n     vertex.size  = 6,\n     vertex.label = NA,\n     edge.color   = \"grey80\",\n     layout       = layout_with_fr(gsbm))\n```\n\n::: {.cell-output-display}\n![Community structure of a simulated graph with planted groups. Nodes are colored by detected community. The Louvain partition recovers the dense subgroups; modularity quantifies how much denser within-community ties are than chance.](54-network-graph_files/figure-html/graph-communities-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nA modularity score comfortably above zero (values around 0.3 to 0.7 are typical of\nclear community structure) confirms that the detected partition captures genuine density\nrather than noise. The marketing payoff is that the community label is now a feature:\nit can segment a campaign, define a competitive set, or, as the next section warns,\nserve as a (dangerous) proxy for the shared environment that confounds influence\nestimation.\n\n## Contagion, Homophily, and the Identification Challenge {#sec-graph-identification}\n\nThe most consequential marketing question one can ask of a network is causal: does a\nconsumer adopt *because* their neighbors adopted? If yes, the firm can engineer\ncascades by seeding well-chosen nodes; if no, network targeting buys nothing beyond\nordinary lookalike targeting. This is also the question on which naive analysis fails\nmost spectacularly, and the failure has a precise structure.\n\nObserved clustering of behavior in a network has at least three distinct generators that\nare observationally similar in cross-sectional data. **Contagion** (or *induction*,\n*influence*) is the causal mechanism of interest: $i$'s adoption changes $j$'s adoption\nprobability. **Homophily** is selection on similarity: $i$ and $j$ are connected\n*because* they were already alike, so they adopt the same things for reasons that\npredate and have nothing to do with the tie. **Common external shocks** (correlated\nenvironment) are exposures shared by connected nodes, such as a local promotion, a\nweather event, or a price change, that hit neighborhoods together. All three produce the\nsame surface pattern, that adoption is correlated across edges, yet only the first\njustifies network-based seeding. Separating them is the central methodological problem\nof the field: @aral2009distinguishing show, using dynamic matched sampling on a\nlarge communication network, that homophily can account for more than half of what\nnaive models attribute to contagion, so that ignoring it overstates influence by a\nfactor of two or more.\n\nThe econometric core of the difficulty is the **reflection problem** named by Manski\n(Manski 1993, *Review of Economic Studies* 60(3), 531--542, doi:10.2307/2298123). If\neach person's behavior depends on the average behavior of their reference group, and the\nreference group's behavior simultaneously depends on each person's, then the endogenous\nsocial effect (true contagion), the exogenous or contextual effect (the group's\ncharacteristics), and correlated effects (shared environment) cannot in general be\nseparated from a single cross-section: the regressors reflect each other. Manski's\nresult is a statement that the data, not merely the estimator, are uninformative about\nthe decomposition without further structure.\n\nThree routes restore identification. The first is **experimental**: randomize the\ntreatment that is supposed to spread, breaking the link between a node's exposure and\nits pre-existing similarity to its neighbors. The cleanest marketing demonstrations are\nrandomized field experiments. @aral2011creating randomized viral product-design features inside\na Facebook app and so measured peer influence free of homophily; in a companion study,\n@aral2012identifying\nidentified *influential* and *susceptible* individuals by exploiting that\nrandomization, showing that influence and susceptibility are distinct traits and that\nthe most influential are not the most susceptible; and @aral2014tie further showed, in a\nlarge networked experiment, how tie strength and structural embeddedness moderate how\nfar influence travels. Bapna and Umyarov (2015, *Management\nScience* 61(8), 1902--1920, doi:10.1287/mnsc.2014.2059) ran a randomized field\nexperiment gifting premium subscriptions in a music social network and recovered a clean\ncausal peer-influence estimate, finding it substantial but far below naive\nobservational figures. Centola (2010, *Science* 329(5996), 1194--1197,\ndoi:10.1126/science.1185231) built artificial online networks with randomly assigned\ntopologies and showed that health behavior spread *farther and faster* in clustered\nnetworks than in random ones, evidence for *complex contagion*, where adoption requires\nreinforcement from multiple sources rather than a single contact. The complex-contagion\nfinding directly qualifies seeding advice: if reinforcement is needed, scattering seeds\nto maximize reach can be worse than concentrating them to manufacture local density.\n\nThe second route is **observational with structure**. When experiments are infeasible,\nidentification can sometimes be recovered from the *architecture* of the network itself.\n@bramoulle2009identification showed that when the network contains *intransitive\ntriads* (friends of friends who are not themselves friends), the characteristics of\nthose second-degree-only contacts serve as instruments that break the reflection\nproblem, partially identifying endogenous from contextual effects. Within marketing,\n@iyengar2011opinion combined sociometric prescription data with self-reports to separate\nopinion leadership from contagion in new-product diffusion, @iyengar2015 separated the\nroles of opinion leadership and susceptibility in new-product\ntrial and repeat, and @iyengar2003 and the broader contagion literature deploy timing,\npanel structure, and dynamic models to argue that influence, not merely similarity,\ndrives observed clustering. @peng2018 exploited *network overlap*, the extent to which\ntwo users share common friends, to study content sharing, a structural feature that\nitself shapes diffusion.\n\nA third route matches on the *content* that travels rather than on the nodes. When the\nobject of transmission is a discrete, datable item—a paper, a design, a piece of\ncode—one can sometimes find near-duplicates of it and ask which version a given actor\npicked up. @arts2026harnessing do this at the scale of the U.S. patent record,\nidentifying **paper twins**, pairs of scientific papers reporting nearly identical\nfindings published at nearly the same time by independent academic teams, and asking\nwhich twin a corporate patent cites. Because the twins carry the same knowledge with\nthe same commercial value at the same moment, the quality of the idea cannot explain\nthe choice, and what remains is the citing inventor's social distance to each set of\nauthors—which turns out to matter only within two degrees of separation. The design is\nthe network analogue of a matched pair: rather than randomizing the tie or instrumenting\nit, it holds the transmitted content fixed and lets the tie vary. Its scope condition is\nthat twins must exist and be findable, which is why it appears in science and patenting,\nwhere the corpus is large enough that near-simultaneous duplicate discovery is common,\nrather than in consumer settings where the adopted object is rarely duplicated.\n\n@fig-net-identification shows why the naive reading fails and how the three routes\nrestore identification.\n\n```{mermaid}\n%%| label: fig-net-identification\n%%| fig-cap: \"The identification problem for social influence. Contagion, homophily, and common external shocks all produce the same observed clustering, the reflection problem blocks their separation from a single cross-section, and only randomization, architecture-based structure, or a content-matched comparison recovers identified contagion.\"\nflowchart LR\n  CO[\"Contagion<br/>(influence)\"] --> OB[\"Observed clustering<br/>(adoption correlated across ties)\"]\n  HO[\"Homophily<br/>(selection on similarity)\"] --> OB\n  CS[\"Common external shocks<br/>(shared environment)\"] --> OB\n  OB --> RP[\"Reflection problem<br/>(not separable from a single cross-section)\"]\n  RP --> EX[\"Randomized experiment\"]\n  RP --> STR[\"Observational with structure<br/>(architecture-based instrument)\"]\n  RP --> CM[\"Content-matched comparison<br/>(near-duplicate transmitted objects)\"]\n  EX --> ID[\"Identified contagion<br/>(justifies seeding)\"]\n  STR --> ID\n  CM --> ID\n```\n\nThe discipline this section imposes is non-negotiable. A centrality score, a community\nlabel, or a \"fraction of neighbors who adopted\" is a generated regressor saturated with\nhomophily and shared-environment variance. Reporting its coefficient as social influence\nis the network analogue of the generated-regressor error that recurs throughout the\nunstructured-data chapters [@balducci2018unstructured], and here it is at its most seductive because the story, \"my\nfriends made me do it,\" is so plausible. The credible default is to treat any\nobservational network-effect estimate as an upper bound and to reach for randomization,\na structural model, or an architecture-based instrument before making a causal claim.\n\n## Diffusion and the Independent-Cascade Process {#sec-graph-diffusion}\n\nWhether or not contagion is cleanly identified, marketers need *models* of how something\nspreads over a fixed graph, both to forecast a campaign's reach and to choose seeds.\nTwo classical families dominate. In the **independent cascade** model, each newly\nactivated node gets a single chance to activate each not-yet-active neighbor,\nsucceeding with an edge-specific probability $p_{ij}$; activation is a one-shot\npush along each edge. In the **linear threshold** model, each node activates once the\nweighted fraction of its already-active neighbors crosses a node-specific threshold,\nwhich is the discrete analogue of the complex-contagion reinforcement Centola observed.\nBoth nest the aggregate-level Bass diffusion logic of @goldenberg2001 at the micro,\nedge-by-edge level.\n\nThese micro-models are also the substrate of **influence maximization**, the\ncombinatorial problem of choosing a seed set of size $k$ that maximizes expected\neventual adoption. Kempe, Kleinberg and Tardos (2003, *Proc. 9th ACM SIGKDD*, 137--146,\ndoi:10.1145/956750.956769) proved that expected spread under both models is a\n*submodular* (diminishing-returns) function of the seed set, so a simple greedy\nalgorithm, repeatedly adding the node with the largest marginal gain, achieves a\nspread within a $(1 - 1/e) \\approx 63\\%$ factor of the optimum. This is the theoretical\nbackbone of principled seeding and the formal counterpart to the empirical seeding\ncomparisons in @hinz2011.\n\nThe simulation below runs an independent-cascade process over the scale-free graph from\nthe centrality section and compares three seeding rules, highest-degree, highest-\nbetweenness, and random, by Monte Carlo over many cascade realizations. It is a small,\nself-contained, genuinely running implementation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(igraph)\nset.seed(20260622)\n\ng <- sample_pa(n = 80, power = 1.1, m = 2, directed = FALSE)\nA <- as_adjacency_matrix(g, sparse = FALSE)\nn <- vcount(g)\n\n# --- One independent-cascade realization from a given seed set ---\n# Each active node gets ONE chance to activate each inactive neighbor,\n# succeeding with probability p along that edge.\nic_spread <- function(adj, seeds, p = 0.12) {\n  active   <- rep(FALSE, nrow(adj)); active[seeds] <- TRUE\n  frontier <- seeds\n  while (length(frontier) > 0) {\n    new_active <- integer(0)\n    for (u in frontier) {\n      nbrs <- which(adj[u, ] == 1 & !active)\n      if (length(nbrs) > 0) {\n        success <- nbrs[runif(length(nbrs)) < p]\n        new_active <- c(new_active, success)\n      }\n    }\n    new_active <- unique(new_active)\n    active[new_active] <- TRUE\n    frontier <- new_active\n  }\n  sum(active)\n}\n\n# --- Monte Carlo: mean spread for each seeding rule ---\nmc_spread <- function(seeds, reps = 200, p = 0.12) {\n  mean(replicate(reps, ic_spread(A, seeds, p)))\n}\n\nk <- 3  # seed-set size\ndeg  <- degree(g)\nbtw  <- betweenness(g)\n\nseeds_degree <- order(deg, decreasing = TRUE)[1:k]\nseeds_betw   <- order(btw, decreasing = TRUE)[1:k]\nset.seed(101)\nseeds_random <- sample(seq_len(n), k)\n\nresults <- c(\n  Degree      = mc_spread(seeds_degree),\n  Betweenness = mc_spread(seeds_betw),\n  Random      = mc_spread(seeds_random)\n)\n\ncat(\"Mean final adopters out of\", n, \"nodes (k =\", k, \"seeds, 200 sims):\\n\")\n#> Mean final adopters out of 80 nodes (k = 3 seeds, 200 sims):\nprint(round(results, 1))\n#>      Degree Betweenness      Random \n#>        12.7        12.8         6.5\n\nbarplot(results,\n        ylab = \"Mean final adopters (of 80)\",\n        col  = c(\"#1f3b73\", \"#3f6fb0\", \"#cdd8e8\"),\n        main = \"\")\n```\n\n::: {.cell-output-display}\n![Independent-cascade diffusion over a simulated scale-free graph. Each bar is the mean final number of adopters (out of 80 nodes) across 200 cascade simulations, for three seeding rules with the same seed-set size. Degree- and betweenness-based seeding outperform random seeding, the simulated counterpart of the empirical 'seed the hubs' result.](54-network-graph_files/figure-html/graph-diffusion-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nThe simulation reproduces the qualitative seeding result in a controlled setting:\ntargeting high-centrality nodes meaningfully outperforms random seeding for the same\nbudget, because hubs reach more of the graph before the cascade dies. The size of the\nadvantage depends on the activation probability $p$ and the network topology, and the\nreader is invited to vary both. The honest caveat is that this gain is a property of the\n*assumed* contagion process; whether it materializes in a real campaign returns us to\nthe identification problem of the previous section, since a process that is mostly\nhomophily will not respond to seeding at all.\n\n## Graph Embeddings and Graph Neural Networks {#sec-graph-embeddings}\n\nCentrality and community labels are hand-designed features. The learned-representation\nrevolution that reshaped text and image analysis has a direct counterpart for graphs:\nmethods that *learn* a low-dimensional vector for each node such that nodes close in the\ngraph are close in the vector space, after which the vectors feed any ordinary\ndownstream model (a churn classifier, a recommender, a link predictor). The conceptual\nmove mirrors word embeddings exactly, with random walks on the graph playing the role\nthat sentences play in text.\n\n**Random-walk embeddings.** The foundational methods generate many random walks from\neach node, treat each walk as a \"sentence\" of node IDs, and run a word2vec-style\nskip-gram model so that nodes appearing in the same walks receive similar vectors.\n*DeepWalk* (Perozzi, Al-Rfou and Skiena 2014, *Proc. 20th ACM SIGKDD*, 701--710,\ndoi:10.1145/2623330.2623732) introduced this idea. *node2vec* (Grover and Leskovec 2016,\n*Proc. 22nd ACM SIGKDD*, 855--864, doi:10.1145/2939672.2939754) generalized it with\nbiased random walks whose two parameters interpolate between breadth-first exploration,\nwhich captures *structural-role* similarity such as \"both are hubs,\" and depth-first\nexploration, which captures *community* proximity. The practical value for marketing is\nthat a single 64- or 128-dimensional node vector compresses a consumer's entire\nrelational position into a feature usable in standard pipelines, sidestepping the need to\npre-commit to degree versus betweenness versus community as the relevant summary.\n\n**Graph neural networks (conceptual).** The following is a *conceptual* description; the\nheavy deep-learning machinery and its training are beyond this chapter's runnable scope\nand are flagged as such. Graph neural networks (GNNs) generalize embeddings from a fixed\nlookup table to a learned function of node and edge *attributes*. The core operation is\n**neighborhood aggregation** (message passing): each node updates its representation by\ncombining its own features with a permutation-invariant aggregate (sum, mean, or\nattention-weighted average) of its neighbors' representations, and stacking $L$ such\nlayers lets information flow from $L$ hops away. The graph convolutional network\nformulates this as a spectral-motivated averaging over neighbors (Kipf and Welling,\n\"Semi-Supervised Classification with Graph Convolutional Networks,\" ICLR 2017, cited by\nname; no canonical Crossref DOI). *GraphSAGE* (Hamilton, Ying and Leskovec,\n\"Inductive Representation Learning on Large Graphs,\" NeurIPS 2017, cited by name; no\ncanonical Crossref DOI) made the scheme *inductive*, learning an aggregation function\nthat generalizes to nodes unseen at training time, which is essential when the customer\ngraph grows daily. Graph attention networks weight neighbors by learned attention rather\nthan treating them uniformly. The marketing relevance is that GNNs jointly exploit graph\nstructure *and* node attributes (a customer's demographics, a product's category) in a\nsingle supervised objective, which is why they now underpin large-scale industrial\nrecommendation and fraud systems.\n\nThe standard caution applies with full force to learned representations. A node\nembedding is a generated feature, and its proximity structure encodes homophily and\nshared environment along with whatever genuine influence exists. Using embeddings to\n*predict* (who will churn, what to recommend) is on firm ground; using an embedding\ncoordinate as a regressor in a *causal* claim about social influence reintroduces every\nhazard of @sec-graph-identification in a less transparent form.\n\n## Industry and Production Practice {#sec-graph-production}\n\nIn production systems, graph methods are deployed overwhelmingly for *prediction and\nranking*, where the identification anxieties recede and the engineering challenges of\nscale, latency, and freshness dominate.\n\n**Recommendation.** The co-purchase and user-item interaction graph is the oldest and\nlargest commercial application. Item-to-item collaborative filtering computes, for each\nitem, the items most co-purchased or co-viewed with it, precisely the neighborhood\nstructure of the co-purchase graph, and serves them as \"related items\" (Linden, Smith\nand York 2003, doi:10.1109/MIC.2003.1167344). Modern systems replace hand-built\nsimilarity with learned node embeddings or GNNs over the bipartite user-item graph, and\ngraph-based candidate generation is now standard at web scale. Because the objective is\nrelevance rather than a causal effect, the right evaluation is held-out predictive\nranking (precision-at-k, recall, NDCG), not a structural parameter.\n\n**Fraud and abuse detection.** Fraud is intrinsically relational: fraudulent accounts\ncollude, share devices and payment instruments, and form dense, anomalous subgraphs that\nlook nothing like organic user clusters. Community detection surfaces suspiciously\ntight rings; centrality and *guilt-by-association* propagation spread suspicion from\nknown-bad nodes to their neighbors; and GNNs trained on labeled fraud generalize these\nsignals. The same machinery flags fake reviews, click farms, and bot-driven engagement,\nwhich directly protects the integrity of the word-of-mouth and influencer signals that\nthe rest of marketing relies upon.\n\n**Influencer selection.** Brands choosing influencers operationalize the centrality and\nseeding ideas of this chapter, but production practice is more skeptical of raw reach\nthan the naive theory. Follower count is in-degree, the crudest centrality, and is\neasily inflated by bots and cheaply purchased. Practitioners increasingly weight\n*engagement* (whether the audience acts), *audience overlap* (whether two influencers\nreach the same people, a network-overlap consideration in the spirit of @peng2018), and\n*authenticity*, all of which are graph- and behavior-based rather than reach-based. The\n@watts2007influentials caution, that ordinary susceptible audiences often matter more\nthan rare special individuals, and the @trusov2010 distinction between activity-driving\ninfluence and mere connectedness, are the academic backbone of this more nuanced\npractice. The video-advertising and platform chapters (@sec-platforms) develop the\ninfluencer economy in its own right; here the point is narrowly that selection is a\nnetwork-position problem dressed in marketing clothes.\n\nA cross-cutting production reality is that these graphs are enormous, dynamic, and often\nprivacy-sensitive. The relevant edges, who is friends with whom, who bought with whom,\nmay be governed by consent and platform policy, and the analyst's access to the true\ngraph is partial and changing. Methods that are inductive (generalizing to new nodes),\nincremental (updating without full recomputation), and robust to missing edges are\nfavored not for elegance but for survival in deployment.\n\n## The Frontier {#sec-graph-frontier}\n\nSeveral directions are actively expanding what network data can do for marketing.\n\n**Causal inference on networks** is the most consequential. The field is moving beyond\nthe simple contagion-versus-homophily dichotomy toward formal treatment of *interference*\nand *spillovers*, the fact that in a connected population the stable-unit-treatment-value\nassumption fails because one unit's treatment affects another's outcome. Designing\nexperiments that *measure* spillovers rather than assuming them away, through\ncluster-randomized, graph-cluster, and ego-network designs, is an area where marketing,\nplatform experimentation, and econometrics are converging, and it is the natural\nextension of the identification discipline in @sec-graph-identification.\n\n**Dynamic and temporal graphs** treat edges as events with timestamps rather than a\nstatic snapshot, letting models capture *when* a tie forms or fires, which is exactly the\ninformation diffusion and influence estimation most need. Temporal GNNs and point-process\nmodels over interaction streams are the methodological frontier here.\n\n**Exponential random graph models (ERGMs)** model the *network itself* as the outcome,\nspecifying the probability of an observed graph as a function of local configurations\n(edges, reciprocated ties, triangles, homophily terms), and so let an analyst test\n*why* ties form, for example whether brand co-mentions cluster by category beyond\nchance. The mature `ergm` software (Hunter, Handcock, Butts, Goodreau and Morris 2008,\n*Journal of Statistical Software* 24(3), doi:10.18637/jss.v024.i03) makes these models\nestimable, and they are the right tool when link *formation*, rather than node behavior,\nis the question, complementing the strategic link-formation models of @katona2008.\n\n**Multimodal graphs** fuse the relational structure of this chapter with the text,\nimage, and behavioral modalities of its sibling chapters: nodes carry text and image\nattributes, edges carry interaction content, and the joint object is modeled with\nattributed GNNs. This is where network data rejoins the broader unstructured-and-\nmultimodal program, and where the generated-feature caution must be enforced across all\nmodalities at once. The unifying thesis of the part holds here without exception: a\ngraph, like a document or a photograph, becomes a learned, lossy feature vector, and\nthat vector is a generated regressor whose error may correlate with the outcome the\nanalyst is trying to explain.\n\n## Summary {#sec-graph-summary}\n\n- Network data make the *relation* the unit of analysis. A node's position in a graph\n  is a marketing feature, and the configuration of the graph is information that\n  rectangular data cannot recover.\n- The applications span social contagion and word of mouth, co-purchase and\n  recommendation graphs, customer-referral and seeding networks, influencer\n  identification, and brand co-mention market-structure maps.\n- **Centrality** measures (degree, betweenness, eigenvector) each formalize a different\n  theory of which node matters, and they can disagree; choosing one is choosing a theory\n  of influence, as the runnable `igraph` demonstration shows.\n- **Brokerage** is also measured locally. Burt's constraint and effective size summarize\n  the structural holes in an ego network, the Gould-Fernandez roles tie brokerage to\n  group boundaries, and the returns to brokerage depend on the outcome, the content of\n  ties, and competition among brokers. Because constraint largely tracks inverse degree\n  and can improve as rival brokers appear, the pair-based measures of @borgatti2026beyond\n  separate opportunity volume ($P$) from exclusivity ($Q$); the runnable demonstration\n  reproduces their shadow-ego result (@sec-graph-brokerage).\n- **Community detection** via modularity maximization (Louvain, Leiden) recovers\n  cohesive subgroups usable as segments, competitive sets, or group-level features.\n- The **contagion-versus-homophily** identification problem, formalized by Manski's\n  reflection problem, is the hardest causal problem in network marketing; credible\n  answers require randomization, architecture-based instruments, or structural models,\n  and observational network-effect estimates should be read as upper bounds.\n- **Diffusion** models (independent cascade, linear threshold) and the submodularity of\n  influence spread justify principled seeding; the simulation confirms that centrality-\n  based seeding beats random seeding *under an assumed contagion process*.\n- **Graph embeddings** (DeepWalk, node2vec) and **graph neural networks** learn node\n  representations that power production recommendation and fraud systems, but a learned\n  embedding is a generated feature carrying the same causal hazards in less transparent\n  form.\n- In production, graphs serve recommendation, fraud detection, and influencer selection,\n  where prediction quality and scale dominate; the frontier is causal inference under\n  interference, temporal graphs, ERGMs for link formation, and multimodal attributed\n  graphs.\n\n## Further Reading\n\nThe word-of-mouth and social-contagion foundations in marketing are developed in\n@goldenberg2001, @godes2004, and @godes2009, with the seeding and influence-targeting\nstrand in @hinz2011, @trusov2009, @trusov2010, and @iyengar2015. The strategic formation\nof commercial networks is treated in @katona2008, network-structure effects on idea\ngeneration in @stephen2016, and network overlap and diffusion in @peng2018. The\nmisinformation-as-diffusion case is @vosoughi2018. For the identification machinery, the\ncanonical references cited by verified DOI in the text are Manski (1993) on the\nreflection problem, Bramoullé, Djebbari and Fortin (2009) on identification through\nnetwork architecture, and the randomized-experiment line of Aral and Walker (2011,\n2012), Bapna and Umyarov (2015), and Centola (2010); the homophily concept traces to\nMcPherson, Smith-Lovin and Cook (2001, *Annual Review of Sociology* 27, 415--444,\ndoi:10.1146/annurev.soc.27.1.415). The methods substrate, community detection (Blondel\net al. 2008; Traag et al. 2019), influence maximization (Kempe, Kleinberg and Tardos\n2003), graph embeddings (Perozzi et al. 2014; Grover and Leskovec 2016), graph neural\nnetworks (Kipf and Welling 2017; Hamilton, Ying and Leskovec 2017, both cited by name),\nERGMs (Hunter et al. 2008), and the Amazon item-to-item recommender (Linden, Smith and\nYork 2003), is referenced inline with verified DOIs where a canonical Crossref DOI\nexists. This chapter sits alongside the text (@sec-text-as-data) and image\n(@sec-image-processing) treatments in the unstructured-and-multimodal family, and its\nplatform and influencer-economy context is developed in @sec-platforms.\n\nFor brokerage and structural holes, the foundations are @granovetter1973,\n@coleman1988social, @burt1992structural, and @gould1989structures, and the reviews by\n@stovel2012brokerage and @burt2013advantage map the field. The measurement debate runs\nfrom @everett2020unpacking through @johnson2026reassessing to @borgatti2026beyond, the\ncontingent returns to brokerage are documented in @burt2004goodideas,\n@ahuja2000collaboration, @shipilov2008cake, and @aral2011diversity, and the competitive\nlogic of brokerage is formalized by @ryall2007brokers and @buskens2008dynamics.\nMarketing applications of network position include @swaminathan2009a on alliance\nnetworks and @gonzalez2014synergistic on relationship managers' networks.\n",
    "supporting": [
      "54-network-graph_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}