{
  "hash": "fbc9b3051d78f5c9e171ef14d39156be",
  "result": {
    "engine": "knitr",
    "markdown": "# Customer-Base Analysis and Latent Attrition Models {#sec-cba}\n\n@sec-clv treated customer lifetime value as a managerial quantity: a number that\nallocates acquisition budget, prices a loyalty program, and, aggregated, tracks\nshareholder value. It surveyed four traditions for producing that number and showed\neach one working. This chapter goes down one level, into the tradition that has the\nlongest run of published theory behind it and the smallest data appetite in front of\nit: *customer-base analysis*, the problem of inferring who in a customer base is still\na customer at all.\n\nThe distinction is not pedantic. In a contractual business, attrition is an observed\nevent with a date attached; churn is a dependent variable and the modeling problem is\na survival problem of a familiar kind. In a *non-contractual* business, which is most\nretail, most hospitality, most e-commerce and most direct marketing, nobody resigns.\nA customer who has not bought in four months may have defected, or may be between\ntrips. There is no dependent variable to regress, because the event of interest is\nnever recorded. Customer-base analysis is the family of models that solves this by\nrefusing to observe attrition and modeling it as latent: the customer buys at some\nrate while \"alive,\" dies at an unobserved moment, and everything the analyst wants\n(the probability the customer is still active, the transactions to expect next year,\nthe discounted residual value) is recovered as a posterior quantity from the shape of\nthe purchase history alone.\n\nThat family has been remarkably productive and remarkably static in one specific way.\nFrom @paretonbd1987 through the closed-form simplifications of the 2000s, the models\ntook as input three numbers per customer, frequency, recency, and observation length,\nand nothing else. They took nothing else because the closed forms that made them\nattractive did not survive contact with covariates. A model that cannot see that a\ncustomer was mailed a catalogue in week 30, or that weeks 46 through 52 are the high\nseason, cannot tell a marketer whether the catalogue worked, and pays for that\nblindness in predictive accuracy on exactly the periods a marketer cares about.\n\nThe organizing paper of this chapter closes that gap. @bachmann2021tvc extend the\nPareto/NBD so that both the purchase rate and the attrition rate are functions of\ncovariates that *change over time*, while preserving the closed-form maximum\nlikelihood solution that made the original model deployable. The extension is not a\nreparameterization; it changes what the sufficient statistics are (the exact timing of\nevery transaction now matters, not just the last one), what the managerial expressions\nmean (a finite-horizon discounted transaction count replaces the infinite-horizon\none), and what the model can be asked (whether a marketing action raises purchasing\nand churn simultaneously becomes a testable restriction). We develop the mathematics\nfrom primitives, replicate the estimation on the retail data that ships with the\nauthors' own software, and then place the whole enterprise in its literature, journal\nby journal, across marketing and economics.\n\n## What Customer-Base Analysis Asks {#sec-cba-questions}\n\n### Four Quadrants, One Hard Cell {#sec-cba-quadrants}\n\nTwo binary features of a business decide which model class is even admissible, and\nthe taxonomy is worth restating because it is the single most common source of\nmisapplied CLV models in practice.\n\nThe first feature is whether attrition is *observed*. In a contractual setting,\nsubscriptions, insurance, telecom postpaid, B2B licensing, the customer must act to\nend the relationship, and the firm records the act. In a non-contractual setting,\nretail, e-commerce, restaurants, catalogue, most consumer packaged goods, the customer\nsimply stops, silently.\n\nThe second feature is whether transactions can occur at *any* moment (continuous) or\nonly at discrete opportunities (discrete): a charity that solicits once a year, a\nseason-ticket renewal, a monthly billing cycle.\n\n\n::: {#tbl-cba-taxonomy .cell layout-align=\"center\" tbl-cap='Which model class is admissible. The top-right cell is customer-base analysis proper: attrition is unobserved and time is continuous, so a latent-attrition model is not one option among several but the only way to define the estimand.'}\n::: {.cell-output-display}\n\n\n|Transaction opportunity |Contractual (attrition observed)                                              |Non-contractual (attrition latent)                                                |\n|:-----------------------|:-----------------------------------------------------------------------------|:---------------------------------------------------------------------------------|\n|Continuous              |Survival / hazard models; sBG on renewal cohorts. Example: mobile postpaid.   |Pareto/NBD, BG/NBD, Pareto/GGG and covariate extensions. Example: apparel retail. |\n|Discrete                |Discrete-time survival; shifted-beta-geometric. Example: annual subscription. |BG/BB. Example: annual charity appeal.                                            |\n\n\n:::\n:::\n\n\nOnly the right-hand column is customer-base analysis. In the left-hand column the\nanalyst has a labelled event and can reach for the entire apparatus of duration\neconometrics; in the right-hand column there is no label, and the models below exist\nto manufacture a posterior belief where the label should have been.\n\n### The Managerial Expressions {#sec-cba-expressions}\n\nWhatever the model, four quantities are asked of it, and the rest of the chapter is\nabout how each is computed. Let $\\mathcal{F}$ denote everything observed about a\ncustomer. For the Pareto/NBD this will be $\\mathcal{F} = \\{x, t_x, T\\}$: the number of\nrepeat transactions, the time of the last one, and the length of the observation\nwindow.\n\n1. **P(alive)**, the posterior probability the customer had not yet churned at $T$.\n2. **CET**, the *conditional expected transactions* $E(X(T, T+t) \\mid \\mathcal{F})$\n   over a finite horizon of length $t$.\n3. **DERT**, the *discounted expected residual transactions*, which is CET's\n   infinite-horizon, discounted analogue.\n4. **Expected spend per transaction** $E(m \\mid \\mathcal{F})$, supplied by a separate\n   model.\n\nFollowing @gupta2006modeling and the general formulation used in the software\nliterature [@meierer2026clvtools], value is the discounted integral of cash flow\nweighted by the probability of still being alive to generate it,\n\n$$\nE(CLV \\mid \\mathcal{F}) = \\int_{T}^{\\infty} E[V(t) \\mid \\mathcal{F}]\\, S(t \\mid \\mathcal{F})\\, d(t)\\, dt ,\n$$ {#eq-cba-clv-integral}\n\nwhere $S(t \\mid \\mathcal{F})$ is the survivor function and $d(t)$ the discount factor.\nUnder the standard assumption that spend per transaction is independent of transaction\ntiming, cash flow factors out and @eq-cba-clv-integral collapses to a product of a\ntransaction quantity and a monetary quantity,\n\n$$\nDERT = \\int_{T}^{\\infty} \\lambda(t)\\, S(t \\mid \\mathcal{F})\\, d(t)\\, dt ,\n\\qquad\nE(CLV \\mid \\mathcal{F}) = E(m \\mid \\mathcal{F}) \\cdot DERT .\n$$ {#eq-cba-dert}\n\nThis factorization is what lets the field maintain two separate literatures, one on\nlatent attrition and one on spend, and bolt them together at the end. It is also the\nfirst assumption to interrogate when a CLV number looks wrong: heavy buyers who spend\ndifferently per basket break it, and @glady2015unveiling document exactly that\ndependence between timing, spending and dropout.\n\n## The Pareto/NBD from Primitives {#sec-cba-pnbd}\n\n@paretonbd1987 is the origin model and still the reference point against which\neverything in this chapter is measured. It is built from four assumptions, two per\nprocess, and the whole of its closed-form machinery follows mechanically from them.\n\n**Attrition.** A customer's unobserved lifetime $\\omega$ is exponential with rate\n$\\mu$,\n\n$$\nf(\\omega \\mid \\mu) = \\mu e^{-\\mu \\omega} ,\n$$ {#eq-cba-life}\n\nand $\\mu$ is Gamma-distributed across the population with shape $s$ and scale $\\beta$,\n\n$$\ng(\\mu) = \\frac{\\beta^{s} \\mu^{s-1} e^{-\\mu\\beta}}{\\Gamma(s)} .\n$$ {#eq-cba-gammamu}\n\nMixing @eq-cba-life over @eq-cba-gammamu gives the lifetime of a randomly chosen\ncustomer as a Pareto distribution of the second kind, which is where half the model's\nname comes from:\n\n$$\nf(\\omega) = \\int_{0}^{\\infty} f(\\omega \\mid \\mu) g(\\mu)\\, d\\mu\n          = \\frac{s}{\\beta}\\left(\\frac{\\beta}{\\beta+\\omega}\\right)^{s+1} .\n$$ {#eq-cba-pareto2}\n\n**Purchasing.** While alive, the customer buys according to a Poisson process with\nrate $\\lambda$, so that\n\n$$\nP(X(t) = x \\mid \\lambda,\\, t < \\omega) = \\frac{(\\lambda t)^{x} e^{-\\lambda t}}{x!},\n\\qquad x = 0, 1, 2, \\dots\n$$ {#eq-cba-poisson}\n\nand $\\lambda$ is Gamma-distributed with shape $r$ and scale $\\alpha$,\n\n$$\ng(\\lambda) = \\frac{\\alpha^{r} \\lambda^{r-1} e^{-\\lambda\\alpha}}{\\Gamma(r)} .\n$$ {#eq-cba-gammalambda}\n\nMixing @eq-cba-poisson over @eq-cba-gammalambda yields the negative binomial\ndistribution, the other half of the name:\n\n$$\nP(X(t) = x \\mid t < \\omega) = \\frac{\\Gamma(r+x)}{\\Gamma(r)\\,x!}\n  \\left(\\frac{\\alpha}{\\alpha+t}\\right)^{r}\\left(\\frac{t}{\\alpha+t}\\right)^{x} .\n$$ {#eq-cba-nbd}\n\n**The individual likelihood.** A customer observed to time $T$ with $x$ repeat\ntransactions, the last at $t_x$, is in one of two states: still alive ($\\omega > T$),\nor dead at some $\\omega \\in (t_x, T]$. Conditional on being alive throughout, the\nlikelihood is the product of exponential inter-transaction densities and the survivor\nterm, $\\lambda^{x} e^{-\\lambda T}$; conditional on dying at $\\omega$, it is\n$\\lambda^{x} e^{-\\lambda \\omega}$. Weighting the two branches by their probabilities\nand integrating out the death time gives\n\n$$\n\\begin{aligned}\nL(\\lambda, \\mu \\mid x, t_x, T)\n&= \\lambda^{x} e^{-\\lambda T} P(\\omega > T \\mid \\mu)\n + \\int_{t_x}^{T} \\lambda^{x} e^{-\\lambda\\omega} f(\\omega \\mid \\mu)\\, d\\omega \\\\\n&= \\frac{\\lambda^{x}\\mu}{\\lambda+\\mu} e^{-(\\lambda+\\mu)t_x}\n + \\frac{\\lambda^{x+1}}{\\lambda+\\mu} e^{-(\\lambda+\\mu)T} .\n\\end{aligned}\n$$ {#eq-cba-indlik}\n\nMarginalizing @eq-cba-indlik over the two Gamma mixing distributions produces a\nclosed-form expression in $(r, \\alpha, s, \\beta)$ involving the Gaussian\nhypergeometric function, and the four parameters are estimated by maximizing\n\n$$\n\\sum_{i=1}^{N} \\log L(r, \\alpha, s, \\beta \\mid x_i, t_{x_i}, T_i) .\n$$ {#eq-cba-loglik}\n\nTwo features of @eq-cba-indlik deserve emphasis because both are lost in the extension\nof @sec-cba-bmn.\n\n### Why Recency and Frequency Are Sufficient {#sec-cba-sufficiency}\n\nNotice what does *not* appear in @eq-cba-indlik: the timing of transactions\n$t_1, \\dots, t_{x-1}$. Only $t_x$ survives. This is a consequence of the memoryless\nproperty of the exponential inter-arrival times, and it is the reason the entire\nliterature summarizes a customer by the triple $(x, t_x, T)$. The practical payoff is\nenormous, a firm with ten million customers stores three numbers each, and it is why\nthese models scale to customer bases where a hierarchical Bayes alternative would not.\nThe interpretive payoff is the *iso-value curve* of @fader2005rfmclv: customers with\ndifferent histories but the same $(x, t_x)$ have identical predicted futures, which\nturns the recency-frequency grid of practitioner RFM scoring into a model-implied\nobject rather than a heuristic one.\n\nThe intuition behind the posterior is worth stating in words, because it is what makes\nthese models feel like inference rather than curve-fitting. Frequency and recency\ncarry opposite signals. Many purchases raise the estimate of $\\lambda$, which raises\nvalue; but many purchases *also* mean that a long recent silence is more surprising,\nwhich raises the posterior probability of death. A customer who bought twenty times\nand has been quiet for six months is in worse shape than one who bought twice and has\nbeen quiet for six months, because for the frequent buyer six months of silence is\nmany missed opportunities and for the infrequent buyer it is barely one. The models\nformalize precisely this trade-off, and it is not something an RFM score computed by\nhand gets right.\n\nRatifying the point, @wubben2008heuristics find that simple managerial heuristics\n(a hiatus rule: \"a customer is dead if they have not bought in $h$ periods\") often\nmatch the probability models for aggregate-level predictions, while\n@zhang2015clumpiness show that adding *clumpiness*, the degree to which purchases\narrive in bursts, to recency-frequency-monetary information improves individual-level\nprediction. Both results are about the same thing: how much of a purchase history the\n$(x, t_x, T)$ summary throws away.\n\n### The Model Zoo {#sec-cba-zoo}\n\nThe Pareto/NBD's inconvenience is computational: the hypergeometric functions in its\nmarginal likelihood are fragile to optimize. Most of the subsequent literature can be\nread as trading one distributional assumption for tractability or for realism.\n\n\n::: {#tbl-cba-zoo .cell layout-align=\"center\" tbl-cap='The latent-attrition model family. Each row swaps a distributional assumption of the Pareto/NBD for tractability, realism, or covariate capability. The right column is the reason the swap was made.'}\n::: {.cell-output-display}\n\n\n|Model                  |Attrition process                   |Transaction process                    |Bought what                                                |Source                         |\n|:----------------------|:-----------------------------------|:--------------------------------------|:----------------------------------------------------------|:------------------------------|\n|Pareto/NBD             |Exponential / Gamma                 |Poisson / Gamma                        |The reference specification                                |@paretonbd1987                 |\n|BG/NBD                 |Geometric after each buy / Beta     |Poisson / Gamma                        |Removes hypergeometrics; near-identical fit                |@fader2005bgnbd                |\n|MBG/NBD                |Geometric incl. at time 0 / Beta    |Poisson / Gamma                        |Fixes BG/NBD's inability to let zero-repeaters die         |@batislam2007                  |\n|BG/BB                  |Beta-Bernoulli (discrete)           |Beta-binomial (discrete)               |Correct estimand when opportunities are discrete           |@faderhardieshang2010          |\n|Pareto/GGG             |Exponential / Gamma                 |Gamma-timing (regularity) / Gamma      |Uses inter-purchase regularity, not just recency           |@platzerreutterer2016          |\n|GGom/NBD               |Gompertz / Gamma                    |Poisson / Gamma                        |Non-monotone (rising then falling) hazard of death         |@bemmaorglady2012              |\n|HB Pareto/NBD          |Exponential / lognormal             |Poisson / lognormal                    |Individual-level covariates and correlated processes       |@abe2009                       |\n|Pareto/NBD + dyn. cov. |Exp. with time-varying rate / Gamma |Poisson with time-varying rate / Gamma |Time-varying covariates with closed-form MLE               |@bachmann2021tvc               |\n|HMM                    |Markov states                       |State-dependent                        |Relationship states with transitions, not one death        |@netzer2008hmm                 |\n|Bayesian nonparametric |Exponential / nonparametric         |Poisson / nonparametric                |Drops the Gamma prior; visualizes the fitted heterogeneity |@dewansari2018                 |\n|Changepoint            |Exponential / Gamma                 |Poisson / Gamma                        |Structural breaks that hit whole acquisition cohorts       |@gopalakrishnan2017changepoint |\n\n\n:::\n:::\n\n\nThree of these rows carry lessons that recur later. @fader2005bgnbd's BG/NBD buys its\ntractability with a structural quirk: because dropout is a coin flip taken *after a\npurchase*, a customer who never repeats can never die, which @batislam2007 correct in\nthe MBG/NBD by allowing dropout at time zero. @jerath2011death generalize the death\nprocess itself, showing that \"death\" in these models is a modeling convention with\nconsequences for how quickly value is written off. And @bemmaorglady2012's\nGamma-Gompertz/NBD replaces the exponential lifetime with a Gompertz one so that the\nhazard of dying can rise and then fall, a shape the exponential cannot produce; the\nsubsequent comment by @adler2023comment on that paper's estimation is a useful\nreminder that closed forms in this literature are not always as closed as they look.\n\nAlongside the timing models sits the spend model. The de facto standard is the\nGamma-Gamma of @colombojiang1999 and @fader2005rfmclv. With $\\bar z = \\sum_{i=1}^{x} z_i / x$\nthe observed average transaction value, spend per transaction is Gamma with shape $p$\nand rate $\\nu$, $\\nu$ is itself Gamma with shape $q$ and scale $\\gamma$ across\ncustomers, and the marginal density of $\\bar z$ given $x$ is\n\n$$\nf(\\bar z \\mid p, q, \\gamma; x) = \\frac{1}{\\bar z\\, B(px, q)}\n  \\left(\\frac{\\gamma}{\\gamma + x\\bar z}\\right)^{q}\n  \\left(\\frac{x \\bar z}{\\gamma + x \\bar z}\\right)^{px} ,\n$$ {#eq-cba-gg}\n\nwith $B(\\cdot,\\cdot)$ the Beta function. Note what @eq-cba-gg does not contain: time.\nThe spend model is stationary by construction, and no published covariate extension of\nit was implemented at the time of writing [@meierer2026clvtools]. Everything this\nchapter says about covariates applies to the timing side only, which is a real\nlimitation when the marketing action being evaluated is a discount.\n\n## The Covariate Problem {#sec-cba-covariates}\n\nTwo motivations push against the covariate-free tradition, and they are worth keeping\nseparate because they impose different standards of proof.\n\nThe first is *prediction*. Gamma heterogeneity is a black box: it concedes that\ncustomers differ and declines to say how. If some of that dispersion is explained by\nobservables (acquisition channel, gender, region, tenure), moving it out of the mixing\ndistribution and into a systematic component should sharpen individual-level forecasts,\nwhich is where the Pareto/NBD is weakest.\n\nThe second is *inference*. A firm that mails a catalogue wants to know what the\ncatalogue did. This is a causal question dressed as a modeling one, and the covariate\ncoefficient answers it only under an exogeneity assumption that the firm's own\ntargeting rule usually violates. We return to this in @sec-cba-pitfalls; it is the\nsingle largest threat to the interpretation of these models, and the literature is\ncandid about it [@shugan2004endogeneity; @ebbes2011holdout].\n\n### Time-Invariant Covariates {#sec-cba-static}\n\nThe time-invariant extension, due to @faderhardie2007covariates, scales the two\nlatent rates multiplicatively:\n$\\lambda = \\lambda_0 \\exp(\\boldsymbol{\\gamma}_{purch}' \\mathbf{x}^{P})$ and\n$\\mu = \\mu_0 \\exp(\\boldsymbol{\\gamma}_{attr}' \\mathbf{x}^{A})$, with $\\lambda_0$ and\n$\\mu_0$ retaining their Gamma priors. Because the covariates are constants, the whole\nconstruction is a reparameterization: each customer's $\\alpha$ and $\\beta$ are simply\nrescaled, and the closed-form likelihood survives untouched. The coefficients are\nsemi-elasticities of the two rates [@gupta1991interpurchase]: a one-unit change in a\ncomponent of $\\mathbf{x}^{P}$ multiplies the average purchase rate by\n$\\exp(\\gamma_{purch})$, and for a covariate entered in logs the coefficient reads\ndirectly as a rate elasticity.\n\n### Why Time-Varying Is Different {#sec-cba-why-dynamic}\n\nTime-varying covariates break that convenience, and it is worth being precise about\nwhere. The literature groups them into two kinds [@platzerreutterer2016]: *seasonality*,\nwhich typically moves every customer at once (holidays, paydays, school terms), and\n*marketing activity*, which is often customer-specific (a catalogue mailed to this\nperson in week 30).\n\nThere is a direct antecedent worth naming, because @bachmann2021tvc's claim to novelty\nis narrower than it first appears. @schweidelknox2013 had already brought direct\nmarketing activity into a latent attrition model, and @vanoestknox2011 had brought\ncomplaints in. What was missing was a *general* treatment of arbitrary time-varying\ncovariates in the continuous-time Pareto/NBD that preserves the closed-form maximum\nlikelihood, and that is the gap being closed.\n\nOnce $\\lambda$ is a function of time, three things fail simultaneously.\n\nInter-transaction times are no longer identically distributed, so the exponential\nmemorylessness that collapsed the history to $(x, t_x, T)$ is gone: the distribution of\nthe gap between purchases $j-1$ and $j$ depends on *when* purchase $j-1$ happened,\nbecause that determines which covariate values were in force. The sufficient statistic\nbecomes the full vector $\\mathbf{t} = (t_1, \\dots, t_x)$.\n\nThe attrition density is no longer exponential either. It now depends on the entire\ncovariate path up to the death time, not on a single rate.\n\nAnd the infinite-horizon integral in @eq-cba-dert becomes undefined in practice,\nbecause it presumes knowledge of $\\lambda(t)$ for all future $t$, which is exactly what\na firm does not have for a covariate like \"was a catalogue mailed.\"\n\n@bachmann2021tvc resolve all three, and the resolution is the substance of this\nchapter.\n\n## Time-Varying Contextual Factors {#sec-cba-bmn}\n\n### Specification {#sec-cba-bmn-spec}\n\nLet $\\mathbf{x}^{P}(s)$ and $\\mathbf{x}^{A}(s)$ be functions mapping a time point $s$\nto the covariate vectors relevant to the purchase and attrition processes at that\nmoment. These are individual-level functions; the customer subscript is suppressed.\nThe key parameterization is that they are *piecewise constant* on a grid of equidistant\nintervals (a week, say), returning the value $\\mathbf{x}^{P}_k$ of the interval $k$\ncontaining $s$. The discretization is a property of the covariate data, not of the\nprocesses: the transaction and attrition processes remain continuous-time, and the\nintervals can be made arbitrarily fine.\n\nThe two rates then become\n\n$$\n\\lambda(t) = \\lambda_0 \\exp\\!\\big(\\boldsymbol{\\gamma}_{purch}' \\mathbf{x}^{P}(t)\\big),\n\\qquad\n\\mu(t) = \\mu_0 \\exp\\!\\big(\\boldsymbol{\\gamma}_{attr}' \\mathbf{x}^{A}(t)\\big),\n$$ {#eq-cba-tvrates}\n\nwith $\\lambda_0 \\sim \\text{Gamma}(r, \\alpha)$ and $\\mu_0 \\sim \\text{Gamma}(s, \\beta)$\nexactly as in @eq-cba-gammalambda and @eq-cba-gammamu. All the heterogeneity machinery\nof the original model is retained; what changes is that each customer's rate is now a\nstep function in time rather than a constant.\n\nThe purchase process becomes a *non-homogeneous* Poisson process. The number of\ntransactions in an interval $(s_1, s_2]$ is\n\n$$\nP\\big(X(s_1, s_2) = x \\mid \\lambda(t)\\big) = \\frac{[\\Lambda(s_1, s_2)]^{x}}{x!}\n  \\exp[-\\Lambda(s_1, s_2)],\n\\qquad\n\\Lambda(s_1, s_2) = \\int_{s_1}^{s_2} \\lambda(s)\\, ds .\n$$ {#eq-cba-nhpp}\n\nThe attrition density is driven by the cumulative hazard along the covariate path,\n\n$$\nf\\big(\\omega \\mid \\mu(t)\\big) = \\mu(\\omega) \\exp[-M(\\omega)],\n\\qquad\nM(\\omega) = \\int_{0}^{\\omega} \\mu(s)\\, ds .\n$$ {#eq-cba-tvdeath}\n\nBecause $\\lambda(\\cdot)$ and $\\mu(\\cdot)$ are piecewise constant, both integrals are\nfinite sums of rectangles, which is the entire trick: $\\Lambda$ and $M$ are available\nin closed form interval by interval, so the awkward objects in @eq-cba-nhpp and\n@eq-cba-tvdeath never require numerical integration.\n\n### The Likelihood {#sec-cba-bmn-lik}\n\nCombining the two processes gives an individual likelihood\n\n$$\nL\\big(\\alpha, r, \\beta, s, \\boldsymbol{\\gamma}_{purch}, \\boldsymbol{\\gamma}_{attr}\n  \\mid \\mathbf{X}^{P}, \\mathbf{X}^{A}, x, \\mathbf{t}, T\\big),\n$$ {#eq-cba-tvlik}\n\nwhere the covariate histories enter as the full sequences\n$\\mathbf{X}^{P} = (\\mathbf{x}^{P}_1, \\dots, \\mathbf{x}^{P}_{k_T})$ and\n$\\mathbf{X}^{A} = (\\mathbf{x}^{A}_1, \\dots, \\mathbf{x}^{A}_{k_T})$ over the $k_T$\nintervals covering the observation window.\n\nThe structural result of @bachmann2021tvc is that @eq-cba-tvlik remains *closed form*.\nIt is a sum of terms each of which has the same functional shape as the standard\nPareto/NBD likelihood @eq-cba-indlik, evaluated on a single covariate interval. The\ncustomer's death, if it occurred, happened in exactly one interval; conditioning on\nwhich interval that was, the rates are constant within it, and the standard algebra\napplies. Summing over the intervals in which death could have occurred, weighted by\nthe probability of surviving to each, reassembles the likelihood. No simulation, no\ndata augmentation, no MCMC: the model is still maximum likelihood, and it still runs on\na laptop for a customer base in the millions.\n\nThe price is the one flagged in @sec-cba-why-dynamic: the likelihood now contains\n$\\mathbf{t} = (t_1, \\dots, t_x)$, every transaction date, not just the last. Recency is\nno longer sufficient. Data storage grows from three numbers per customer to a full\ntransaction log plus a covariate panel with one row per customer-period, and estimation\ntime grows with it, from seconds to minutes on the data in @sec-cba-replication.\n\n### DECT, Not DERT {#sec-cba-bmn-dect}\n\nThe managerial expressions change in one visible way. DERT in @eq-cba-dert integrates\nto infinity, which under @eq-cba-tvrates would require the analyst to assert covariate\nvalues for all future time. @bachmann2021tvc therefore define the *discounted expected\nconditional transactions* (DECT), the same discounted quantity over a **finite** horizon\nfor which covariate paths are actually available. Software reports DECT in place of\nDERT whenever a model carries time-varying covariates [@meierer2026clvtools], and the\nsubstitution is not cosmetic: DECT is bounded by the horizon and will generally be\nsmaller than the DERT the same customer would have been assigned by a covariate-free\nmodel. Comparing a covariate model's CLV to a base model's CLV without noticing this\nsubstitution is a live way to produce a spurious \"the covariates destroyed value\"\nfinding.\n\n### Nesting and What Identifies the Coefficients {#sec-cba-bmn-nesting}\n\nThe specification nests cleanly. Set $\\boldsymbol{\\gamma}_{purch} =\n\\boldsymbol{\\gamma}_{attr} = \\mathbf{0}$ and @eq-cba-tvlik returns the standard\nPareto/NBD; hold the covariates constant across all intervals and it returns the\ntime-invariant extension of @sec-cba-static. Model comparison is therefore a likelihood\nratio test on nested specifications, and the AIC/BIC ordering across the three is\ninterpretable.\n\nIdentification of $\\boldsymbol{\\gamma}_{purch}$ comes from *within-customer, over-time*\nvariation: whether this customer's purchases cluster in the intervals when the\ncovariate was high. Identification of $\\boldsymbol{\\gamma}_{attr}$ is more delicate and\ncomes from the timing of the *last* observed transaction relative to the covariate\npath, since the model must attribute a long silence either to a low purchase rate or to\ndeath. This asymmetry is why the attrition coefficients in @sec-cba-replication are\nestimated far less precisely than the transaction coefficients, and why practitioners\nwho care mainly about prediction sometimes include covariates only in the purchase\nprocess, halving the parameter count for most of the accuracy gain.\n\n## Advanced Extensions {#sec-cba-advanced}\n\n### Correlated Processes {#sec-cba-sarmanov}\n\nEvery model so far assumes $\\lambda \\perp \\mu$: how often a customer buys tells you\nnothing about how quickly they will churn. That is a strong claim, and\n@glady2015unveiling reject it empirically. The Sarmanov family provides a tractable\ndependence structure, writing the joint density as the independent product plus a\ncorrection term built from the same univariate densities:\n\n$$\n\\begin{aligned}\ng(\\lambda, \\mu \\mid \\alpha, r, \\beta, s, m)\n&= g(\\lambda \\mid r, \\alpha)\\, g(\\mu \\mid s, \\beta) \\\\\n&\\quad + m \\left(\\frac{\\alpha}{1+\\alpha}\\right)^{r}\\left(\\frac{\\beta}{1+\\beta}\\right)^{s}\n \\big[g(\\lambda \\mid r, \\alpha+1) - g(\\lambda \\mid r, \\alpha)\\big]\n \\big[g(\\mu \\mid s, \\beta+1) - g(\\mu \\mid s, \\beta)\\big] .\n\\end{aligned}\n$$ {#eq-cba-sarmanov}\n\nThe mechanism is transparent once you see that $g(\\lambda \\mid r, \\alpha+1)$ is smaller\nthan $g(\\lambda \\mid r, \\alpha)$ for large $\\lambda$, so each bracket is negative in the\nupper tail and the product is positive there. A positive $m$ therefore piles density\nwhere both rates are high or both are low. Because @eq-cba-sarmanov is a linear\ncombination of independent-case densities, the correlated likelihood is a linear\ncombination of independent-case *likelihoods*: writing $\\tilde L(\\alpha, \\beta)$ for the\nuncorrelated likelihood,\n\n$$\n\\begin{aligned}\nL(\\alpha, r, \\beta, s, m \\mid x, t, T) &= \\tilde L(\\alpha, \\beta)\n + m \\left(\\frac{\\alpha}{1+\\alpha}\\right)^{r}\\left(\\frac{\\beta}{1+\\beta}\\right)^{s} \\\\\n&\\quad \\times \\big[\\tilde L(\\alpha+1, \\beta+1) - \\tilde L(\\alpha+1, \\beta)\n - \\tilde L(\\alpha, \\beta+1) + \\tilde L(\\alpha, \\beta)\\big] .\n\\end{aligned}\n$$ {#eq-cba-sarmanov-lik}\n\nThe parameter $m$ is not itself a correlation; the implied correlation is\n\n$$\np_m = m\\, \\frac{\\sqrt{r}}{1+\\alpha}\\left(\\frac{\\alpha}{1+\\alpha}\\right)^{r}\n        \\frac{\\sqrt{s}}{1+\\beta}\\left(\\frac{\\beta}{1+\\beta}\\right)^{s} .\n$$ {#eq-cba-sarmanov-corr}\n\nA positive $p_m$ says heavy buyers churn faster, which is the empirically common sign\nin categories where high frequency signals a short, intense relationship rather than\nloyalty.\n\n### Regularization and Equality Constraints {#sec-cba-reg}\n\nTwo further devices matter once covariate counts grow. Placing Gaussian priors\n$\\boldsymbol{\\gamma}_{purch} \\sim N(0, 1/\\lambda_1^{reg} I)$ and\n$\\boldsymbol{\\gamma}_{attr} \\sim N(0, 1/\\lambda_2^{reg} I)$ turns estimation into the\npenalized problem\n\n$$\n\\arg\\max \\sum_{i=1}^{n} L\\big(\\cdot \\mid \\mathbf{X}^{P}_i, \\mathbf{X}^{A}_i, x_i,\n  \\mathbf{t}_i, T_i\\big)\n - \\lambda_1^{reg}\\|\\boldsymbol{\\gamma}_{purch}\\|^{2}\n - \\lambda_2^{reg}\\|\\boldsymbol{\\gamma}_{attr}\\|^{2} ,\n$$ {#eq-cba-reg}\n\nan $L_2$ penalty that stabilizes an otherwise ill-conditioned optimization. (The symbol\n$\\lambda^{reg}$ here is a regularization weight and has nothing to do with the purchase\nrate $\\lambda$; the collision is unfortunate and standard.)\n\nThe second device is inferentially more interesting. Imposing\n\n$$\n\\boldsymbol{\\gamma}_{purch} \\equiv \\boldsymbol{\\gamma}_{attr}\n$$ {#eq-cba-constraint}\n\nfor a covariate present in both processes forces the optimizer to use one coefficient\nfor both. The constrained model is a valid null against which a likelihood ratio test\nasks a genuinely managerial question: *does this marketing activity affect purchasing\nand churning differently?* A campaign that lifts transactions while also accelerating\nattrition is a campaign that borrows from the future, and @eq-cba-constraint is how the\nmodel is made to answer whether that is happening.\n\n```{mermaid}\n%%| label: fig-cba-structure\n%%| fig-cap: \"The generative structure of a covariate-extended latent attrition model. The two shaded inserts are what @bachmann2021tvc add: multiplicative, time-indexed scaling of both latent rates. The spending process remains stationary and covariate-free, which bounds what the model can say about price and promotion.\"\nflowchart TB\n  L0[\"Purchase heterogeneity<br/>lambda_0 ~ Gamma(r, alpha)\"] --> LT\n  CP[\"Time-varying covariates<br/>lambda(t) = lambda_0 x exp(gamma_purch' x_P(t))\"] --> LT\n  M0[\"Attrition heterogeneity<br/>mu_0 ~ Gamma(s, beta)\"] --> MT\n  CA[\"Time-varying covariates<br/>mu(t) = mu_0 x exp(gamma_attr' x_A(t))\"] --> MT\n  MT[\"Attrition rate path mu(t)\"] --> W[\"Unobserved lifetime<br/>omega ~ Exp with cumulative hazard M(omega)\"]\n  LT[\"Purchase rate path lambda(t)\"] --> B[\"Purchases t_j ~ non-homogeneous<br/>Poisson on (0, omega]\"]\n  W --> B\n  B --> DT[\"CET and DECT<br/>(finite horizon)\"]\n  S0[\"Spending heterogeneity<br/>nu ~ Gamma(q, gamma)\"] --> SP[\"Spend z_j ~ Gamma(p, nu)<br/>stationary, no covariates\"]\n  SP --> ES[\"Expected spend per transaction\"]\n  DT --> CLV[\"Predicted CLV = DECT x E(m)\"]\n  ES --> CLV\n```\n\n## Replication: An Apparel Retailer's Acquisition Cohort {#sec-cba-replication}\n\nEverything above is now estimated on real transaction data. We use the apparel retailer\ndata that ships with `CLVTools` [@clvtoolspkg], the package written by the authors of\n@bachmann2021tvc, which is also the running case study in their software paper\n[@meierer2026clvtools]. Using their data and their implementation makes this a genuine\nreplication: the coefficients reported below can be checked against the published ones.\n\n### The Data {#sec-cba-data}\n\n`apparelTrans` is a single acquisition cohort, all 600 customers made their first\npurchase on 2005-01-02, observed for six years. `apparelStaticCov` carries two\ntime-invariant covariates (gender, acquisition channel) and `apparelDynCov` carries a\nweekly `High.Season` indicator alongside repeated copies of the time-invariant ones,\nbecause the dynamic-covariate interface requires one row per customer-week.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(CLVTools)\nlibrary(data.table)\nlibrary(dplyr)\nlibrary(knitr)\n\ndata(\"apparelTrans\")\ndata(\"apparelStaticCov\")\ndata(\"apparelDynCov\")\ndata(\"apparelDynCovFuture\")\n\nhead(apparelTrans, 3)\n#>        Id       Date  Price\n#>    <char>     <Date>  <num>\n#> 1:      1 2005-01-02 230.30\n#> 2:      1 2005-09-06  84.39\n#> 3:      1 2006-01-18 131.07\nhead(apparelDynCov, 3)\n#>        Id   Cov.Date High.Season Gender Channel\n#>    <char>     <Date>       <num>  <num>   <num>\n#> 1:      1 2005-01-02           0      0       0\n#> 2:      1 2005-01-09           0      0       0\n#> 3:      1 2005-01-16           0      0       0\n```\n:::\n\n\nWe split the history into a 104-week estimation period and leave everything after it as\nholdout. That split is a modelling decision with real content: @sec-cba-pitfalls returns\nto why two years, rather than one, is the right default when seasonality is present.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclv.apparel <- clvdata(apparelTrans, date.format = \"ymd\", time.unit = \"week\",\n                       estimation.split = 104,\n                       name.id = \"Id\", name.date = \"Date\", name.price = \"Price\")\nsummary(clv.apparel)\n#> CLV Transaction Data \n#>                                 \n#> Time unit         Weeks         \n#> Estimation length 104.0000 Weeks\n#> Holdout length    207.0000 Weeks\n#> \n#> Transaction Data Summary \n#>                                    Estimation      Holdout         Total     \n#> Period Start                       2005-01-02      2007-01-01      2005-01-02\n#> Period End                         2006-12-31      2010-12-20      2010-12-20\n#> Number of customers                -               -               600       \n#> First Transaction in period        2005-01-02      2007-01-01      2005-01-02\n#> Last Transaction in period         2006-12-31      2010-12-20      2010-12-20\n#> Total # Transactions               1866            1317            3183      \n#> Mean # Transactions per cust       3.110           5.557           5.305     \n#> (SD)                               2.714           5.123           6.119     \n#> Mean Spending per Transaction      40.545          36.977          39.069    \n#> (SD)                               73.362          55.356          66.519    \n#> Total Spending                     75657.730       48699.170       124356.900\n#> Total # zero repeaters             213             -               -         \n#> Percentage of zero repeaters       35.500          -               -         \n#> Mean Interpurchase time            24.823          30.604          37.817    \n#> (SD)                               19.417          24.756          42.339\n```\n:::\n\n\nThe summary reports the number that governs everything downstream: 35.5% of the cohort\nare *zero repeaters*, customers who bought once and never returned. A latent-attrition\nmodel has to place those customers somewhere, and the choice of death process\n(@sec-cba-zoo) is largely a fight over how fast to write them off.\n\n### Baseline: Pareto/NBD and Gamma-Gamma {#sec-cba-repl-base}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nest.pnbd <- latentAttrition(family = pnbd, data = clv.apparel, verbose = FALSE)\nround(coef(est.pnbd), 4)\n#>       r   alpha       s    beta \n#>  1.4490 48.6361  0.5613 46.8844\n\nest.gg <- spending(family = gg, data = clv.apparel, verbose = FALSE)\nround(coef(est.gg), 3)\n#>      p      q  gamma \n#>  3.099  5.654 56.504\n```\n:::\n\n\nThese reproduce the published estimates exactly: $r = 1.4490$, $\\alpha = 48.6361$,\n$s = 0.5613$, $\\beta = 46.8844$ for the timing model and $p = 3.099$, $q = 5.654$,\n$\\gamma = 56.504$ for the spend model [@meierer2026clvtools]. The ratios are the\ninterpretable quantities: $r/\\alpha \\approx 0.030$ is the average customer's weekly\npurchase rate and $s/\\beta \\approx 0.012$ the average weekly attrition rate.\n\nResist the temptation to invert that second number into a mean lifetime. The reciprocal\n$\\beta/s \\approx 84$ weeks is a convenient scale but it is not $E[\\omega]$: the mean of\nthe Pareto II lifetime distribution in @eq-cba-pareto2 is $\\beta/(s-1)$, which for\n$s = 0.5613 < 1$ does not exist. The fitted mixture puts enough mass near $\\mu = 0$ that\nthe population contains effectively immortal customers, which is the formal version of\nthe caution in @schmittleinpeterson1994 about long estimation windows and is a standing\nreason to report DERT or DECT, which are discounted and therefore finite, rather than an\nexpected lifetime.\n\n### Adding Time-Invariant Covariates {#sec-cba-repl-static}\n\nThe formula interface takes a two-part right-hand side with no dependent variable,\nbecause the dependent variables ($x_i$, $t_{x_i}$, $T_i$) are derived from the\ntransaction log rather than supplied. The part before the `|` selects covariates for the\n*attrition* process, the part after for the *purchase* process.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclv.static <- SetStaticCovariates(\n  clv.data = clv.apparel,\n  data.cov.life  = apparelStaticCov, data.cov.trans = apparelStaticCov,\n  names.cov.life = c(\"Gender\", \"Channel\"),\n  names.cov.trans = c(\"Gender\", \"Channel\"),\n  name.id = \"Id\")\n\nest.static <- latentAttrition(formula = ~ Gender + Channel | Gender + Channel,\n                              family = pnbd, data = clv.static, verbose = FALSE)\nsummary(est.static)\n#> Pareto/NBD with Static Covariates  Model \n#> \n#> Call:\n#> latentAttrition(formula = ~Gender + Channel | Gender + Channel, \n#>     family = pnbd, data = clv.static, verbose = FALSE)\n#> \n#> Fitting period:                                \n#> Estimation start  2005-01-02    \n#> Estimation end    2006-12-31    \n#> Estimation length 104.0000 Weeks\n#> \n#> Coefficients:\n#>               Estimate Std. Error  z-val Pr(>|z|)    \n#> r               1.8378     0.3455     NA       NA    \n#> alpha          92.9123    16.9670     NA       NA    \n#> s               0.5920     0.2609     NA       NA    \n#> beta           49.6227    36.2509     NA       NA    \n#> life.Gender    -0.6430     0.2955 -2.176  0.02957 *  \n#> life.Channel    0.7907     0.3059  2.585  0.00973 ** \n#> trans.Gender    0.2859     0.1041  2.745  0.00605 ** \n#> trans.Channel   0.6241     0.1050  5.946 2.74e-09 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Optimization info:                 \n#> LL     -5821.0627\n#> AIC    11658.1254\n#> BIC    11693.3009\n#> KKT 1  TRUE      \n#> KKT 2  TRUE      \n#> fevals 41.0000   \n#> Method L-BFGS-B  \n#> \n#> Used Options:                     \n#> Correlation     FALSE\n#> Regularization  FALSE\n#> Constraint covs FALSE\n```\n:::\n\n\nThe coefficients are rate multipliers on the log scale. Female customers (coded 1) have\na purchase rate $\\exp(0.2859) \\approx 1.33$ times that of male customers, and\ncustomers acquired offline (coded 1) purchase about $\\exp(0.6241) \\approx 1.87$ times as\noften, but their attrition rate is $\\exp(0.7907) \\approx 2.20$ times higher: they buy\nmore and leave sooner. That pattern, an acquisition channel that looks excellent on\nfrequency and mediocre on retention, is exactly the kind of finding a covariate-free\nmodel cannot produce, and it changes what the retailer should pay for an offline\nacquisition.\n\nNote that the four base parameters $r, \\alpha, s, \\beta$ are reported without $z$- or\n$p$-values. They are constrained strictly positive, so the null $\\theta = 0$ lies\noutside the admissible parameter space and a Wald test against it is meaningless. The\nsoftware reports `NA` rather than a misleading number.\n\n### Adding Time-Varying Covariates {#sec-cba-repl-dynamic}\n\nThe dynamic-covariate data must supply a value for every customer in every period, and\nthe time unit of the covariate panel must match the time unit of the transaction object.\nEstimation is materially more expensive, so we disable the Hessian (and therefore the\nKKT checks and standard errors) as the authors recommend for a first pass.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclv.mixed <- SetDynamicCovariates(\n  clv.data = clv.apparel,\n  data.cov.life  = apparelDynCov, data.cov.trans = apparelDynCov,\n  names.cov.life = c(\"High.Season\", \"Gender\", \"Channel\"),\n  names.cov.trans = c(\"High.Season\", \"Gender\", \"Channel\"),\n  name.id = \"Id\", name.date = \"Cov.Date\")\n\nest.mixed <- latentAttrition(\n  formula = ~ Gender + Channel + High.Season | Gender + Channel + High.Season,\n  family = pnbd, data = clv.mixed, verbose = FALSE,\n  optimx.args = list(hessian = FALSE, control = list(kkt = FALSE)))\n\nround(coef(est.mixed), 4)\n#>                 r             alpha                 s              beta \n#>            1.9777          115.1779            2.0127          158.1818 \n#>       life.Gender      life.Channel  life.High.Season      trans.Gender \n#>           -0.5125            0.5057           -2.4827            0.2649 \n#>     trans.Channel trans.High.Season \n#>            0.6137            0.7183\n```\n:::\n\n\nThe high-season coefficient on the transaction process is the headline. Purchasing runs\nat roughly $\\exp(0.72) \\approx 2.05$ times its base rate in high-season weeks. The\ncorresponding attrition coefficient is large and negative, which reads as customers\nbeing far less likely to lapse during the season, but this is the coefficient the\nidentification argument in @sec-cba-bmn-nesting warns about: it is pinned down by the\ntiming of last observed transactions relative to the seasonal calendar, and it should be\ntreated as a nuisance parameter absorbing seasonal structure rather than as an estimate\nof a seasonal retention effect.\n\n### Does Any of It Help Out of Sample? {#sec-cba-repl-holdout}\n\nThe three models are nested, so the fair comparison is out-of-sample accuracy on the\nholdout period. The metric must be built on CET, the finite-horizon conditional expected\ntransactions, because DERT and DECT incorporate discounting and cannot be compared\nagainst a raw observed count.\n\n\n::: {#tbl-cba-holdout .cell layout-align=\"center\" tbl-cap='Out-of-sample accuracy on the 207-week holdout period, in transactions per customer. Each row is a nested restriction of the row below it. Time-varying covariates cut mean absolute error by roughly nine percent relative to the covariate-free Pareto/NBD; time-invariant covariates alone buy almost nothing.'}\n\n```{.r .cell-code}\nmae  <- function(x, y) mean(abs(x - y))\nrmse <- function(x, y) sqrt(mean((x - y)^2))\n\nacc <- function(fit, label) {\n  p <- predict(fit, verbose = FALSE)\n  data.frame(Model = label,\n             MAE  = mae(p$CET, p$actual.x),\n             RMSE = rmse(p$CET, p$actual.x))\n}\n\nbind_rows(\n  acc(est.pnbd,  \"Pareto/NBD, no covariates\"),\n  acc(est.static, \"+ time-invariant covariates\"),\n  acc(est.mixed,  \"+ time-varying covariates\")\n) |>\n  mutate(across(where(is.numeric), \\(z) round(z, 4))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Model                       |    MAE|   RMSE|\n|:---------------------------|------:|------:|\n|Pareto/NBD, no covariates   | 2.0396| 3.3294|\n|+ time-invariant covariates | 2.0069| 3.2768|\n|+ time-varying covariates   | 1.8578| 3.2536|\n\n\n:::\n:::\n\n\nThe published comparison reports MAE of 2.0395, 2.0069 and 1.8578 and RMSE of 3.3294,\n3.2768 and 3.2536 for the three specifications [@meierer2026clvtools]. Our\ntime-invariant and time-varying rows match to all four decimals; the covariate-free row\ndiffers in the fourth (2.0396 against 2.0395), a consequence of the optimizer's stopping\ntolerance rather than of the model.\n\nTwo things are worth reading off @tbl-cba-holdout. First, the gain is real but modest,\nabout nine percent of MAE, which is a useful calibration against the enthusiasm the\ncovariate literature sometimes generates. Second, essentially all of it comes from the\n*time-varying* covariate; the time-invariant ones move MAE by 1.6%. The seasonal\nindicator is doing the work, and it is doing it because it lets the model attribute a\npurchase-free stretch to a low season rather than to death. That is precisely the\nconfusion between \"quiet\" and \"dead\" that latent-attrition modelling exists to manage,\nand the covariate is telling the model when to stop worrying.\n\nThe tracking plot makes the mechanism visible: the covariate-free model can only\nproduce a smooth decay, while the seasonal model tracks the spikes.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(est.pnbd, which = \"tracking\", cumulative = FALSE, verbose = FALSE,\n     other.models = list(est.static, est.mixed),\n     label = c(\"No covariates\", \"Time-invariant\", \"Time-invariant & -varying\"))\n```\n\n::: {.cell-output-display}\n![Weekly repeat transactions, actual versus fitted, for the three nested specifications. The dashed line marks the end of the estimation period. Only the model with the time-varying seasonal covariate can produce the peaks; the other two can only trend.](13a-customer-base-analysis_files/figure-html/fig-cba-tracking-1.png){#fig-cba-tracking fig-align='center' width=85%}\n:::\n:::\n\n\n### Testing a Restriction: Equality Constraints {#sec-cba-repl-constraints}\n\n@eq-cba-constraint says a covariate can be forced to carry the same coefficient in both\nprocesses. Fitting the constrained model and comparing log-likelihoods gives a\nlikelihood ratio test of whether the covariate acts differently on buying and on\nleaving.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nest.constr <- latentAttrition(\n  formula = ~ . | ., names.cov.constr = \"Gender\",\n  family = pnbd, data = clv.mixed, verbose = FALSE,\n  optimx.args = list(hessian = FALSE, control = list(kkt = FALSE)))\n\nlr <- 2 * (as.numeric(logLik(est.mixed)) - as.numeric(logLik(est.constr)))\ndata.frame(\n  Model = c(\"Unconstrained\", \"Gender constrained equal across processes\"),\n  logLik = round(c(as.numeric(logLik(est.mixed)), as.numeric(logLik(est.constr))), 3),\n  k = c(length(coef(est.mixed)), length(coef(est.constr)))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Model                                     |    logLik|  k|\n|:-----------------------------------------|---------:|--:|\n|Unconstrained                             | -5752.937| 10|\n|Gender constrained equal across processes | -5760.335|  9|\n\n\n:::\n\n```{.r .cell-code}\n\ncat(sprintf(\"LR statistic = %.3f on 1 df, p = %.3f\\n\", lr, pchisq(lr, 1, lower.tail = FALSE)))\n#> LR statistic = 14.796 on 1 df, p = 0.000\n```\n:::\n\n\nThe restriction is rejected: forcing gender to act identically on buying and on leaving\ncosts about 7.4 log-likelihood points, an LR statistic near 14.8 on one degree of\nfreedom ($p \\approx 0.0001$). Substantively that is the static-covariate finding of @sec-cba-repl-static\nrestated as a test, since gender raised the purchase rate and lowered the attrition\nrate there. The restriction, not the parameter, is the interesting object. Applied to a\nmarketing covariate rather than a demographic one, the same test asks whether a campaign\nbuys transactions at the cost of accelerated attrition, and answers it inside the model\nthat generated the CLV number rather than in a separate regression.\n\n### Correlated Processes in the Data {#sec-cba-repl-cor}\n\n@eq-cba-sarmanov-lik is available as a switch. Fitting the covariate-free model with\nthe Sarmanov correlation turned on adds one parameter, reported directly on the\ncorrelation scale via @eq-cba-sarmanov-corr.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nest.cor <- latentAttrition(family = pnbd, data = clv.apparel,\n                           use.cor = TRUE, verbose = FALSE)\nround(coef(est.cor), 4)\n#>               r           alpha               s            beta Cor(life,trans) \n#>          1.4705         48.5546          0.2462         11.2052         -0.0010\n```\n:::\n\n\nThe estimated correlation is essentially zero for this cohort, so purchase frequency\ncarries no information about churn propensity here beyond what recency already conveys.\nNote, though, how much the attrition parameters move ($s$ and $\\beta$ both fall\nsharply) once the correlation parameter is free: the likelihood surface is flat in a\ndirection that trades attrition heterogeneity against dependence. This is the usual\noutcome in applied work, and it is why practitioners often skip the correlation\nparameter, but the flatness itself is a warning about how precisely the attrition side\nof these models is identified at all.\n\n### Predicting Past the End of the Data {#sec-cba-repl-future}\n\nHere the time-varying model imposes a requirement no other model in this chapter does.\nTo predict forward, the analyst must supply covariate values *for the entire prediction\nhorizon*. This is why so few time-varying covariates are usable in production: a firm\ndoes not know next quarter's catalogue schedule at the moment of estimation. Seasonality\nis the honourable exception, because holidays and school terms are known in advance,\nand it is not a coincidence that the seasonal indicator is the covariate that earns its\nkeep in @tbl-cba-holdout.\n\n`apparelDynCovFuture` extends the covariate panel roughly two years beyond the last\nrecorded purchase. Note that the fitted model is *not* re-estimated; the extended\ncovariate panel is passed to `predict()` as new data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclv.full <- clvdata(apparelTrans, date.format = \"ymd\", time.unit = \"week\",\n                    estimation.split = NULL,\n                    name.id = \"Id\", name.date = \"Date\", name.price = \"Price\")\n\ncovs.all <- rbind(apparelDynCov, apparelDynCovFuture)\n\nclv.full.cov <- SetDynamicCovariates(\n  clv.data = clv.full,\n  data.cov.life = covs.all, data.cov.trans = covs.all,\n  names.cov.life = c(\"High.Season\", \"Gender\", \"Channel\"),\n  names.cov.trans = c(\"High.Season\", \"Gender\", \"Channel\"),\n  name.id = \"Id\", name.date = \"Cov.Date\")\n\npred.future <- predict(est.mixed, newdata = clv.full.cov,\n                       predict.spending = est.gg,\n                       prediction.end = 60,\n                       continuous.discount.factor = log(1.075) / 52,\n                       verbose = FALSE)\n\nas.data.frame(pred.future) |>\n  head(6) |>\n  mutate(across(where(is.numeric), \\(z) round(z, 3))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Id  |period.first |period.last | period.length| PAlive|   CET|  DECT| predicted.mean.spending| predicted.period.spending| predicted.period.CLV|\n|:---|:------------|:-----------|-------------:|------:|-----:|-----:|-----------------------:|-------------------------:|--------------------:|\n|1   |2010-12-21   |2012-02-13  |            60|  0.006| 0.008| 0.007|                  88.646|                     0.677|                0.649|\n|10  |2010-12-21   |2012-02-13  |            60|  0.631| 1.586| 1.519|                  35.248|                    55.894|               53.535|\n|100 |2010-12-21   |2012-02-13  |            60|  0.810| 4.492| 4.303|                  37.123|                   166.772|              159.735|\n|101 |2010-12-21   |2012-02-13  |            60|  0.085| 0.007| 0.007|                  34.563|                     0.241|                0.231|\n|102 |2010-12-21   |2012-02-13  |            60|  0.004| 0.004| 0.004|                  37.628|                     0.152|                0.145|\n|103 |2010-12-21   |2012-02-13  |            60|  0.258| 0.020| 0.019|                  33.471|                     0.657|                0.629|\n\n\n:::\n:::\n\n\nTwo conventions in that call are worth spelling out. The discount factor is continuous\nand expressed per time unit: for a discrete annual rate $d$ and $k$ periods per year,\n$\\delta_k = \\ln(1+d)/k$, so a 7.5% annual rate on weekly data is $\\ln(1.075)/52$. And\nthe returned value column is a *period* CLV rather than an infinite-horizon one, because\nDECT has replaced DERT (@sec-cba-bmn-dect).\n\n## What Breaks {#sec-cba-pitfalls}\n\nThe models above are easy to fit and easy to misinterpret. Six failure modes account\nfor most of the damage.\n\n**Endogenous covariates.** The coefficient on \"was mailed a catalogue\" is a causal\neffect only if mailing was as good as random. It never is: firms mail the customers a\nscoring model says will respond, so the covariate is a function of the same latent\n$\\lambda$ the model is trying to estimate, and the coefficient absorbs the targeting\nrule. @bachmann2021tvc address this directly with instrumental variables; where\ninstruments are unavailable, internal-instrument methods exist [@gui2023rendo], and the\ncontrol-function tradition [@riversvuong1988; @wooldridge2015control] supplies the\ngeneral machinery. @shugan2004endogeneity is the standing warning for marketing\ngenerally; @hruschka2010catalog and @schroderhruschka2016 work the specific catalogue\ncase.\n\n**Holdout validation does not rescue you.** The natural defence, \"my covariate model\npredicts better out of sample, so the coefficient must be right,\" is invalid.\n@ebbes2011holdout show formally that holdout performance does not discriminate between\nan endogenous and an exogenous specification: the endogenous model can predict better\n*because* the endogeneity encodes information about the firm's targeting. Prediction and\nidentification are separate claims requiring separate evidence, and @tbl-cba-holdout\nlicenses only the first.\n\n**Cohort construction.** These models assume a homogeneous-enough population. The\nstandard defence is to fit per acquisition cohort, which is why `apparelTrans` is a\nsingle cohort. Recommendations on minimum cohort size cluster in the 750-1,600 range,\nthough smaller samples of 250-500 have been found workable, and covariates offer an\nalternative to splitting: cohort dummies inside one model preserve sample size while\nabsorbing cohort effects [@meierer2026clvtools]. @faderhardieross2022 argue for merging\nold cohorts once the distinctions stop being managerially interesting.\n\n**Estimation window.** The window must be at least as long as the average interpurchase\ntime, and should be extended to 24 months when seasonality is present, so that the\nseasonal covariate has more than one cycle to be identified from. Yet\n@schmittleinpeterson1994 caution in the other direction: with very long histories,\nBayesian updating drives some customers' $\\mu$ toward zero and produces unrealistically\nimmortal customers. There is no universally right window, which is an argument for\nreporting sensitivity to it.\n\n**The first transaction.** By convention these models discard the first purchase and\nmodel repeat behaviour, because the first purchase defines cohort membership rather than\nongoing behaviour. But if a separate signup event exists (a loyalty enrolment, a free\ntrial), cohort membership can be defined by that instead, and the first purchase counted.\nThe spending model follows a different convention again, excluding the first transaction\nby default because initial baskets are atypical, which means a CLV built by multiplying\n*all* expected transactions by a repeat-only spend estimate is internally inconsistent.\n\n**Computational and data cost.** The dynamic-covariate model on this 600-customer cohort\ntakes on the order of a minute where the covariate-free model takes under a second, and\nrequires a covariate panel with one row per customer-period rather than three numbers per\ncustomer. It also defaults to Nelder-Mead rather than L-BFGS-B, because the surface is\nharder. At production scale this is the difference between a nightly job and a weekly one.\n\n## The Literature, Journal by Journal {#sec-cba-journals}\n\nCustomer-base analysis is unusual among marketing topics in having a clearly dominant\nhome journal and a clearly delineated set of neighbours. What follows maps the terrain\nby venue, because the venue determines what a contribution has to look like.\n\n\n::: {#tbl-cba-journals .cell layout-align=\"center\" tbl-cap='Where customer-base analysis is published and what each venue rewards. The \\'contribution that clears the bar\\' column is the practical statement of each journal\\'s revealed preference, inferred from the exemplar papers listed.'}\n::: {.cell-output-display}\n\n\n|Venue                                |Contribution that clears the bar                                                                           |Exemplars                                                                                      |\n|:------------------------------------|:----------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------|\n|Marketing Science                    |A new stochastic process, or a generalization that nests the incumbent and beats it out of sample          |@fader2005bgnbd, @jerath2011death, @schweidelknox2013, @platzerreutterer2016, @bachmann2021tvc |\n|Journal of Marketing Research        |A substantive marketing finding, often experimental or valuation-oriented, where the model is instrumental |@fader2005rfmclv, @braun2015transaction, @ascarza2018futility, @mccarthyfader2018              |\n|Journal of Marketing                 |Managerial consequence: what the customer base is worth and what to do about it                            |@reinartzkumar2000, @reinartzkumar2003, @wubben2008heuristics, @mccarthy2017                   |\n|Management Science                   |Methodological generality; models of firm-level or multi-service dynamics                                  |@paretonbd1987, @borle2008clvmeasurement, @schweidel2011portfolio, @bemmaorglady2012           |\n|Quantitative Marketing and Economics |Structural or econometric identification of customer dynamics                                              |@donkers2007clv, @singh2009framework, @erdem2003pricedynamics                                  |\n|Int. J. of Research in Marketing     |Focused extensions and applications; strong on complaint and service behaviour                             |@vanoestknox2011, @glady2015unveiling                                                          |\n|Economics journals                   |Customer base as a firm asset; state dependence and switching costs                                        |@heckmansinger1984, @klemperer1987switching, @dube2010statedependence, @gouriorudanko2014      |\n|Statistics / OR / software           |Estimation, computation, and reproducible implementation                                                   |@hausman1984countdata, @gui2023rendo, @meierer2026clvtools                                     |\n\n\n:::\n:::\n\n\n### Marketing Science {#sec-cba-mksc}\n\n*Marketing Science* is where the model class lives. The pattern of a successful paper is\nconsistent across four decades: take the incumbent specification, identify an assumption\nthat is doing unexamined work, replace it, show the new model nests the old one, and\ndemonstrate out-of-sample improvement on several data sets.\n\nThe chain runs from @fader2005bgnbd (replace the Pareto death process with a\nbeta-geometric one to remove the hypergeometric functions) through\n@faderhardieshang2010 (BG/BB for discrete transaction opportunities), @jerath2011death\n(generalize the death process itself), @platzerreutterer2016 (exploit inter-purchase\nregularity, not just recency, via a Gamma timing process), @gopalakrishnan2017changepoint\n(cohort-level changepoints), @dewansari2018 (replace the Gamma prior with a Bayesian\nnonparametric one and make the fitted heterogeneity visible rather than assumed) and\n@bachmann2021tvc (time-varying covariates). Adjacent to\nthe timing models are the relationship-state models: @netzer2008hmm's hidden Markov\nmodel replaces \"one irreversible death\" with transitions among latent relationship\nstates, and @schwartz2014modelselection ask the meta-question of which model class a\ndatabase's characteristics should select.\n\nThe covariate thread specifically runs @schweidelknox2013 (direct marketing activity in\na latent attrition model) into @bachmann2021tvc, and the \"what counts as death\" thread\nruns @braunschweidel2011causes (customers can churn for several distinct reasons, and\ncollapsing them loses information) alongside @jerath2011death. On the contractual side,\n@faderhardie2010contractual is the standing demonstration that ignoring heterogeneity\nbiases customer-base valuation even where attrition *is* observed, and\n@ascarzahardie2013usage model usage and churn jointly rather than treating usage as an\nexogenous predictor of it.\n\nThe journal has also hosted the field's self-criticism. @abe2009's hierarchical Bayes\nPareto/NBD showed what the closed forms were giving up; @ebbes2011holdout undermined\nholdout validation as a defence against endogeneity; @ascarza2018goodbye showed that\n\"silent\" attrition and stated attrition are different processes;\n@schmittlein1985nbdrobust asked, unusually early, *why* the NBD works at all, and found\nits robustness came from properties that survive violations of its own assumptions.\nMore recently @xia2019rbm brought conditional restricted Boltzmann machines to shopping\npatterns, which is the machine-learning frontier arriving in the model class's home\njournal.\n\n### Journal of Marketing Research {#sec-cba-jmr}\n\n*JMR* takes customer-base analysis when the modelling serves a substantive or\nexperimental claim. @fader2005rfmclv's iso-value curves connected the academic model to\npractitioner RFM. @braun2015transaction showed that *what* was bought, not just when,\ncarries valuation information. @ascarza2018futility's retention-futility result, that\ntargeting the highest-risk customers can be ineffective because risk and persuadability\nare different quantities, is a JMR-style intervention: it changes what a manager should\ndo with a churn model's output. @mccarthyfader2018 pushed customer-base analysis into\ncorporate valuation for publicly traded non-contractual firms. @ascarza2016perils is\nthe cautionary field experiment: a proactive churn-prevention campaign built on a churn\nmodel's output *raised* churn, because the intervention itself drew attention to a\ndecision the customer had not been making. On the prediction side, @neslin2006churn's\ntournament and @lemmenscroux2006's bagging-and-boosting comparison set the\nmachine-learning benchmark, and @dew2020gaussianprocess brought Gaussian-process\nheterogeneity to bear. The tournament genre has its own history: the\n@malthouse2009competition modeling competition and the empirical generalizations\nassembled by @blattberg2009clvgeneralizations are the closest this field has to an\nagreed scoreboard.\n\n### Journal of Marketing {#sec-cba-jm}\n\n*JM* asks what the customer base means for the firm. @reinartzkumar2000 and\n@reinartzkumar2003 established, against considerable prior belief, that long-life\ncustomers are not reliably more profitable. @wubben2008heuristics asked whether the\nacademic machinery beats a hiatus heuristic, and found the answer to be \"often not, at\nthe aggregate level,\" a genuinely uncomfortable result the field has had to absorb.\n@mccarthy2017 valued subscription businesses from publicly disclosed customer data,\n@knoxvanoest2014 examined complaint and recovery through a customer-base lens, and\n@hanssenspauwels2016 situated the whole enterprise in the demonstrating-marketing-value\nagenda.\n\n### Management Science {#sec-cba-mnsc}\n\n*Management Science* published @paretonbd1987 itself and continues to take the\nmethodologically general papers. @borle2008clvmeasurement models the three processes\njointly rather than sequentially; @schweidel2011portfolio handles customers who hold\nevolving portfolios of services rather than a single relationship; @bemmaorglady2012\nintroduces the Gamma-Gompertz/NBD, with @adler2023comment as a published corrective on\nits estimation. The venue's revealed preference is for models whose generality extends\npast a single marketing application.\n\n### Quantitative Marketing and Economics, and IJRM {#sec-cba-qme}\n\n*QME* is the natural home for identification-forward treatments. @donkers2007clv ran a\ncompeting-models horse race for CLV in insurance; @singh2009framework built a general\nframework for estimating CLV when lifetimes are unobserved; @erdem2003pricedynamics is\nthe structural-dynamics reference point for how forward-looking consumers respond to\nprice uncertainty, which is the demand-side counterpart to a latent attrition process.\n*IJRM* takes focused, well-executed extensions: @vanoestknox2011 extends the BG/NBD to\nmodel purchases and complaints jointly, and @glady2015unveiling establishes the\ndependence between timing, spending and dropout that the standard factorization\n@eq-cba-dert assumes away.\n\n### Economics {#sec-cba-econ}\n\nThe economics literature has no \"customer-base analysis\" label, but it owns three of the\ncomponents and a fourth question the marketing literature mostly does not ask.\n\nThe first component is *duration modelling with unobserved heterogeneity*.\n@heckmansinger1984's method for minimizing the impact of distributional assumptions in\nduration models is the canonical statement of the problem the Gamma mixing distribution\nsolves by assumption: mixing distributions are weakly identified, and conclusions about\nduration dependence are sensitive to them. Any claim that \"attrition hazard rises with\ntenure\" made from a Pareto/NBD should be read against this.\n\nThe second is *count-data econometrics*. @hausman1984countdata established the Poisson\nand negative-binomial panel machinery, including the fixed-effects treatments that the\nmarketing models replace with a Gamma prior. The NBD half of the Pareto/NBD is exactly\nthis literature's workhorse, arrived at independently.\n\nThe third is *state dependence versus heterogeneity*, the identification problem that\nsits underneath every claim a latent-attrition model makes. @dube2010statedependence\nseparate true state dependence from persistent heterogeneity in consumer inertia, and\n@dube2009switchingcosts examine whether the resulting switching costs soften competition,\nbuilding on @klemperer1987switching. The parallel to customer-base analysis is exact: a\nlong silence is either a low-$\\lambda$ type (heterogeneity) or a changed state (death),\nand the model's assignment of one versus the other is an identification claim, not a\nmeasurement.\n\nThe fourth is the question marketing rarely asks: what is a customer base *worth as a\ncapital asset to the firm*, and how does accumulating one shape firm behaviour?\n@gouriorudanko2014 model customer capital explicitly, showing how the costly, slow\naccumulation of a customer base explains investment and firm dynamics that a\nfrictionless demand model cannot. @foster2008reallocation supply the empirical\ncounterpart, separating physical productivity from demand-side fundamentals and finding\nthat survival and growth track the latter: young producers are not less efficient so\nmuch as less known, and what they are accumulating is a customer base. This is the\nstrongest available argument that the CLV construct belongs in economics and not only in\nmarketing, and it is nearly absent from the marketing citation graph.\n\n### Statistics, OR, and Software {#sec-cba-stats}\n\n@allenby1999timing brought purchase-timing models into *JASA*;\n@morrisonschmittlein1988 in *JBES* asked when generalizing the NBD is worth the effort,\na question the field would benefit from asking more often. @jeuland1980multibrand in\n*Operations Research* is an early compound-process ancestor. On the software side,\n@meierer2026clvtools documents `CLVTools` and @gui2023rendo documents `REndo`'s\ninternal-instrument methods; and @ni2012ismsdata is a database submission, a publication\ngenre that exists because model comparison in this literature is bottlenecked on data\naccess rather than on ideas. Reproducible implementation is a real\ncontribution in this literature precisely because the likelihoods are intricate and the\noptimization is fragile.\n\n### Open Problems {#sec-cba-open}\n\nFour gaps are visible from the material above and each is a viable project.\n\n*Covariates in the spending model.* @eq-cba-gg is stationary and covariate-free, so no\nmodel in this chapter can say what a discount does to basket size. Working papers exist;\na published, closed-form treatment does not.\n\n*Aleatoric uncertainty in the predictions.* Bootstrapping the fitted model gives\nconfidence intervals on parameters (epistemic uncertainty), not predictive intervals on\noutcomes. A customer-level predictive distribution rather than a point estimate would\nchange how these numbers are used in targeting.\n\n*Endogeneity as a default, not a robustness check.* The identification tools exist\n[@gui2023rendo; @wooldridge2015control] but are bolted on. A latent-attrition model with\nan integrated control function would make the causal claim available rather than\naspirational.\n\n*Reconciling the two literatures on firm value.* @mccarthyfader2018 value firms from\ncustomer data; @gouriorudanko2014 model customer capital from firm data. Neither cites\nthe other. A paper that reconciles the marketing bottom-up valuation with the\nmacroeconomic customer-capital stock would have an unusually wide audience.\n\n## Key Takeaways {#sec-cba-takeaways}\n\n- Customer-base analysis is defined by what it *cannot* observe. In non-contractual\n  settings attrition is never recorded, so it is modeled as a latent event, and the\n  estimand is a posterior belief rather than a measured outcome (@tbl-cba-taxonomy).\n- The Pareto/NBD's power comes from its sufficiency result: exponential memorylessness\n  collapses an entire purchase history into $(x, t_x, T)$ (@eq-cba-indlik), which is why\n  it scales to millions of customers and why RFM scoring is a shadow of it.\n- Frequency and recency pull in opposite directions. Many purchases raise the estimated\n  purchase rate but also make a given silence more damning, and the models formalize a\n  trade-off that hand-built RFM scores get wrong.\n- @bachmann2021tvc make both latent rates functions of time-varying covariates\n  (@eq-cba-tvrates) while keeping a closed-form maximum likelihood. The cost is that\n  recency is no longer sufficient: every transaction date enters the likelihood, and\n  storage and estimation cost rise accordingly.\n- Because future covariate paths are unknown, the infinite-horizon DERT is replaced by\n  the finite-horizon DECT. Comparing a covariate model's CLV to a base model's without\n  accounting for that substitution manufactures a spurious result.\n- On the replication data, time-varying covariates cut holdout MAE by about nine percent\n  and time-invariant covariates by under two (@tbl-cba-holdout). Almost all the gain comes\n  from letting the model attribute a quiet stretch to a low season instead of to death.\n- Better holdout prediction is not evidence of a valid causal coefficient\n  [@ebbes2011holdout]. Marketing covariates are chosen by the firm's own targeting rule,\n  and the coefficient absorbs it unless an instrument or control function is supplied.\n- The equality constraint (@eq-cba-constraint) turns the model into a hypothesis test:\n  whether a marketing activity raises purchasing and attrition differently, that is,\n  whether a campaign is borrowing from the future.\n- The economics literature owns three of the components (duration heterogeneity, count\n  data, state dependence versus heterogeneity) and one question marketing has not\n  claimed: the customer base as a capital asset shaping firm dynamics\n  [@gouriorudanko2014; @foster2008reallocation].\n\n## Further Reading {#sec-cba-further}\n\nStart with @faderhardie2009probmodels for the tutorial-level view of the whole family\nand @paretonbd1987 for the original derivation. @bachmann2021tvc is the organizing paper\nof this chapter and its appendices carry the likelihood derivations compressed in\n@sec-cba-bmn-lik; @meierer2026clvtools is the companion software paper and the practical\nroute into the code. @faderhardieross2022 is the least mathematical and most useful book\non what to *do* with a customer base once you can describe it. For the criticism,\n@wubben2008heuristics and @ebbes2011holdout are the two papers most likely to change how\na practitioner reads their own results. @ascarza2018retentionreview surveys the\nretention-management literature that consumes these models' output, and @sec-clv places\nthe whole enterprise in the broader CLV context.\n",
    "supporting": [
      "13a-customer-base-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}