# Introduction {#intro}

This is not an actual book or guide on marketing research, but more like a placeholder for major constructs in marketing as well as interesting articles in marketing.

Feel free to comment or suggest changes to the content of this book.

Differences between goods and services:

-   Intangibility
-   Complexity
-   Heterogeneity

Dimensions of [Qualitative Research](https://www.sagepub.com/sites/default/files/upm-binaries/34087_Chapter1.pdf):

1.  Ontology: "is a philosophical belief system about the nature of social reality- what can be known and how".

2.  Epistemology: "is a philosophical belief system about who can be a knower".

3.  Methodology (theoretical perspective): "an account of social reality or some component of it that extends further than what has been empirically investigated":

    -   Post-positivist: causal relationship can be tested (i.e., disprove)
    -   Interpretive: assumes the world is constantly being constructed through group interactions;hence social reality can be understood via the perspectives of social actors enmeshed in meaning-making activities".
    -   Critical: view social reality as an ongoing construction, and suggest that discourses created in shifting fields of social power shape social reality and its study.

4.  Methods: "technique for gathering evidence".



Procedures recommended for literature review papers:

-   [@katsikeas2016]

-   [@lipsey2001practical]



This part is based on professor Ajay Kohli's workshop on theory

Purpose of theory is to

1.  Explain
2.  Predict
3.  Control

We need to have theory because it's economical and can help us figure out many other manifestations.

Definition: Theory is hypothesized/expected description of causal relationships among construct

Parts of theory:

1.  Constructs (labels, definitions)
2.  Statement stating relationship among constructs
3.  Arguments to why X causes Y (including assumptions)
4.  Boundary conditions

Developing theoretical arguments

1.  Main effect: X -\> A -\> Y
    1.  Both arrows are assumptions that can be agreed upon provided prior theory or anecdotal evidence

    2.  Assumptions are taken to be true

    3.  Propositions are yet to be true

    4.  Difference between a proposition and assumption is the Goldilocks distance between X and Y



One proposition can become a theory

Conceptual models = linkages without arguments

Framework = linkages between categories of variables, theory at abstract level

Framework is important because you can come up with more holes (generative power)

How to argue for U and inverted-U effect [@haans2016thinking]
