# Advertising

People don't like intrusive ads, especially when they are vulnerable [@kellogg_2005, p.143]

<br>

Visual Persuasion

-   [@visualp1997] and [@visualp2003] are two books on this subject

<br>

Prior distribution for TV advertising elasticity for consumer packaged goods can be found in [@Shapiro_2018]. A substantial portion of products has statistically insignificant or negative estimates for advertising elasticity. TV ads might not be the best vehicle to reach the customer now.

[@Gordon_2019] reframe our idea of advertising effect, which should be thought in the sense of incremental effect above the baseline of an ad on consumer behavior.

[@Gordon_2017] and [@Lewis_2015] provided evidence that observational data can hardly detect adverting effect from noise (i.e., we could either over or under-estimate).

The goal standard to measure advertising is random experiment, but it not possible. An improvement is to have panel data from different regions of your market to estimate the baseline for each market. Then, you can uncover the advertising effect.

Spillover effect in advertising:

-   [@Rutz_2011]

<br>

(McGuire, 1978):

-   Information processing model of social influence (e.g., advertising effectiveness)

-   Behavioral chain of information profession model. (p. 158) (Markov process) - persuasion

-   P(presentation of message) x P(attention to message) x P(Comprehension of Conclusion) x P(Yielding to the Conclusion) x P (retention of the new belief) x P (Behaving on the basis of belief)

    -   Presentation of message = \# of reach (advertising investment)

    -   attention to message = \# of true reach or Recognition test

    -   comprehension = recall test or semantic differential profiles or checklist tests

    -   yielding = attitude change

    -   retention = attitude change after time interval

    -   behavior = actual observation

-   Independent variables (components of persuasive communication): source, message, channel, receiver, and destination (Table 1, p. 167)

-   Matrix of persuasion

-   Advertising appeals:

    -   Positive (gain): reduce anxiety

    -   Negative (loss): increase anxiety

-   Development in the field: this model assume 1 hierarchy, but later developments change the idea of hierarchy model.

<br>

Court et al. (2009)

Traditional funnel:

1.  Awareness

2.  Familiarity

3.  Consideration

4.  Purchase

5.  Loyalty

    1.  Active loyalist

    2.  Passive loyalist

Consumer decision journey McKinsey (2009):

1.  Initial consideration set
2.  Active evaluation
3.  Decision at moment of purchase
4.  Postpurchase experience

-   Customer Decision Journey is from the perspective of consumers

-   Customer Funnel is still important but it's from the company's perspective.

-   Analogy here is that you look from 3D (Customer Decision Journey) to 2D (Customer Funnel).

<br>

[@maclnnis1989]

1.  Hierarchy of effects model (1960s)

2.  Multiattribute attitude model and cognitive response models (1970s)

Proposed model:

-   Antecedents:

    -   Types of needs

        -   Utilitarian needs

        -   Expressive needs

            -   Socially expressive needs: to express, or reflect self-image

            -   Experiential needs: to satisfy one's cognitive or sensory

    -   Motivation (in CB **involvement**): "the desire to process brand information in the ad." (p. 4)

        -   situational

        -   enduring

-   Processing

    -   Attention:

        -   higher processing motivation leads to higher attention

        -   higher utilitarian needs, more focused on brand attributes

        -   higher expressive needs, more focused on symbolic/ experiential value

    -   Processing capacity:

        -   greater processing motivation leads to greater processing capacity for analyzing the ad

        -   greater the processing capacity results in less processing capacity for other task.

    -   Level of brand processing matches processing operations

        1.  feature analysis: salient properties/features

        2.  basic categorization

        3.  meaning analysis: basic understanding

        4.  information integration: Is this brand association?

        5.  role-taking

        6.  constructive processes

    -   Ability and opportunity are moderators of processing

-   Consequences

    -   Cognitive responses (thoughts)

    -   Emotional responses (feelings)\
        \
        Another classifications of responses:

    -   message-related (brand-relevant)

    -   execution-related (brand-irreverent)

    -   viewing-context-related (environment-related)

Advantages of the proposed model: Incorporate

-   Elaboration Likelihood model: [@petty1986]

-   Mitchell's brand processing model

-   Greenwald and Leavitt's model

-   Lutz's typology

Note:

-   $A_{Ad}$ mediates $A_B$ based on levels of processing (specifically, meaning analysis, information integration, and role taking - high levels).
-   Tradeoff between brand/message-related elements and ad-execution elements
-   Cohen and chestnut 1990, behavioral loyalty and attitudinal loyalty stem did not stem from the gap between attitude and actual behavioral.

<br>

[@vakratsas1999]

-   Advertising input -\> Filters -\> Consumer (Cognition, Affect, Experience) -\> Behavior

-   Market Response Models:

    -   Aggregate level (Bass' model): market data

        -   3 exposures per purchase cycle is optimal (p. 29)

    -   Individual level: individual brand choice

-   Cognitive Information Models (C)

    -   There is a differential effect between price (increase) and non-price (decrease) advertising on price sensitivity

-   Pure Affect Models (A)

    -   Mere exposure theories

        -   Response competition and Optimal arousal theories: "wear-in" effect which means it takes time to getting familiar to advertising messages to reach optimal effectiveness.

        -   Two-factor theory: wear-out effect: after optimal exposures, the effect of advertising starts to decrease

        -   Hence, advertising response has an inverted-U shape

    -   Affective responses to advertising:

        -   Attitude towards the brand

        -   Attitude towards the ad

-   Persuasive Hierarchy Models (CA)

    -   Cognition -\> Affect -\> behavior. (CA)

    -   Elaboration Likelihood Model (ELM): [@petty1986]

    -   Another model is [@maclnnis1989]

    -   Fishbein-Ajzen (1975) involvement model

    -   Batra and Ray (1985): Utilitarian and hedonic effect on attitudes towards the brand

    -   Involvement moderates the effect of ad evaluation (persuasion is found in low-involvement consumers with attitude towards the ad).

    -   Little support for CA model, but the authors still believe in it.

-   Low-involvement (motivation) Hierarchy Models (CEA)

    -   Cognition -\> Experience -\> Affect

-   Integrative Models (CAE)

    -   Information Integration Response Model (IIRM)

    -   Deighton's (1984, 1986) two-stage model:

        -   first experience = expectations

        -   second stage = product trail/experience

-   Hierarchy-Free Models (NH)

-   Generalizations:

    1.  Experience, affect, cognition are mediators of advertising effects.

    2.  "Short-term ad elasticities are small and decrease during the product life cycle (p. 35).

<br>

[@wind2009]

-   23 Empirical Generalizations

-   Gaps:

    -   Boundary conditions

    -   Advertising properties

    -   Measurement issues

<br>

[@batra2016]

-   Media:

    -   search

    -   display

    -   mobile

    -   TV

    -   social media

-   Considerations for a well-integrated marketing communications program

    -   Consistency

    -   Complementarity

    -   Cross-effects

-   Dynamic Expanded Customer Decision Journey

    -   traditional media

    -   newer media

        -   Search ads

        -   display ads

        -   websites

        -   email

        -   social media

        -   Mobile

-   Interaction and Cross-effects

    -   Traditional media synergies

    -   sales force and personal selling interactions

    -   Online and offline synergies

-   Drawbacks

    -   Limited outcome variables

    -   Limited longitudinal studies

    -   Did not account for consumer decision stage

-   Media type

    -   Paid (TV, print, direct)

    -   owned (websites, blogs, apps, social media)

    -   earned (WOM, press coverage)

-   Factors that affect consumer communication processing (model) (p. 130)

-   Communication Matching Model: "matches the expected main and interactive effects of different media options with the communications objectives for a brand"

-   Communications Optimization Model

    -   Coverage

    -   Cost

    -   Contribution

    -   Commonality: different communications share the same meaning

    -   Complementarity

    -   Cross-Effects

    -   Conformability

-   IMC Conceptual Framework

<br>

## Cognitive and Affective mediators of Advertising Effects

Evaluative responses = attitude

Cognitive approach -\> Affective approach (not only comes from cognitive) -\> Behavioral approach (Fishbein & Ajzen, 1975 - theory of planned behavior)

System 2: is kinda of independent of Cognitive, but Affective is system 1.

-   Expanded model added subjective norm

-   @zajonc1980

-   Evaluation from cognitive approach is multi-attribute model

-   Anthony Greenwald: Cognitive Response Theory: what important is what is in the consumer mind when they see the ad.

<br>

Conditioning:

-   Classical (Pavlovian) conditioning: physiological automatic reaction occurred after being exposed to an unconditioned stimulus.

-   Evaluative conditioning: direct transfer of affect from one stimulus to another via a conditioning paradigm.

<br>

Affective route:

Moods = diffuse, hard to pin down the source, more long-lasting

Emotion = specific, discrete

[@wright1973]

-   Three modes of spontaneous cognitive responses to advertising stimulus:

    -   Counterargument

    -   Source Derogation

    -   Support Argument

$$
Accecptance = w_{SA} \sum_{i} SA_i - w_{CA} \sum_j CA_j - w_{SD} \sum_k SD_k
$$

Situational Factors

-   Content-processing involvement: "stemming from receiver's perception of the relevancy"

-   Message Modality: audio, print

<br>

[@batra1986]

-   Advertising repetition increases brand attitude and purchase intention when support and counter argument production are low; while under high level of such production, brand attitude and purchase intention level off.

-   What happen to make the downturn of advertising repetition earlier or later?

-   Appropriate interval: purchase cycle (number of exposure per purchase cycle). 3 exposures per purchase cycle is the optimal number

-   Wear-in: how many times it takes for the ad to take effect?

-   Wear-out: how many times it takes for the ad to bore you?

    -   If you change the ad execution, the wear-out is pushed back.

-   Traditional thoughts advertising repetition would always wear out (inverted-U curve between repetition and impact on customer's attitude) because of wearout and mere exposure

-   Ability, motivation and opportunity are antecedents of cognitive processing

<br>

[@kupor2015]

-   Momentary interruptions can promote persuasion

    -   higher for low need for cognitive individuals (motivation to engage in thoughtful processing) than high ones

-   In other words, interruptions can increase consumers' processing of a message.

-   Interruption amplified arousal (need for completion/ goal pursuit and curiosity)

<br>

[@gibson2008]: Affective Responses Mediating Acceptance of Advertising

-   Using Implicit Association Test **(???)**

-   Evaluative conditioning only influences explicit attitudes when there is no previous strong preference or priori

<br>

@batra1986a

-   Antecedents of attitude towards the ad:

-   Attitude toward the ad leads changes in brand attitudes [@mackenzie1986; @mitchell1981]

-   In low involvement context, execution cues and source likeability (message-oriented and communicator-oriented) have greater impact on persuasion

-   Affect typologies (p. 237)

<br>

@pham2013

-   ad-evoked feelings positively influence brand attitudes both directly and indirectly (via changes in attitude toward the ad), regardless of involvement with the product category, products types (e.g., durables, nondurables, services, search or experience goods).

-   This effect is greater among hedonic products than utilitarian ones.

<br>

@holbrook1987

-   emotional reactions mediate the effect of advertising on attitudes toward ad or brand.

-   Why divided two articles? the second study claimed that the last paper's list of positive affective mediators was limited, the second one expands to range of emotions.

-   Is there a difference between affect and emotions?

<br>

[@batra1991; @voss2003] offer scale to measure the hedonic and utilitarian dimensions of consumer attitude
