# Brand Equity


Brand identity offers a value proposition to customers, where “a brand’s value proposition is a statement of the functional, emotional, and self-expressive benefits delivered by the brand that provide value to the customers” [@Aaker_1996, pp.95]. Functional benefits are product attributes that deliver functional utility to customers, while emotional benefits are positive feelings customers feel when using the brand. Ads that provide emotional benefits are higher in effectiveness score compared to functional benefits ads [@Aaker_1996, pp.98]. For example, Evian – “Another day, another chance to feel healthy” ad - which provides emotional benefits of feeling satisfied after a workout. Moreover, self-expressive benefits are when brands provide a means for consumers to express their self-image. A person/ consumer can have multiple roles which associate with multiple self-concepts. Such as a woman, a mother, an author. The difference between emotional benefits and self-expressive benefits can be subtle. Emotional benefits focus on feelings, private setting (e.g., feeling of watching a TV show), past-oriented (memories), transitory, after-use emotional; In contrast, self-expressive benefits focus on self, public settings (e.g., using cars or clothes to signal), aspiration or future-oriented, permanent (i.e., the self links to person's personality), and during-use (wearing fancy clothes to signify a successful person). (cf. [@Aaker_1996, pp.99])

With the advancement in mass production of high -quality products, quality is no longer a dimension of status signal [@Holt_1998]
