# Brand Equity

brand and psychological distance: Congruence effect: "information is easier to
process, which leads consumers to respond more favorably." [@Connors_2020]
"consumer spending higher when distance between consumer and brand matched with
construal level of marketing communications."

Value-added is the difference between a product's price to consumers and the
cost of producing it.

Whereas, brand equity is the difference between a branded product's price to a
generic product's price.

This generic product can also have value-added in it in other forms (e.g.,
convenience)

Brand identity offers a value proposition to customers, where "a brand's value
proposition is a statement of the functional, emotional, and self-expressive
benefits delivered by the brand that provide value to the customers"
[@Aaker_1996, pp.95].

Functional benefits are product attributes that deliver functional utility to
customers, while emotional benefits are positive feelings customers feel when
using the brand. Ads that provide emotional benefits are higher in effectiveness
score compared to functional benefits ads [@Aaker_1996, pp.98].

For example, Evian -- "Another day, another chance to feel healthy" ad - which
provides emotional benefits of feeling satisfied after a workout. Moreover,
self-expressive benefits are when brands provide a means for consumers to
express their self-image. A person/ consumer can have multiple roles which
associate with multiple self-concepts. Such as a woman, a mother, an author. The
difference between emotional benefits and self-expressive benefits can be
subtle. Emotional benefits focus on feelings, private setting (e.g., feeling of
watching a TV show), past-oriented (memories), transitory, after-use emotional;
In contrast, self-expressive benefits focus on self, public settings (e.g.,
using cars or clothes to signal), aspiration or future-oriented, permanent
(i.e., the self links to person's personality), and during-use (wearing fancy
clothes to signify a successful person). (cf. [@Aaker_1996, pp.99])

With the advancement in mass production of high -quality products, quality is no
longer a dimension of status signal [@Holt_1998]

In the virality framework, the first and foremost driver is social currency.
Social currency refers to things worth sharing. People share so that they can
let others know that they are in the know. Sharing a new product to assimilate
his or her identity with the product and its brand identity, customers are
acquiring social currency. Moreover, brand identity is a driver of brand equity,
which refers to the value portion that customers are willing to pay above the
product's utility value (practical value). Brand identity offers a value
proposition to customers, where "a brand's value proposition is a statement of
the functional, emotional, and self-expressive benefits delivered by the brand
that provide value to the customers" (Aaker, 1996, p. 95). Functional benefits
are product attributes that deliver functional utility to customers, while
emotional benefits are positive feelings customers feel when using the brand.
Ads that provide emotional benefits are higher in effectiveness score compared
to functional benefits ads (Aaker, 1996, p. 99). For example, Evian -- "Another
day, another chance to feel healthy" ad - which provides emotional benefits of
feeling satisfied after a workout. Moreover, self-expressive benefits are when
brands provide a means for consumers to express their self-image. A person/
consumer can have multiple roles which associate with multiple self-concepts.
Such as a woman, a mother, an author. The difference between emotional benefits
and self-expressive benefits can be subtle. Emotional benefits focus on
feelings, private setting (e.g., feeling of watching a TV show), past-oriented
(memories), transitory, after-use emotional; In contrast, self-expressive
benefits focus on self, public settings (e.g., using cars or clothes to signal),
aspiration or future-oriented, permanent (i.e., the self links to person's
personality), and during-use (wearing fancy clothes to signify a successful
person). (cf. (Aaker, 1996, p. 99)) Hence, one can see that the brand identity
portion that provides self-expressive benefits is social currency while
exhaustively different from the brand identity portion that provides functional
benefits (i.e., the practical value/ usefulness/ utility) .

We acknowledge that some might view usefulness/ utility as a dimension of brand
equity (perceived quality): the perceived quality dimension can signal the true
practical value. However, the practical value that drives virality is usually
understood, experimented, experienced; while perceived quality is subjective
comprehension that is hard to demonstrate. Moreover, quality used to be the
status signal. However, with the advancement in mass production of high-quality
products, quality is no longer a status signal dimension (Holt, 1998). Thus, we
believe that the distinction between the two understandings should be
appreciated.


## Brand Association
“different groups of people can have different or even contradictory associations with the same stimulus” (Wheeler & Berger, 2007)