# WOM / Virality

To understand virality, we first need to comprehend its root, which is WOM. Acknowledging that there are subtle differences among WOM, virality, and sharing, we use the three terms interchangeably in this paper. Previous authors provide strong supports for the similarity between virality and WOM (Camarero & San José, 2011; Phelps, Lewis, Mobilio, Perry, & Raman, 2004).  

Formally, (Westbrook, 1987, p. 261) defined WOM as “informational communication directed at other consumers about the ownership, usage, or characteristics of particular goods and services or their sellers.” In the age of the Internet, WOM evolves to “word of mouse” (or e-WOM). Both virality and WOM take advantages of the network effect to reach wide audiences (Vilpponen, Winter, & Sundqvist, 2006), but virality does it better due to its competitive cost, rapid diffusion, and better targeting (Bampo, Ewing, Mather, Stewart, & Wallace, 2008; Khan & Vong, 2014). Hence, virality is more synonymous with e-WOM.  

Virality comes up as a by-product of the Internet, social media platforms, and network theory developments. In network theory, researchers from the domain of sociology or computer science study the structural characteristics/properties of a node (an individual) or a network, such as a node’s position in a network or network’s cluster. While epidemiologists, management, and marketing researcher study the characteristics of the entity being transmitted, such as virus or message itself. Thus, virality can be driven by content or context of the message (Berger & Milkman, 2012), nature of the spreader, and audience (Hennig-Thurau, Gwinner, Walsh, & Gremler, 2004; Iyengar, van den Bulte, & Valente, 2011), seeding strategies (Kalish, Mahajan, & Muller, 1995; Libai, Muller, & Peres, 2005), and social network structure (Bampo et al., 2008). In this conceptual development, we focus on the content and context drivers of virality.  

Virality is defined as the probability of an entity being passed along (Hansen, Arvidsson, Nielsen, Colleoni, & Etter, 2011). The entity can be a message, content, video, knowledge, or disease. Alternatively, (Tucker, 2015) defines virality as “a process whereby an ad is successively shared by viewers.” These two definitions focus on virality as a process; instead, we focus on viral as a construct. Hence, we are in line with (Chandler & Munday, 2016) defining virality (social media virality, social shareability, social media shareability) as “the potential for spreadability of any given content; or particular qualities which are considered to have led to content ‘going viral’.”  

For WOM to work, people must share brand-related content, and attention needs to be translated into sales. With these positive associations towards a brand, marketers can increase a customer’s positive brand attitude and later purchase behavior (Faircloth, Capella, & Alford, 2001).  


81 percent of a telecom firm indicated that they are likely to refer other to the company; however, only 33 percent actually did. And of those who are referred, only 8 percent became profitable customer. [@kumar_2007]

Even though suffering from the same fate as brand equity, WOM has made it come back under a different alias - virality. The attention that virality has garnered in recent years can be attributed to several reasons:  

 (1) the dawn of the Internet helps propel marketing into a new paradigm - digital marketing - where earned media is the new king  
 (2) the introduction of social network platforms such as Facebook, Twitter that facilitate the transmission of information and messages seamlessly and provide an unlimited source of data  
 (3) The advancement in network theory both theoretically, and empirically. 

One platform that can be representative of this digital revolution is Twitter. According to a recent report, Twitter has 145 million monetizable daily active users. Twelve percent of Americans get their news from Twitter. And  Twitter has 2 billion video impressions per day (25 Twitter Stats All Marketers Need to Know in 2020. There are more than 500 million Tweets are sent per day. (The 2014 #YearOnTwitter, 2014). One cannot deny the power of online WOM as well as its potential reach; hence, viral marketing has been born with these platforms.

The age group from 18-24 can be more challenging to target since they reported fewer positive responses compared to other age groups [@Libert_2014]. Since their threshold is higher due to the overwhelming digital content they encounter, their emotions are harder to activate.   

<br>

Wide gaps between two opposing opinions can increase future discussion (reviews); however, fluctuation around one opinion does not. Higher informational content moderate positively the relationship between opposing opinions and future reviews. [@Nagle_2014]

<br>

WOM should be taken under the context of the evolution of conversation. [@Berger_2014]

<br>

**Valuable virality** [@Akpinar_2017]

Establishes causality of appeals and brand integralness to virality.   

 * Compared to informative appeal ads (focus on product features), emotional appeal ads (drama, mood, music, emotion-eliciting strategies) are more likely to be shared.  
 * Informative appeals boost brand evaluations and purchase because the brand is an integral part of the ad content.  
 * Hence, to combine the best of both worlds, emotional brand-integral ads boost sharing while also bolstering brand-related outcomes (embedded the brand into the stories).   
 * The mechanism that ads affect brand evaluation through two simultaneous mechanisms: persuasive attempt and brand knowledge. 


“keeping viewers involved depends in large part on two emotions: joy and surprise”(Teixeira, 2012) - "Research: The Emotions that Make Marketing Campaigns Go Viral"

“ads that produce stable emotional states generally aren’t effective at engaging viewers for very long.” And “shock may get people to watch an ad privately, it often works against their desire to share the spot. Like Clothing Drive that try to mimic “Swear Jar” by Bud Light”  (Teixeira, 2012)


<br>

(Westbrook, 1987, p. 261) defined WOM as “informational communication directed at other consumers about the ownership, usage, or characteristics of particular goods and services or their sellers.” WOM evolves to “word of mouse” (or e-WOM). 

[@Berger_2014]:   

WOM is goal-driven and serves five key functions:   

 * [Impression Management]  
 * [Emotion regulation]  
 * [Information acquisition]  
 * [Social bonding]   
 * [Persuasion][Persuading others]  


The motivation behind this process is self -serving and even subconscious level. Hence, we can predict the types of news and information people are most likely to discuss.  

 * Over 70% of everyday speech is about the self, such as personal experiences or relationships (Dunbar et al., 1997). Consistent with previous research, online behaviors exhibit the same pattern: over 70% of social media posts are about self (Naaman et al., 2010).
 * At any given point in time, multiple drivers can be present. 

## Impression Management  

Consumers buy to signal their derived identities to achieve desired impressions (J. Berger & Heath, 2007)  

Interpersonal communication (WOM) influences impression management in 3 ways: (1) self-enhancement, (2) identity -signaling, and (3) filling conversational space.   

 * **Self-enhancement**: human has a tendency to self-enhance (Markus, 1987). Hence, people like to share things to help them look good (Chung & Darke, 2006; Hennig-Thurau et al., 2004). Since bragging too much about oneself might have an opposite effect. People sometimes engage in” humblebragging”: brag but self-deprecating at the same time. (Sezer et al., 2018)  
 * **Identity-signalling**: they talk about themselves to signal they have certain traits or expertise (G. Packard & Wooten, 2013), such as opinion leaders talk to signal their identity (share to show their knowledge).  
 * **Filling conversational space**: (small talk) people engage in small talk to avoid pauses and silence in between conversations so that the other party would not make lousy inferences about the person. (J. Berger, 2014)  



Hence impression management induces people to share things that are  

 * **Entertaining** (i.e., interesting, surprising, funny or extreme) so that they shared look more interesting, and in-the-know. Interesting products get more word of mouth (J. Berger & Iyengar, 2013; J. Berger & Milkman, 2012; J. Berger & Schwartz, 2011). Moderate controversy is a catalyst for word of mouth to spread (Chen & Berger, 2013). And sometimes, people even exaggerate stories to make things more interesting (C. Heath, 1996); around 60% of the stories are distorted (Marsh & Tversky, 2004). Things that can be considered interesting are those that are either novel, exciting, or violate previous expectations (i.e., surprise) (Berlyne, 2006; Silvia, 2008). Nevertheless, comprehensibility can be a moderate of whether a novel thing is interesting: novel and comprehensible equals interesting, while novel and incomprehensible equal confusing (Silvia, 2008). Novelty refers to things that are new, surprising, exciting, or complex [@Berlyne_1960]. Comprehensibility refers to the fact that the novelty must be understandable.

 * **Useful**: because it makes the sharer smart and helpful. Empirical evidence show that useful stories(J. Berger & Milkman, 2012) and higher quality brands (Lovett et al., 2013) are more likely to be shared.  
 * **Self-concept relevant**: different people see different domain as the optimal signal amplifier such as politics, economics, etc. hence symbolic products are more likely to be shared than utilitarian ones  (Chung & Darke, 2006) (even though useful information is helpful, but the signal to be smart and helpful are not appreciated as being interesting and entertaining).  
 * **Status related**: premium brands are talked about more (Lovett et al., 2013). Knowledge is can also be considered as a status symbol, and people share to signal that they re in the know (Ritson & Elliott, 1999)  
 * **Unique**: unique products are more likely to be shared, but people with a high need for uniqueness will be less likely to share positive WOM because they do not want people to adopt the product and reduces their uniqueness (Cheema & Kaikati, 2010). Sometimes they even scare others by citing product complexity (Moldovan et al., 2015)   
 * **Common ground**: sharing common things induces listener to convey that there is interpersonal similarity and facilitates conversation.  
 * **Emotional valence**: people prefer to share positive things than negative news (J. Berger & Milkman, 2012). However, in some special cases, negative WOM can be perceived as a desired component such as reviewers are seen as more intelligent, (Amabile, 1983). Which is moderated by whether people are refereeing to themselves or others will affect WOM valence (positive vs. negative)(Kamins et al., 1997). Positive WOM when talking oneself conveys a positive image, while negative WOM about others convey that they are relatively better than the other party.  
 * **Incidental arousal**: unrelated arousal (e.g., running in place) can increase sharing in general (J. Berger, 2011) because of the increase in arousal levels.  
 * **Accessible things**: products with more cued or triggered will be discussed more (J. Berger & Schwartz, 2011). Hence, more advertised products generate more WOM (Onishi & Manchanda, 2012). “top of mind” and “tip of the tongue.” Availability bias means that the easier we can recall something, the more likely we are going to talk bout it.  Publicly visible products also have more WOM (J. Berger & Schwartz, 2011)

## Emotion regulation

WOM help consumers regulate their emotions. Emotion regulation refers to “a person’s ability to effectively manage and respond to an emotional experience”  (Rolston & Lloyd-Richardson, 2017). and sharing with other (WOM) can facilitate emotion regulation by:  

 * **Generating social support**: sharing can give you comfort and consolation (Rimé, 2009). For example, after a negative emotional experience, sharing can help increase well-being through perceived social support (J. A. Berger & Buechel, 2012)  
 * **Venting**: WOM (sharing) helps people achieve catharsis when experiencing negative experiences(Alicke et al., 1992): consumers express when they are angry (Wetzer et al., 2007) or dissatisfied (Anderson, 1998).  
 * **Sensemaking**: “talking can help people understand what they feel and why” (J. Berger, 2014)  
 * **Reducing dissonance**: even after making a decision, we want to make sure we make the right choice by talking to others tot reduce feelings of doubt (Rosnow, 1980)  
 * **Taking vengeance:** to punish the company (different from venting, which makes you feel better), consumers share negative consumption experience (Ward & Ostrom, 2006)  
 * **Rehearsal**: people talk to relive positive experiences (Rimé, 2009)  

<br>

Emotion regulation drives people to share (1) emotional content (2) influence the valence of the content shared, (3) lead people to share more emotionally arousing content:   

 * **Emotionality**: more emotional intensity, more sharing (J. Berger & Milkman, 2012), people share more emotional social anecdotes (Peters et al., 2009). But not all emotions increase sharing: for example, shame and guilt decreases sharing (Finkenauer & Rimé, 1998) since sharing those things makes people look bad.  
 * **Valence**: “Emotion regulation tends to focus on the management of negative emotions” (J. Berger, 2014), but a counter vailing effect is that under impression management, people avoid sharing negative stories since it might reflect on the shares. Sharing negative things can decrease willingness to share (Chen & Berger, 2013)  
 * **Emotional arousal**:  
    + **Negative** side: low arousal emotion (sadness), high arousal (anger or anxiety) should increase the need to vent.  
    + **Positive** side: low arousal (contentment), high arousal (awe, excitement or amusement) increase desires for rehearsal.

## Information acquisition  

WOM helps acquire information.   

 * **Seeking advice**: (Hennig-Thurau et al., 2004; Rimé, 2009). Rather than trial and error, or direct observation, gossip serves as another form of learning (Baumeister et al., 2004)  
 * **Resolving problems**: online forums or other online opinion platforms help customers find a solution quickly from others (Hennig-Thurau et al., 2004)

<br> 
Hence the process of information acquisition would induce to talk more about   

 * **Risky, important, complex, or uncertainty-ridden decision**: talking to others can reduce risk, simplify complexity, and increase consumer's confidence (Hennig-Thurau et al., 2004)  
 * **Lack of (trustworthy) information**: 


## Social bonding

"people have a fundamental desire for social relationships (Baumeister & Leary, 1995), and interpersonal communication fills that need (Hennig-Thurau et al., 2004)". Empirically, people in brand communities because want to connect with others like them (Muniz & O’Guinn, 2001). Sharing facilitates social bonding through   

 * **Reinforce shared views**: group memberships, and one’s place in the social hierarchy. WOM (sharing) allows people to fit in as a group member (J. Berger & Heath, 2007; Ritson & Elliott, 1999)  
 * **Reducing loneliness and social exclusion**: sharing decrease interpersonal distance and decreases loneliness and exclusion (Maner et al., 2007)  

<br>

Social bonding drives what people share: people share things are :  

 * **Common ground**: social bonding drives people to talk about things they have in common because it makes them feel socially connected (Clark & Kashima, 2007)
 * **Emotionality**: “sharing an emotional story or narrative increases the chance that others will feel similarly” (J. Berger, 2014). Emotional similarity increase group cohesiveness (Barsade & Gibson, 2007). And emotion sharing and social bonding can be a simultaneous process since previous works found that emotion sharing bonds people (Peters & Kashima, 2007) and high arousal emotion increase social bonding needs (Chen & Berger, 2013)

## Persuading others

people use WOM to persuade others to affect their satisfaction or choices (J. Berger, 2014). Persuasive drive people to share things that are   

 * **Emotionally polarized** (polarized valence): since the goal is to convince something is good or bad (i.e., people share extremely rather than moderately positive(negative) information   
 * **Arousing content**: “people who want to persuade others may find shared arousing content to incite others to take desired actions” (J. Berger, 2014)  

## Moderators

 - Two key moderators when different WOM functions have a greater impact:  
    + **Communication audience**: 
        * Tie strength 
        * Audience size 
        * Tie status 
    + **Communication Channel**
        * Written vs. oral 
        * Identifiability: whether communicators are identifiable. (anonymously)  
        * Audience salience: whether the audience is salient during communication (online communication, the audience is less salient).



Social motivation: why we share :(why_some_videos_go_viral_2015)  

 * Impression management:  
    + authority (e.g., “I want to demonstrate my knowledge”)  
    + Social utility (e.g., this could be useful to my friends)  
    + coolhunter (e.g., I want to be the first o tell my friends)  
    + Zeitgeist (e.g., It’s about a current trend or event)  
    + Conversation starting (e.g., I want to start an online conversation)  
    + Self-expression (e.g., it says something about me)  
    + Social good (e.g., It’s for a good cause, and I want to help”).  
 * Information acquisition:   
    + Opinion seeking (e.g., “I want to see what my friends think)  
 * Social bonding:   
    + Shared passion (e.g, “it lets me connect with my friends bout a shared interest)  
    + Social in real life (e.g., it will help me socialize with my friends offline).  

More frequent exposure to perceptually or conceptually related cues increases product accessibility and makes the product easier to process. In turn, this increased accessibility influences product evaluation and choice, which are found to vary directly with the frequency of exposure to conceptually related cues. These results support the hypothesis that conceptual priming effects can have a strong impact on real-world consumer judgment” [@Berger_2008]


## Social Currency

Different people see different domain as the optimal signal amplifier, such as politics, economics  

Even though useful information is helpful, the signal of being smart and helpful is not appreciated as being interesting and entertaining (Berger, 2014).  

People talk more about status-related products because they enhance their impression.  


In extreme cases, they even scare others by citing product complexity (Moldovan, Steinhart, & Ofen, 2015).  

Interesting things are discussed more in online settings (J. Berger & Milkman, 2012), but this effect fails to replicate in the case of face-to-face settings (Berger & Schwartz, 2011). Hence, research has found that written communication (e.g., texting, messaging, posting online) leads people to talk more about interesting products or brands than oral communication because they have more time to think and polish what to say, leading to more prevalent self-enhancement motives (Berger & Iyengar, 2013). In other words, not because people do not have self-enhancement motives, but because synchronous conversations do not allow for much time to think and posish ideas, people might talk about mundane things to fill the gaps between conversational turns (Berger, 2014).  




## Accessibility

Accessibility drives ongoing WOM (i.e., publicly visible products are cued more in the environment – top of mind), regardless of how mundane it might be. 


From the theory of semantic process (Collins & Loftus, 1975), priming can help activate related perceptual or conceptual constructs in memory spontaneously (Berger & Fitzsimons, 2008). For example, prior exposure affects the brand choice of both target brand and competing brands (Nedungadi, 1990). In other words, the activation of one brand can lead to others more accessible, which increases the chance of remembered brands to be included in the consideration set. 
(Lee & Labroo, 2004) argues that ease of processing drives our positive evaluation, which is also consistent with the discrepancy -attribution hypothesis. The Discrepancy-attribution hypothesis states that if people cannot easily attribute the ease of processing to a source, they will likely attribute it to the positive quality of the target. 
Additionally, (Nedungadi, 1990) found that recently exposed brands are more likely to be included and chosen from consumers’ consideration set. Repeated exposure to an object increases favorable ratings (e.g., an object, or person) (Zajonc, 1968), which also apply to attractive people (Moreland & Beach, 1992), and brand (Baker, 1999).
Behavioral can be influenced by incidental exposure to stimuli because the primes can activate relevant constructs associated in memory (Christian Wheeler & Petty, 2001; Dijksterhuis & Bargh, 2001; Wheeler & Berger, 2007)


## Emotions

(Milkman & Berger, 2014) found that contents that are (1) emotional aroused, (2) useful, or (3) interesting have a higher chance of being shared. Consistently, (Milkman & Berger, 2014) also found that women produce articles that are more likely to be shared because female authors write more comprehensible, useful, and interesting articles.  

People share their extreme emotional experience (i.e., either highly satisfied or highly dissatisfied) (Anderson, 1998)  

Lastly, people use WOM to persuade others to affect their satisfaction or choice (Berger, 2014). Thus, emotionally polarized (polarized valance) are more likely to be shared due to persuasion reasons. Since the goal is to convince something is good or bad, people share extremely rather moderately positive (negative) information.  

Virality is partially driven by physiological arousal (Berger, 2011; Berger & Milkman, 2012). These results hold even when the authors control how surprising, interesting, or practically useful content is (all of which are positively linked to virality) and external drivers of attention (e.g., how prominently content was featured) (Berger & Milkman, 2012). Different emotion evokes different levels of physiological arousal (i.e., activation) (Smith & Ellsworth, 1985). Arousal is an excitatory state that increases action-related behavior, such as helping others (Gaertner & Dovidio, 1977). Hence, we see contents that are physiological arousal get shared more. Specifically, Negative high arousal emotions (e.g., anger or anxiety) are shared more than negative low arousal (e.g., sadness). Moreover, sharing negative experiences can help people vent to regulate their emotions (Berger, 2014). On the other hand, positive emotion high arousal emotions (e.g., awe, excitement, or amusement) are shared more than positive low arousal (e.g., contentment). Furthermore, sharing for the purpose of rehearsal (i.e., people talk to relive positive experiences) helps people regulate their emotions (Rimé, 2009). 
