# Review Process

Communicate your review by O. C. Ferrell:

1.  Paragraph

    1.  contextualize the research

    2.  convey the key message of the research

    3.  be positive about what was done well

2.  Paragraph:

    1.  Is the paper well written, interesting and important?

    2.  Are the methods, data, etc. appropriate?

    3.  Does the data support the findings?

3.  Paragraphs: Numbers, topics-examples of an issue:

    1.  Factual errors

    2.  Invalid arguments

    3.  length/journal guidance

    4.  Paths to improve the research



Why review?

-   Contribution/ Give back to the community

-   Get to the fore front of current research

-   Understand what a strong paper looks like



Documenting your reviews

-   Use publons.com to document manuscripts you reviewed for promotion and CV

-   to verify your review, send the "thank you for reviewing" email to reviews\@publons.com

The review process:

-   Journals always look for reviewers

    -   Get involved and email your CV to editor, or area editor.

-   Do not wait to answer whether you review or not.

Responding to reviews

-   Turn around in 3 months

-   R & R: reject and resubmit (new). The turn around will be sent to a new set of reviewers

-   R & R: review and resubmit.

## Review at JM

For data replication submission, read [here](https://www.ama.org/journal-of-marketing-policy-for-research-transparency/#_ftn3)

For detail, read [here](https://www.ama.org/wp-content/uploads/2019/11/Managing-the-Review-Process-at-the-Journal-of-Marketing-Final.pdf)

JM articles should have:

1.  New knowledge

2.  Real-world marketing topics and problems (i.e., relevance to stakeholders)

3.  Validity (i.e., good approximation of the truth)

Expected quality review process:

1.  Fairness

2.  Reviewers should have reasonable knowledge

3.  No conflicts of interests

4.  Consistency

    1.  Interesting and important
    2.  Empirical rigor
    3.  Conceptual rigor
    4.  Relevance
    5.  Constructive
    6.  Risk-taking

5.  Not a vote-counting exercise (i.e., number of rejections from reviewers)

6.  Responsible

    1.  Respect author's original objective

    2.  Explain fatal flaws

    3.  Privacy

7.  Timely: reviewers (three weeks after the review invitation) and AEs (within two weeks)

8.  Roadmap



Format

-   2 single-spaced pages

-   reviewers number their comments.

-   Suggested structure:

    -   A short synopsis of the paper and its findings

    -   Evaluate the contribution: Suggestions to improve contribution(if needed)

    -   Identify major strengths, weaknesses, recommendations regarding

        -   conceptual

        -   empirical

    -   Readability

    -   Minor comments and suggestions

## Review Process Back end

When you submit an article

-   Plagiarism check

-   Repeat submission check

-   An editor reviews the paper for suitability (might be desk-reject)

-   An area/associate editor is assigned

-   Reviewers (2-3) are assigned

Reviewers are chosen based on

-   your reference list

-   your suggested list of reviewers

-   the editor's knowledge of the domain

-   Candidate reviewers that declined to review

-   web search

-   a publisher's database
