{
  "hash": "b5aa8ab1d5d4883dbb0ed0da0d315623",
  "result": {
    "engine": "knitr",
    "markdown": "# Normative Benchmarks: Models of Optimal Behavior {#sec-normative-benchmarks}\n\nYou cannot call a choice a mistake without saying what the right choice was. This\nis the sentence that separates a policy paper that survives review from one that\ndoes not. An evaluation showing that a rule changed behavior establishes that\nconsumers responded; it establishes nothing about whether the response was good.\nTo get from \"borrowing rose\" to \"students were made better off,\" someone has to\nwrite down what an unconstrained, well-informed, correctly-optimizing consumer\nwould have done in the same situation—and then measure the distance between that\nbenchmark and the behavior actually observed.\n\nThis chapter is about constructing that benchmark. The object is a **normative\nmodel**: a small analytical model of the consumer's problem whose solution\ncharacterizes optimal behavior, whose comparative statics generate testable\npredictions, and whose parameters are quantities that can be measured or bounded\nrather than assumed. It is deliberately not a full structural model estimated on\nthe data. The distinction is central and is developed in @sec-nb-role: a normative\nmodel earns its place by being *smaller* than a structural model, because it is\nasked to do less.\n\nThe running construction is the student-borrowing model of @brown2026spillover,\nwhich is unusually well suited to teaching because it is simple enough to solve on\npaper and rich enough to generate a threshold rule, a welfare formula, and four\ndistinct forms of consumer error. We build it from primitives, derive its central\nproposition, catalogue the departures from it, and then abstract the recipe so it\ncan be re-used on marketing problems that have nothing to do with credit.\n\n## What a Normative Model Is For {#sec-nb-role}\n\nMarketing research uses models for at least three incompatible purposes, and\nconflating them produces papers that satisfy nobody.\n\nA **descriptive** model reproduces observed behavior. Its success criterion is\nfit, and its parameters are whatever makes the fit good.\n\nA **structural** model recovers deep parameters—preferences, costs, beliefs—that\nare invariant to the policy under study, so that counterfactual equilibria can be\nsimulated (@sec-structural-models). Its success criterion is that the recovered\nparameters are policy-invariant and identified, which is demanding, and it usually\nrequires functional-form commitments the theory does not justify\n[@nevo2010dogma; @rust2014limits].\n\nA **normative** model characterizes what an agent *should* do given a stated\nobjective and constraint set. Its success criterion is neither fit nor\nidentification: it is that the optimality conditions are correct, that the\npredictions distinguish optimizing from non-optimizing agents, and that the\ncomparative statics are sharp enough to be refuted. A normative model is allowed\nto be wrong about average behavior. Indeed, if consumers systematically deviate\nfrom it, that gap is the paper's finding.\n\n@fig-nb-three-roles places the three side by side and shows what each licenses.\n\n```{mermaid}\n%%| label: fig-nb-three-roles\n%%| fig-cap: \"Three roles a model can play in a policy paper. The normative model is the one that licenses the word mistake; it is smaller than a structural model because it is not asked to reproduce the data.\"\nflowchart TB\n  Q[\"Policy question:<br/>did the rule help consumers?\"] --> D[\"Descriptive model:<br/>reproduce observed choices\"]\n  Q --> S[\"Structural model:<br/>recover policy-invariant<br/>preferences and costs\"]\n  Q --> N[\"Normative model:<br/>characterize the optimal<br/>choice given objective<br/>and constraints\"]\n  D --> D2[\"Licenses: prediction<br/>within the observed regime\"]\n  S --> S2[\"Licenses: counterfactual<br/>equilibria and full welfare<br/>Costs: functional forms,<br/>identification burden\"]\n  N --> N2[\"Licenses: the words<br/>optimal, mistake, and<br/>welfare bound<br/>Costs: none if it stays small\"]\n  N2 --> W[\"Departures from N become<br/>the measurement target\"]\n```\n\nThe practical consequence is a sequencing rule. Write the normative model\n*before* looking at the mechanism data, because its role is to tell you which\nsurvey questions and which behavioral signatures are diagnostic. A model written\nafter the fact to rationalize a pattern is a description with equations.\n\n## Building a Normative Model From Primitives {#sec-nb-build}\n\nWe now construct the benchmark. The economic content is a tension every marketing\nscientist will recognize: a cheap instrument that must be committed to in advance\nversus an expensive instrument that can be deployed after uncertainty resolves.\nCall it the **price-versus-flexibility trade-off**. In the borrowing application,\nthe cheap-but-inflexible instrument is a student loan, taken at the start of the\nyear at a low posted rate on the full amount; the expensive-but-flexible one is a\ncredit card, a line of credit drawn only if and when the need materializes, at a\nmuch higher rate.\n\n### Primitives {#sec-nb-primitives}\n\nAt the start of period $t$ a consumer must finance consumption. She holds outside\nfunds $w$ and enters with debts $b^{c}_{0}$ on the flexible instrument and\n$b^{s}_{0}$ on the committed one, writing $b_0 = b^{c}_{0} + b^{s}_{0}$. Period\nutility is defined relative to a subsistence requirement $\\underline{x}_t$:\n\n$$\nu_t(x) \\;=\\;\n\\begin{cases}\nv_t\\!\\left(x - \\underline{x}_t\\right), & x \\ge \\underline{x}_t,\\\\[2pt]\n-\\infty, & x < \\underline{x}_t,\n\\end{cases}\n$$ {#eq-nb-utility}\n\nwith $v_t$ twice differentiable, increasing, and concave. The $-\\infty$ branch is\ndoing real work: it says the requirement must be met, which is what makes the\nfinancing decision non-trivial rather than a smooth trade-off against\nconsumption. Subsistence is stochastic and binary,\n\n$$\n\\underline{x}_t \\;=\\;\n\\begin{cases}\nh & \\text{with probability } p,\\\\\n\\ell & \\text{with probability } 1-p,\n\\end{cases}\n\\qquad h > \\ell ,\n$$ {#eq-nb-shock}\n\nso $p$ is the probability of the high-need state—an unexpected expense, an\nemergency, a demand shock. The consumer chooses borrowing $b^{s}_{t}$ and\n$b^{c}_{t}$ to solve\n\n$$\n\\max_{b^{s}_{t},\\, b^{c}_{t}} \\; u_t(x_t) \\;+\\; \\beta V_t\\!\\left((1+r^{s})b^{s}_{t} + (1+r^{c})b^{c}_{t}\\right),\n$$ {#eq-nb-problem}\n\nsubject to an accounting constraint tying consumption to endowment and net new\nborrowing, non-negativity, a card limit $\\overline{b}^{c}$, and an availability\nlimit on the committed instrument. Here $0 \\le r^{s} < r^{c} \\le 1$ and\n$\\beta \\in (0,1)$; the continuation value $V_t$ is decreasing in debt carried\nforward, twice differentiable, and weakly concave.\n\nTwo structural features generate everything that follows. First, the committed\ninstrument is chosen *before* the state is realized and accrues interest on the\nfull amount drawn, whether or not it is spent. Second, the flexible instrument is\ndrawn *after* the state is known, at a higher price. This is insurance pricing:\npaying $r^{s}$ with certainty to avoid paying $r^{c}$ in a state that occurs with\nprobability $p$.\n\n### Reduction to a one-dimensional insurance problem {#sec-nb-reduction}\n\nBecause the committed instrument is strictly cheaper, any *known* expense—existing\ndebt, certain future outlays—is optimally financed with it. The only interesting\ndecision concerns the *uncertain* portion. Define the uncertain shortfall\n\n$$\n\\Gamma \\;\\equiv\\;\n\\begin{cases}\n0, & w - b_0 > h,\\\\\nh - (w - b_0), & \\ell < w - b_0 < h,\\\\\nh - \\ell, & w - b_0 < \\ell,\n\\end{cases}\n$$ {#eq-nb-shortfall}\n\nthe amount the consumer would have to borrow in the high state but not in the low\nstate. The decision collapses to a single scalar: how much of $\\Gamma$ to insure\nin advance. Let $\\gamma \\in [0,\\Gamma]$ be the insured amount. Writing\n$A_h = (1+r^{s})(b_0 + h - w)$ and $A_\\ell = (1+r^{s})(b_0 + \\ell - w)$ for the\nbaseline debt carried into each state, the problem becomes\n\n$$\n\\max_{0 \\le \\gamma \\le \\Gamma} \\; J(\\gamma) \\;\\equiv\\; v_t(0) \\;+\\; p\\,V_t\\!\\left(A_h + (r^{c}-r^{s})(\\Gamma-\\gamma)\\right) \\;+\\; (1-p)\\,V_t\\!\\left(A_\\ell + r^{s}\\gamma\\right).\n$$ {#eq-nb-insurance}\n\nRead the two terms. In the high state the consumer needed all of $\\Gamma$; the\ninsured part cost her the cheap rate, and the uninsured remainder $\\Gamma - \\gamma$\nmust be drawn on the flexible instrument, costing an extra $(r^{c}-r^{s})$ per\ndollar. In the low state she did not need the money, and the $\\gamma$ she borrowed\nin advance costs her $r^{s}\\gamma$ for nothing. Insurance has a premium and a\npayout, exactly as it should.\n\n### The optimality condition and the threshold rule {#sec-nb-threshold}\n\nDifferentiating @eq-nb-insurance,\n\n$$\nJ'(\\gamma) \\;=\\; -\\,p\\,(r^{c}-r^{s})\\,V_t'\\!\\left(A_h + (r^{c}-r^{s})(\\Gamma-\\gamma)\\right) \\;+\\; (1-p)\\,r^{s}\\,V_t'\\!\\left(A_\\ell + r^{s}\\gamma\\right).\n$$ {#eq-nb-foc}\n\nSince $V_t' < 0$, the first term is positive (insuring lowers debt in the state\nwhere debt is high) and the second is negative (insuring raises debt in the state\nwhere it was unnecessary). Full insurance $\\gamma^{*} = \\Gamma$ is optimal when\n$J'(\\Gamma) \\ge 0$, that is when\n\n$$\np\\,(r^{c}-r^{s})\\,\\bigl|V_t'(A_h)\\bigr| \\;\\ge\\; (1-p)\\,r^{s}\\,\\bigl|V_t'(A_\\ell + r^{s}\\Gamma)\\bigr| ,\n$$ {#eq-nb-full}\n\nand zero insurance $\\gamma^{*}=0$—financing the whole shortfall on the expensive\nflexible instrument—is optimal when $J'(0) \\le 0$, that is when\n\n$$\np\\,(r^{c}-r^{s})\\,\\bigl|V_t'\\!\\left(A_h + (r^{c}-r^{s})\\Gamma\\right)\\bigr| \\;\\le\\; (1-p)\\,r^{s}\\,\\bigl|V_t'(A_\\ell)\\bigr| .\n$$ {#eq-nb-none}\n\nBecause $V_t$ is concave and decreasing, $|V_t'|$ is increasing in debt, so the\nleft side of @eq-nb-none is evaluated at a *higher* debt level than the left side\nof @eq-nb-full. This yields the central result.\n\n::: {.callout-important}\n## The threshold characterization\n\nThere exist probabilities $p_1 \\le p_2$ with $0 < p_1 \\le p_2 \\le r^{s}/r^{c}$\nsuch that the optimal policy is: **fully insure** with the committed instrument\nwhen $p \\ge p_2$; **partially insure** when $p_1 < p < p_2$; and **finance the\nentire shortfall on the flexible instrument** when $p \\le p_1$. If the\ncontinuation value is linear, the two thresholds coincide at exactly\n$p_1 = p_2 = r^{s}/r^{c}$ [@brown2026spillover].\n:::\n\nThe linear case is worth verifying because it delivers the formula that later\ncarries the entire welfare calculation. With $|V_t'|$ constant, @eq-nb-full\nbecomes $p(r^{c}-r^{s}) \\ge (1-p)r^{s}$, hence $p\\,r^{c} \\ge r^{s}$, hence\n\n$$\np \\;\\ge\\; \\frac{r^{s}}{r^{c}} .\n$$ {#eq-nb-linear-threshold}\n\nEverything hinges on two observable magnitudes: how likely the shock is, and how\nmuch more the flexible instrument costs. That is a remarkably small informational\nrequirement for a normative statement, and it is the reason the model can be\ncalibrated from a survey and two posted interest rates rather than estimated.\n\nTwo comparative statics follow and are directly testable. Insuring becomes more\nattractive when the shock is more likely and when the price gap is larger. And\nunder non-increasing absolute risk aversion, consumers who enter with more debt or\nfewer resources are *less* willing to gamble on the expensive instrument—so the\npoorer and more indebted consumer should, if optimizing, rely more on the cheap\ncommitted instrument, not less.\n\n@fig-nb-policy summarizes the decision.\n\n```{mermaid}\n%%| label: fig-nb-policy\n%%| fig-cap: \"The normative policy function. Known expenses always go on the cheap committed instrument; only the uncertain shortfall is a real decision, and it is resolved by comparing the shock probability to the price ratio of the two instruments.\"\nflowchart TB\n  E[\"Financing need this period\"] --> K{\"Is the expense known<br/>at the decision date?\"}\n  K -->|\"Yes\"| CH[\"Committed instrument:<br/>strictly dominates<br/>because r_s < r_c\"]\n  K -->|\"No: uncertain shortfall Gamma\"| PR{\"Compare shock probability p<br/>to the price ratio r_s / r_c\"}\n  PR -->|\"p >= p_2\"| FI[\"Fully insure:<br/>borrow Gamma in advance<br/>on the committed instrument\"]\n  PR -->|\"p_1 < p < p_2\"| PI[\"Partially insure:<br/>interior gamma*\"]\n  PR -->|\"p <= p_1\"| NI[\"Do not insure:<br/>draw the flexible instrument<br/>only if the shock hits\"]\n  CH --> OUT[\"Normative benchmark:<br/>the behavior a well-informed<br/>optimizer would display\"]\n  FI --> OUT\n  PI --> OUT\n  NI --> OUT\n```\n\n## Solving and Exploring the Benchmark Numerically {#sec-nb-numeric}\n\nAnalytical thresholds are only useful if you can compute them for the parameters\nof your setting. The code below specifies a concrete continuation value, solves\n@eq-nb-insurance for the optimal insured amount, and locates $p_1$ and $p_2$. We\nuse $V(D) = -D^{1+\\varphi}/(1+\\varphi)$ with $\\varphi \\ge 0$, which is decreasing\nand concave in debt, and which nests the linear benchmark at $\\varphi = 0$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Continuation value over debt carried forward: decreasing and concave.\n# phi = 0 is the linear (risk-neutral-in-debt) benchmark.\nV     <- function(D, phi) if (phi == 0) -D else -(D^(1 + phi)) / (1 + phi)\nVprime <- function(D, phi) -(D^phi)          # negative, magnitude increasing in D\n\n# Objective (4): choose gamma in [0, Gamma] to insure the uncertain shortfall.\nobjective <- function(gamma, p, rs, rc, Gamma, A_h, A_l, phi) {\n  p * V(A_h + (rc - rs) * (Gamma - gamma), phi) +\n    (1 - p) * V(A_l + rs * gamma, phi)\n}\n\ngamma_star <- function(p, rs, rc, Gamma, A_h, A_l, phi) {\n  opt <- optimize(objective, interval = c(0, Gamma), maximum = TRUE,\n                  p = p, rs = rs, rc = rc, Gamma = Gamma,\n                  A_h = A_h, A_l = A_l, phi = phi)\n  # The linear case (phi = 0) is bang-bang, so compare the interior candidate\n  # against both corners rather than trusting a golden-section search on a\n  # monotone objective.\n  cand <- c(0, opt$maximum, Gamma)\n  vals <- vapply(cand, objective, numeric(1),\n                 p = p, rs = rs, rc = rc, Gamma = Gamma,\n                 A_h = A_h, A_l = A_l, phi = phi)\n  cand[which.max(vals)]\n}\n\n# Baseline calibration: posted subsidized/unsubsidized student loan rates versus\n# a prime credit card rate, and a $1,000 uncertain shortfall.\nrs <- 0.068; rc <- 0.195\nGamma <- 1000; A_h <- 2500; A_l <- 1500\n\n# Linear case: the interior solution disappears and the cutoff is exactly rs/rc.\nc(cutoff_linear = rs / rc,\n  gamma_at_p_below = gamma_star(0.30, rs, rc, Gamma, A_h, A_l, phi = 0),\n  gamma_at_p_above = gamma_star(0.45, rs, rc, Gamma, A_h, A_l, phi = 0))\n#>    cutoff_linear gamma_at_p_below gamma_at_p_above \n#>        0.3487179        0.0000000     1000.0000000\n```\n:::\n\n\nWith a linear continuation value the policy is bang-bang and switches exactly at\n$r^{s}/r^{c} \\approx 0.349$. Curvature opens an interior region between $p_1$ and\n$p_2$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\ngrid <- expand.grid(p = seq(0.02, 0.95, by = 0.01), phi = c(0, 0.5, 1.5))\ngrid$gamma <- mapply(function(p, phi)\n  gamma_star(p, rs, rc, Gamma, A_h, A_l, phi), grid$p, grid$phi)\n\nggplot(grid, aes(p, gamma / Gamma, colour = factor(phi))) +\n  geom_vline(xintercept = rs / rc, linetype = \"dashed\", linewidth = 0.3) +\n  geom_line(linewidth = 0.8) +\n  scale_colour_discrete(name = \"Curvature (phi)\") +\n  labs(x = \"Probability of the high-need state (p)\",\n       y = \"Optimal insured share  gamma* / Gamma\",\n       title = \"The normative policy function\") +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![Optimal insured share of the uncertain shortfall as a function of the shock probability, for three degrees of curvature in the continuation value. The dashed line marks the linear-case cutoff r_s / r_c. Curvature converts the knife-edge switch into an interval of partial insurance, but the qualitative rule is unchanged: insure more when shocks are likelier.](67-normative-benchmarks_files/figure-html/fig-nb-gamma-1.png){#fig-nb-gamma fig-align='center' width=85%}\n:::\n:::\n\n\nThe comparative static in the price gap is what makes the model useful for a\nmarketing setting where the two instruments' prices are institutional facts:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncutoffs <- data.frame(\n  card_rate   = c(0.12, 0.155, 0.195, 0.215, 0.25),\n  loan_rate   = 0.068\n)\ncutoffs$cutoff_p <- cutoffs$loan_rate / cutoffs$card_rate\ncutoffs$reading  <- ifelse(cutoffs$cutoff_p > 0.5,\n                           \"flexible instrument optimal for most consumers\",\n                           \"committed instrument optimal for most consumers\")\ncutoffs\n#>   card_rate loan_rate  cutoff_p                                         reading\n#> 1     0.120     0.068 0.5666667  flexible instrument optimal for most consumers\n#> 2     0.155     0.068 0.4387097 committed instrument optimal for most consumers\n#> 3     0.195     0.068 0.3487179 committed instrument optimal for most consumers\n#> 4     0.215     0.068 0.3162791 committed instrument optimal for most consumers\n#> 5     0.250     0.068 0.2720000 committed instrument optimal for most consumers\n```\n:::\n\n\nAt a 19.5 percent card rate against a 6.8 percent loan rate, any consumer facing\nbetter than a roughly 35 percent chance of an emergency should be pre-borrowing on\nthe cheap instrument. That threshold is low enough that a large share of the\npopulation sits above it—which is precisely why the empirical question of what\nconsumers actually do is interesting.\n\n## Departures From the Benchmark {#sec-nb-departures}\n\nA normative model becomes a research instrument only when you enumerate the ways\nconsumers can fail it, because each failure mode implies a different prediction and\na different welfare sign. The taxonomy that has become standard in consumer\nfinancial regulation distinguishes ignorance of contract terms, ignorance of\nfinancial concepts, ignorance of one's own financial history, and ignorance of\none's own future behavior [@campbell2016restoring; @campbell2011consumer].\n\n**Ignorance of terms.** The consumer optimizes under wrong beliefs about\n$r^{c}$ or $r^{s}$. If she believes the rates are equal, @eq-nb-linear-threshold\nimplies the flexible instrument is weakly better at *every* $p$, so she never\ninsures. Diagnostic: does she know the rate on her own account?\n\n**Ignorance of concepts.** She misunderstands compounding, inflation, or risk, and\nso misprices the future consequence of debt [@lusardi2014economic]. Diagnostic:\nstandard financial-literacy items. This is the departure most reliably tied to\ncarrying expensive debt, and it is also the one for which the marketing evidence on\nremediation is least encouraging: financial education explains very little\nvariance in downstream behavior once endowed traits are accounted for\n[@fernandes2014financial].\n\n**Ignorance of own history.** She does not know what options she already has—for\nexample, believing she has exhausted her cheap borrowing capacity when unclaimed\nsubsidized capacity remains. She then behaves as if $r^{s}$ were prohibitive and\nfinances everything on the flexible instrument. Diagnostic: compare stated\navailability against the administrative record. This departure is invisible in\nsurvey-only and in records-only data; it requires the two to be linked, which is\nthe methodological point of @sec-complementary-evidence.\n\n**Ignorance of own behavior.** She is present-biased and naive about it\n[@odonoghue1999doing]. She selects the instrument correctly ex ante, then\noverspends on the flexible one regardless of the state. Diagnostic: elicited\ndiscounting, and the signature that card use is uncorrelated with the emergency\nprobability that is supposed to drive it.\n\n@tbl-nb-departures maps each departure to its behavioral signature, its\nmeasurement, and—critically—the sign of the welfare effect of a policy that\nrestricts the flexible instrument.\n\n| Departure | Behavioral signature | How it is measured | Effect of restricting the flexible instrument |\n|:--|:--|:--|:--|\n| None (optimizer) | Insures iff $p \\ge p_2$; known expenses on the cheap instrument | Consistency of choices with @eq-nb-linear-threshold | Weakly negative: choice restriction cannot help someone already optimizing |\n| Terms unknown | Uses flexible instrument at all $p$; cannot state own rate | Direct question on own APR | Positive when $p > r^{s}/r^{c}$; negative when $p$ is very low |\n| Concepts unknown | Revolves expensive debt; low literacy score | Standard literacy items | Positive on average, magnitude rising in $p$ |\n| Own history unknown | Revolves while holding unclaimed cheap capacity | Survey response matched to records | Positive: the restriction pushes search toward the option she wrongly believed unavailable |\n| Own behavior unknown (naive present bias) | Borrows the same total but on the expensive instrument; use uncorrelated with $p$ | Elicited discounting; correlation of use with stated shock risk | Weakly positive: same debt, lower price |\n\n: Departures from the normative benchmark, their empirical signatures, and the welfare consequence of a policy that steers consumers away from the expensive flexible instrument. The welfare column is what converts a taxonomy into a research design. {#tbl-nb-departures}\n\nThe last column is the payoff of the whole exercise. Restricting choice can only\nhurt an optimizer; every positive welfare entry in the table comes from a consumer\nwho was choosing badly. Therefore the empirical share of each type is not a\ndescriptive detail—it is the weight in the welfare aggregate, which is exactly how\n@sec-welfare-calibration uses it.\n\n::: {.callout-warning}\n## The identification problem inside the taxonomy\n\nSeveral departures predict the same *aggregate* behavior—more expensive borrowing—so\nthey cannot be separated by the borrowing data alone. Distinguishing them requires\nmeasures that are diagnostic of the mechanism rather than the outcome: knowledge\nof one's own rate separates terms-ignorance, literacy items separate\nconcept-ignorance, record-linked availability separates history-ignorance, and the\ncorrelation between use and stated shock probability separates present bias.\nDesigning those measures is part of designing the model, not a downstream data\ntask.\n:::\n\n## Abstracting the Recipe {#sec-nb-recipe}\n\nStrip the credit context away and the construction has four moving parts. Any\nmarketing problem with the same four parts admits the same treatment.\n\n1. **Two or more instruments serving one need, ordered by price and flexibility.**\n   Cheap-but-committed versus expensive-but-contingent. The ordering must be\n   institutional, not estimated, so the benchmark does not depend on the data.\n2. **Uncertainty resolved between the commitment and the contingent draw.** Without\n   the timing wedge there is no insurance problem and the cheap instrument\n   trivially dominates.\n3. **A scalar reduction.** Push everything known into the dominant instrument so\n   the decision collapses to a single choice variable. This is what keeps the model\n   solvable in closed form and calibratable from a handful of moments.\n4. **A cutoff expressed in observable quantities.** The threshold should be a\n   function of prices and a probability, not of a preference parameter, because\n   prices are posted and probabilities can be elicited.\n\n@tbl-nb-translations applies the recipe to marketing settings.\n\n| Setting | Cheap / committed instrument | Expensive / flexible instrument | Uncertainty | Normative cutoff governed by |\n|:--|:--|:--|:--|:--|\n| Subscription vs. à la carte | Annual plan or bundle | Pay-per-use | Usage volume next year | Usage probability vs. price ratio |\n| Loyalty currency | Points banked toward a fixed redemption | Cash purchase at posted price | Whether the redemption occasion arises | Redemption probability vs. breakage-adjusted price gap |\n| Insurance and warranties | Ex ante premium | Ex post out-of-pocket repair | Failure event | Failure probability vs. loading factor |\n| Pre-commitment promotions | Prepaid or pre-ordered quantity | Spot purchase during the season | Demand realization | Stockout probability vs. price premium |\n| Media and inventory buying | Upfront guaranteed buy | Spot / real-time auction | Audience availability and price | Scarcity probability vs. spot-price premium |\n| Data and consent | Broad first-party consent gathered early | Costly per-instance targeting workarounds | Whether the targeting occasion arises | Occasion probability vs. workaround cost ratio |\n\n: The price-versus-flexibility template translated into marketing settings. Each row supports the same normative analysis: characterize the cutoff, measure the departure, and evaluate a policy or platform change that pushes consumers across it. {#tbl-nb-translations}\n\nThe same structure appears in the choice-friction literature that produced the\nbest-known welfare estimates in applied microeconomics: consumers who stay in\ndominated health-insurance plans [@handel2013adverse; @handel2015health], elderly\nenrollees who choose dominated drug plans [@abaluck2011choice], homeowners who\nfail to refinance at large certain gains [@keys2016failure], savers who split\ncontributions naively across offered funds [@benartzi2001naive], and buyers who\nunderweight future fuel costs [@busse2013myopic]. In each, the paper's contribution\nis a credible normative benchmark plus a measured distance from it. Marketing has\nthe same opportunity in every category where a firm offers a menu whose optimal\nselection is computable.\n\n::: {.callout-tip}\n## Keeping the model small on purpose\n\nThe temptation, once a normative model is written, is to enrich it: add\nheterogeneity, add dynamics, estimate it. Resist until you know what the added\nstructure buys. In the anchor paper the authors explicitly decline full estimation\nbecause it \"requires substantial functional form restrictions on students'\npreferences for which theory provides little guidance,\" and instead derive bounds\nthat hold for *any* utility function satisfying their assumptions\n[@brown2026spillover]. A result that survives an entire class of preferences is\nworth more to a referee than a point estimate that survives one.\n:::\n\n## From Benchmark to Welfare {#sec-nb-to-welfare}\n\nThe normative model has now produced three things a policy evaluation needs. It has\nproduced a *prediction*—who should use which instrument, and how that varies with\nprices, shock risk, and resources—that the reduced-form heterogeneity analysis of\n@sec-policy-spillovers can test. It has produced a *taxonomy* of departures, each\nwith a distinct measurable signature, which tells the survey what to ask. And it\nhas produced a *welfare expression*: because we know the optimal policy, we can\nwrite the change in the consumer's continuation value when the flexible instrument\nis taken away, separately by type.\n\nThat last object is the input to @sec-welfare-calibration, where the utility\nfunction is normalized away, the expression is reduced to a formula in $p$ and\n$r^{c}/r^{s}$, and the population shares from the survey turn it into a number.\n\n## Key Takeaways {#sec-nb-takeaways}\n\n- The word \"mistake\" requires a benchmark. A normative model supplies it by\n  characterizing what an informed optimizer would do, and it is deliberately\n  smaller than a structural model because it is not asked to fit the data.\n- Write the normative model before the mechanism data are collected; its function\n  is to determine which measurements are diagnostic.\n- The workhorse structure is the price-versus-flexibility trade-off\n  (@eq-nb-insurance): a cheap instrument committed to before uncertainty resolves\n  versus an expensive one drawn after, which is formally an insurance problem.\n- The solution is a threshold rule (@eq-nb-full, @eq-nb-none). Under a linear\n  continuation value it collapses to the strikingly simple cutoff\n  $p \\ge r^{s}/r^{c}$ (@eq-nb-linear-threshold), a normative statement requiring\n  only two posted prices and one elicited probability.\n- Enumerate departures explicitly (@tbl-nb-departures). Each has a distinct\n  behavioral signature, a distinct measurement, and—decisively—a distinct sign for\n  the welfare effect of restricting the expensive instrument.\n- Restricting choice can never help an agent who is already optimizing, so the\n  entire welfare case for a paternalistic policy rests on the measured population\n  share of each non-optimizing type.\n- The recipe (@tbl-nb-translations) transfers to subscriptions, loyalty currencies,\n  warranties, pre-commitment promotions, media buying, and consent regimes—any\n  marketing menu whose optimal selection is computable from posted terms.\n\n## Further Reading {#sec-nb-further}\n\nThe model developed here is that of @brown2026spillover; read it for the formal\npropositions and the appendix proofs. The taxonomy of consumer financial mistakes\nis due to @campbell2016restoring, with the policy framing in @campbell2011consumer;\n@lusardi2014economic surveys the literacy evidence and @fernandes2014financial\nprovides the marketing field's most influential skeptical assessment of financial\neducation as a remedy. On naive present bias as a distinct departure, see\n@odonoghue1999doing. For exemplary applications of the normative-benchmark strategy\nin adjacent fields, @handel2013adverse and @handel2015health on insurance,\n@abaluck2011choice on Medicare Part D, @keys2016failure on refinancing,\n@benartzi2001naive on retirement allocation, and @busse2013myopic on durable-good\npurchases. @gabaix2006shrouded supplies the supply-side counterpart—why competitive\nfirms may have no incentive to unshroud the attribute the consumer is getting\nwrong—and @dellavigna2009psychology surveys the field evidence for departures from\nthe standard model. The relationship between normative, descriptive, and structural\nmodeling is developed further in @sec-model-building, @sec-analytical-models, and\n@sec-structural-models.\n",
    "supporting": [
      "67-normative-benchmarks_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}