<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>31&nbsp; Measurement Scales – Marketing Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./31-surveys.html" rel="next">
<link href="./29-structural-models.html" rel="prev">
<link href="./favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-364982630eef5352dd1537128a8ed5cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="site_libs/quarto-diagram/mermaid.min.js"></script><script src="site_libs/quarto-diagram/mermaid-init.js"></script><link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./23-metrics.html">Methodology</a></li><li class="breadcrumb-item"><a href="./30-measurement-scales.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Measurement Scales</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Marketing Research</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/mikenguyen13/marketing_research" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b-history-of-marketing-thought.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A Short History of Marketing Thought</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Constructs &amp; Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-construct-vs-variable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Constructs vs.&nbsp;Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-satisfaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Customer Satisfaction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-innovation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Innovation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-market-entry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Market Entry</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-virality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Virality and Word of Mouth</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-sarcasm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sarcasm and Figurative Language</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Substantive Domains</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-branding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Branding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-online-environments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Online Environments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-advertising.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Advertising</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-communication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Communication</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-sales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-clv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Customer Lifetime Value</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-celebrity-endorsement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Celebrity Endorsement</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-influencer-marketing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Influencer Marketing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-nudges.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Nudges and Choice Architecture</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-pricing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Pricing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-service.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Services Marketing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-health.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Healthcare and Pharmaceutical Marketing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-gaming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Games and Gamification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-marketing-finance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Marketing–Finance Interface</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-privacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Privacy</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-metrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Metrics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Modeling in Marketing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-analytical-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Analytical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-empirical-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Empirical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-model-building.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Model Building</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-structural-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Structural Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-measurement-scales.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Measurement Scales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-surveys.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Surveys and Experiments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-preference-measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Preference Measurement</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33-qualitative-research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Qualitative Research</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34-image-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Images as Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35-industrial-organization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Industrial Organization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./47-causal-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Causal Inference and Field Experiments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./50-choice-bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Discrete Choice and Bayesian Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./49-text-as-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Text as Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Topics &amp; Seminars</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./36-marketing-mix-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Marketing Mix Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./37-strategic-dynamic-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Strategic Dynamic Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./48-ai-ml-marketing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Artificial Intelligence and Machine Learning in Marketing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./51-platforms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Platforms and Two-Sided Markets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./38-consumer-behavior-seminar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Consumer Behavior: A Doctoral Seminar</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./39-analytical-modeling-seminar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Analytical Modeling Seminar</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40-marketing-strategy-seminar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Marketing Strategy Seminar</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Research Craft</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41-scientific-writing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Scientific Writing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42-review-process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">The Review Process</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Reporting Research Results</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Case Studies</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./44-case-branding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Case Studies in Branding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./45-case-branding-instructor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Case Studies in Branding: An Instructor’s Companion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./46-case-advertising.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Case Studies in Advertising</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a1-others.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Selected Topics in Marketing Strategy and Measurement</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#true-score-theory-and-the-definition-of-reliability" id="toc-true-score-theory-and-the-definition-of-reliability" class="nav-link active" data-scroll-target="#true-score-theory-and-the-definition-of-reliability"><span class="header-section-number">31.1</span> True-Score Theory and the Definition of Reliability</a></li>
  <li>
<a href="#reflective-versus-formative-measurement" id="toc-reflective-versus-formative-measurement" class="nav-link" data-scroll-target="#reflective-versus-formative-measurement"><span class="header-section-number">31.2</span> Reflective versus Formative Measurement</a>
  <ul class="collapse">
<li><a href="#the-reflective-model" id="toc-the-reflective-model" class="nav-link" data-scroll-target="#the-reflective-model"><span class="header-section-number">31.2.1</span> The Reflective Model</a></li>
  <li><a href="#the-formative-model" id="toc-the-formative-model" class="nav-link" data-scroll-target="#the-formative-model"><span class="header-section-number">31.2.2</span> The Formative Model</a></li>
  <li><a href="#a-formal-contrast-and-the-mimic-bridge" id="toc-a-formal-contrast-and-the-mimic-bridge" class="nav-link" data-scroll-target="#a-formal-contrast-and-the-mimic-bridge"><span class="header-section-number">31.2.3</span> A Formal Contrast and the MIMIC Bridge</a></li>
  <li><a href="#why-misspecification-is-costly" id="toc-why-misspecification-is-costly" class="nav-link" data-scroll-target="#why-misspecification-is-costly"><span class="header-section-number">31.2.4</span> Why Misspecification Is Costly</a></li>
  </ul>
</li>
  <li><a href="#scale-development" id="toc-scale-development" class="nav-link" data-scroll-target="#scale-development"><span class="header-section-number">31.3</span> Scale Development</a></li>
  <li>
<a href="#sec-reliability-validity" id="toc-sec-reliability-validity" class="nav-link" data-scroll-target="#sec-reliability-validity"><span class="header-section-number">31.4</span> Reliability and Validity</a>
  <ul class="collapse">
<li><a href="#internal-consistency-reliability" id="toc-internal-consistency-reliability" class="nav-link" data-scroll-target="#internal-consistency-reliability"><span class="header-section-number">31.4.1</span> Internal-Consistency Reliability</a></li>
  <li><a href="#convergent-and-discriminant-validity" id="toc-convergent-and-discriminant-validity" class="nav-link" data-scroll-target="#convergent-and-discriminant-validity"><span class="header-section-number">31.4.2</span> Convergent and Discriminant Validity</a></li>
  <li><a href="#criterion-and-nomological-validity" id="toc-criterion-and-nomological-validity" class="nav-link" data-scroll-target="#criterion-and-nomological-validity"><span class="header-section-number">31.4.3</span> Criterion and Nomological Validity</a></li>
  <li><a href="#inter-rater-reliability-for-coded-data" id="toc-inter-rater-reliability-for-coded-data" class="nav-link" data-scroll-target="#inter-rater-reliability-for-coded-data"><span class="header-section-number">31.4.4</span> Inter-Rater Reliability for Coded Data</a></li>
  <li><a href="#a-worked-reflective-measurement-model" id="toc-a-worked-reflective-measurement-model" class="nav-link" data-scroll-target="#a-worked-reflective-measurement-model"><span class="header-section-number">31.4.5</span> A Worked Reflective Measurement Model</a></li>
  </ul>
</li>
  <li>
<a href="#common-method-bias" id="toc-common-method-bias" class="nav-link" data-scroll-target="#common-method-bias"><span class="header-section-number">31.5</span> Common-Method Bias</a>
  <ul class="collapse">
<li><a href="#a-formal-model-of-the-bias" id="toc-a-formal-model-of-the-bias" class="nav-link" data-scroll-target="#a-formal-model-of-the-bias"><span class="header-section-number">31.5.1</span> A Formal Model of the Bias</a></li>
  <li><a href="#procedural-and-statistical-remedies" id="toc-procedural-and-statistical-remedies" class="nav-link" data-scroll-target="#procedural-and-statistical-remedies"><span class="header-section-number">31.5.2</span> Procedural and Statistical Remedies</a></li>
  </ul>
</li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">31.6</span> Key Takeaways</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">31.7</span> Further Reading</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/mikenguyen13/marketing_research/edit/main/30-measurement-scales.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/mikenguyen13/marketing_research/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./23-metrics.html">Methodology</a></li><li class="breadcrumb-item"><a href="./30-measurement-scales.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Measurement Scales</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-measurement-scales" class="quarto-section-identifier"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Measurement Scales</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Most of the constructs marketing cares about—brand equity, satisfaction, involvement, trust, perceived authenticity—cannot be read off a receipt. They are <em>latent</em>: properties of a consumer’s mind that leave only indirect traces in answers to survey questions, in choices, and in behavior. A <strong>measurement scale</strong> is the instrument that turns those traces into numbers we can analyze, and the <strong>measurement model</strong> is the formal theory that says how the numbers relate to the construct they are supposed to capture. Getting the measurement model wrong is not a cosmetic error. It silently biases every downstream coefficient, invalidates the reliability and validity tests a reviewer will demand, and—most consequentially—can reverse a managerial recommendation, because the model dictates whether a manager should strengthen a coherent latent disposition or intervene on specific, possibly uncorrelated, drivers.</p>
<p>This chapter develops measurement as a modeling problem rather than a checklist. We begin with the classical theory that underwrites almost all psychometrics—<strong>true-score theory</strong>—and use it to define reliability precisely. We then draw the central distinction of the modern literature, between <strong>reflective</strong> and <strong>formative</strong> measurement, and make it formal with structural equations, including the identification conditions that decide whether a model can be estimated at all. With that machinery in place we walk through <strong>scale development</strong> as a disciplined sequence, define the standard battery of <strong>reliability and validity</strong> statistics and give their estimators and assumptions, and confront <strong>common-method bias</strong>—the contamination that arises when the same respondent supplies both predictor and outcome through the same instrument. Throughout, the goal is the one set in <a href="08-branding.html" class="quarto-xref"><span>Chapter 9</span></a> when it asked whether brand equity is reflective or formative: to let the reader decide a construct’s measurement model on principled grounds and defend that decision to a skeptical referee.</p>
<p>A note on scope. We treat <em>psychometric</em> measurement—scales built from multiple survey items—because that is where the reflective/formative question is sharpest and where the field’s two leading handbooks of marketing scales live <span class="citation" data-cites="bearden2011 stewart1993">(<a href="#ref-bearden2011" role="doc-biblioref">Bearden, Netemeyer, and Haws 2011</a>; <a href="#ref-stewart1993" role="doc-biblioref">Stewart et al. 1993</a>)</span>. The logic transfers directly to behavioral and text-derived measures, which are developed in <a href="49-text-as-data.html" class="quarto-xref"><span>Chapter 39</span></a>.</p>
<section id="true-score-theory-and-the-definition-of-reliability" class="level2" data-number="31.1"><h2 data-number="31.1" class="anchored" data-anchor-id="true-score-theory-and-the-definition-of-reliability">
<span class="header-section-number">31.1</span> True-Score Theory and the Definition of Reliability</h2>
<p>The foundation of classical test theory is disarmingly simple. An observed score <span class="math inline">\(X\)</span> on an item is the sum of a <strong>true score</strong> <span class="math inline">\(T\)</span>—the construct value we wish we could see—and a <strong>measurement error</strong> <span class="math inline">\(E\)</span>:</p>
<p><span id="eq-truescore"><span class="math display">\[
X = T + E .
\tag{31.1}\]</span></span></p>
<p>The theory’s content is in three assumptions about <span class="math inline">\(E\)</span>: it has mean zero, <span class="math inline">\(\mathbb{E}[E] = 0\)</span>, so <span class="math inline">\(T = \mathbb{E}[X]\)</span> is <em>defined</em> as the expected observed score; it is uncorrelated with the true score, <span class="math inline">\(\mathrm{Cov}(T, E) = 0\)</span>; and errors on distinct items are mutually uncorrelated. Under these assumptions the observed variance decomposes additively,</p>
<p><span id="eq-varsplit"><span class="math display">\[
\sigma_X^2 = \sigma_T^2 + \sigma_E^2 ,
\tag{31.2}\]</span></span></p>
<p>and <strong>reliability</strong> is <em>defined</em> as the share of observed variance that is true variance,</p>
<p><span id="eq-30-reliability"><span class="math display">\[
\rho_{XX'} \;=\; \frac{\sigma_T^2}{\sigma_X^2} \;=\; \frac{\sigma_T^2}{\sigma_T^2 + \sigma_E^2} \in [0,1].
\tag{31.3}\]</span></span></p>
<p>Reliability is therefore not “consistency” in a loose sense; it is a variance ratio, equal to the squared correlation between observed and true scores and to the correlation between two <em>parallel</em> measurements of the same construct (hence the notation <span class="math inline">\(\rho_{XX'}\)</span>). It says nothing about whether <span class="math inline">\(T\)</span> measures the <em>right</em> construct—that is validity, and the two must never be conflated. A bathroom scale that always reads three kilograms heavy is perfectly reliable and invalid.</p>
<p>Reliability matters beyond bookkeeping because unreliable measurement <em>attenuates</em> relationships. If a predictor <span class="math inline">\(X\)</span> measures a true <span class="math inline">\(T\)</span> with reliability <span class="math inline">\(\rho_{XX}\)</span> and an outcome <span class="math inline">\(Y\)</span> measures <span class="math inline">\(U\)</span> with reliability <span class="math inline">\(\rho_{YY}\)</span>, the observable correlation is shrunk toward zero relative to the construct-level correlation:</p>
<p><span id="eq-30-attenuation"><span class="math display">\[
\mathrm{Corr}(X, Y) \;=\; \mathrm{Corr}(T, U)\,\sqrt{\rho_{XX}\,\rho_{YY}} .
\tag{31.4}\]</span></span></p>
<p><a href="#eq-30-attenuation" class="quarto-xref">Equation&nbsp;<span>31.4</span></a> is the <em>correction for attenuation</em>. It is why a true effect can be buried by a noisy scale, and why latent-variable models—which estimate <span class="math inline">\(\mathrm{Corr}(T,U)\)</span> directly—are preferred to regressions on summed scores when reliability is modest.</p>
<blockquote class="blockquote">
<p>Multiple-item measurement exists almost entirely to beat down <span class="math inline">\(\sigma_E^2\)</span>. By the Spearman–Brown logic, averaging <span class="math inline">\(k\)</span> interchangeable items whose errors are independent divides the error variance of the composite by <span class="math inline">\(k\)</span> while leaving the true variance intact, so a composite of many noisy items can be far more reliable than any single item.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> This is the engine behind multi-item scales—and, as we will see, it is exactly the property a <em>formative</em> index does not have.</p>
</blockquote>
</section><section id="reflective-versus-formative-measurement" class="level2" data-number="31.2"><h2 data-number="31.2" class="anchored" data-anchor-id="reflective-versus-formative-measurement">
<span class="header-section-number">31.2</span> Reflective versus Formative Measurement</h2>
<p>The single most consequential decision in scale construction is the direction of causality between the latent construct and its indicators. The choice is not a matter of taste; it is a substantive claim about how the world works, and it determines which model is even identified <span class="citation" data-cites="coltman2008 diamantopoulos2013quantitative">(<a href="#ref-coltman2008" role="doc-biblioref">Coltman et al. 2008</a>; <a href="#ref-diamantopoulos2013quantitative" role="doc-biblioref">Diamantopoulos, Fritz, and Hildebrandt 2013</a>)</span>.</p>
<section id="the-reflective-model" class="level3" data-number="31.2.1"><h3 data-number="31.2.1" class="anchored" data-anchor-id="the-reflective-model">
<span class="header-section-number">31.2.1</span> The Reflective Model</h3>
<p>In a <strong>reflective</strong> (effect-indicator) model, the latent construct <em>causes</em> its indicators: the items are manifestations, symptoms, or reflections of an underlying common cause. Let <span class="math inline">\(\eta\)</span> be a scalar latent construct and <span class="math inline">\(x_1,\dots,x_K\)</span> its observed indicators. The model is the common-factor model,</p>
<p><span id="eq-30-reflective"><span class="math display">\[
x_k \;=\; \lambda_k\, \eta \;+\; \varepsilon_k, \qquad k = 1,\dots,K,
\tag{31.5}\]</span></span></p>
<p>with <span class="math inline">\(\mathbb{E}[\varepsilon_k]=0\)</span>, <span class="math inline">\(\mathrm{Cov}(\eta,\varepsilon_k)=0\)</span>, and <span class="math inline">\(\mathrm{Cov}(\varepsilon_j,\varepsilon_k)=0\)</span> for <span class="math inline">\(j\neq k\)</span> (uncorrelated errors). The arrows run <em>from</em> <span class="math inline">\(\eta\)</span> <em>to</em> each <span class="math inline">\(x_k\)</span>. Three properties follow and are diagnostic. First, because the indicators share a single common cause, they must be <strong>positively correlated</strong>; the off-diagonal covariances are <span class="math inline">\(\mathrm{Cov}(x_j,x_k)=\lambda_j\lambda_k\,\sigma_\eta^2\)</span>, all of the same sign as the loadings. Second, the indicators are <strong>interchangeable</strong>: dropping one changes the construct’s domain coverage but not its meaning, since each is a noisy replica of the same <span class="math inline">\(\eta\)</span>. Third, internal consistency (Cronbach’s alpha, composite reliability) is the <em>appropriate</em> quality criterion, precisely because <a href="#eq-30-reflective" class="quarto-xref">Equation&nbsp;<span>31.5</span></a> is the model under which <a href="#eq-30-reliability" class="quarto-xref">Equation&nbsp;<span>31.3</span></a> was derived.</p>
<p>A reflective construct is the right model when the construct is a real, unitary attribute that radiates into measurable symptoms—the way a fever radiates into a high thermometer reading, a flushed face, and chills. Brand love <span class="citation" data-cites="batra2012 bagozzi2016">(<a href="#ref-batra2012" role="doc-biblioref">Batra, Ahuvia, and Bagozzi 2012</a>; <a href="#ref-bagozzi2016" role="doc-biblioref">Bagozzi, Batra, and Ahuvia 2016</a>)</span>, satisfaction, and attitude are conventionally modeled this way: a more satisfied customer answers <em>every</em> satisfaction item more favorably, so the items co-move.</p>
</section><section id="the-formative-model" class="level3" data-number="31.2.2"><h3 data-number="31.2.2" class="anchored" data-anchor-id="the-formative-model">
<span class="header-section-number">31.2.2</span> The Formative Model</h3>
<p>In a <strong>formative</strong> (causal-indicator) model, the indicators <em>cause</em> the construct: the latent variable is a composite <em>formed by</em> its indicators, which are defining ingredients rather than reflections. The structural equation reverses the arrows,</p>
<p><span id="eq-30-formative"><span class="math display">\[
\eta \;=\; \sum_{k=1}^{K} \gamma_k\, x_k \;+\; \zeta,
\tag{31.6}\]</span></span></p>
<p>where <span class="math inline">\(\gamma_k\)</span> are formative weights and <span class="math inline">\(\zeta\)</span> is a disturbance capturing the part of <span class="math inline">\(\eta\)</span> not explained by the chosen indicators, with <span class="math inline">\(\mathrm{Cov}(x_k,\zeta)=0\)</span>. Everything that was diagnostic for the reflective model is now reversed. The indicators need <strong>not</strong> be correlated—socioeconomic status formed from income, education, and occupation does not require that high earners be highly educated. The indicators are <strong>not interchangeable</strong>: removing one (say, income) deletes part of the construct’s <em>definition</em>, not merely part of its sampling. And internal-consistency reliability is <strong>inapplicable</strong>: there is no common cause to make the items co-vary, so a low alpha is no defect. Quality is judged instead by indicator weights, their significance, and <strong>multicollinearity</strong> among indicators (high collinearity makes the weights unstable and uninterpretable), typically diagnosed with the variance inflation factor.</p>
<p>A construct should be formative when it is constituted by a combination of distinct facets that need not move together. Classic examples are an index of <em>life stress</em> (a job loss and a marriage are both stressors but are uncorrelated causes), a <em>marketing capability</em> composite, or a <em>deprivation</em> index. <a href="08-branding.html" class="quarto-xref"><span>Chapter 9</span></a> raised the live debate over whether <strong>brand equity</strong> and <strong>brand authenticity</strong> are reflective or formative; the two leading authenticity scales take opposite stances—<span class="citation" data-cites="morhart2015">Morhart et al. (<a href="#ref-morhart2015" role="doc-biblioref">2015</a>)</span> reflective, <span class="citation" data-cites="nunes2021">Nunes, Ordanini, and Giambastiani (<a href="#ref-nunes2021" role="doc-biblioref">2021</a>)</span> formative—and the disagreement is exactly a disagreement about the direction of <a href="#eq-30-reflective" class="quarto-xref">Equation&nbsp;<span>31.5</span></a> versus <a href="#eq-30-formative" class="quarto-xref">Equation&nbsp;<span>31.6</span></a>.</p>
</section><section id="a-formal-contrast-and-the-mimic-bridge" class="level3" data-number="31.2.3"><h3 data-number="31.2.3" class="anchored" data-anchor-id="a-formal-contrast-and-the-mimic-bridge">
<span class="header-section-number">31.2.3</span> A Formal Contrast and the MIMIC Bridge</h3>
<p><a href="#fig-meas-models" class="quarto-xref">Figure&nbsp;<span>31.1</span></a> contrasts the two path structures, and the table that follows states the operational consequences side by side.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-meas-models" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-meas-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-meas-models">flowchart LR
  subgraph R["Reflective"]
    direction TB
    ETA1((η)) --&gt; X1[x1]
    ETA1 --&gt; X2[x2]
    ETA1 --&gt; X3[x3]
    X1 --- E1((ε1))
    X2 --- E2((ε2))
    X3 --- E3((ε3))
  end
  subgraph F["Formative"]
    direction TB
    Z1[x1] --&gt; ETA2((η))
    Z2[x2] --&gt; ETA2
    Z3[x3] --&gt; ETA2
    ZETA((ζ)) --- ETA2
  end
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-meas-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;31.1: Reflective versus formative measurement. In the reflective model the latent construct η causes the indicators (arrows out, each indicator carries its own error ε). In the formative model the indicators cause the construct (arrows in, a single disturbance ζ attaches to the construct). A MIMIC model combines both: formative causes and reflective indicators of the same latent variable.
</figcaption></figure>
</div>
</div>
</div>
<div id="tbl-refl-form" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-refl-form-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.1: Operational consequences of the reflective–formative distinction.
</figcaption><div aria-describedby="tbl-refl-form-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Property</th>
<th>Reflective (<a href="#eq-30-reflective" class="quarto-xref">Equation&nbsp;<span>31.5</span></a>)</th>
<th>Formative (<a href="#eq-30-formative" class="quarto-xref">Equation&nbsp;<span>31.6</span></a>)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Causal direction</td>
<td>Construct → indicators</td>
<td>Indicators → construct</td>
</tr>
<tr class="even">
<td>Indicator correlation</td>
<td>High, same sign (required)</td>
<td>Not required; any sign</td>
</tr>
<tr class="odd">
<td>Interchangeability</td>
<td>Indicators interchangeable</td>
<td>Indicators define the construct</td>
</tr>
<tr class="even">
<td>Dropping an indicator</td>
<td>Narrows sampling of the domain</td>
<td>Changes the construct’s meaning</td>
</tr>
<tr class="odd">
<td>Error term</td>
<td>One per indicator (<span class="math inline">\(\varepsilon_k\)</span>)</td>
<td>One per construct (<span class="math inline">\(\zeta\)</span>)</td>
</tr>
<tr class="even">
<td>Reliability criterion</td>
<td>Internal consistency (alpha, CR, AVE)</td>
<td>Indicator weights; collinearity (VIF)</td>
</tr>
<tr class="odd">
<td>Identification</td>
<td>Standard (factor model)</td>
<td>Needs external structure (e.g., MIMIC)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The deepest difference in <a href="#tbl-refl-form" class="quarto-xref">Table&nbsp;<span>31.1</span></a> is the last row. A pure formative model is <strong>not identified</strong> in isolation: <a href="#eq-30-formative" class="quarto-xref">Equation&nbsp;<span>31.6</span></a> places no testable restrictions on the indicator covariances, the scale and location of <span class="math inline">\(\eta\)</span> are arbitrary, and the disturbance variance <span class="math inline">\(\sigma_\zeta^2\)</span> cannot be separated from the weights without further information. Identification requires that the formative construct emit <em>at least two reflective indicators</em> (or two paths to downstream constructs), which fixes its metric and disturbance. The resulting hybrid is the <strong>multiple-indicators, multiple-causes (MIMIC)</strong> model: formative causes <span class="math inline">\(x_1,\dots,x_K\)</span> feed a latent <span class="math inline">\(\eta\)</span>, which in turn emits reflective indicators <span class="math inline">\(y_1,\dots,y_M\)</span>,</p>
<p><span id="eq-mimic"><span class="math display">\[
\eta \;=\; \sum_{k=1}^{K}\gamma_k x_k + \zeta,
\qquad
y_m \;=\; \lambda_m \eta + \varepsilon_m, \quad m = 1,\dots,M .
\tag{31.7}\]</span></span></p>
<p>The MIMIC structure is the standard way marketing accommodates a genuinely formative construct inside an estimable structural-equation model <span class="citation" data-cites="diamantopoulos2013quantitative">(<a href="#ref-diamantopoulos2013quantitative" role="doc-biblioref">Diamantopoulos, Fritz, and Hildebrandt 2013</a>)</span>. It also clarifies a common error: estimating <a href="#eq-30-formative" class="quarto-xref">Equation&nbsp;<span>31.6</span></a> by ordinary least squares treats <span class="math inline">\(\eta\)</span> as observed and conflates the formative weights with a regression of an <em>index</em> on its parts, discarding the disturbance and the very latency that motivated the construct. <!-- CITE-NEEDED: Jarvis, MacKenzie & Podsakoff 2003 on misspecification of formative vs reflective constructs --> <!-- CITE-NEEDED: Bollen & Lennox 1991 conventional wisdom on measurement --></p>
</section><section id="why-misspecification-is-costly" class="level3" data-number="31.2.4"><h3 data-number="31.2.4" class="anchored" data-anchor-id="why-misspecification-is-costly">
<span class="header-section-number">31.2.4</span> Why Misspecification Is Costly</h3>
<p>Treating a formative construct as reflective (or the reverse) is not a venial sin. Forcing reflective machinery onto formative indicators discards items that fail to correlate—dropping low-alpha items <em>narrows the construct’s content</em>, biasing it toward whatever facet happens to be internally consistent. Conversely, modeling a reflective construct formatively throws away the error structure that <a href="#eq-30-attenuation" class="quarto-xref">Equation&nbsp;<span>31.4</span></a> depends on and inflates apparent validity. Simulation and analytic work show the resulting structural-coefficient bias can be large and of either sign, which is why the direction-of-causality decision belongs at the <em>start</em> of scale development, justified on conceptual grounds, not discovered after the data are in. <!-- CITE-NEEDED: MacKenzie, Podsakoff & Jarvis 2005 on measurement-model misspecification consequences --></p>
</section></section><section id="scale-development" class="level2" data-number="31.3"><h2 data-number="31.3" class="anchored" data-anchor-id="scale-development">
<span class="header-section-number">31.3</span> Scale Development</h2>
<p>Scale development is the disciplined translation of a construct definition into a validated instrument. The field’s canonical paradigm is a staged procedure that moves from conceptual specification to a purified, validated multi-item scale, and modern treatments differ mainly in how much weight they place on the formative possibility <span class="citation" data-cites="bearden2011">(<a href="#ref-bearden2011" role="doc-biblioref">Bearden, Netemeyer, and Haws 2011</a>)</span>. The stages below are reflective by default; we flag where a formative construct diverges.</p>
<ol type="1">
<li>
<strong>Construct definition and domain specification.</strong> State precisely what the construct is and is not, its conceptual boundaries, and—critically—the <em>direction of measurement</em> (<a href="#tbl-refl-form" class="quarto-xref">Table&nbsp;<span>31.1</span></a>). This step decides everything downstream and cannot be repaired later by statistics. <!-- CITE-NEEDED: Churchill 1979 paradigm for developing marketing measures -->
</li>
<li>
<strong>Item generation.</strong> Draft a large pool of candidate items spanning the domain, from theory, qualitative interviews, and existing scales. For reflective constructs the pool should oversample each facet (items are replaceable); for formative constructs the pool must <em>exhaust</em> the facets (each is constitutive).</li>
<li>
<strong>Content validity / expert judging.</strong> Have domain experts rate each item’s relevance and representativeness, retaining items with high agreement. This is a qualitative check that no statistic substitutes for.</li>
<li>
<strong>Purification on a calibration sample.</strong> Collect data and trim items. For reflective scales, drop items with low item–total correlations or weak loadings and inspect exploratory factor structure for dimensionality. For formative indices, <em>do not</em> trim on inter-item correlation; trim only on collinearity and weight significance.</li>
<li>
<strong>Confirmatory validation on a fresh sample.</strong> Fit the hypothesized measurement model (confirmatory factor analysis for reflective constructs; a MIMIC model for formative) and assess fit, reliability, and the validity battery of <a href="#sec-reliability-validity" class="quarto-xref"><span>Section 31.4</span></a> below. Cross-validation on data not used for purification guards against capitalizing on chance.</li>
<li>
<strong>Norming and replication.</strong> Establish means, variances, and stability across populations and over time, and demonstrate the nomological network—correlations with antecedents and consequences in the predicted pattern.</li>
</ol>
<p><a href="#fig-scale-dev" class="quarto-xref">Figure&nbsp;<span>31.2</span></a> renders the pipeline. The arrows back from validation to item generation are essential: scale development is iterative, and a construct that fails discriminant validity often needs its <em>definition</em> sharpened, not just its items re-fitted.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-scale-dev" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-scale-dev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-scale-dev">flowchart TB
  A[Define construct\n&amp; measurement direction] --&gt; B[Generate item pool]
  B --&gt; C[Expert content judging]
  C --&gt; D[Purify on\ncalibration sample]
  D --&gt; E[Confirm on\nfresh sample]
  E --&gt; F[Norm &amp; replicate\nnomological network]
  E -. fails discriminant/convergent .-&gt; A
  D -. weak items .-&gt; B
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scale-dev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;31.2: The scale-development pipeline. Conceptual specification fixes the measurement direction; item generation and content judging are qualitative; purification and confirmatory validation are quantitative and run on separate samples. Validation failures feed back to redefinition, not merely re-estimation.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="sec-reliability-validity" class="level2" data-number="31.4"><h2 data-number="31.4" class="anchored" data-anchor-id="sec-reliability-validity">
<span class="header-section-number">31.4</span> Reliability and Validity</h2>
<p>A scale must be both <strong>reliable</strong> (low error variance) and <strong>valid</strong> (measures the intended construct). We give the standard estimators, their assumptions, and what breaks them.</p>
<section id="internal-consistency-reliability" class="level3" data-number="31.4.1"><h3 data-number="31.4.1" class="anchored" data-anchor-id="internal-consistency-reliability">
<span class="header-section-number">31.4.1</span> Internal-Consistency Reliability</h3>
<p><strong>Cronbach’s alpha</strong> estimates reliability from a single administration of <span class="math inline">\(K\)</span> items as</p>
<p><span id="eq-30-alpha"><span class="math display">\[
\alpha \;=\; \frac{K}{K-1}\left(1 - \frac{\sum_{k=1}^{K}\sigma_{x_k}^2}{\sigma_{X_{\text{tot}}}^2}\right),
\tag{31.8}\]</span></span></p>
<p>where <span class="math inline">\(\sigma_{x_k}^2\)</span> is item variance and <span class="math inline">\(\sigma_{X_{\text{tot}}}^2\)</span> the variance of the summed score. Alpha is a <em>lower bound</em> on reliability and equals it only under <strong>tau-equivalence</strong>—all items load equally on the common factor. When loadings differ (the congeneric case), alpha understates reliability, and <strong>composite reliability</strong> (CR), computed from the CFA loadings <span class="math inline">\(\hat\lambda_k\)</span> and error variances <span class="math inline">\(\hat\theta_k\)</span>,</p>
<p><span id="eq-cr"><span class="math display">\[
\mathrm{CR} \;=\; \frac{\left(\sum_{k}\hat\lambda_k\right)^2}{\left(\sum_{k}\hat\lambda_k\right)^2 + \sum_{k}\hat\theta_k},
\tag{31.9}\]</span></span></p>
<p>is preferred because it does not assume equal loadings. Both assume a <em>reflective</em> unidimensional model; <strong>neither is meaningful for a formative index</strong>, where the items are not expected to covary. Conventional thresholds put acceptable internal consistency at roughly <span class="math inline">\(0.70\)</span> and above, though the number is a heuristic, not a law. <!-- CITE-NEEDED: Cronbach 1951 coefficient alpha --></p>
</section><section id="convergent-and-discriminant-validity" class="level3" data-number="31.4.2"><h3 data-number="31.4.2" class="anchored" data-anchor-id="convergent-and-discriminant-validity">
<span class="header-section-number">31.4.2</span> Convergent and Discriminant Validity</h3>
<p><strong>Construct validity</strong> asks whether the scale measures its target construct. <span class="citation" data-cites="fornell1981a">Fornell and Larcker (<a href="#ref-fornell1981a" role="doc-biblioref">1981</a>)</span> give the workhorse criteria for reflective constructs estimated by CFA. <strong>Convergent validity</strong>—indicators of one construct converge—is evidenced when the <strong>average variance extracted</strong> (AVE),</p>
<p><span id="eq-30-ave"><span class="math display">\[
\mathrm{AVE} \;=\; \frac{\sum_{k}\hat\lambda_k^2}{\sum_{k}\hat\lambda_k^2 + \sum_{k}\hat\theta_k},
\tag{31.10}\]</span></span></p>
<p>exceeds <span class="math inline">\(0.50\)</span>, i.e., the construct explains more than half the variance in its indicators. <strong>Discriminant validity</strong>—distinct constructs are empirically distinct—holds, by the Fornell–Larcker criterion, when each construct’s <span class="math inline">\(\sqrt{\mathrm{AVE}}\)</span> exceeds its correlation with every other construct <span class="citation" data-cites="fornell1981a">(<a href="#ref-fornell1981a" role="doc-biblioref">Fornell and Larcker 1981</a>)</span>. A construct that fails discriminant validity against a neighbor is not separately measurable from it, and the usual remedy is conceptual: merge the constructs or sharpen their definitions. These criteria are reflective; for formative constructs, validity is assessed through the nomological net and the significance of formative weights instead.</p>
</section><section id="criterion-and-nomological-validity" class="level3" data-number="31.4.3"><h3 data-number="31.4.3" class="anchored" data-anchor-id="criterion-and-nomological-validity">
<span class="header-section-number">31.4.3</span> Criterion and Nomological Validity</h3>
<p><strong>Criterion validity</strong> is the scale’s correlation with an external criterion it should predict—<em>concurrent</em> when measured contemporaneously, <em>predictive</em> when the criterion is future behavior. <strong>Nomological validity</strong>, the most demanding, asks whether the construct relates to <em>other</em> constructs as theory dictates: a valid brand-equity scale should predict price premium and choice share in the direction <a href="08-branding.html" class="quarto-xref"><span>Chapter 9</span></a> specifies. Validity, unlike reliability, is never established by a single coefficient; it is the accumulated weight of a construct behaving as its theory says it should.</p>
</section><section id="inter-rater-reliability-for-coded-data" class="level3" data-number="31.4.4"><h3 data-number="31.4.4" class="anchored" data-anchor-id="inter-rater-reliability-for-coded-data">
<span class="header-section-number">31.4.4</span> Inter-Rater Reliability for Coded Data</h3>
<p>When measurement comes from human coders rather than respondents—coding ad content, classifying reviews, labeling images—reliability is <em>agreement</em> between raters corrected for chance. <strong>Cohen’s kappa</strong> <span class="citation" data-cites="Cohen_1960">(<a href="#ref-Cohen_1960" role="doc-biblioref">Cohen 1960</a>)</span> for two raters is</p>
<p><span id="eq-30-kappa"><span class="math display">\[
\kappa \;=\; \frac{p_o - p_e}{1 - p_e},
\tag{31.11}\]</span></span></p>
<p>where <span class="math inline">\(p_o\)</span> is observed agreement and <span class="math inline">\(p_e\)</span> is the agreement expected if raters labeled independently at their marginal rates. <span class="math inline">\(\kappa = 1\)</span> is perfect agreement, <span class="math inline">\(\kappa = 0\)</span> is chance-level; conventional benchmarks read <span class="math inline">\(0.41\)</span>–<span class="math inline">\(0.60\)</span> as moderate and above <span class="math inline">\(0.60\)</span> as substantial <span class="citation" data-cites="Landis_1977">(<a href="#ref-Landis_1977" role="doc-biblioref">Landis and Koch 1977</a>)</span>. For continuous ratings, the <strong>intraclass correlation coefficient</strong> (ICC) plays the analogous role, partitioning variance into rater, target, and error components <span class="citation" data-cites="Shrout_1979">(<a href="#ref-Shrout_1979" role="doc-biblioref">Shrout and Fleiss 1979</a>)</span>. The worked example below estimates kappa for a two-coder labeling task.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Two coders label 200 reviews as positive (1) or negative (0).</span></span>
<span><span class="co"># Simulate a shared latent truth plus idiosyncratic coder noise.</span></span>
<span><span class="va">n</span>      <span class="op">&lt;-</span> <span class="fl">200</span></span>
<span><span class="va">truth</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">1</span>, <span class="fl">0.5</span><span class="op">)</span></span>
<span><span class="va">flip_a</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">1</span>, <span class="fl">0.10</span><span class="op">)</span>          <span class="co"># coder A errs 10% of the time</span></span>
<span><span class="va">flip_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">1</span>, <span class="fl">0.12</span><span class="op">)</span>          <span class="co"># coder B errs 12% of the time</span></span>
<span><span class="va">coder_a</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">flip_a</span> <span class="op">==</span> <span class="fl">1</span>, <span class="fl">1</span> <span class="op">-</span> <span class="va">truth</span>, <span class="va">truth</span><span class="op">)</span></span>
<span><span class="va">coder_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">flip_b</span> <span class="op">==</span> <span class="fl">1</span>, <span class="fl">1</span> <span class="op">-</span> <span class="va">truth</span>, <span class="va">truth</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">coder_a</span>, <span class="va">coder_b</span><span class="op">)</span></span>
<span><span class="va">p_o</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span>                       <span class="co"># observed agreement</span></span>
<span><span class="va">p_e</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span>   <span class="co"># chance agreement</span></span>
<span><span class="va">kappa</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">p_o</span> <span class="op">-</span> <span class="va">p_e</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p_e</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Observed agreement p_o:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">p_o</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Observed agreement p_o: 0.805</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Chance agreement   p_e:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">p_e</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Chance agreement   p_e: 0.504</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Cohen's kappa        :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">kappa</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Cohen's kappa        : 0.607</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="a-worked-reflective-measurement-model" class="level3" data-number="31.4.5"><h3 data-number="31.4.5" class="anchored" data-anchor-id="a-worked-reflective-measurement-model">
<span class="header-section-number">31.4.5</span> A Worked Reflective Measurement Model</h3>
<p>To make <a href="#eq-30-reflective" class="quarto-xref">Equation&nbsp;<span>31.5</span></a> through <a href="#eq-30-ave" class="quarto-xref">Equation&nbsp;<span>31.10</span></a> concrete, we simulate a single reflective construct with four congeneric indicators, recover the loadings by factor analysis, and compute composite reliability and AVE from the estimates.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2024</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n</span>       <span class="op">&lt;-</span> <span class="fl">500</span></span>
<span><span class="va">lambda</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.85</span>, <span class="fl">0.80</span>, <span class="fl">0.75</span>, <span class="fl">0.70</span><span class="op">)</span>   <span class="co"># true (heterogeneous) loadings</span></span>
<span><span class="va">theta</span>   <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">lambda</span><span class="op">^</span><span class="fl">2</span>                 <span class="co"># error variances (unit-variance items)</span></span>
<span><span class="va">eta</span>     <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>                     <span class="co"># latent construct, Var = 1</span></span>
<span></span>
<span><span class="co"># Generate indicators under the reflective model x_k = lambda_k * eta + e_k</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">lambda</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">k</span><span class="op">)</span> <span class="va">lambda</span><span class="op">[</span><span class="va">k</span><span class="op">]</span> <span class="op">*</span> <span class="va">eta</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">theta</span><span class="op">[</span><span class="va">k</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"x"</span>, <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">lambda</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Recover a one-factor solution; loadings are the std. correlations with the factor</span></span>
<span><span class="va">fa</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/factanal.html">factanal</a></span><span class="op">(</span><span class="va">X</span>, factors <span class="op">=</span> <span class="fl">1</span>, scores <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span>
<span><span class="va">lhat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">fa</span><span class="op">$</span><span class="va">loadings</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span><span class="op">)</span>     <span class="co"># estimated loadings</span></span>
<span><span class="va">ehat</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">lhat</span><span class="op">^</span><span class="fl">2</span>                       <span class="co"># implied error variances</span></span>
<span></span>
<span><span class="va">CR</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">lhat</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">lhat</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">ehat</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">AVE</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">lhat</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">lhat</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">ehat</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Cronbach's alpha from the item covariance matrix</span></span>
<span><span class="va">S</span>       <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cov</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span></span>
<span><span class="va">K</span>       <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span></span>
<span><span class="va">alpha</span>   <span class="op">&lt;-</span> <span class="op">(</span><span class="va">K</span> <span class="op">/</span> <span class="op">(</span><span class="va">K</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">S</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">S</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Estimated loadings:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">lhat</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Estimated loadings: 0.85 0.831 0.71 0.72</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Cronbach's alpha  :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">alpha</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Cronbach's alpha  : 0.859</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Composite reliab. :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">CR</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Composite reliab. : 0.861</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"AVE               :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">AVE</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"(&gt; 0.50 =&gt; convergent)\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; AVE               : 0.609 (&gt; 0.50 =&gt; convergent)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Because the loadings are heterogeneous, alpha will sit <em>below</em> composite reliability in this example—the tau-equivalence gap of <a href="#eq-30-alpha" class="quarto-xref">Equation&nbsp;<span>31.8</span></a> made visible. AVE above <span class="math inline">\(0.50\)</span> confirms convergent validity for the simulated construct.</p>
</section></section><section id="common-method-bias" class="level2" data-number="31.5"><h2 data-number="31.5" class="anchored" data-anchor-id="common-method-bias">
<span class="header-section-number">31.5</span> Common-Method Bias</h2>
<p>A pervasive threat to survey-based measurement is <strong>common-method variance</strong> (CMV): variance attributable to the <em>measurement method</em> rather than the constructs the measures represent. When the same respondent rates both an independent and a dependent variable, on the same scale, at the same sitting, shared method factors—consistency motifs, social desirability, acquiescence, common scale anchors, transient mood—inject a spurious component into every item. The bias, <strong>common-method bias</strong> (CMB), is the distortion this induces in observed relationships, and it can inflate <em>or</em> deflate correlations <span class="citation" data-cites="mackenzie1986">(<a href="#ref-mackenzie1986" role="doc-biblioref">MacKenzie, Lutz, and Belch 1986</a>)</span>.</p>
<section id="a-formal-model-of-the-bias" class="level3" data-number="31.5.1"><h3 data-number="31.5.1" class="anchored" data-anchor-id="a-formal-model-of-the-bias">
<span class="header-section-number">31.5.1</span> A Formal Model of the Bias</h3>
<p>Augment the reflective model <a href="#eq-30-reflective" class="quarto-xref">Equation&nbsp;<span>31.5</span></a> with a method factor <span class="math inline">\(M\)</span> common to all items measured by the shared method:</p>
<p><span id="eq-method-factor"><span class="math display">\[
x_k \;=\; \lambda_k\, \eta \;+\; \omega_k\, M \;+\; \varepsilon_k,
\tag{31.12}\]</span></span></p>
<p>with <span class="math inline">\(M \perp \eta\)</span>, <span class="math inline">\(M \perp \varepsilon_k\)</span>, and method loadings <span class="math inline">\(\omega_k\)</span>. Two items measuring <em>different</em> substantive constructs <span class="math inline">\(\eta\)</span> and <span class="math inline">\(\eta'\)</span> now share the method factor, so their observed covariance picks up a method term that has nothing to do with their true relationship:</p>
<p><span id="eq-cmb-bias"><span class="math display">\[
\mathrm{Cov}(x_j, y_l) \;=\; \underbrace{\lambda_j \lambda_l\,\mathrm{Cov}(\eta,\eta')}_{\text{substantive}}
\;+\; \underbrace{\omega_j \omega_l\,\sigma_M^2}_{\text{method bias}} .
\tag{31.13}\]</span></span></p>
<p>When predictor and outcome share the method, the second term is added to <em>every</em> cross-construct covariance, biasing structural estimates—usually upward, because method loadings of the same sign inflate correlations, though differential signs can deflate. The contaminant is most dangerous in single-source, single-instrument designs: exactly the cross-sectional self-report survey that dominates applied marketing.</p>
</section><section id="procedural-and-statistical-remedies" class="level3" data-number="31.5.2"><h3 data-number="31.5.2" class="anchored" data-anchor-id="procedural-and-statistical-remedies">
<span class="header-section-number">31.5.2</span> Procedural and Statistical Remedies</h3>
<p>Defenses fall into two families. <strong>Procedural</strong> remedies design the bias out before data collection: obtain predictor and outcome measures from <em>different sources</em> (e.g., attitudes from the consumer, behavior from the firm’s records) or at different times; separate the measurement of constructs psychologically or temporally; counterbalance item order; protect respondent anonymity to blunt social desirability; and write items to reduce ambiguity and common scale anchoring. Separating the source of the predictor from the source of the outcome severs the <span class="math inline">\(M\)</span> that links them in <a href="#eq-cmb-bias" class="quarto-xref">Equation&nbsp;<span>31.13</span></a> and is the single most effective remedy. <!-- CITE-NEEDED: Podsakoff, MacKenzie, Lee & Podsakoff 2003 common method biases --></p>
<p><strong>Statistical</strong> remedies detect or partial out the method factor after the fact, and none is a substitute for good design. Harman’s single-factor test—loading all items on one unrotated factor and checking that it explains less than half the variance—is widely reported but weak, detecting only gross contamination. Stronger is to estimate <a href="#eq-method-factor" class="quarto-xref">Equation&nbsp;<span>31.12</span></a> directly: include an unmeasured <strong>latent method factor</strong> in the CFA, let all indicators load on it alongside their substantive constructs, and compare structural estimates with and without it. A <strong>marker-variable</strong> approach uses a theoretically unrelated marker construct as a proxy for <span class="math inline">\(M\)</span> and partials its correlation out of the substantive correlations. The diagnostic below implements the marker-variable logic on simulated data containing a known method component.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">7</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n</span>   <span class="op">&lt;-</span> <span class="fl">800</span></span>
<span><span class="va">eta1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>; <span class="va">eta2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>            <span class="co"># two substantive constructs</span></span>
<span><span class="va">M</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>                               <span class="co"># shared method factor</span></span>
<span></span>
<span><span class="co"># Substantive correlation between constructs is set to ZERO here:</span></span>
<span><span class="co"># any observed X-Y correlation is pure method bias.</span></span>
<span><span class="va">w</span> <span class="op">&lt;-</span> <span class="fl">0.5</span>                                        <span class="co"># common method loading</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fl">0.8</span> <span class="op">*</span> <span class="va">eta1</span> <span class="op">+</span> <span class="va">w</span> <span class="op">*</span> <span class="va">M</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, sd <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span>    <span class="co"># predictor (one item)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fl">0.8</span> <span class="op">*</span> <span class="va">eta2</span> <span class="op">+</span> <span class="va">w</span> <span class="op">*</span> <span class="va">M</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, sd <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span>    <span class="co"># outcome   (one item)</span></span>
<span><span class="va">marker</span> <span class="op">&lt;-</span> <span class="fl">0.0</span> <span class="op">*</span> <span class="va">eta1</span> <span class="op">+</span> <span class="va">w</span> <span class="op">*</span> <span class="va">M</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, sd <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span>  <span class="co"># theoretically unrelated marker</span></span>
<span></span>
<span><span class="va">raw_xy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Marker-variable correction: subtract the method-induced correlation,</span></span>
<span><span class="co"># proxied by the smallest observed correlation with the marker.</span></span>
<span><span class="va">r_xm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">marker</span><span class="op">)</span>; <span class="va">r_ym</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">marker</span><span class="op">)</span></span>
<span><span class="va">r_m</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">r_xm</span>, <span class="va">r_ym</span><span class="op">)</span>                         <span class="co"># conservative marker correlation</span></span>
<span><span class="va">adj_xy</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">raw_xy</span> <span class="op">-</span> <span class="va">r_m</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">r_m</span><span class="op">)</span>            <span class="co"># partial out shared method</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Raw X-Y correlation (contaminated):"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">raw_xy</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Raw X-Y correlation (contaminated): 0.312</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Marker correlation used           :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">r_m</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Marker correlation used           : 0.417</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Method-adjusted X-Y correlation   :"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">adj_xy</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Method-adjusted X-Y correlation   : -0.181</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"True substantive correlation      : 0.000\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; True substantive correlation      : 0.000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The raw correlation is spuriously positive—pure method bias, since the substantive correlation was set to zero—and the marker adjustment pulls the estimate back toward the truth. The lesson is the one <a href="#eq-cmb-bias" class="quarto-xref">Equation&nbsp;<span>31.13</span></a> formalizes: when a relationship is estimated from a single self-report instrument, part of it may be the instrument talking to itself, and the credible defense is procedural separation of sources, with statistical partialling as a fallback.</p>
</section></section><section id="key-takeaways" class="level2" data-number="31.6"><h2 data-number="31.6" class="anchored" data-anchor-id="key-takeaways">
<span class="header-section-number">31.6</span> Key Takeaways</h2>
<ul>
<li>Measurement is a <em>modeling</em> problem. Under true-score theory (<a href="#eq-truescore" class="quarto-xref">Equation&nbsp;<span>31.1</span></a>), reliability is a variance ratio (<a href="#eq-30-reliability" class="quarto-xref">Equation&nbsp;<span>31.3</span></a>), and unreliability <em>attenuates</em> every estimated relationship (<a href="#eq-30-attenuation" class="quarto-xref">Equation&nbsp;<span>31.4</span></a>).</li>
<li>The reflective–formative distinction is a claim about the <strong>direction of causality</strong> between construct and indicators (<a href="#eq-30-reflective" class="quarto-xref">Equation&nbsp;<span>31.5</span></a> vs. <a href="#eq-30-formative" class="quarto-xref">Equation&nbsp;<span>31.6</span></a>) and dictates the entire validity battery; it must be decided conceptually, <em>before</em> data collection (<a href="#tbl-refl-form" class="quarto-xref">Table&nbsp;<span>31.1</span></a>).</li>
<li>A pure formative model is <strong>not identified</strong>; it needs external structure, most commonly the <strong>MIMIC</strong> specification (<a href="#eq-mimic" class="quarto-xref">Equation&nbsp;<span>31.7</span></a>), to fix its metric and disturbance.</li>
<li>Internal-consistency reliability (alpha, CR, AVE) and the Fornell–Larcker discriminant-validity criterion apply to <strong>reflective</strong> constructs only; formative indices are judged by weights and collinearity.</li>
<li>
<strong>Common-method bias</strong> arises when one instrument supplies both predictor and outcome (<a href="#eq-cmb-bias" class="quarto-xref">Equation&nbsp;<span>31.13</span></a>); the strongest remedy is procedural—separate the sources—not a post-hoc statistical patch.</li>
</ul></section><section id="further-reading" class="level2" data-number="31.7"><h2 data-number="31.7" class="anchored" data-anchor-id="further-reading">
<span class="header-section-number">31.7</span> Further Reading</h2>
<p>The two standard compendia of validated marketing instruments are the <em>Handbook of Marketing Scales</em> <span class="citation" data-cites="bearden2011">(<a href="#ref-bearden2011" role="doc-biblioref">Bearden, Netemeyer, and Haws 2011</a>)</span> and the <em>Marketing Scales Handbook</em> <span class="citation" data-cites="stewart1993">(<a href="#ref-stewart1993" role="doc-biblioref">Stewart et al. 1993</a>)</span>; both organize scales by construct with reliability and validity evidence. For the reflective–formative debate, <span class="citation" data-cites="coltman2008">Coltman et al. (<a href="#ref-coltman2008" role="doc-biblioref">2008</a>)</span> and <span class="citation" data-cites="diamantopoulos2013quantitative">Diamantopoulos, Fritz, and Hildebrandt (<a href="#ref-diamantopoulos2013quantitative" role="doc-biblioref">2013</a>)</span> give the theoretical and operational decision rules, and <span class="citation" data-cites="edwards2010">Edwards (<a href="#ref-edwards2010" role="doc-biblioref">2010</a>)</span> examines the construct-validity consequences of the choice. <span class="citation" data-cites="fornell1981a">Fornell and Larcker (<a href="#ref-fornell1981a" role="doc-biblioref">1981</a>)</span> remains the reference for convergent and discriminant validity with unobservable variables, and <span class="citation" data-cites="mackenzie1986">MacKenzie, Lutz, and Belch (<a href="#ref-mackenzie1986" role="doc-biblioref">1986</a>)</span> for method effects in marketing measurement. The branding constructs whose measurement models are actively contested—brand love <span class="citation" data-cites="batra2012 bagozzi2016">(<a href="#ref-batra2012" role="doc-biblioref">Batra, Ahuvia, and Bagozzi 2012</a>; <a href="#ref-bagozzi2016" role="doc-biblioref">Bagozzi, Batra, and Ahuvia 2016</a>)</span> and authenticity <span class="citation" data-cites="morhart2015 nunes2021">(<a href="#ref-morhart2015" role="doc-biblioref">Morhart et al. 2015</a>; <a href="#ref-nunes2021" role="doc-biblioref">Nunes, Ordanini, and Giambastiani 2021</a>)</span>—are treated substantively in <a href="08-branding.html" class="quarto-xref"><span>Chapter 9</span></a>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-bagozzi2016" class="csl-entry" role="listitem">
Bagozzi, Richard P., Rajeev Batra, and Aaron Ahuvia. 2016. <span>“Brand Love: Development and Validation of a Practical Scale.”</span> <em>Marketing Letters</em> 28 (1): 1–14. <a href="https://doi.org/10.1007/s11002-016-9406-1">https://doi.org/10.1007/s11002-016-9406-1</a>.
</div>
<div id="ref-batra2012" class="csl-entry" role="listitem">
Batra, Rajeev, Aaron Ahuvia, and Richard P. Bagozzi. 2012. <span>“Brand Love.”</span> <em>Journal of Marketing</em> 76 (2): 1–16. <a href="https://doi.org/10.1509/jm.09.0339">https://doi.org/10.1509/jm.09.0339</a>.
</div>
<div id="ref-bearden2011" class="csl-entry" role="listitem">
Bearden, William, Richard Netemeyer, and Kelly Haws. 2011. <span>“Handbook of Marketing Scales: Multi-Item Measures for Marketing and Consumer Behavior Research.”</span> <a href="https://doi.org/10.4135/9781412996761">https://doi.org/10.4135/9781412996761</a>.
</div>
<div id="ref-Cohen_1960" class="csl-entry" role="listitem">
Cohen, Jacob. 1960. <span>“A Coefficient of Agreement for Nominal Scales.”</span> <em>Educational and Psychological Measurement</em> 20 (1): 37–46. <a href="https://doi.org/10.1177/001316446002000104">https://doi.org/10.1177/001316446002000104</a>.
</div>
<div id="ref-coltman2008" class="csl-entry" role="listitem">
Coltman, Tim, Timothy M. Devinney, David F. Midgley, and Sunil Venaik. 2008. <span>“Formative Versus Reflective Measurement Models: Two Applications of Formative Measurement.”</span> <em>Journal of Business Research</em> 61 (12): 1250–62. <a href="https://doi.org/10.1016/j.jbusres.2008.01.013">https://doi.org/10.1016/j.jbusres.2008.01.013</a>.
</div>
<div id="ref-diamantopoulos2013quantitative" class="csl-entry" role="listitem">
Diamantopoulos, Adamantios, Wolfgang Fritz, and Lutz Hildebrandt. 2013. <em>Quantitative Marketing and Marketing Management: Marketing Models and Methods in Theory and Practice</em>. Springer.
</div>
<div id="ref-edwards2010" class="csl-entry" role="listitem">
Edwards, Jeffrey R. 2010. <span>“The Fallacy of Formative Measurement.”</span> <em>Organizational Research Methods</em> 14 (2): 370–88. <a href="https://doi.org/10.1177/1094428110378369">https://doi.org/10.1177/1094428110378369</a>.
</div>
<div id="ref-fornell1981a" class="csl-entry" role="listitem">
Fornell, Claes, and David F. Larcker. 1981. <span>“Structural Equation Models with Unobservable Variables and Measurement Error: Algebra and Statistics.”</span> <em>Journal of Marketing Research</em> 18 (3): 382. <a href="https://doi.org/10.2307/3150980">https://doi.org/10.2307/3150980</a>.
</div>
<div id="ref-Landis_1977" class="csl-entry" role="listitem">
Landis, J. Richard, and Gary G. Koch. 1977. <span>“The Measurement of Observer Agreement for Categorical Data.”</span> <em>Biometrics</em> 33 (1): 159. <a href="https://doi.org/10.2307/2529310">https://doi.org/10.2307/2529310</a>.
</div>
<div id="ref-mackenzie1986" class="csl-entry" role="listitem">
MacKenzie, Scott B., Richard J. Lutz, and George E. Belch. 1986. <span>“The Role of Attitude Toward the Ad as a Mediator of Advertising Effectiveness: A Test of Competing Explanations.”</span> <em>Journal of Marketing Research</em> 23 (2): 130. <a href="https://doi.org/10.2307/3151660">https://doi.org/10.2307/3151660</a>.
</div>
<div id="ref-morhart2015" class="csl-entry" role="listitem">
Morhart, Felicitas, Lucia Malär, Amélie Guèvremont, Florent Girardin, and Bianca Grohmann. 2015. <span>“Brand Authenticity: An Integrative Framework and Measurement Scale.”</span> <em>Journal of Consumer Psychology</em> 25 (2): 200–218. <a href="https://doi.org/10.1016/j.jcps.2014.11.006">https://doi.org/10.1016/j.jcps.2014.11.006</a>.
</div>
<div id="ref-nunes2021" class="csl-entry" role="listitem">
Nunes, Joseph C., Andrea Ordanini, and Gaia Giambastiani. 2021. <span>“The Concept of Authenticity: What It Means to Consumers.”</span> <em>Journal of Marketing</em> 85 (4): 1–20. <a href="https://doi.org/10.1177/0022242921997081">https://doi.org/10.1177/0022242921997081</a>.
</div>
<div id="ref-Shrout_1979" class="csl-entry" role="listitem">
Shrout, Patrick E., and Joseph L. Fleiss. 1979. <span>“Intraclass Correlations: Uses in Assessing Rater Reliability.”</span> <em>Psychological Bulletin</em> 86 (2): 420–28. <a href="https://doi.org/10.1037/0033-2909.86.2.420">https://doi.org/10.1037/0033-2909.86.2.420</a>.
</div>
<div id="ref-stewart1993" class="csl-entry" role="listitem">
Stewart, David W., William O. Bearden, Richard G. Netemeyer, Mary F. Mobley, Gordon C. Bruner, and Paul J. Hensel. 1993. <span>“Handbook of Marketing Scales, Multi-Item Measures for Marketing and Consumer Behavior Research.”</span> <em>Journal of Marketing Research</em> 30 (4): 525. <a href="https://doi.org/10.2307/3172696">https://doi.org/10.2307/3172696</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The Spearman–Brown prophecy formula gives the reliability of a test lengthened by a factor <span class="math inline">\(k\)</span> as <span class="math inline">\(\rho_k = k\rho_1 / [1 + (k-1)\rho_1]\)</span>, where <span class="math inline">\(\rho_1\)</span> is the reliability of the original test. It assumes the added items are <em>parallel</em>—equal true-score loadings and equal error variances—an assumption formative indicators violate by construction. <!-- CITE-NEEDED: Spearman 1910 / Brown 1910 prophecy formula --><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./29-structural-models.html" class="pagination-link" aria-label="Structural Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Structural Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./31-surveys.html" class="pagination-link" aria-label="Surveys and Experiments">
        <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Surveys and Experiments</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/mikenguyen13/marketing_research/edit/main/30-measurement-scales.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/mikenguyen13/marketing_research/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>