# Empirical IO

Primitives for analysis

1.  A demand system
2.  A cost system
3.  An equilibrium assumption

Books:

1.  Tirole (1988) general reference textbook
2.  Train (2009) discrete choice models
3.  Rossi, Allenby and McCulloch (2003) Bayesian
4.  Heiss and Winschel (2008): integrating likelihood, sparse grids.

Demand System Estimation

1.  Discrete choice models
2.  IV models of product differentiation

Single Agent Dynamics

1.  Nested Fixed point
2.  Conditional Choice Probability model

Applications

1.  Merger Analysis
2.  Vertical contracting and integration
3.  Housing markets
4.  Market Design

Practical tips

1.  When you write your model, think:
    1.  Are the parameters identified? Is the identification coming the from th variation in the data, or from the assumptions of your model
2.  Always have a reduced-form evidence (e.g., data patterns, or causal effects) that back your model assumptions
3.  Once you have a model, dont dive into data directly
    1.  Do Monte Carlo Simulations
        1.  Build example of randomly generated data
        2.  Do estimation with them, see if the code can recover "true" parameter
