# Retailing

## Shipping

[@guo2023express] Membership-based free shipping (MFS)

-   MFS doesn't increase average consumer spending at enrollment due to smaller order sizes

-   Retailers don't gain extra revenue due to increased shipping costs

-   Free shipping may build a switching barrier, leading to increased spending and revenue over time

-   MFS increases purchase variety and impulse buys, resulting in higher net revenue for light buyers and variety seekers

-   Heavy buyers contribute less revenue under MFS

-   MFS reduces customer churn and strengthens retailer-consumer relationships

## Subscription

[@iyengar2022impact] Subscription program

-   Subscription impact is economically significant, persistent, and varies among customers

-   Only 1/3 of the effect on purchases is due to economic benefits

-   The remaining 2/3 is attributed to the noneconomic effect, such as sunk cost fallacy

-   Upfront payment of subscription programs leads to sunk cost fallacy

-   Firms can calculate the profitability of subscription programs
