{
  "hash": "b3054ee13b44a6d8643484c4715973a2",
  "result": {
    "engine": "knitr",
    "markdown": "# Industrial Organization {#sec-industrial-organization}\n\nIndustrial organization (IO) studies how firms behave in markets, how that behavior\nmaps into prices, product variety, and welfare, and how researchers can recover the\ndeep parameters—preferences, costs, conduct—that generate observed market outcomes.\nFor marketing, IO is the structural backbone: it supplies the demand systems that\nprice a product line, the equilibrium concepts that turn one firm's pricing problem\ninto an industry forecast, and the identification arguments that let an analyst run\n*counterfactuals*—what would happen to prices, shares, and surplus if two firms\nmerged, if a new product entered, or if a regulator capped a fee. Where reduced-form\nmarketing analytics describe correlations, structural IO builds an economic model\nwhose estimated primitives remain invariant under the policy change being studied,\nso that the model can be re-solved under the new regime.\n\nThis chapter develops the toolkit in the order a modeler actually uses it. It opens\nwith the methodological frame: the core questions of IO, the modeling tools\n(demand, constrained profit maximization, game theory, comparative statics), and the\ndiscipline of turning a question into a solvable model. It then builds **consumer\ndemand** from two directions. The *classical* approach treats a representative\nconsumer choosing continuous quantities, yielding the elegant Slutsky/Roy machinery,\nthe CES and quasi-linear special cases, diversion ratios, and the homothetic-surplus\nfamily that makes multiproduct pricing tractable. The *discrete-choice* approach\ntreats heterogeneous consumers each picking one option from a menu, which is how\nmodern empirical IO and quantitative marketing estimate demand for differentiated\nproducts. We give each model its formal definition, its estimator, its identifying\nassumptions, and the failures that break identification—price endogeneity,\nzero-valued shares, selection on unobservables—and we close with the frontier\napplications in marketing: dynamic pricing of new products, behavioral price\ndiscrimination in channels, email contact policy, and multi-sided platforms. Code is\nrunnable and seeded throughout. The companion structural-econometrics machinery\nappears in @sec-marketing-finance and in the demand-estimation discussions elsewhere\nin the book; here the emphasis is on the economic models themselves.\n\n## The IO Research Program\n\nThree questions organize the field. First, **why do firms behave as we observe**—why\nthis price, this product line, this bundle, this contract? Second, **what are the\neffects** of that behavior on consumers, rivals, and employees, and against which\nwelfare standard should those effects be judged? Third, **how can we design better\nstrategy** for firms and better policy for regulators? The first question is\npositive, the second normative, and the third prescriptive; a complete IO study\nusually touches all three, because a counterfactual that improves firm profit and one\nthat improves consumer surplus are different optimizations over the same estimated\nmodel.\n\nThree methodological approaches answer these questions and are complementary rather\nthan competing. The **theoretical** approach builds a model and derives predictions;\nthe **empirical** approach estimates the model from data, tests its predictions, and\nruns counterfactual and welfare analysis; the **experimental and behavioral**\napproach manipulates conditions to isolate causal mechanisms and to discipline the\nbehavioral assumptions the other two impose. The structural empirical tradition that\ndominates this chapter fuses the first two: it writes down a theoretical model of\ndemand and conduct, then estimates its primitives so the model can be re-solved under\nhypothetical policies.\n\n### Building an IO Model\n\nA study begins with an *idea*—a question drawn from the literature in IO and adjacent\nfields, or from the world (a news item, a consulting engagement, an unexplained\npattern in data). The idea is then expressed through a small set of **modeling\ntools** that recur across nearly every IO paper, summarized in @fig-io-workflow.\n\n```{mermaid}\n%%| label: fig-io-workflow\n%%| fig-cap: \"The structural IO modeling workflow, from question to welfare statement. Each stage constrains the next: the demand system feeds the firm's first-order conditions, which define equilibrium, whose comparative statics answer the counterfactual.\"\nflowchart TD\n    A[Idea / Question<br/>literature or world] --> B[Model consumer demand]\n    B --> C[Profit maximization<br/>subject to constraints]\n    C --> D[Game-theoretic equilibrium<br/>among firms]\n    D --> E[Comparative statics<br/>& counterfactuals]\n    E --> F[Welfare & policy<br/>evaluation]\n    F -.->|do results make<br/>intuitive sense?| B\n```\n\nThe first tool is a **model of consumer demand** for the products or services in\nquestion. The modeler decides whether consumers choose among single or multiple\nproducts, single or multiple units, and whether products are differentiated—and if\nso, whether they are substitutes or complements, and whether differentiation is\n*vertical* (everyone agrees more is better, as with quality) or *horizontal*\n(consumers disagree about the ideal variety, as with location or flavor). Demand\n*complementarities* deserve special attention because they reshape strategy: when\nproducts are complements, raising one price depresses demand for both, so a\nmonopolist who internalizes the cross-effect charges *lower* prices than two\nindependent firms would, and the complementarity can itself become a barrier to\nentry. Network effects, multi-sided markets, and ecosystems are demand\ncomplementarities operating across consumers or across platform sides rather than\nwithin a single basket.\n\nThe second tool is **profit maximization subject to constraints**. The modeler\nspecifies choice variables and an objective, then layers on the constraints that make\nthe problem economically interesting: technology constraints from the cost side;\nconsumer *participation* constraints (the consumer must prefer buying to not buying),\nwhich rationalize bundling and tied selling and let contracts act as entry barriers;\n*arbitrage* constraints that limit price discrimination across consumers who can\nresell; and *incentive* constraints in principal–agent settings, which generate\nsecond-degree price discrimination (self-selection across a menu) and franchise\ncontracts. The third tool is **game theory**, treated next. The fourth is\n**comparative static analysis**: with exogenous parameters and policy variables on one\nside and endogenous equilibrium variables on the other, the modeler asks how the\noptimum or equilibrium shifts as a parameter moves—the formal content of every\n\"what if\" the study can answer.\n\n### Game-Theoretic Models\n\nStrategic interaction among firms is modeled non-cooperatively or cooperatively.\n**Non-cooperative** models come in two forms. *Normal-form* (simultaneous-move) games\nspecify a set of players, a strategy set for each, and a payoff function for each, and\nsolve for Nash equilibrium in whatever strategic variable is relevant—price\n(Bertrand), quantity (Cournot), capacity, advertising, or location. *Extensive-form*\n(sequential-move) games capture first-mover advantages, entry deterrence, and\ncollusion sustained through repeated interaction, where the threat of future\npunishment supports prices above the static equilibrium. **Cooperative** models, used\nheavily in channel and platform settings, center on **Nash bargaining**: two parties\nsplit the gains from agreement according to their bargaining power, relative to a\n*threat point* (the disagreement payoff). The **Nash-in-Nash** refinement embeds\nbilateral Nash bargains inside a larger non-cooperative game—each upstream–downstream\npair bargains taking all other negotiated prices as given—and has become the workhorse\nfor modeling negotiated wholesale prices in vertical markets.\n\n> A profile of strategies is a **Nash equilibrium** if no player can raise its own\n> payoff by unilaterally deviating, holding all rivals' strategies fixed. In a pricing\n> game this means each firm's price is a best response to its rivals' prices, so the\n> equilibrium price vector solves all firms' first-order conditions simultaneously.\n\nThe output of this machinery is a set of results, after which—per the discipline of\nthe field—the modeler pauses to ask whether the results make intuitive sense before\ntrusting them. A written IO study then motivates the question (with examples,\nstatistics, prior work, and policy stakes), states the approach and headline\nfindings, constructs the model, derives the equilibrium and its comparative statics,\nand closes with limitations and extensions.\n\n## Consumer Demand {#sec-io-demand}\n\nThe central modeling primitive is a **demand system**: a description of how the\nquantities consumers buy respond to firms' offers—prices, qualities, versions,\nadvertising, warranties. Three questions drive the demand modeler. How should demand\nbe formally specified given the product and the market? What properties must a demand\n*system* (more than one product) satisfy to be internally consistent? And how can the\nsystem be estimated so that own-price elasticities, cross-price elasticities, and\ndiversion ratios can be computed and fed into a pricing or merger analysis?\n\nDemand is fundamentally a **matching process** between a population of consumers—each\nwith observable and unobservable characteristics—and a set of products with their own\nobservable and unobservable characteristics. The microeconomics and IO literatures\noffer three routes through this matching problem: *classical consumer theory* with\ncontinuous choices; *discrete-choice models* with heterogeneous tastes, which\naccommodate horizontal differentiation, vertical differentiation, or both; and *hybrid\ndiscrete–continuous* models in which the consumer first chooses which product and then\nhow much. The next two parts develop the classical and discrete-choice routes in\nturn.\n\n## Classical Consumer Demand {#sec-io-classical}\n\nA representative consumer with utility $U(q_0, q_1, \\dots, q_n)$ and income $I$, facing\nprices $\\mathbf{p} = (p_1, \\dots, p_n)$, chooses continuous quantities\n$\\mathbf{q} = (q_1, \\dots, q_n)$ to solve\n\n$$\n\\max_{q_0, \\dots, q_n} \\; U(q_0, q_1, \\dots, q_n)\n\\quad \\text{s.t.} \\quad q_0 + \\sum_{i=1}^n p_i q_i \\le I,\n$$ {#eq-um-classical}\n\nwhere $q_0$ is a numeraire good with normalized price $p_0 = 1$. The solution is the\n**Walrasian** (or Marshallian) demand system $q_i = D_i(\\mathbf{p}, I)$, and\nsubstituting it back into $U$ gives the **indirect utility** $V(\\mathbf{p}, I)$.\n\nThis system is not an arbitrary set of functions; it inherits a rigid structure from\noptimization, and that structure is what makes the classical approach powerful. Two\nidentities encode it. **Roy's identity** recovers demand from the indirect utility,\n\n$$\nq_i(\\mathbf{p}, I) = -\\,\\frac{\\partial V / \\partial p_i}{\\partial V / \\partial I},\n$$ {#eq-roy}\n\nso the entire demand system is implicit in a single scalar function $V$. The **Slutsky\nequation** decomposes the response of demand to a price change into a substitution\neffect (the compensated, or Hicksian, derivative $\\partial h_i / \\partial p_j$) and an\nincome effect,\n\n$$\n\\frac{\\partial h_i(\\mathbf{p}, u)}{\\partial p_j}\n= \\frac{\\partial q_i(\\mathbf{p}, I)}{\\partial p_j}\n+ \\frac{\\partial q_i(\\mathbf{p}, I)}{\\partial I}\\, q_j(\\mathbf{p}, I).\n$$ {#eq-slutsky}\n\nThe matrix of compensated derivatives—the **Slutsky substitution matrix**—is symmetric\nand negative semi-definite. Symmetry is the testable fingerprint of utility\nmaximization: absent income effects, the cross-price response of good $i$ to $p_j$\nequals that of good $j$ to $p_i$. Negative semi-definiteness encodes the law of\ndemand, that compensated own-price effects are non-positive.\n\n### CES Sub-Utility and the Taste for Variety\n\nA leading special case separates the numeraire from a bundle of differentiated goods,\n$U = U(q_0, Q)$, with the differentiated goods aggregated by a **constant elasticity\nof substitution** (CES) sub-utility. Taking $U = q_0 Q$ with\n\n$$\nQ = \\Big( \\sum_{i=1}^n q_i^{\\rho} \\Big)^{1/\\rho}, \\qquad \\rho \\le 1,\n$$ {#eq-ces-Q}\n\ndelivers the CES demand system. The parameter $\\rho$ controls substitutability: the\nelasticity of substitution is $1/(1-\\rho)$, so $\\rho \\in (0,1)$ makes the goods\nimperfect substitutes (elasticity above one), $\\rho \\to 1$ makes them perfect\nsubstitutes, and $\\rho \\to 0$ approaches Cobb–Douglas. The CES form is the standard\ntool for studying product *variety*, because the consumer values having many distinct\nvarieties even at equal total quantity—the \"love of variety\" that justifies entry of\ndifferentiated competitors.\n\nTo derive demand, write the consumer problem over $n+1$ goods with the multiplicative\nspecification\n\n$$\nU = q_0 \\Big[ \\sum_{i=1}^n q_i^{\\rho} \\Big]^{1/\\rho}, \\qquad \\rho \\in (0,1),\n$$\n\nsubject to the budget $P_0 q_0 + \\sum_{i=1}^n P_i q_i = M$. The Lagrangian is\n\n$$\n\\mathcal{L} = q_0 \\Big[ \\sum_{i=1}^n q_i^{\\rho} \\Big]^{1/\\rho}\n+ \\lambda \\Big( M - P_0 q_0 - \\sum_{i=1}^n P_i q_i \\Big).\n$$\n\nThe first-order condition for the numeraire,\n$\\partial \\mathcal{L}/\\partial q_0 = \\big[\\sum_i q_i^{\\rho}\\big]^{1/\\rho} - P_0\\lambda = 0$,\nidentifies the marginal utility of income with the aggregate $Q$ scaled by price,\n$\\big[\\sum_i q_i^{\\rho}\\big]^{1/\\rho} = P_0 \\lambda$. The condition for a\ndifferentiated good,\n\n$$\n\\frac{\\partial \\mathcal{L}}{\\partial q_i}\n= q_0 \\Big[ \\sum_{i=1}^n q_i^{\\rho} \\Big]^{1/\\rho - 1} q_i^{\\rho - 1} - P_i \\lambda = 0,\n$$\n\ngives $q_0 \\big[\\sum_i q_i^{\\rho}\\big]^{1/\\rho - 1} q_i^{\\rho-1} = P_i \\lambda$.\nDividing the two conditions eliminates $\\lambda$ and yields the *direct* CES demand;\nsolving instead for $P_i$ yields the *inverse* demand. The economic reading is the one\nabove: with $\\rho \\in (0,1)$ the varieties are imperfect substitutes.\n\n### Quasi-Linear Utility and the Absence of Income Effects\n\nA second special class drops income effects entirely. With **quasi-linear** utility,\n\n$$\nU = q_0 + u(q_1, \\dots, q_n),\n$$ {#eq-quasilinear}\n\nsubstituting the budget constraint turns the consumer problem into\n\n$$\n\\max_{q_1, \\dots, q_n} \\; u(q_1, \\dots, q_n) - \\sum_{i=1}^n p_i q_i + I,\n$$\n\nwith first-order conditions $\\partial u / \\partial q_i = p_i$. Because $I$ enters\nadditively, the demands for the $n$ differentiated goods are **independent of income**\n(provided income is large enough that $q_0 > 0$). All income is absorbed by the\nnumeraire, and the maximized utility is $V = v(p_1, \\dots, p_n) + I$, where\n$v(\\cdot)$ is the consumer-surplus function. This additive separability is what makes\nquasi-linear utility the default for welfare analysis in IO: changes in consumer\nsurplus are read directly off $v$, untangled from income.\n\nThe structure delivers three results used repeatedly below. First, demand is the\nnegative gradient of surplus, $-\\partial v / \\partial p_i = q_i(\\mathbf{p})$, a special\ncase of Roy's identity (@eq-roy). Second, the **Jacobian** of the demand system,\n$J = \\big( \\partial q_i(\\mathbf{p}) / \\partial p_j \\big)_{n \\times n}$, is symmetric and\nnegative semi-definite—the Slutsky matrix (@eq-slutsky) stripped of income terms.\nThird, the construction can be **reverse-engineered**: if an observed demand system\nhas a symmetric, negative-definite Jacobian, it is rationalizable by a representative\nconsumer maximizing a concave quasi-linear utility, recovered by substituting the\ninverse demand into the first-order conditions and integrating the resulting system of\npartial differential equations $\\partial u / \\partial q_i = p_i(q)$. Recovering $u$ in\nturn enables exact welfare statements.\n\n#### Substitutes, Complements, and Diversion {#sec-io-diversion}\n\nWith $n = 2$, the sign of the cross-effect classifies the goods. They are\n**demand-substitutes** if good $j$'s demand rises with $p_i$ and **demand-complements**\nif it falls. Applying Cramer's rule to the first-order conditions of quasi-linear\nmaximization,\n\n$$\n|J|\\, \\frac{\\partial q_1}{\\partial p_2}\n= |J|\\, \\frac{\\partial q_2}{\\partial p_1}\n= -\\,u_{12} = -\\,u_{21},\n$$ {#eq-cramer-cross}\n\nwhere $|J| > 0$ by negative definiteness (strict concavity of $u$). The products are\ntherefore demand-substitutes when $u_{12} = u_{21} < 0$ and demand-complements when\n$u_{12} = u_{21} > 0$: the *sign of the utility cross-partial* governs the substitution\nrelationship.\n\nThe **diversion ratio** quantifies substitution and is the single most important\ndemand statistic in merger analysis. For imperfect substitutes, it measures how much\nof the demand lost from raising $p_1$ is recaptured by product 2,\n\n$$\nd_{12} = \\frac{\\partial q_2 / \\partial p_1}{-\\,\\partial q_1 / \\partial p_1} > 0.\n$$ {#eq-diversion}\n\nIntuitively, if a consumer prefers coffee brand A but buys brand B when A's price\nrises (or A is out of stock), sales \"divert\" from A to B; $d_{12}$ is the fraction of\nA's lost sales that lands on B. Negative definiteness of the substitution matrix\nimposes a discipline on the pair of diversion ratios,\n\n$$\n\\frac{\\partial q_1}{\\partial p_1}\\frac{\\partial q_2}{\\partial p_2}\n- \\frac{\\partial q_2}{\\partial p_1}\\frac{\\partial q_1}{\\partial p_2} > 0\n\\quad \\Longleftrightarrow \\quad d_{12}\\, d_{21} < 1,\n$$\n\nso two goods cannot each divert most of their lost sales to the other. The empirically\nestimable version, for products $A$ and $B$ with quantities and prices\n$(Q_A, P_A, Q_B, P_B)$, is\n\n$$\nD_{AB} = \\frac{\\Delta Q_B / \\Delta P_A}{\\Delta Q_A / \\Delta P_A},\n$$ {#eq-diversion-emp}\n\nthe change in $B$'s quantity per unit change in $A$'s price, normalized by $A$'s own\nquantity response. The following seeded example simulates two products and estimates\nthe diversion ratio from first differences.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 100\nprice_A <- runif(n, 5, 10)\nprice_B <- runif(n, 5, 10)\nquantity_A <- 100 - 5 * price_A + rnorm(n)\nquantity_B <-  80 - 4 * price_B + rnorm(n)\n\n# Diversion ratio from first differences (eq. of D_AB)\ndelta_QA <- diff(quantity_A)\ndelta_PA <- diff(price_A)\ndelta_QB <- diff(quantity_B)\n\nD_AB <- mean(delta_QB / delta_PA) / mean(delta_QA / delta_PA)\nD_AB\n#> [1] 4.606575\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nplot_df <- data.frame(delta_PA, delta_QA, delta_QB)\nggplot(plot_df, aes(x = delta_PA)) +\n  geom_point(aes(y = delta_QA), color = \"blue\", alpha = 0.5) +\n  geom_point(aes(y = delta_QB), color = \"red\",  alpha = 0.5) +\n  geom_smooth(aes(y = delta_QA), method = \"lm\", color = \"blue\", se = FALSE) +\n  geom_smooth(aes(y = delta_QB), method = \"lm\", color = \"red\",  se = FALSE) +\n  labs(x = \"Change in price of A\", y = \"Change in quantity\",\n       title = \"Change in quantity vs. change in price of A\",\n       subtitle = \"Blue: product A   Red: product B\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Change in quantity of each product against the change in product A's price. Product A (blue) responds steeply to its own price; product B (red) is comparatively unresponsive, so little demand diverts from A to B.](35-industrial-organization_files/figure-epub/io-diversion-plot-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n### The Linear Demand System from Quadratic Utility\n\nThe most-used closed-form demand system comes from a quasi-linear **quadratic**\nutility. Over two differentiated goods,\n\n$$\nU(q_0, q_1, q_2) = q_0 + \\alpha_1 q_1 + \\alpha_2 q_2\n- \\tfrac{1}{2}\\big[ \\beta_1 q_1^2 + 2\\gamma\\, q_1 q_2 + \\beta_2 q_2^2 \\big],\n$$ {#eq-quad-utility}\n\nwith $\\alpha_i > 0$, $\\beta_i > 0$, and $\\beta_1 \\beta_2 - \\gamma^2 > 0$ (concavity).\nThe first-order conditions are the **inverse** (linear) demands,\n\n$$\np_1 = \\alpha_1 - \\beta_1 q_1 - \\gamma q_2, \\qquad\np_2 = \\alpha_2 - \\beta_2 q_2 - \\gamma q_1,\n$$ {#eq-linear-inverse}\n\nand inverting this linear system gives the direct demands with constant diversion\nratios. The cross-partial of utility is exactly $\\partial^2 U / \\partial q_1 \\partial q_2\n= \\gamma$, so $\\gamma$ *is* the substitution parameter: under the sign convention of\n@eq-cramer-cross, a positive cross-partial signals complements and a negative one\nsignals substitutes. Two parameterization styles appear in practice. Treating $\\gamma$\nas a free parameter captures the relationship directly and flexibly. Tying the\ncurvature to substitution by setting $\\beta_1 = \\beta_2 = 1 - \\gamma$ is more\nparsimonious but restrictive: it forces own-curvature to move with the cross-effect,\nwhich can be arbitrary when theory offers no guidance.\n\n#### The Shubik–Levitan Normalization\n\nA subtle defect of the raw quadratic form is that adding products mechanically changes\nthe scale of demand. @shubik1980 propose a normalization that separates the *number*\nof products from their *substitutability*. With\n\n$$\nu(q_1, \\dots, q_n) = \\alpha \\sum_{i=1}^n q_i\n- \\frac{n}{2(1+\\gamma)}\\Big[ \\sum_{i=1}^n q_i^2\n+ \\frac{\\gamma}{n}\\Big( \\sum_{i=1}^n q_i \\Big)^2 \\Big],\n$$ {#eq-shubik-utility}\n\nwhere $\\alpha > 0$ and $\\gamma \\in [0, \\infty)$ indexes substitutability, the demand\nsystem becomes\n\n$$\nq_i = \\frac{1}{n}\\Big[ \\alpha - p_i(1+\\gamma) + \\frac{\\gamma}{n} \\sum_{j=1}^n p_j \\Big].\n$$ {#eq-shubik-demand}\n\nThis form has two properties that make it the standard for oligopoly-variety models.\nThe aggregate demand $Q = \\sum_i q_i = \\alpha - \\tfrac{1}{n}\\sum_j p_j$ does not depend\non the degree of substitution $\\gamma$, and under symmetric prices $p_i = p$ the\naggregate $Q = \\alpha - p$ does not depend on the number of products $n$. Holding the\n\"market\" fixed while varying competition and variety is exactly what one wants when\nasking how entry or differentiation reshapes equilibrium.\n\nThe normalization supports two instructive applications. In the first, a downstream\n**buyer** with revenue $u(q_1, q_2)$ faces a *market-share restriction* imposed by the\nseller of product 1: $q_1/(q_1 + q_2) \\ge s$ or $q_1 = 0$, where $s \\in [0,1]$ is the\nrequired share and $s = 1$ is an exclusive contract. The buyer solves\n$\\max_{q_1, q_2} u(q_1, q_2) - p_1 q_1 - p_2 q_2$ subject to that constraint, and the\nlinear-quadratic utility yields a constrained demand $q(p, s)$ whose comparative\nstatics in $p$ and $s$ reveal how share-based contracts distort purchasing. In the\nsecond, a demand system satisfies the **strong-complements** property if the ratio\n$q_i^*(p)/q_1^*(p)$ is independent of $p_1$ for $i = 2, \\dots, n$. This is equivalent\nto the statement that, for any constant marginal costs $c_i > 0$, the monopolist's\nproblem $\\max_p \\sum_i (p_i - c_i) q_i^*(p)$ sets $p_i^* = c_i$ for $i = 2, \\dots, n$:\nwhen goods are strong complements, the multiproduct monopolist prices the\ncomplementary goods at marginal cost and earns its margin entirely on the base good.\nWriting $v(p) = u(q^*(p)) - \\sum_i p_i q_i^*(p)$ for indirect utility, the maximum\nprofit conditional on delivering the consumer at least $u$,\n$\\pi(u) = \\max_p \\{ \\sum_i (p_i - c_i) q_i^*(p) : v(p) \\ge u \\}$, is decreasing and\nconcave in the promised surplus.\n\n### Equilibrium Pricing and Cost Pass-Through {#sec-io-bertrand}\n\nThe demand system is only half the model; the other half is firm conduct. Suppose two\nsingle-product firms with constant marginal costs $c_1, c_2$ set prices\nsimultaneously. Firm 1 maximizes $\\pi_1(p_1, p_2) = (p_1 - c_1) q_1(p_1, p_2)$, with\nfirst-order condition\n\n$$\nq_1 + (p_1 - c_1)\\frac{\\partial q_1}{\\partial p_1} = 0,\n$$ {#eq-bertrand-foc}\n\nand symmetrically for firm 2. The pair of conditions defines the **Bertrand–Nash**\nequilibrium prices $(p_1^*, p_2^*)$. A key comparative static is **cost pass-through**\n(CPT)—how an equilibrium price responds to a marginal-cost shock—with own and cross\nrates\n\n$$\nCPT_{11} = \\frac{\\partial p_1^*}{\\partial c_1}, \\quad\nCPT_{22} = \\frac{\\partial p_2^*}{\\partial c_2}, \\quad\nCPT_{12} = \\frac{\\partial p_1^*}{\\partial c_2}, \\quad\nCPT_{21} = \\frac{\\partial p_2^*}{\\partial c_1}.\n$$ {#eq-cpt}\n\nPass-through is the quantity a regulator or analyst needs to predict how a tax,\ntariff, or input-cost shock reaches consumers, and it depends on the *curvature* of\ndemand, not merely its slope.\n\nWhen the two firms **merge or collude**, the combined entity becomes a multiproduct\nmonopolist maximizing joint profit\n$\\pi(p_1, p_2) = (p_1 - c_1) q_1 + (p_2 - c_2) q_2$, with first-order conditions\n\n$$\n\\begin{aligned}\n\\frac{\\partial \\pi}{\\partial p_1}\n&= q_1 + (p_1 - c_1)\\frac{\\partial q_1}{\\partial p_1}\n+ (p_2 - c_2)\\frac{\\partial q_2}{\\partial p_1} = 0,\\\\[4pt]\n\\frac{\\partial \\pi}{\\partial p_2}\n&= q_2 + (p_2 - c_2)\\frac{\\partial q_2}{\\partial p_2}\n+ (p_1 - c_1)\\frac{\\partial q_1}{\\partial p_2} = 0.\n\\end{aligned}\n$$ {#eq-monopoly-foc}\n\nThe monopolist's conditions differ from the competitive ones (@eq-bertrand-foc) by the\nextra cross-effect term $(p_j - c_j)\\,\\partial q_j / \\partial p_i$: the merged firm\n**internalizes** the demand it steals from itself. For substitutes this raises both\nprices above the Bertrand level—the classic unilateral-effects concern in merger\nreview—while pass-through rates $CPT^M$ generally differ from the competitive case\nbecause the monopolist accounts for cross-effects when passing through cost shocks.\n@tbl-bertrand-monopoly contrasts the two regimes.\n\n| Feature | Bertrand competition | Multiproduct monopoly / collusion |\n|---|---|---|\n| First-order condition | own margin × own slope only | own margin + cross-margin × cross-slope |\n| Internalizes cross-effects | no | yes |\n| Equilibrium prices (substitutes) | lower | higher |\n| Cost pass-through | own-cost driven | reflects internalized cross-effects |\n| Treatment of rival product | competitor | own product line |\n\n: Bertrand competition versus joint pricing under the same linear demand system. The single structural difference—internalizing cross-demand—drives the price and pass-through divergence. {#tbl-bertrand-monopoly}\n\nThe consumer side of this model is closed by **consumer surplus**. Integrating each\ninverse demand from @eq-linear-inverse below the price gives\n$CS_i = \\int_0^{q_i} p_i(q_i', q_{-i})\\,dq_i' - p_i q_i$, and total surplus is\n$CS = CS_1 + CS_2$; this is the welfare object compared across the competitive and\nmonopoly regimes.\n\n### Properties of Multiproduct Demand and the Symmetry of Cross-Effects\n\nFor a single product, demand $q = D(p)$ is downward-sloping, $q'(p) < 0$, with price\nelasticity $\\epsilon(p) = -q'(p)\\,p/q$. With multiple products the new content is the\n*cross*-price structure. A linear system\n\n$$\n\\begin{aligned}\nq_1 &= \\alpha_1 - \\beta_{11} p_1 + \\gamma_{12} p_2 + \\cdots,\\\\\nq_2 &= \\alpha_2 - \\beta_{22} p_2 + \\gamma_{21} p_1 + \\cdots,\n\\end{aligned}\n$$\n\nhas own-price effects $\\partial q_i / \\partial p_i < 0$ and cross-price effects whose\nsign is positive for substitutes and negative for complements. A foundational result\nis that the cross-effects are **symmetric**,\n$\\partial q_1 / \\partial p_2 = \\partial q_2 / \\partial p_1$, whenever consumers have\nquasi-linear utility (no income effect). The derivation makes the source of symmetry\nexplicit. From $\\max_{q_1, q_2} u(q_1, q_2) - p_1 q_1 - p_2 q_2$ the first-order\nconditions $u_1(q_1^*, q_2^*) = p_1$ and $u_2(q_1^*, q_2^*) = p_2$ hold; differentiating\nthe system with respect to $p_1$,\n\n$$\n\\begin{aligned}\nu_{11}\\frac{\\partial q_1^*}{\\partial p_1} + u_{12}\\frac{\\partial q_2^*}{\\partial p_1} &= 1,\\\\\nu_{21}\\frac{\\partial q_1^*}{\\partial p_1} + u_{22}\\frac{\\partial q_2^*}{\\partial p_1} &= 0,\n\\end{aligned}\n$$\n\nand solving yields\n\n$$\n\\frac{\\partial q_2^*}{\\partial p_1} = -\\,\\frac{u_{21}}{u_{11}u_{22} - u_{12}u_{21}},\n\\qquad\n\\frac{\\partial q_1^*}{\\partial p_2} = -\\,\\frac{u_{12}}{u_{11}u_{22} - u_{12}u_{21}}.\n$$\n\nBecause $u_{12} = u_{21}$ (Young's theorem on the symmetry of cross-partials), the two\ncross-effects are equal. This is the Slutsky symmetry of @eq-slutsky with the income\nterms switched off.\n\nWhen income effects are present, symmetry of the *uncompensated* cross-effects no\nlonger follows automatically. Slutsky symmetry holds for the *compensated* derivatives,\n\n$$\n\\frac{\\partial h_i}{\\partial p_j}\n= \\frac{\\partial q_i}{\\partial p_j} + \\frac{\\partial q_i}{\\partial I} q_j\n= \\frac{\\partial h_j}{\\partial p_i}\n= \\frac{\\partial q_j}{\\partial p_i} + \\frac{\\partial q_j}{\\partial I} q_i,\n$$\n\nso the observed (uncompensated) cross-effects are equal only if the income terms\nbalance, i.e. if $\\frac{\\partial q_i}{\\partial I}/q_i = \\frac{\\partial q_j}{\\partial I}/q_j$.\nThe empirical reading is useful: if the data show *equal* uncompensated cross-price\neffects, that is consistent evidence for either no income effect, or income effects\nthat scale the two goods' consumption proportionally—an additional rupee of income\nexpands consumption of both goods in the same relative measure. Two normalizations make\nthe cross-versus-own comparison concrete: assuming\n$-\\partial q_i / \\partial p_i > \\partial q_j / \\partial p_i$ keeps the diversion ratio\nbelow one, and assuming $-\\partial q_i / \\partial p_i > \\partial q_i / \\partial p_j$\nkeeps the *indirect* diversion ratio below one. Own- and cross-price elasticities are\ndefined analogously by scaling each derivative by $p/q$.\n\nThe classical, continuous approach has real strengths: the tight algebraic structure\nof the demand system delivers clean pricing strategies and exact welfare statements.\nBut it pays little attention to product *characteristics*—quality, location, timing,\navailability, the consumer's information about a product's existence and quality—and it\ndoes not formally model the *heterogeneity* of consumer preferences. Discrete-choice\nmodels, developed in @sec-io-discrete, are designed precisely to address these gaps.\n\n### Tractable Multiproduct Demand: Homothetic Surplus {#sec-io-armstrong}\n\nA frontier question is which multiproduct demand systems are simultaneously rich\nenough to be realistic and tractable enough to solve. @armstrong2018multiproduct\nanswer it by characterizing the demand systems whose *consumer surplus* is homothetic,\na property that collapses a high-dimensional pricing problem into a one-dimensional\none. Begin with the representative consumer's quasi-linear problem: utility $u(q)$ with\n$u(0) = 0$, increasing and strictly concave, choosing $q$ to solve $\\max_q u(q) - p\n\\cdot q$. The inverse demand is the gradient $p(q) = \\nabla u(q)$, total revenue is\n$R(q) = q \\cdot \\nabla u(q)$, and consumer surplus is\n\n$$\ns(q) = u(q) - q \\cdot \\nabla u(q).\n$$ {#eq-armstrong-surplus}\n\n> **Proposition** [@armstrong2018multiproduct]. Consumer surplus $s(q)$ is homothetic\n> in $q$ if and only if utility takes the form\n> $$ u(q) = h(q) + g\\big(f(q)\\big), $$\n> where $h$ and $f$ are homogeneous of degree one and $g$ is concave with $g(0) = 0$.\n\nThis is a far wider class than the systems whose surplus is homothetic in *prices*\n(the case $h = 0$), and it exposes exactly **three degrees of freedom**—the functions\n$f(q)$, $h(q)$, and $g(\\cdot)$—that the modeler can choose to match data while\npreserving tractability. The \"if\" direction is instructive. Inverse demand is\n$p(q) = \\nabla h(q) + g'(f(q))\\,\\nabla f(q)$, and since $q \\cdot \\nabla h(q) \\equiv\nh(q)$ for a degree-one homogeneous function, revenue is $R(q) = h(q) + g'(f(q)) f(q)$,\nso surplus reduces to $s(q) = g(f(q)) - g'(f(q)) f(q)$—a monotone function of the\nsingle composite $f(q)$.\n\nThe proof technique is a change to \"polar coordinates\" that pays off conceptually.\nWrite $q = f(q) \\cdot \\tfrac{q}{f(q)}$, where $q/f(q)$ is homogeneous of degree zero and\ndepends only on the *ray* from the origin (the mix of products), while $f(q)$—the\n**composite quantity**—measures how far along that ray the bundle lies. The consumer's\nproblem then *separates* into two stages. Surplus\n$u(q) - p\\cdot q = g(f(q)) - f(q)\\frac{p\\cdot q - h(q)}{f(q)}$ is maximized, for any\nfixed $f(q)$, by minimizing $\\frac{p\\cdot q - h(q)}{f(q)}$; define the **composite\nprice**\n\n$$\n\\phi(p) \\equiv \\min_{q \\ge 0} \\frac{p \\cdot q - h(q)}{f(q)},\n$$ {#eq-armstrong-phi}\n\nwhich is increasing and concave in $p$. By the envelope theorem the optimal *relative\nquantities* are $q^r(p) \\equiv \\nabla \\phi(p)$. Given those, the consumer chooses the\ncomposite quantity $Q$ to maximize the concave objective $g(Q) - Q\\,\\phi(p)$, whose\nsolution $\\hat{Q}(\\phi(p))$ is the demand for the composite. The full demand function\nfactors as $q(p) = \\hat{Q}(\\phi(p)) \\times q^r(p)$: the consumer picks a *mix* from\nrelative prices and a *scale* from the composite price, and all prices with the same\n$\\phi(p)$ induce the same composite quantity through the inverse relation\n$\\phi(p) = g'(\\hat{Q})$.\n\nThree examples show the family's reach. The **linear** system $u(q) = aq -\n\\tfrac{1}{2} q^\\top B q$ with $a > 0$ and $B$ positive definite gives $p(q) = a - Bq$\nand decomposes as $h(q) = aq$, $f(q) = \\sqrt{q^\\top B q}$, $g(f) = -\\tfrac{1}{2}f^2$,\nand $s(q) = \\tfrac{1}{2} f(q)^2$. The **logit** system\n$q_i(p) = \\frac{e^{(a_i - p_i)/\\mu}}{k + \\sum_j e^{(a_j - p_j)/\\mu}}$ corresponds to\nsurplus $v(p) = \\mu \\log\\!\\big(1 + \\tfrac{1}{k}\\sum_j e^{(a_j - p_j)/\\mu}\\big)$, with\nthe decomposition $f(q) = \\sum_j q_j$ (total quantity),\n$g(f) = -\\mu\\big(f\\log f + (1-f)\\log(1-f)\\big)$, and $s(q) = -\\mu\\log(1 - f(q))$. The\n**complementary-products** example captures hardware-plus-services: if $q_1$ is the\nnumber of access units (hardware) and each requires services $y = q_2/q_1$, gross\nutility is $u(q_1, q_2) = q_1 \\hat{u}(q_2/q_1) + g(q_1)$, an instance with $f(q) = q_1$,\nso surplus depends only on the number of access units. The ratio $q_2/q_1$ is\nindependent of $p_1$—precisely the strong-complements property of @sec-io-classical—\nwith the implication that the monopolist prices services to extract the base-good\nmargin.\n\n## Vertical Differentiation: Quality {#sec-io-vertical}\n\nDifferentiation is **vertical** when augmenting a product characteristic benefits *all*\nconsumers: everyone prefers higher quality, faster delivery, longer battery life. The\ncanonical model gives a consumer of type $\\theta$ utility\n\n$$\nu =\n\\begin{cases}\n\\theta s - p & \\text{if she buys quality } s \\text{ at price } p,\\\\\n0 & \\text{if she does not buy,}\n\\end{cases}\n$$ {#eq-vertical-utility}\n\nwhere $s > 0$ is quality (common knowledge), utility is separable in quality and\nprice, and $\\theta > 0$ is a taste parameter—the consumer's marginal willingness to pay\nfor quality—distributed across the population with density $f(\\theta)$ and cdf\n$F(\\theta)$ on $[\\underline{\\theta}, \\bar{\\theta}]$. Firms know the distribution but not\nany individual's $\\theta$. The defining feature is unanimity: every consumer prefers\nhigher $s$, in contrast to horizontal differentiation where consumers disagree about\nthe ideal variety.\n\n**One quality.** When a single quality $s$ is offered at price $p$, a type $\\theta$\nbuys iff $\\theta s - p \\ge 0$, i.e. $\\theta \\ge p/s$. With $N$ identical consumers,\naggregate demand is\n\n$$\nD(p) = N\\big[1 - F(p/s)\\big],\n$$ {#eq-vertical-demand1}\n\nwhich is downward-sloping. Under the uniform $F$, $D(p) = N(1 - p/s)$ for $p \\le s$ and\nzero otherwise. Unlike classical demand, quality $s$ enters *explicitly*, so the model\ncan speak to quality choice, not just price.\n\n**Two qualities.** Offering a product line $s_1 < s_2$ (with $p_1 < p_2$) lets the firm\nscreen consumers and extract more surplus—the logic of second-degree price\ndiscrimination. A type $\\theta$ buys $s_1$ iff $\\theta s_1 - p_1 \\ge 0$ and\n$\\theta s_1 - p_1 \\ge \\theta s_2 - p_2$; she buys $s_2$ iff $\\theta s_2 - p_2 \\ge 0$ and\n$\\theta s_2 - p_2 \\ge \\theta s_1 - p_1$. Three cutoffs—$p_1/s_1$, $p_2/s_2$, and the\nindifference type $\\theta^* \\equiv (p_2 - p_1)/(s_2 - s_1)$—partition consumers across\nnot buying, buying low, and buying high. The configuration depends on which good offers\nmore *quality per dollar*. If the high good dominates on quality-per-dollar\n($p_2/s_2 \\le p_1/s_1$), the low good is driven out and only $s_2$ sells; otherwise both\nsell, with the low good serving an interior band of types. Collecting both cases,\n\n$$\nD_1(p_1, p_2) =\n\\begin{cases}\n0 & \\text{if } \\tfrac{p_1}{p_2} \\ge \\tfrac{s_1}{s_2},\\\\[4pt]\nN\\big[F(\\tfrac{p_2 - p_1}{s_2 - s_1}) - F(\\tfrac{p_1}{s_1})\\big] & \\text{if } \\tfrac{p_1}{p_2} < \\tfrac{s_1}{s_2},\n\\end{cases}\n$$ {#eq-vertical-D1}\n\n$$\nD_2(p_1, p_2) =\n\\begin{cases}\nN\\big[1 - F(\\tfrac{p_2}{s_2})\\big] & \\text{if } \\tfrac{p_1}{p_2} \\ge \\tfrac{s_1}{s_2},\\\\[4pt]\nN\\big[1 - F(\\tfrac{p_2 - p_1}{s_2 - s_1})\\big] & \\text{if } \\tfrac{p_1}{p_2} < \\tfrac{s_1}{s_2}.\n\\end{cases}\n$$ {#eq-vertical-D2}\n\nUnder the uniform special case $F(\\theta) = \\theta$ on $[0,1]$, the interior cross-price\nderivatives are $\\partial D_1 / \\partial p_2 = \\partial D_2 / \\partial p_1 = N/(s_2 -\ns_1) > 0$: the two qualities are **substitutes**, and the strength of substitution\nscales inversely with the quality gap $s_2 - s_1$. Widening the quality ladder softens\ncompetition between the firm's own tiers—the structural reason a multiproduct firm\nspaces its versions apart.\n\nThe taste parameter $\\theta$ admits a measurable interpretation: it can stand for\nwillingness to pay for quality and is often linked to **income**, the most observable\naxis of consumer heterogeneity. If consumers differ in income and utility is\n$U = u(I - p) + s$, a first-order Taylor expansion of $u$ around $I$ recovers the\nquasi-linear form $\\theta s - p$ with $\\theta$ tied to the marginal utility of income,\nmaking the abstract taste parameter empirically grounded.\n\n## Discrete-Choice Demand {#sec-io-discrete}\n\nDiscrete-choice models replace the continuous-quantity consumer with one who selects a\nsingle alternative from a menu, which is how modern empirical IO and quantitative\nmarketing estimate demand for differentiated products. The payoff is twofold: a small\nnumber of *preference* parameters generates the full matrix of own- and cross-price\nelasticities, and demand can be predicted for *new* or hypothetical products by\nprojecting them into characteristic space. @fig-discrete-lineage traces the lineage of\nmodels this section develops, from the workhorse logit through its corrections for\nheterogeneity and endogeneity to the frontier estimators for zero shares and\nmulti-sided markets.\n\n```{mermaid}\n%%| label: fig-discrete-lineage\n%%| fig-cap: \"Lineage of discrete-choice demand models. Each arrow relaxes a limitation of the parent: random coefficients break the IIA restriction, BLP adds price endogeneity, and the frontier estimators handle zero shares and platform externalities.\"\nflowchart TD\n    A[Random utility<br/>McFadden] --> B[Multinomial logit MNL<br/>closed form, but IIA]\n    B --> C[Nested logit / GEV<br/>relax IIA across groups]\n    B --> D[Multinomial probit<br/>flexible correlation]\n    B --> E[Random-coefficients logit<br/>heterogeneous tastes]\n    E --> F[BLP<br/>+ price endogeneity, share inversion]\n    F --> G[Zero-share estimator<br/>pairwise differencing]\n    F --> H[Multi-sided markets<br/>+ cross-side externalities]\n```\n\n### Random Utility and the Multinomial Logit {#sec-io-mnl}\n\n@mcfadden1986choice frames market research through **economic choice theory**: a\nconsumer is an \"optimizing black box\" mapping inputs (product attributes, socioeconomic\nfeatures, market information, history, constraints) to outputs (purchase decisions,\nconsumption levels). The behavioral premise is that individuals maximize a preference\norder influenced by perceptions, attitudes, and past decisions, with commodities\nrepresented as bundles of attributes. The intellectual debt is explicit: Thurstone's\n1927 *random utility* idea—choice of the momentarily most beneficial alternative—was\nrevived by Luce in 1959 and married, by the mid-1960s, to a *multidimensional\nattribute* representation of goods, producing the multinomial logit. McFadden's program\nis to model the cognitive process inside the black box using experimental data on\nconsumer cognition, because historical field data may not reveal how consumers would\nrespond to genuinely new product designs. The constructs that populate the box—product\nperceptions, general attitudes, preferences, decision protocols, and behavioral\nintentions—are measured by psychometric instruments (multidimensional scaling for\nperceptions, factor analysis for tastes, verbal protocols for decision-making, conjoint\nanalysis for preferences), and the central challenge is to turn those psychometric\nindicators into market forecasts that can be validated. Laboratory elicitation is\nattractive for its precise control, ability to study not-yet-marketed innovations, and\nlow cost, but only field validation is fully convincing, and the literature warns that\nincentive-poor experiments may mispredict real behavior.\n\nThe **multinomial logit** (MNL) is the workhorse random-utility model. With a choice\nset $C = \\{1, \\dots, M\\}$ and scale values (strict utilities) $V_i$, the probability of\nchoosing $i$ is\n\n$$\nP_C(i) = \\frac{\\exp(V_i)}{\\sum_{j \\in C} \\exp(V_j)}.\n$$ {#eq-35-mnl}\n\nThe scale values are functions of alternatives' attributes, can interact with\nindividual characteristics and choice-set features, and usually take an additively\nseparable linear form $V_i = \\mathbf{X}_i \\boldsymbol{\\beta}$. The closed form follows\nfrom assuming the unobserved utility component is i.i.d. type-I extreme value (double\nexponential). The MNL inherits Luce's **independence of irrelevant alternatives**\n(IIA) axiom,\n\n$$\n\\frac{P_A(i)}{P_A(j)} = \\frac{P_C(i)}{P_C(j)}\n\\qquad \\forall\\, i, j \\in A \\subseteq C,\n$$ {#eq-35-iia}\n\nwhich states that the relative odds of two alternatives do not depend on what else is\navailable. IIA is a double-edged property. It buys real advantages: inference about\nmany alternatives from paired comparisons, easy demand forecasting for new\nalternatives, a clean link between choice probabilities and ranking data (ideal for\nconjoint), and the closed form itself. But it is often unrealistic—it forces a uniform\nsubstitution response to any one alternative's attribute change, at odds with the\nclustered similarity patterns of real markets (the \"red bus / blue bus\" problem), and\nthis defect, too, traces to the extreme-value error assumption.\n\nThe literature addresses IIA in three ways: test for it empirically; modify the MNL so\nscale values depend on choice-set features; or switch models. The alternatives include\n**multinomial probit** (MNP), which permits arbitrary correlation patterns through\nnormally distributed utilities at the cost of high-dimensional integration; **nested\nMNL**, the marketing standard, which groups similar alternatives so IIA holds only\n*within* nests; **generalized extreme value**; and elimination-by-aspects variants\n(HEBA, elimination by strategy). Consumer heterogeneity is handled by random-\ncoefficients MNL (the marketing standard for breaking IIA), fixed-coefficient\nspecifications, or hierarchical Bayesian models. Estimation is normally by maximum\nlikelihood, though richer models demand more computation: hierarchical models arrange\nalternatives in a preference tree and choose by eliminating clusters, while MNP and\nrandom-coefficients MNP rely on **Monte Carlo simulation** for both estimation and\nforecasting. A low-dimensional **factor-analytic** structure on the covariance matrix\nkeeps MNP tractable, and the *hybrid* model of Westin and Talvitie makes choice\nprobabilities logit with scale values linear in random taste parameters. The\n**simulated moments** estimator of @mcfadden1986method makes high-dimensional MNP\npractical: it is consistent and asymptotically normal while requiring only one Monte\nCarlo draw per observation, and it supplies computationally feasible instruments and a\ncovariance estimator for hypothesis testing. Market demand is then the sum of\nindividual choice probabilities, approximated either by **microsimulation** (Monte\nCarlo sampling over the population, the more flexible route, which reflects population\nheterogeneity when the model carries fixed-effect parameters) or by segmenting the\npopulation and summing representative probabilities. Forecasting additionally requires\nexternal projections of prices, attributes, demographics, and population size.\n\nA distinctive strand of @mcfadden1986choice incorporates **psychometric data** directly\ninto the choice model. Perceptions and attitudes—scaled metrically—shape the utility\nfunction and the product-attribute scales, formalized in a latent-variable system that\nlinks measured causes and indicators to a utility-maximizing choice protocol.\nPsychometricians favor *fixed-effect* descriptions of individual heterogeneity;\nmarketing favors *random-effect* models for their parsimony, forecast accuracy, and\nflexibility. A practical sequential estimator first regresses the psychometric\nindicators to recover the latent variables, then estimates the choice model on the\nfitted latents; a more efficient estimator integrates over the latent-variable\ndistribution by maximum likelihood, with the simulated-moments estimator as a lighter\nalternative. **Conjoint analysis** is the experimental engine for this program: it\ngathers laboratory choice data in simulated markets plus self-explicated attribute\nimportances, and—because everything is exogenous by design—it can be used much like\nreal market data for forecasting, with *choice-based* conjoint the gold standard for\nmimicking reality. Its validity hinges on the stability of preferences across task\nframings and incentives, the structure of the preference map, and the cognitive\ncongruence of experimental and market tasks. Because the MNL's IIA structure is a\nmaintained assumption when conjoint data are summarized this way, it must be tested:\nauxiliary regressions detect omitted variables and interactions, and the tests of\nMcFadden–Tye–Train and Hausman–McFadden gauge IIA, with power depending on the\nvariables already in the base model and the capacity to discriminate among nesting\nstructures.\n\n### Differentiated-Products Demand and Price Endogeneity {#sec-io-berry}\n\nThe defining obstacle in estimating differentiated-products demand is **price\nendogeneity** arising from *unobserved* product characteristics. @berry1994estimating\ngives the structural interpretation: a demand error represents unobserved demand\ninfluences—style, design, perceived quality, durability—that the econometrician cannot\nmeasure but that firms observe and price against. Because high-$\\xi$ products carry\nboth higher demand and higher prices, the correlation between price and the demand\nerror biases naive estimates and can even produce upward-sloping fitted demand curves,\nexactly the anomaly Trajtenberg documents in CT scanners and Berry, Levinsohn, and\nPakes confirm in automobiles. For *homogeneous* goods this is a standard endogeneity\nproblem fixable with instrumental variables on a constant-elasticity system\n$\\ln(q_j) = \\alpha_j + \\sum_k \\eta_{jk}\\ln(p_k) + \\epsilon_j$, where $\\eta_{jk}$ is the\nelasticity of good $j$ to price $k$. But in discrete-choice models price and $\\xi$ enter\ndemand *non-linearly*, so linear IV cannot be applied directly.\n\nThere is also a dimensionality problem. A system of $N$ goods has $N^2$ elasticities,\ninfeasible to estimate freely. Imposing *a priori* restrictions (setting some\ncross-elasticities to zero or to common values) is arbitrary and weakly grounded in\ntheory. The discrete-choice solution is to project demand onto a low-dimensional\n**characteristic space**: consumer utility depends on product characteristics and a few\nrandom taste parameters, market demand aggregates individual choices, and all\nelasticities are derived from the handful of utility parameters—which also lets the\nmodel predict demand for new and dissimilar products and move freely between aggregate\ndemand and the underlying utility. The cost is the discrete-choice straitjacket: it\nrules out buying multiple items, struggles with dynamics, and imposes parametric\nstructure. This program descends from McFadden (1974) and Bresnahan's (1987) vertical\nmodel of autos, both of which model utility over characteristics, allow an *outside\ngood*, and use price-setting firms' first-order conditions—while, like most of the\nempirical literature, treating characteristics as exogenous even as prices are\ndetermined within the model.\n\n@berry1994estimating resolves the non-linear IV problem with the **mean-utility\ninversion**. The data are $R$ independent markets; market $r$ has $N_r$ single-product\nfirms; product $j$ in market $r$ has observed characteristics $z_{jr} \\in\n\\mathbb{R}^{K_z}$ (affecting demand $x_j$ and marginal cost $w_j$) and unobserved\ncharacteristics $(\\xi_j, \\omega_j)$, where $\\xi_j$ shifts demand and $\\omega_j$ shifts\ncost. The unobservables are assumed mean-independent of observed characteristics and\nindependent across markets, so $(\\mathbf{z}, \\boldsymbol{\\xi}, \\boldsymbol{\\omega})$ are\nexogenous to pricing. Consumer $i$'s utility for product $j$ is $U(x_j, \\xi_j, p_j,\n\\nu_i, \\theta_d)$, with $\\nu_i$ a consumer-specific term. The leading **random-\ncoefficients** specification is\n\n$$\nu_{ij} = x_j \\tilde{\\beta} - \\alpha p_j + \\xi_j + \\epsilon_{ij},\n$$ {#eq-35-blp-utility}\n\nwhere the taste for characteristic $k$ is $\\tilde{\\beta}_k = \\beta_k + \\sigma_k\n\\zeta_{ik}$ with $\\beta_k$ the mean taste and $\\zeta_{ik}$ i.i.d. standard normal across\nconsumers and characteristics. Substituting,\n\n$$\nu_{ij} = x_j \\beta + \\xi_j - \\alpha p_j + \\nu_{ij},\n\\qquad\n\\nu_{ij} = \\sum_k x_{jk}\\,\\sigma_k\\,\\zeta_{ik} + \\epsilon_{ij},\n$$ {#eq-blp-decomp}\n\nwhere $\\nu_{ij}$ is a mean-zero, heteroskedastic error capturing the random tastes.\nCollecting the terms common to all consumers defines the **mean utility**\n\n$$\n\\delta_j \\equiv x_j \\beta - \\alpha p_j + \\xi_j.\n$$ {#eq-blp-mean-utility}\n\nThe estimator's insight is that observed market shares can be *inverted* to recover the\n$\\delta_j$, which are linear in the demand error $\\xi_j$; instrumental variables can\nthen be applied to that linear equation. We make the inversion explicit in\n@sec-io-zeroshares, where the zero-share problem is also confronted. The companion\npapers extend the framework to equilibrium: @berry1995automobile estimates automobile\nprices in market equilibrium with supply-side first-order conditions, and\n@berry2004differentiated combine micro (individual) and macro (aggregate) data to\nsharpen identification of the new-car demand system.\n\n### Zero-Valued Market Shares {#sec-io-zeroshares}\n\nThe BLP machinery assumes every product has a strictly positive share, because the\nshare inversion takes logs. Real retail data violate this constantly:\n@dube2021random report that in scanner data, products with literally zero sales are\nubiquitous—30.7% of store-day-product observations in their ice-cream application\nrecord no sale—and these zeros persist even in large consumer populations, so they are\nnot sampling noise. The standard fixes are *ad hoc* and biased: imputing a tiny share\n(say $s_j = 10^{-12}$) makes results sensitive to the arbitrary small number, dropping\nzero-share observations discards information and, worse, induces **selection bias**\nwhen zeros are systematic, and common data sources (IRI, Nielsen) silently exclude\nzero-sales products. @dube2021random build an estimator that treats the zeros as\ninformative through a regime-switching selection model and a pairwise-difference GMM.\n\nThe demand side is a **random-coefficients logit**. With a consideration set $J = \\{1,\n\\dots, J+1\\}$ where $J+1$ is the outside option ($p_{J+1} = 0$), household $h$ with\nbudget $y$ maximizes $U(\\mathbf{q}, y; \\theta^h) = \\sum_{j=1}^{J+1} (\\chi_j^h q_j)\n\\exp(\\alpha^h q_0)$ over discrete consumption, where perceived quality is $\\chi_j^h =\n\\exp(x_j'\\beta^h + \\xi_j + \\epsilon_j^h)$, $x_j$ are exogenous attributes, $\\xi_j$ is an\nunobserved vertical characteristic, $\\beta^h$ are taste parameters, and $\\alpha^h$ is\nthe marginal value of the numeraire. The choice-specific indirect utilities are\n\n$$\nu_j^h = \\alpha^h(y - p_j) + x_j'\\beta^h + \\xi_j + \\epsilon_j^h,\n\\qquad\nu_{J+1}^h = \\alpha^h y + \\epsilon_{J+1}^h,\n$$ {#eq-dube-utility}\n\nwith $\\epsilon_j^h$ i.i.d. extreme value and preferences $\\theta^h = (\\alpha^h,\n\\beta^h)' \\sim F_\\theta(\\cdot; \\Theta)$. The predicted share integrates the logit\nprobability over the taste distribution,\n\n$$\n\\pi_j(\\mathbf{p}, \\mathbf{x}, \\xi; \\Theta)\n= \\int \\frac{\\exp(\\alpha^h p_j + x_j'\\beta^h + \\xi_j)}\n{1 + \\sum_{k=1}^J \\exp(\\alpha^h p_k + x_k'\\beta^h + \\xi_k)}\\,\ndF_\\theta(\\theta^h; \\Theta),\n$$ {#eq-dube-share}\n\nand is always strictly positive, which is exactly why the model alone cannot rationalize\nan observed zero.\n\nThe fix is a **product-selection** stage. For each product an indicator $d_j = \\mathbf{1}\n\\big(\\phi(p_j, x_j, \\tilde{\\mathbf{w}}_j) + \\eta_j > 0\\big)$ governs whether $j$ enters\nthe consumer's choice set, where $\\tilde{\\mathbf{w}}_j$ are selection-shifting factors\n(stock-outs, feature ads, in-store displays) that move a product's *consideration* but\nnot its consumption value [@mehta2003price], and $\\eta_j$ is a continuous selection\nshock. Observed shares then follow a **regime switch**,\n\n$$\n\\pi_j(\\mathbf{p}, \\mathbf{x}, \\xi; \\Theta) =\n\\begin{cases}\n\\displaystyle \\int \\frac{\\exp(\\alpha^h p_j + x_j'\\beta^h + \\xi_j)}\n{1 + \\sum_{k \\in C} \\exp(\\alpha^h p_k + x_k'\\beta^h + \\xi_k)}\\, dF_\\theta & d_j = 1,\\\\[10pt]\n0 & d_j = 0,\n\\end{cases}\n$$ {#eq-dube-regime}\n\nwith $C$ the realized choice set. The econometric danger is **selection on\nunobservables**: demand and selection shocks can be correlated, $\\mathrm{cov}(\\xi_j,\n\\eta_j) \\ne 0$. The motivating example is a locally sourced premium item (high $\\xi_j$)\nthat retailers give scarce shelf space and stock thinly (high non-selection), so quality\nand consideration move together; if shelf-space and inventory data are unavailable, the\ncorrelation is unavoidable.\n\nIdentification rests on **BLP's moment condition** $E(\\xi_j \\mid \\mathbf{z}_j) = 0$,\nwhere $\\mathbf{z}_j$ stacks attributes $x_j$ and excluded price shifters\n$\\tilde{\\mathbf{r}}_j$. @berry1994estimating proves the share map $s_j = \\pi_j(\\mathbf{p},\n\\mathbf{x}, \\xi; \\Theta)$ is invertible in the demand shocks, $\\xi(\\Theta) = \\pi^{-1}\n(\\mathbf{x}, \\mathbf{s}; \\Theta)$, and @berry1995 propose the GMM estimator built on the\nempirical analogue of $E(\\xi_j(\\Theta) \\mid \\mathbf{z}_j) = 0$. With any zero share the\ninversion fails. Dropping zeros invokes the weaker condition $E[\\xi_j \\mid \\mathbf{z}_j,\nd_j = 1] = 0$, valid only under selection-at-random ($\\mathrm{cov}(\\xi_j, \\eta_j) = 0$);\nunder selection on unobservables it fails and GMM is inconsistent. Reduced-form prices\nare modeled additively, $p_j = \\Pi(\\mathbf{r}_j; g) + \\upsilon_j$ with supply shock\n$\\upsilon_j$, which is reasonable under cost-plus grocery pricing and supports a\n**control-function** correction for endogenous prices.\n\nThe solution is **pairwise differencing**. Assume the demand shock decomposes through\nthe non-selection propensity $\\mu_j$ as $\\xi_j = \\iota(\\mu_j) + \\zeta_j$ with $E[\\zeta_j\n\\mid \\mu_j, \\mathbf{z}] = 0$ for a smooth increasing $\\iota(\\cdot)$. Then for a pair of\nproducts with equal propensities the selection terms cancel, yielding the moment\n\n$$\nE[\\xi_i - \\xi_j \\mid \\mathbf{z}_i, \\mathbf{z}_j, \\mu_i = \\mu_j, d_i = d_j = 1] = 0.\n$$ {#eq-dube-moment}\n\nIn the homogeneous-logit case the inverted demand is $\\ln(s_j/s_0) = \\alpha p_j + x_j'\n\\beta + \\iota(\\mu_j) + \\zeta_j$, and differencing two products with $\\mu_i = \\mu_j$\neliminates the unknown selection function,\n\n$$\n\\ln(s_i/s_0) - \\ln(s_j/s_0) = \\alpha(p_i - p_j) + (x_i - x_j)'\\beta + (\\zeta_i - \\zeta_j),\n$$ {#eq-dube-diff}\n\nso the conditional moment $E[\\zeta_i - \\zeta_j \\mid \\cdots] = E[\\xi_i - \\xi_j \\mid \\cdots]\n= 0$ identifies $(\\alpha, \\beta)$ without ever logging a zero share. The price is that the\nutility *intercept* is differenced away and cannot be identified.\n\nEstimation is a three-step procedure. **Stage 1** estimates the pricing equation $p_j =\n\\Pi(\\mathbf{r}_j; g) + \\upsilon_j$ (known functional form) with a $\\sqrt{n}$-consistent\n$\\hat{g}$, forms residuals $\\hat{\\upsilon}_j = p_j - \\Pi(\\mathbf{r}_j; \\hat{g})$, and\nbuilds the control vector $\\mathbf{w}_j' = (\\hat{\\upsilon}_j, \\tilde{\\mathbf{w}}_j')$;\nunder the distributional exclusion restriction, $p_j$ and $x_j$ are excluded from\n$\\mathbf{w}_j$. **Stage 2** estimates the selection propensity nonparametrically by\nNadaraya–Watson kernel regression,\n\n$$\n\\hat{\\mu}(\\mathbf{w}_j) = 1 - \\frac{\\sum_k d_k\\, H\\!\\big(\\tfrac{\\mathbf{w}_k - \\mathbf{w}_j}{b_n}\\big)}\n{\\sum_k H\\!\\big(\\tfrac{\\mathbf{w}_k - \\mathbf{w}_j}{b_n}\\big)},\n$$ {#eq-dube-nw}\n\nwith kernel $H$ and bandwidth $b_n$. **Stage 3** is the **pairwise-difference weighted\nGMM** (PDWGMM) estimator. Writing $\\Delta$ for the differencing operator over product\npairs, $g_{i,j}(\\Theta) = \\Delta \\mathbf{z}_{i,j}\\,\\Delta \\xi_{i,j}(\\Theta)$, kernel\nweights $\\hat{w}_{i,j} = h_{n_d}^{-1}\\kappa\\big((\\hat{\\mu}_i - \\hat{\\mu}_j)/h_{n_d}\\big)$\nthat upweight pairs with similar propensities, and a GMM weight matrix $\\Phi$, the\nestimator solves\n\n$$\n\\Theta^{\\text{PDWGMM}} = \\arg\\min_{(\\Theta, \\xi)}\n\\frac{2}{n(n-1)} \\sum_{i=1}^{n-1} \\sum_{j=i+1}^{n}\n\\hat{w}_{i,j}\\, \\mathbf{g}_{i,j}(\\Theta)'\\, \\Phi\\, \\mathbf{g}_{i,j}(\\Theta)\n\\quad \\text{s.t.}\\quad \\mathbf{s} = \\pi(\\mathbf{p}, \\mathbf{x}, \\xi; \\Theta),\n$$ {#eq-dube-pdwgmm}\n\nwith the share constraint imposed only where shares are positive.\n\nMonte Carlo evidence sharpens the stakes. Under **selection on unobserved demand**\n(scenario a), PDWGMM recovers the mean parameters accurately while the drop-zero\nestimator overstates the price coefficient by roughly 150%. When zeros are **missing at\nrandom** (scenario b) both estimators are accurate, and PDWGMM loses no precision. With\n**strictly positive shares** (scenario c) PDWGMM needs no first two stages and matches\nthe drop-zero estimates. In the ice-cream application—nonpremium brands (Breyers,\nDean's, Edy's, store brand), the 48-oz size that is 98.5% of sales, two stores,\nThursdays, January 2013–June 2014, 14,907 product-store observations—price endogeneity\nis instrumented by unit cost and its square, and consideration is instrumented by UPC-\nand brand-level feature advertising. Across six estimators (random-coefficients and\nhomogeneous logit, each with PDWGMM, drop-zero, and where applicable Heckman and impute\ncorrections), the imputed-share correction is unstable, PDWGMM's mean price coefficient\nis significantly *lower* (demand more elastic) than drop-zero's, the hypothesis of equal\nmean elasticities is rejected at 5%, and the Heckman two-step resembles drop-zero. The\nmethodological contribution is to accommodate zero shares within aggregate\ndiscrete-choice demand—extensible to CES demand—rather than papering over them.\n\n### Multi-Sided Markets {#sec-io-platforms}\n\nPlatforms—marketplaces, payment networks, operating systems—create value through\n*cross-side network externalities*: a buyer's utility rises with the number of sellers,\nand vice versa. @tan2021effects extend the discrete-choice framework to such settings by\nletting a consumer's utility incorporate an externality term $\\phi_i(\\mathbf{x}^k)$ that\ndepends on participation on the platform's other side. This converts the demand system\ninto a fixed point—each side's demand depends on the other side's realized\nparticipation—so entry and competition analysis must account for feedback that is absent\nin single-sided markets. Adding a competitor or a new platform shifts not only the\ndirect substitution among options but also the externality each side confers on the\nother, which is why competition and entry in multi-sided markets can have welfare\neffects that single-sided intuition gets backwards.\n\n## Vertical Relations and Negotiated Wholesale Prices {#sec-io-bargaining}\n\nEvery supply-side model so far has taken each firm's marginal cost $c_j$ as an\nexogenous primitive to be recovered from a pricing first-order condition\n(@eq-bertrand-foc). In a distribution channel that premise is wrong in a way that\nmatters. A grocery retailer's marginal cost of a national brand is a **wholesale price\nnegotiated bilaterally with the manufacturer**, and it moves when anything that\nchanges either side's outside option changes—an entrant, a patent expiry, a new\nprivate label on the retailer's own shelf. Treating $w_j$ as a technological constant\nthrows away exactly the variation a channel study is about.\n\nThe textbook alternative is not much better. The classical channel model makes the\nmanufacturer a Stackelberg leader who posts $w_j$ and lets the retailer respond, which\nproduces double marginalization and assigns *all* channel power to the upstream firm\nby assumption. Real negotiations are neither take-it-or-leave-it nor costlessly\nefficient, and the position of a given pair on that spectrum is precisely what an\nempirical channel study wants to measure. The **Nash-in-Nash** framework introduced in\npassing above is the workhorse that makes channel power an estimated parameter rather\nthan a modelling assumption. @horn1988bilateral supplies the original bilateral-\nmonopoly formulation, @collardwexler2019nash supplies the non-cooperative\nmicrofoundation, @draganska2010larger brings it into marketing to measure who captures\nthe channel margin in German coffee, and @ellickson2026private uses it to answer a\nquestion the reduced-form literature could not: *how much* of a retailer's gain from\nlaunching a private label comes from the private label's own margin, and how much from\nthe improved terms it wins on the national brands it still carries.\n\n### Setup and Notation {#sec-io-nn-setup}\n\nA single retailer sells $J$ differentiated products, one from each upstream supplier\n$j = 1, \\dots, J$, to a unit mass of consumers. Demand $q_j(\\mathbf{p})$ comes from\nthe discrete-choice system estimated in @sec-io-berry: with mean utilities\n$\\delta_j$ (@eq-blp-mean-utility) and price coefficient $\\alpha$, logit shares are\n$q_j(\\mathbf{p}) = \\exp(\\delta_j - \\alpha p_j) / [1 + \\sum_k \\exp(\\delta_k - \\alpha p_k)]$.\nSupplier $j$ produces at constant marginal cost $c_j$ and sells to the retailer at the\n**linear wholesale price** $w_j$; the retailer incurs an additional handling cost\n$c^R_j$ and sets the retail price $p_j$. Profits are\n\n$$\n\\Pi^R(\\mathbf{p}; \\mathbf{w}) = \\sum_{j} (p_j - w_j - c^R_j)\\, q_j(\\mathbf{p}),\n\\qquad\n\\Pi^S_j(\\mathbf{p}; \\mathbf{w}) = (w_j - c_j)\\, q_j(\\mathbf{p}).\n$$ {#eq-nn-profits}\n\nThe retailer is a multiproduct monopolist over its own shelf, so its pricing\nfirst-order condition is @eq-monopoly-foc applied to all $J$ products with $w_j + c^R_j$\nin place of $c_j$. In matrix form, with $\\Omega_{jk} \\equiv -\\partial q_k / \\partial p_j$,\nthe retail equilibrium given $\\mathbf{w}$ solves\n\n$$\n\\mathbf{p}^*(\\mathbf{w}) = \\mathbf{w} + \\mathbf{c}^R + \\Omega^{-1}\\mathbf{q}.\n$$ {#eq-nn-retail-foc}\n\nTwo derived objects carry all the economics. The **gains from trade** on agreement $j$\nare what each side would lose if that one negotiation broke down,\n\n$$\nG^R_j(\\mathbf{w}) = \\Pi^R\\!\\left(\\mathbf{p}^*(\\mathbf{w}); \\mathbf{w}\\right) - \\Pi^R_{-j}(\\mathbf{w}_{-j}),\n\\qquad\nG^S_j(\\mathbf{w}) = \\Pi^S_j\\!\\left(\\mathbf{p}^*(\\mathbf{w}); \\mathbf{w}\\right) - \\underline{\\pi}_j,\n$$ {#eq-nn-gft}\n\nwhere $\\Pi^R_{-j}$ is the retailer's profit when product $j$ is off the shelf and all\nremaining retail prices are **re-optimised**, and $\\underline{\\pi}_j$ is the supplier's\noutside option (normalised to zero when the retailer is its only route to market).\nThe second object is the **effective quantity response to a wholesale price**,\n\n$$\n\\Gamma_j \\equiv \\frac{d\\, q_j}{d\\, w_j}\n= \\sum_{k} \\frac{\\partial q_j}{\\partial p_k}\\,\\frac{\\partial p^*_k(\\mathbf{w})}{\\partial w_j} \\;<\\; 0,\n$$ {#eq-nn-gamma}\n\nwhich is *not* the own-price slope $\\partial q_j / \\partial p_j$: it is that slope\ncomposed with the retailer's pass-through matrix from @eq-cpt. Confusing the two is the\nmost common arithmetic error in applied bargaining work.\n\n### Assumptions {#sec-io-nn-assumptions}\n\n**Assumption 1 (Two-stage timing).** Wholesale prices are agreed in stage one; the\nretailer then sets $\\mathbf{p}$ in stage two taking $\\mathbf{w}$ as given, so realised\nprices satisfy @eq-nn-retail-foc. *Substantively:* contracts are signed before the\npricing period and are not renegotiated within it. Violated by trade deals struck\nmid-period in response to a competitor's promotion.\n\n**Assumption 2 (Nash-in-Nash / passive beliefs).** Each pair $(R, j)$ chooses $w_j$ to\nmaximise the generalised Nash product of the two sides' gains from trade, taking all\n*other* agreements $\\mathbf{w}_{-j}$ as given and unchanged:\n\n$$\nw_j^* \\;=\\; \\arg\\max_{w_j}\\;\n\\left[G^R_j(\\mathbf{w})\\right]^{\\lambda_j}\n\\left[G^S_j(\\mathbf{w})\\right]^{1-\\lambda_j},\n\\qquad \\lambda_j \\in (0,1).\n$$ {#eq-nn-objective}\n\n*Substantively:* a buyer who is renegotiating with one supplier does not infer from\nthat conversation anything about what its rivals are being offered. @collardwexler2019nash\nshow this is the limit of a non-cooperative alternating-offers game with simultaneous,\nnon-observable bilateral negotiations. Violated when a supplier can credibly threaten\nto punish the retailer in *other* categories, or when most-favoured-nation clauses link\nthe agreements.\n\n**Assumption 3 (Disagreement removes only the focal product).** If $(R,j)$ fails to\nagree, product $j$ alone leaves the shelf; every other agreement stands and the\nretailer re-optimises $\\mathbf{p}_{-j}$. *Substantively:* the threat is delisting one\nSKU or brand, not the end of the trading relationship. Violated by all-or-nothing\ncategory-captain arrangements and by settings where a breakdown triggers renegotiation\nof the surviving contracts.\n\n**Assumption 4 (Linear wholesale prices).** The transfer is $w_j q_j$ with no fixed\nfee, slotting allowance, or quantity discount. *Substantively:* the per-unit invoice\nprice is the whole contract. This is the assumption most likely to fail in grocery, and\n@sec-io-nn-failure shows what it costs.\n\n### The Estimating Equation and Its Derivation {#sec-io-nn-derivation}\n\nTake logs of @eq-nn-objective and differentiate in $w_j$:\n\n$$\n\\lambda_j\\, \\frac{\\partial G^R_j / \\partial w_j}{G^R_j}\n\\;+\\;\n(1-\\lambda_j)\\, \\frac{\\partial G^S_j / \\partial w_j}{G^S_j}\n\\;=\\; 0 .\n$$ {#eq-nn-foc}\n\nThe retailer's derivative collapses by an **envelope argument**. Total profit at the\noptimum is $\\Pi^R(\\mathbf{p}^*(\\mathbf{w}); \\mathbf{w})$, so\n\n$$\n\\frac{d}{d w_j}\\Pi^R\\!\\left(\\mathbf{p}^*(\\mathbf{w}); \\mathbf{w}\\right)\n= \\underbrace{\\sum_k \\frac{\\partial \\Pi^R}{\\partial p_k}\\frac{\\partial p^*_k}{\\partial w_j}}_{=\\,0 \\text{ by @eq-nn-retail-foc}}\n\\;+\\; \\frac{\\partial \\Pi^R}{\\partial w_j}\n\\;=\\; -\\,q_j .\n$$ {#eq-nn-envelope}\n\nEach term in the first sum vanishes because $\\mathbf{p}^*$ solves the retailer's own\nfirst-order conditions; the only surviving effect of a wholesale-price increase is the\nmechanical one, an extra dollar paid on each of the $q_j$ units already sold. Because\nthe disagreement profit $\\Pi^R_{-j}$ does not depend on $w_j$, @eq-nn-gft gives\n$\\partial G^R_j / \\partial w_j = -q_j$ exactly.\n\nThe supplier's derivative does *not* collapse, because the supplier does not choose\n$\\mathbf{p}$: writing $\\mu_j \\equiv w_j - c_j$ for the wholesale margin,\n\n$$\n\\frac{\\partial G^S_j}{\\partial w_j} = q_j + \\mu_j \\Gamma_j .\n$$ {#eq-nn-supplier-deriv}\n\nSubstituting @eq-nn-envelope and @eq-nn-supplier-deriv into @eq-nn-foc, using\n$G^S_j = \\mu_j q_j$, and solving for the margin yields the **bargaining-augmented\nmarkup equation**\n\n$$\n\\mu_j \\;=\\; w_j - c_j \\;=\\;\n\\frac{q_j}{\\;-\\Gamma_j \\;+\\; \\dfrac{\\lambda_j}{1-\\lambda_j}\\cdot\\dfrac{q_j^{\\,2}}{G^R_j}\\;} .\n$$ {#eq-nn-markup}\n\nThis single equation is the supply-side analogue of @eq-bertrand-foc for a negotiated\ninput, and it is what makes the framework empirically useful: given demand estimates\n(which deliver $q_j$ and $\\Gamma_j$) and an observed wholesale price, it maps a value\nof $\\lambda_j$ into a marginal cost $c_j$, or a known $c_j$ into a $\\lambda_j$.\n\nTwo limits confirm that @eq-nn-markup nests what the book already teaches. As\n$\\lambda_j \\to 0$ the second term in the denominator vanishes and\n$\\mu_j = q_j / (-\\Gamma_j)$, which is exactly the first-order condition of a\nmanufacturer that posts $w_j$ unilaterally and anticipates the retailer's response—the\nStackelberg channel model, with its double marginalization. As $\\lambda_j \\to 1$ the\nsecond term diverges and $\\mu_j \\to 0$, so $w_j \\to c_j$: the retailer buys at marginal\ncost and the channel replicates the vertically integrated outcome. The bargaining\nweight is the estimable parameter that interpolates between the two textbook cases.\n\nThe comparative static that drives @ellickson2026private falls straight out of\n@eq-nn-markup. Anything that raises the retailer's disagreement profit $\\Pi^R_{-j}$—a\nprivate label that keeps earning when a national brand is delisted—*lowers* $G^R_j$,\nwhich *raises* $q_j^2/G^R_j$, which *lowers* $\\mu_j$. A better outside option buys\nbetter terms on the products you still carry. This is the \"indirect\" channel the paper\nisolates, and it is invisible to any model that treats $w_j$ as a cost parameter.\n\n### Intuition {#sec-io-nn-intuition}\n\nStrip the algebra away and the bargain is a fight over a fixed pie whose *size* the\nper-unit price itself distorts. Raising $w_j$ transfers surplus to the supplier\none-for-one on the units sold (the $q_j$ term), but it also raises the retail price and\nshrinks the units (the $\\mu_j \\Gamma_j$ term), so the supplier's own gain is\nconcave in $w_j$. The retailer's loss, by contrast, is *linear* in $w_j$ at the margin,\nbecause the retailer re-optimises prices and the envelope theorem kills the second-order\neffect. Bargaining weight decides where on that trade-off the pair lands. What makes\nthe outcome estimable is that the two sides' gains from trade are *observable functions\nof the demand system*: $G^R_j$ is computable by simply re-solving the retail pricing\nproblem with product $j$ deleted, which is why credible identification of $\\lambda_j$\ndemands variation that shifts outside options rather than variation that shifts costs.\n\n### Simulation {#sec-io-nn-simulation}\n\nThe simulation below builds a channel with one retailer and two national-brand\nsuppliers, solves the Nash-in-Nash fixed point exactly, and asks three questions: does\n$\\lambda$ really interpolate between the two textbook channel models; what does an\nanalyst lose by imposing the posted-price model the book teaches when the truth is a\nnegotiation; and how does a private label change the terms on the national brands.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(35201)\nalpha <- 1.5   # price coefficient; unit mass of consumers, so profits are per-consumer\n\nshares <- function(p, delta) { v <- exp(delta - alpha * p); v / (1 + sum(v)) }\n\n# Retail stage: multiproduct-monopoly FOC, p = w + cR + Omega^{-1} q   (eq-nn-retail-foc)\nretail_prices <- function(w, delta, cR, tol = 1e-12, maxit = 1000) {\n  p <- w + cR + 1 / alpha\n  for (i in seq_len(maxit)) {\n    q  <- shares(p, delta)\n    Om <- -alpha * outer(q, q); diag(Om) <- alpha * q * (1 - q)\n    p_new <- w + cR + solve(Om, q)\n    if (max(abs(p_new - p)) < tol) { p <- p_new; break }\n    p <- 0.5 * p + 0.5 * p_new          # damped iteration\n  }\n  p\n}\nretail_profit <- function(w, delta, cR) {\n  p <- retail_prices(w, delta, cR); q <- shares(p, delta)\n  sum((p - w - cR) * q)\n}\n# Disagreement (Assumption 3): product j leaves, survivors are re-priced.\n# reoptimise = FALSE is the shortcut examined in the failure analysis below.\nretail_profit_drop <- function(j, w, delta, cR, reoptimise = TRUE) {\n  keep <- setdiff(seq_along(w), j)\n  if (reoptimise) return(retail_profit(w[keep], delta[keep], cR[keep]))\n  p <- retail_prices(w, delta, cR)\n  sum((p[keep] - w[keep] - cR[keep]) * shares(p[keep], delta[keep]))\n}\n# Gamma_j = dq_j/dw_j through retail pass-through   (eq-nn-gamma)\nGamma <- function(j, w, delta, cR, h = 1e-5) {\n  wp <- w; wp[j] <- w[j] + h; wl <- w; wl[j] <- w[j] - h\n  (shares(retail_prices(wp, delta, cR), delta)[j] -\n   shares(retail_prices(wl, delta, cR), delta)[j]) / (2 * h)\n}\n# Log-Nash-product FOC   (eq-nn-foc)\nnash_foc <- function(j, w, delta, cR, cS, lam, reoptimise = TRUE) {\n  q  <- shares(retail_prices(w, delta, cR), delta)\n  gR <- retail_profit(w, delta, cR) - retail_profit_drop(j, w, delta, cR, reoptimise)\n  mu <- w[j] - cS[j]; gS <- mu * q[j]\n  if (gR <= 1e-10 || gS <= 1e-10) return(NA_real_)\n  lam[j] * (-q[j]) / gR + (1 - lam[j]) * (q[j] + mu * Gamma(j, w, delta, cR)) / gS\n}\n# Nash-in-Nash equilibrium: solve each bilateral FOC taking w_{-j} as given (Assumption 2)\nnash_in_nash <- function(delta, cR, cS, lam, reoptimise = TRUE,\n                         fixed = NULL, w_fixed = NULL, tol = 1e-10, maxit = 400) {\n  w <- cS + 0.5\n  if (!is.null(fixed)) w[fixed] <- w_fixed\n  free <- setdiff(seq_along(w), fixed)\n  for (it in seq_len(maxit)) {\n    w_old <- w\n    for (j in free) {\n      f <- function(x) { ww <- w; ww[j] <- x; nash_foc(j, ww, delta, cR, cS, lam, reoptimise) }\n      lo <- cS[j] + 1e-4; hi <- cS[j] + 8\n      flo <- f(lo); fhi <- f(hi)\n      while ((is.na(fhi) || flo * fhi > 0) && hi > lo + 1e-3) {\n        hi <- lo + 0.6 * (hi - lo); fhi <- f(hi)\n      }\n      if (is.na(flo) || is.na(fhi) || flo * fhi > 0) next\n      w[j] <- uniroot(f, c(lo, hi), tol = 1e-12)$root\n    }\n    if (max(abs(w - w_old)) < tol) break\n  }\n  w\n}\ncons_surplus <- function(p, delta) log(1 + sum(exp(delta - alpha * p))) / alpha\n\ndelta <- c(4.0, 3.6)      # mean utilities of the two national brands\ncS    <- c(1.00, 0.90)    # supplier marginal costs\ncR    <- c(0.20, 0.20)    # retailer handling costs\n```\n:::\n\n\nThe envelope result @eq-nn-envelope is not an approximation, and it is cheap to verify\nnumerically before relying on it.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nw5 <- nash_in_nash(delta, cR, cS, rep(0.5, 2)); h <- 1e-5\nwp <- w5; wp[1] <- w5[1] + h\nwl <- w5; wl[1] <- w5[1] - h\nc(numeric = (retail_profit(wp, delta, cR) - retail_profit(wl, delta, cR)) / (2 * h),\n  minus_q = -shares(retail_prices(w5, delta, cR), delta)[1])\n#>    numeric    minus_q \n#> -0.2781481 -0.2781481\n```\n:::\n\n\n**Does $\\lambda$ interpolate between the textbook models?** @tbl-nn-lambda traces the\nequilibrium across bargaining weights, with the vertically integrated benchmark in the\nlast row.\n\n\n::: {#tbl-nn-lambda .cell layout-align=\"center\" tbl-cap='Nash-in-Nash equilibrium as the retailer\\'s bargaining weight rises. The lambda = 0.01 row reproduces the manufacturer-Stackelberg channel; the final row is the vertically integrated benchmark. Channel profit is the sum of retailer and supplier profit, and the gap between it and the integrated benchmark is the double-marginalization loss.'}\n\n```{.r .cell-code}\ntab_lambda <- do.call(rbind, lapply(c(0.01, 0.25, 0.50, 0.75, 0.99), function(L) {\n  w <- nash_in_nash(delta, cR, cS, rep(L, 2))\n  p <- retail_prices(w, delta, cR); q <- shares(p, delta)\n  data.frame(lambda = L, w_NB1 = w[1], p_NB1 = p[1],\n             pi_R = sum((p - w - cR) * q), pi_S = sum((w - cS) * q),\n             channel = sum((p - cS - cR) * q), CS = cons_surplus(p, delta))\n}))\np_vi <- retail_prices(cS, delta, cR); q_vi <- shares(p_vi, delta)\ntab_lambda <- rbind(tab_lambda,\n  data.frame(lambda = NA, w_NB1 = cS[1], p_NB1 = p_vi[1],\n             pi_R = sum((p_vi - cS - cR) * q_vi), pi_S = 0,\n             channel = sum((p_vi - cS - cR) * q_vi), CS = cons_surplus(p_vi, delta)))\nknitr::kable(round(tab_lambda, 4), align = \"r\")\n```\n\n::: {.cell-output-display}\n\n\n| lambda|  w_NB1|  p_NB1|   pi_R|   pi_S| channel|     CS|\n|------:|------:|------:|------:|------:|-------:|------:|\n|   0.01| 2.0096| 3.3332| 0.4570| 0.3977|  0.8547| 0.3480|\n|   0.25| 1.7572| 3.1876| 0.5637| 0.3351|  0.8989| 0.4085|\n|   0.50| 1.4924| 3.0471| 0.6880| 0.2411|  0.9291| 0.4727|\n|   0.75| 1.2371| 2.9224| 0.8186| 0.1259|  0.9445| 0.5340|\n|   0.99| 1.0091| 2.8193| 0.9436| 0.0051|  0.9487| 0.5879|\n|     NA| 1.0000| 2.8154| 0.9487| 0.0000|  0.9487| 0.5900|\n\n\n:::\n:::\n\n\nThe two limits derived above appear exactly. At $\\lambda = 0.01$ the wholesale price is\n2.010 and channel profit 0.855; at $\\lambda = 0.99$ the wholesale price is 1.009 against\na marginal cost of 1.00 and channel profit is 0.949, indistinguishable from the\nintegrated benchmark. Roughly 9.9% of attainable channel profit is destroyed by conduct\nalone at the manufacturer-power extreme, and consumer surplus is 41% lower there\n(0.348 versus 0.590) even though costs, preferences, and the number of products are\nidentical throughout. Channel power is not a distributional detail; it is an efficiency\nparameter.\n\n**What does imposing the posted-price model cost?** This is the comparison that\nmatters for practice, because the posted-price model is what @eq-bertrand-foc delivers\nif an analyst treats $w_j$ as an observed cost and never models the negotiation.\nInverting @eq-nn-markup at an *assumed* $\\lambda_a$ recovers a supplier marginal cost;\n@tbl-nn-misspec sets $\\lambda_a = 0$ and varies the truth.\n\n\n::: {#tbl-nn-misspec .cell layout-align=\"center\" tbl-cap='Recovering supplier marginal cost for national brand 1 under an assumed bargaining weight of zero (the posted-price channel model) when the truth is a negotiation. dp_true and dp_assumed are the retail price change predicted by the true and the misspecified model for a 25% supplier cost shock.'}\n\n```{.r .cell-code}\nrecover_c <- function(j, w, delta, cR, lam_a) {           # invert eq-nn-markup for c_j\n  q  <- shares(retail_prices(w, delta, cR), delta)[j]\n  G  <- Gamma(j, w, delta, cR)\n  gR <- retail_profit(w, delta, cR) - retail_profit_drop(j, w, delta, cR)\n  w[j] - q / (-G + (lam_a / (1 - lam_a)) * q^2 / gR)\n}\ntab_mis <- do.call(rbind, lapply(c(0.10, 0.30, 0.50, 0.70, 0.90), function(Lt) {\n  w  <- nash_in_nash(delta, cR, cS, rep(Lt, 2))\n  cS_hat <- sapply(1:2, function(j) recover_c(j, w, delta, cR, 1e-6))   # assume lambda = 0\n  shock  <- 1.25\n  p_true <- retail_prices(nash_in_nash(delta, cR, cS * shock, rep(Lt, 2)), delta, cR)[1]\n  w_base <- nash_in_nash(delta, cR, cS_hat, rep(1e-6, 2))\n  p_mis  <- retail_prices(nash_in_nash(delta, cR, cS_hat * shock, rep(1e-6, 2)), delta, cR)[1]\n  data.frame(lambda_true = Lt, c_true = cS[1], c_hat = cS_hat[1],\n             bias_pct = 100 * (cS_hat[1] - cS[1]) / cS[1],\n             dp_true = p_true - retail_prices(w, delta, cR)[1],\n             dp_assumed = p_mis - retail_prices(w_base, delta, cR)[1])\n}))\nknitr::kable(round(tab_mis, 4), align = \"r\")\n```\n\n::: {.cell-output-display}\n\n\n| lambda_true| c_true|   c_hat|  bias_pct| dp_true| dp_assumed|\n|-----------:|------:|-------:|---------:|-------:|----------:|\n|         0.1|      1|  0.8723|  -12.7670|  0.1273|     0.1068|\n|         0.3|      1|  0.6124|  -38.7623|  0.1261|     0.0691|\n|         0.5|      1|  0.3528|  -64.7249|  0.1236|     0.0367|\n|         0.7|      1|  0.1009|  -89.9098|  0.1202|     0.0096|\n|         0.9|      1| -0.1371| -113.7086|  0.1162|    -0.0127|\n\n\n:::\n\n```{.r .cell-code}\nc(RMSE_assumed_lambda0 = sqrt(mean((tab_mis$c_hat - tab_mis$c_true)^2)))\n#> RMSE_assumed_lambda0 \n#>            0.7330517\n```\n:::\n\n\nThe damage is severe and systematic. At a true $\\lambda = 0.5$ the recovered supplier\nmarginal cost is 0.353 against a truth of 1.00, a 64.7% understatement; the RMSE across\nthe grid is 0.733 on a cost of 1.00, against exactly zero when the correct $\\lambda$ is\nimposed. The mechanism is transparent from @eq-nn-markup: a negotiated wholesale price\nis *lower* than a posted one, and a model that insists the supplier was a monopolist\nmust explain the low price by attributing a low cost to the supplier. At\n$\\lambda_{\\text{true}} = 0.9$ the recovered cost is **negative** ($-0.137$), which is a\nuseful diagnostic in real work—negative implied costs in a channel study are usually\nevidence of imposed conduct that is too manufacturer-favourable, not of subsidised\nproduction.\n\nThe counterfactual columns show why this is not merely a labelling problem. For a 25%\nsupplier cost shock at $\\lambda_{\\text{true}} = 0.5$, the true model predicts national\nbrand 1's retail price rises by 0.124; the misspecified model predicts 0.037, understating\npass-through by a factor of 3.4. At $\\lambda_{\\text{true}} = 0.9$ the misspecified model\npredicts a price *decrease* of 0.013—the sign is wrong—because a 25% increase applied to\na negative recovered cost moves it further below zero. Conduct misspecification does not\nwash out of a counterfactual; it propagates through it.\n\n**What does a private label do?** @ellickson2026private decompose the retailer's gain\nfrom a private label into a direct margin effect and an indirect bargaining effect. The\ndecomposition is reproducible here by solving the three-product channel twice: once with\nthe national-brand wholesale prices frozen at their pre-entry values (direct effect only)\nand once with everything renegotiated (total effect).\n\n\n::: {#tbl-nn-privatelabel .cell layout-align=\"center\" tbl-cap='Private-label entry with national-brand bargaining weight fixed at 0.5. dw_NB1 is the change in national brand 1\\'s negotiated wholesale price relative to the no-private-label equilibrium. The indirect gain is the part of the retailer\\'s profit increase that comes from renegotiated national-brand terms rather than from the private label\\'s own margin.'}\n\n```{.r .cell-code}\nlamNB <- 0.5\nw0    <- nash_in_nash(delta, cR, cS, rep(lamNB, 2))\np0    <- retail_prices(w0, delta, cR)\nbase  <- sum((p0 - w0 - cR) * shares(p0, delta))\n\ndelta3 <- c(delta, 2.8); cS3 <- c(cS, 0.70); cR3 <- c(cR, 0.20)\ntab_pl <- do.call(rbind, lapply(c(0.30, 0.50, 0.70, 0.90), function(Lpl) {\n  lam3 <- c(lamNB, lamNB, Lpl)\n  w_d  <- nash_in_nash(delta3, cR3, cS3, lam3, fixed = 1:2, w_fixed = w0)  # NB terms frozen\n  p_d  <- retail_prices(w_d, delta3, cR3)\n  pi_d <- sum((p_d - w_d - cR3) * shares(p_d, delta3))\n  w_f  <- nash_in_nash(delta3, cR3, cS3, lam3)                            # all renegotiated\n  p_f  <- retail_prices(w_f, delta3, cR3)\n  pi_f <- sum((p_f - w_f - cR3) * shares(p_f, delta3))\n  data.frame(lambda_PL = Lpl, w_PL = w_f[3], w_NB1 = w_f[1], dw_NB1 = w_f[1] - w0[1],\n             gain_total = pi_f - base, gain_direct = pi_d - base,\n             gain_indirect = pi_f - pi_d,\n             indirect_pct = 100 * (pi_f - pi_d) / (pi_f - base))\n}))\nknitr::kable(round(tab_pl, 4), align = \"r\")\n```\n\n::: {.cell-output-display}\n\n\n| lambda_PL|   w_PL|  w_NB1|  dw_NB1| gain_total| gain_direct| gain_indirect| indirect_pct|\n|---------:|------:|------:|-------:|----------:|-----------:|-------------:|------------:|\n|       0.3| 1.2343| 1.4577| -0.0347|     0.0889|      0.0753|        0.0136|      15.2636|\n|       0.5| 1.0851| 1.4515| -0.0409|     0.1078|      0.0924|        0.0154|      14.3101|\n|       0.7| 0.9327| 1.4444| -0.0480|     0.1307|      0.1135|        0.0173|      13.2032|\n|       0.9| 0.7778| 1.4366| -0.0558|     0.1581|      0.1392|        0.0189|      11.9526|\n\n\n:::\n:::\n\n\nBoth of @ellickson2026private's headline patterns reproduce. First, entry improves the\nterms on the products the retailer still carries: national brand 1's wholesale price\nfalls by 0.041 at $\\lambda_{PL} = 0.5$, purely because the retailer now loses less when\nit threatens to delist. Second, the retailer's total gain rises monotonically in its\nbargaining position against the *private-label supplier*—from 0.089 at\n$\\lambda_{PL} = 0.30$ to 0.158 at $\\lambda_{PL} = 0.90$, a 78% difference driven entirely\nby supply-side arrangements that a demand-side analysis cannot see. The indirect channel\nis a minority of the gain but not a rounding error: 14.3% of the retailer's profit\nincrease at $\\lambda_{PL} = 0.5$, or 0.0154 on a base of 0.688. Its *share* falls as\n$\\lambda_{PL}$ rises even though its level rises, because a cheaper private label grows\nthe direct margin faster than it grows the threat value.\n\n### When the Assumptions Fail {#sec-io-nn-failure}\n\nTwo of the four assumptions are worth stress-testing, and they fail very differently.\n\n\n::: {#tbl-nn-failure .cell layout-align=\"center\" tbl-cap='Two assumption failures. Panel A: the retailer\\'s disagreement payoff computed without re-pricing the surviving products (Assumption 3 shortcut). Panel B: a share phi of the supplier\\'s rent is paid as a fixed fee rather than a per-unit margin, violating Assumption 4; the linear-wholesale-price estimator is applied anyway. True lambda is 0.5 in Panel B.'}\n\n```{.r .cell-code}\nrecover_lambda <- function(j, w, delta, cR, cS, reoptimise = TRUE) {\n  q  <- shares(retail_prices(w, delta, cR), delta)[j]\n  G  <- Gamma(j, w, delta, cR); mu <- w[j] - cS[j]\n  gR <- retail_profit(w, delta, cR) - retail_profit_drop(j, w, delta, cR, reoptimise)\n  A  <- -q / gR; B <- (q + mu * G) / (mu * q)\n  B / (B - A)\n}\npanelA <- do.call(rbind, lapply(c(0.10, 0.30, 0.50, 0.70, 0.90), function(Lt) {\n  w <- nash_in_nash(delta, cR, cS, rep(Lt, 2))\n  data.frame(panel = \"A: no re-pricing\", setting = Lt, lambda_true = Lt,\n             lambda_hat = recover_lambda(1, w, delta, cR, cS, reoptimise = FALSE))\n}))\nmu_star <- nash_in_nash(delta, cR, cS, rep(0.5, 2)) - cS\npanelB <- do.call(rbind, lapply(c(0, 0.25, 0.50, 0.75, 0.95), function(phi) {\n  w_obs <- cS + (1 - phi) * mu_star     # share phi of the rent moved into a fixed fee\n  data.frame(panel = \"B: two-part tariff\", setting = phi, lambda_true = 0.5,\n             lambda_hat = recover_lambda(1, w_obs, delta, cR, cS))\n}))\nout <- rbind(panelA, panelB)\nout$bias <- out$lambda_hat - out$lambda_true\nout[, 2:5] <- round(out[, 2:5], 4)\nknitr::kable(out, align = \"r\", row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|              panel| setting| lambda_true| lambda_hat|   bias|\n|------------------:|-------:|-----------:|----------:|------:|\n|   A: no re-pricing|    0.10|         0.1|     0.1036| 0.0036|\n|   A: no re-pricing|    0.30|         0.3|     0.3108| 0.0108|\n|   A: no re-pricing|    0.50|         0.5|     0.5158| 0.0158|\n|   A: no re-pricing|    0.70|         0.7|     0.7158| 0.0158|\n|   A: no re-pricing|    0.90|         0.9|     0.9078| 0.0078|\n| B: two-part tariff|    0.00|         0.5|     0.5000| 0.0000|\n| B: two-part tariff|    0.25|         0.5|     0.6188| 0.1188|\n| B: two-part tariff|    0.50|         0.5|     0.7409| 0.2409|\n| B: two-part tariff|    0.75|         0.5|     0.8674| 0.3674|\n| B: two-part tariff|    0.95|         0.5|     0.9729| 0.4729|\n\n\n:::\n\n```{.r .cell-code}\nc(RMSE_panelA = sqrt(mean((panelA$lambda_hat - panelA$lambda_true)^2)),\n  RMSE_panelB = sqrt(mean((panelB$lambda_hat - panelB$lambda_true)^2)))\n#> RMSE_panelA RMSE_panelB \n#>  0.01171374  0.29353274\n```\n:::\n\n\n**Assumption 3 bends.** Computing $\\Pi^R_{-j}$ without re-pricing the survivors—a\nshortcut that saves one equilibrium solve per negotiation and is common in applied\ncode—biases $\\hat\\lambda$ upward by 0.004 to 0.016, an RMSE of 0.0117 on a parameter\nbounded in $[0,1]$. The direction is predictable: skipping the re-optimisation\nunderstates the disagreement profit, overstates the retailer's gains from trade, and so\nattributes more of the observed wholesale discount to retailer power. The magnitude is\nsmall enough that the shortcut is defensible in a first pass and indefensible in a\npublished estimate.\n\n**Assumption 4 breaks.** Moving the supplier's rent from a per-unit margin into a fixed\nfee leaves the *total* transfer and the split of surplus untouched, but drives the\nobserved per-unit price toward marginal cost. The linear-wholesale-price estimator reads\nthat as retailer power and nothing else: at $\\phi = 0.95$ it returns\n$\\hat\\lambda = 0.973$ against a truth of 0.5, a bias of 0.473 on a $[0,1]$ parameter, and\nin the limit $\\phi \\to 1$ it returns $\\hat\\lambda \\to 1$ for *every* true split. This is\nnot a precision problem that more data fixes—it is a failure of identification, and it is\nwhy credible applications either observe contract terms directly or argue explicitly that\nlinear pricing describes the institution.\n\n**What the simulation demonstrates:** the bargaining weight is the parameter that decides\nwhether a channel behaves like a Stackelberg manufacturer or a vertically integrated\nfirm; imposing the former when the truth lies between them understates supplier marginal\ncosts by up to 114%—far enough to drive the recovered cost below zero—and gets the sign\nof a cost-shock counterfactual wrong; a private\nlabel raises retailer profit both directly and by cheapening the national brands the\nretailer still stocks; and the whole apparatus rests on linear pricing, which is the one\nassumption whose failure destroys identification rather than merely degrading precision.\n\n### Replication and Practical Guidance {#sec-io-nn-practice}\n\n**Replication.** @ellickson2026private's estimates cannot be reproduced here. The paper\ncombines retailer scanner data with proprietary information on the *identity* of\nprivate-label manufacturers—the feature that lets it measure disagreement payoffs\ndirectly—and neither input is public. The simulation above reproduces the paper's\nqualitative decomposition and comparative statics on synthetic data; the magnitudes are\nnot comparable to its published tables and should not be read as such.\n@draganska2010larger use commercially available German coffee scanner data and report\nbargaining weights that vary substantially across manufacturer–retailer pairs, which is\nthe closest public-data analogue.\n\n**Estimation in practice.** The pipeline is nested three deep: a retail-equilibrium\nsolve (@eq-nn-retail-foc) inside a bargaining fixed point (@eq-nn-foc) inside the GMM\nobjective that also estimates demand. Cost grows with the number of *negotiations*\nrather than products, because every $G^R_j$ requires an additional retail solve with\nproduct $j$ deleted—so a category with 40 SKUs from 12 suppliers needs 13 equilibrium\nsolves per bargaining iteration, not 41. Estimate demand first and hold it fixed;\nthere is no R package for the supply side, so the bargaining solver is written by hand\n(the ~60 lines above are the whole method), while demand estimation goes through\n`PyBLP` in Python or a hand-rolled GMM routine in R.\n\n**Identification.** $\\lambda_j$ and $c_j$ are not separately identified from a single\ncross-section of wholesale prices: @eq-nn-markup is one equation in two unknowns per\nproduct. Applications break the tie with variation that shifts *disagreement payoffs*\nwhile holding costs fixed—@ellickson2026private uses a patent expiry that coincided with\nprivate-label entry, @grennan2013price uses staggered adoption of a competing medical\ndevice, @crawford2012welfare uses channel carriage disputes. Cost-shifting instruments,\nthe workhorse of @sec-io-berry, are the wrong instrument here: they identify demand, not\nconduct.\n\n**Pitfalls.**\n\n1. **Using $\\partial q_j/\\partial p_j$ where @eq-nn-gamma calls for $\\Gamma_j$.** The\n   correct object composes the demand slope with retail pass-through and is\n   substantially smaller in magnitude; substituting the raw slope inflates the implied\n   supplier markup.\n2. **Fixed fees and slotting allowances.** See @sec-io-nn-failure. If the institution\n   uses two-part tariffs, the per-unit price is close to marginal cost by construction\n   and carries almost no information about the split.\n3. **Treating a private label as just another product.** Its effect on the shelf runs\n   through the *threat point*, not only through substitution. A demand-side model that\n   adds a product and holds $\\mathbf{w}$ fixed recovers 86% of the retailer's gain in\n   @tbl-nn-privatelabel and misses the rest entirely.\n4. **Reading $\\lambda_j$ as a preference or a personality.** It is a reduced-form summary\n   of an unmodelled negotiation protocol. @collardwexler2019nash show it maps to the\n   probability of making the offer in an alternating-offers game, which means it can\n   shift with the institutional environment and should not be held fixed across a\n   counterfactual that changes that environment.\n\n## Structural Applications in Marketing {#sec-io-applications}\n\nThe discrete-choice and dynamic-pricing apparatus underwrites a body of empirical\nmarketing work that estimates structural primitives and runs managerial\ncounterfactuals. Four applications illustrate the range.\n\n**Dynamic pricing of new products.** @cosguner2022dynamic confront a limitation of the\nGeneralized Bass Model (GBM): although the Bass diffusion model is the standard new-\nproduct sales forecaster, the GBM extension responds only to *percentage* changes in\nmarketing variables, not their levels, so it cannot prescribe an optimal *launch\nprice*. The authors propose utility-based generalizations—the Bass–Gumbel and\nBass–Logit diffusion models (BGDM, BLDM)—that ground diffusion in discrete choice and\ntherefore prescribe both the launch price and the post-launch price path. Across four\nproduct categories both models outperform the GBM in predicting new-product sales, the\npaper supplies methods to estimate them when no prior sales data exist, contrasts the\nBLDM's optimal pricing policy with the GBM's across parameter ranges, and offers a\ncomputationally light routine—extensible to competitive, multiproduct settings—for\nmanagers to set dynamic pricing and advertising.\n\n**Behavioral price discrimination in channels.** @cosguner2017behavioral study\nbehavioral price discrimination (BPD) when consumers face switching costs, so price\nelasticity varies *over time* and not only across customers as in prior work. Estimating\na dynamic pricing model on cola-category data, they find that retailers profit more by\n*delegating* coupon customization and data analytics to manufacturers than by managing\ncoupons themselves, that retailers can profit substantially by selling their customer\ndatabases to manufacturers, and that—despite gaining data access—manufacturers earn\n*lower* profits, evidence that customer information confers channel power on the\nretailer. Strikingly, conditioning BPD on only the *most recent* purchase is a simple,\ncheap policy that materially shifts profitability, so customer information drives channel\ndynamics even when used coarsely.\n\n**Email contact policy.** @zhang2017dynamically address an understudied but profitable\nchannel by modeling customer email-open behavior jointly with purchases in a unified\nhidden-Markov and copula framework, using data from a U.S. home-improvement retailer.\nTwo findings matter for practice: active email readers are not necessarily active\nbuyers (and vice versa), and email *volume* affects short- and long-run profitability\n*non-linearly*. Their decision-support system locates an interior optimum—around seven\nemails—where deviating is costly: sending four rather than seven loses about 32% of\nper-customer lifetime profit, and sending ten loses about 16%. Over- and under-\ncommunicating both destroy value, so frequency must be tuned, not maximized.\n\n**Online word of mouth and sales.** @chintagunta2010effects estimate the effect of\nnationwide online user reviews on *local* box-office performance at the\ndesignated-market-area (DMA) level, confronting three identification threats: spatial\naggregation across heterogeneous markets, serial correlation from staged film rollout,\nand other unobserved serial correlation. Using daily ticket sales for 148 of 874 films\nover 16 months with Yahoo! Movies ratings, and instrumenting ratings with the staged\nrelease across markets, they find that review **valence** (sentiment), not volume,\ndrives local sales—reversing the volume-dominates conclusion of studies that use\n*aggregated national* data, which their disaggregated design shows to be an artifact of\naggregation. The rollout-based instrument for review endogeneity generalizes to any\nindustry with sequential product releases.\n\nThese applications share a structural logic that distinguishes IO-style marketing from\nreduced-form analysis: each estimates preference and cost primitives that are invariant\nto the policy being studied, then re-solves the model under the counterfactual—a new\nprice path, a different coupon regime, an altered email cadence, a changed information\nenvironment—to compute the managerially relevant outcome.\n\n## Key Takeaways\n\n- Industrial organization supplies the structural primitives—demand systems,\n  equilibrium concepts, and identification arguments—that let an analyst run policy\n  counterfactuals, in contrast to reduced-form analytics that describe correlations.\n- The classical, continuous-quantity approach yields the Slutsky/Roy machinery, the CES\n  and quasi-linear special cases, and clean diversion ratios (@eq-diversion); its\n  symmetry of cross-effects (@eq-slutsky) is the empirical fingerprint of utility\n  maximization, and the homothetic-surplus family of @armstrong2018multiproduct makes\n  multiproduct pricing tractable by reducing it to a composite-price problem.\n- Vertical differentiation makes quality explicit in demand (@eq-vertical-demand1) and\n  shows why a multiproduct firm spaces its quality tiers apart to soften internal\n  competition.\n- Discrete-choice models recover the full elasticity matrix from a few preference\n  parameters and predict demand for new products, but the multinomial logit's IIA\n  restriction (@eq-35-iia) forces unrealistic substitution, motivating random coefficients,\n  nested logit, and probit.\n- Price endogeneity from unobserved characteristics is the central estimation obstacle;\n  @berry1994estimating solves it by inverting market shares to recover mean utilities\n  (@eq-blp-mean-utility) that are linear in the demand error and amenable to\n  instrumental variables.\n- Zero-valued market shares break the share inversion and, when driven by selection on\n  unobservables, bias the drop-zero estimator severely; the pairwise-difference GMM of\n  @dube2021random (@eq-dube-pdwgmm) restores consistency by differencing out the\n  selection function.\n- Structural marketing applications—dynamic new-product pricing, behavioral price\n  discrimination in channels, email contact policy, and online word of mouth—estimate\n  policy-invariant primitives and re-solve the model under counterfactuals to answer\n  managerial questions.\n\n## Further Reading\n\nThe structural-econometrics toolkit underlying this chapter—GMM, simulation estimation,\nand the marketing–finance event-study machinery—is developed in @sec-marketing-finance.\nThe classical demand foundations connect to the welfare and pricing material throughout\nthe pricing chapters; the discrete-choice estimators here are the demand-side complement\nto the supply-side conduct models. For the homothetic-surplus characterization and its\npricing implications see @armstrong2018multiproduct; for the canonical share-inversion\nestimator and its equilibrium extensions, @berry1994estimating, @berry1995,\n@berry1995automobile, and @berry2004differentiated; for the choice-theoretic foundations\nof market research, @mcfadden1986choice and @mcfadden1986method; and for the frontier\ntreatment of zero shares and platform competition, @dube2021random and @tan2021effects.\nThe structural marketing applications—@cosguner2022dynamic, @cosguner2017behavioral,\n@zhang2017dynamically, and @chintagunta2010effects—are entry points to the empirical\nliterature that puts these models to work.\n\n## Full-semester seminar reading map {#sec-io-seminar-reading-map}\n\nThe discrete-choice and structural material developed above is, in most doctoral\nprograms, only the first movement of a full-semester sequence in structural\neconometrics / empirical industrial organization (EIO). This section appends a\n13–14 week seminar reading map that situates the chapter's BLP-style demand model\ninside the broader EIO pipeline—demand, then supply and conduct, then\ncounterfactuals, taught first for static markets and then again for dynamic ones.\nEvery reading carries a Crossref-verified version-of-record DOI (copied verbatim from\nthe source syllabus, verified 2026-06-21); where a work has no entry in this book's\nbibliography it is named in full rather than cited by key. Foundational canon is marked\n**[F]** and frontier / actively-contested methods **[R]**.\n\n### The semester arc {#sec-io-semester-arc}\n\nThe structural-IO seminar is organized as a single methodological pipeline taught\ntwice—once for *static* markets and once for *dynamic* ones. The spine is the\ndemand–supply equilibrium model of a differentiated-products oligopoly: students first\nlearn to estimate **demand** for differentiated products (logit, nested logit, and the\nrandom-coefficients/BLP workhorse), then to layer a **supply side** (Bertrand–Nash\npricing, markups, conduct) on top, and finally to use the estimated structural\nparameters to run **counterfactuals** (mergers, new goods, price regulation, taxes).\nThis static arc—roughly the first half of the term—is where the field's identification\narguments, instruments, and estimation algorithms (GMM, the BLP nested fixed point, and\nMPEC) are taught most carefully, because every later model reuses them.\n\nThe second half generalizes the same logic to settings where agents are\n**forward-looking**. Consumers become dynamic when goods are durable or storable; firms\nbecome dynamic when they invest, enter, or exit. The methodological payload here is\n**dynamic discrete choice**—Rust's nested fixed point and the conditional-choice-\nprobability (CCP) shortcut of Hotz–Miller—extended to dynamic games via two-step\nestimators. The seminar then surveys the major application areas that have organized the\nfield's recent agenda: entry and market structure, auctions, two-sided/platform markets,\nand consumer search and consideration. The term typically closes on the active frontier\nwhere machine learning meets structural estimation (heterogeneous treatment effects,\ntext-as-data, high-dimensional demand) and on a recurring debate that runs through the\nwhole course: structural vs. reduced-form / \"credible\" design-based inference.\nPedagogically, most programs intertwine three threads every week: the economic *model*\nand its equilibrium concept; the *econometrics* of what is identified, from what\nvariation, under what exclusion restrictions; and *computation*—students are expected to\ncode estimators (increasingly in Python with PyBLP, or in Julia/MATLAB) and replicate a\ncanonical paper. The marketing version of the seminar leans harder on individual-level\nscanner/CRM data, consumer heterogeneity, micro-moments, and managerial counterfactuals\nthan the economics version, which leans toward antitrust and policy.\n\n### Week 1 — Foundations: the structural approach and the modeling cycle {#sec-io-week01}\n\n**Topic:** What the structural approach buys and what it costs, and the demand–supply–\ncounterfactual loop that organizes the rest of the term.\n\n**Subtopics:** What \"structural\" buys you (welfare, counterfactuals, extrapolation) vs.\nits costs (assumptions, computation); the demand–supply–counterfactual loop; the\nstructural vs. reduced-form debate.\n\n**Methods:** Reading a structural paper; mapping primitives → estimating equations →\ncounterfactual.\n\n**Key readings:**\n\n- **[F]** @berry1994discretechoice — Berry, S. (1994), \"Estimating Discrete-Choice Models\n  of Product Differentiation,\" *RAND Journal of Economics* 25(2): 242–262.\n  [doi:10.2307/2555829](https://doi.org/10.2307/2555829). The mean-utility inversion that\n  makes aggregate differentiated-products demand estimable—the conceptual on-ramp to the\n  whole field.\n- **[F]** Nevo, A. (2000), \"A Practitioner's Guide to Estimation of Random-Coefficients\n  Logit Models of Demand,\" *Journal of Economics & Management Strategy* 9(4): 513–548.\n  [doi:10.1162/105864000567954](https://doi.org/10.1162/105864000567954). The teaching\n  reference that turns BLP into runnable code; a near-universal Week 1–3 reading.\n\n**Debate:** When are structural assumptions worth their cost vs. a clean natural\nexperiment?\n\n### Week 2 — Discrete-choice demand I: logit and nested logit {#sec-io-week02}\n\n**Topic:** Random-utility demand and the substitution patterns that logit and nested\nlogit can and cannot represent.\n\n**Subtopics:** Random utility; IIA and its failures; the logit \"red bus/blue bus\"\nproblem; nested logit and the substitution-pattern fix; aggregate vs. individual data.\n\n**Methods:** Deriving choice probabilities; computing own- and cross-price elasticities;\nhandling the \"outside good.\"\n\n**Key readings:**\n\n- **[F]** @berry1994estimating — Berry, S. (1994), *RAND J. Econ.* 25(2): 242–262.\n  [doi:10.2307/2555829](https://doi.org/10.2307/2555829). (Re-used) the mean-utility\n  inversion specializes cleanly to logit and nested logit.\n\n**Debate:** Is IIA an acceptable approximation, or does it doom logit for policy work?\n\n### Week 3 — Discrete-choice demand II: random coefficients / BLP {#sec-io-week03}\n\n**Topic:** The random-coefficients demand-and-supply workhorse and the endogeneity\nproblem it solves.\n\n**Subtopics:** Unobserved product characteristics (ξ) and price endogeneity; random\ncoefficients for flexible substitution; the contraction mapping; BLP instruments.\n\n**Methods:** GMM with the BLP nested fixed point; constructing demand-side instruments;\nmicro-moments.\n\n**Key readings:**\n\n- **[F]** @berry1995automobile — Berry, S., Levinsohn, J., & Pakes, A. (1995),\n  \"Automobile Prices in Market Equilibrium,\" *Econometrica* 63(4): 841–890.\n  [doi:10.2307/2171802](https://doi.org/10.2307/2171802). The foundational\n  random-coefficients demand-and-supply paper; the workhorse of the field.\n- **[F]** Nevo, A. (2001), \"Measuring Market Power in the Ready-to-Eat Cereal Industry,\"\n  *Econometrica* 69(2): 307–342.\n  [doi:10.1111/1468-0262.00194](https://doi.org/10.1111/1468-0262.00194). The canonical\n  applied BLP study; introduces brand-specific intercepts and panel structure to control\n  for ξ.\n- **[R]** @berry2004differentiated — Berry, S., Levinsohn, J., & Pakes, A. (2004),\n  \"Differentiated Products Demand Systems from a Combination of Micro and Macro Data: The\n  New Car Market,\" *Journal of Political Economy* 112(1): 68–105.\n  [doi:10.1086/379939](https://doi.org/10.1086/379939). Shows how consumer-level\n  micro-moments sharpen identification of heterogeneity; the template for modern marketing\n  applications.\n\n**Debate:** What variation actually identifies the random coefficients, and how fragile\nis it to weak instruments?\n\n### Week 4 — Identification & instruments in demand estimation {#sec-io-week04}\n\n**Topic:** What differentiated-products demand identifies nonparametrically, and which\ninstruments deliver it.\n\n**Subtopics:** Price endogeneity; cost-shifters, Hausman, and BLP-type instruments;\nnonparametric identification of demand; instrument relevance and validity.\n\n**Methods:** Exclusion restrictions; testing instrument strength; the \"connected\nsubstitutes\" condition.\n\n**Key readings:**\n\n- **[R]** Berry, S. & Haile, P. (2014), \"Identification in Differentiated Products Markets\n  Using Market Level Data,\" *Econometrica* 82(5): 1749–1797.\n  [doi:10.3982/ECTA9027](https://doi.org/10.3982/ECTA9027). Establishes nonparametric\n  identification of differentiated-products demand and supply; reframes BLP's parametric\n  choices as identification, not just estimation.\n\n**Debate:** Are the standard instruments (rival characteristics, cost shifters) credible,\nand what do they identify nonparametrically?\n\n### Week 5 — Estimation & computation: GMM, NFP, and MPEC {#sec-io-week05}\n\n**Topic:** How the BLP estimator is actually computed, and how much numerical choices move\npublished results.\n\n**Subtopics:** GMM objective and weighting; the nested fixed-point (NFP) algorithm; MPEC\n(constrained optimization) as an alternative; numerical pitfalls (tight inner loops,\nlocal minima); modern software.\n\n**Methods:** Coding the contraction; MPEC vs. NFP; optimal instruments; supply-side\nmoments; PyBLP.\n\n**Key readings:**\n\n- **[R]** Dubé, J.-P., Fox, J. T., & Su, C.-L. (2012), \"Improving the Numerical\n  Performance of Static and Dynamic Aggregate Discrete Choice Random Coefficients Demand\n  Estimation,\" *Econometrica* 80(5): 2231–2267.\n  [doi:10.3982/ecta8585](https://doi.org/10.3982/ecta8585). Reformulates BLP estimation as\n  MPEC, showing the NFP inner-loop tolerance can bias estimates; reshaped how the field\n  computes BLP.\n- **[R]** @conlon2020 — Conlon, C. & Gortmaker, J. (2020), \"Best Practices for\n  Differentiated Products Demand Estimation with PyBLP,\" *RAND Journal of Economics* 51(4):\n  1108–1161. [doi:10.1111/1756-2171.12352](https://doi.org/10.1111/1756-2171.12352). The\n  current computational standard and the software most students now use; consolidates two\n  decades of practical lessons.\n\n**Debate:** How much do numerical choices (tolerances, optimizers, starting values) drive\npublished BLP results?\n\n### Week 6 — Supply, conduct, and markups {#sec-io-week06}\n\n**Topic:** Adding the supply side—recovering marginal costs and markups, and testing how\nfirms compete.\n\n**Subtopics:** Bertrand–Nash pricing with differentiated products; recovering marginal\ncosts from the first-order conditions; testing conduct (Cournot vs. Bertrand vs.\ncollusion); identification of the conduct parameter.\n\n**Methods:** Inverting FOCs for markups/marginal costs; ownership matrices; conduct\ntests.\n\n**Key readings:**\n\n- **[F]** Bresnahan, T. F. (1982), \"The Oligopoly Solution Concept Is Identified,\"\n  *Economics Letters* 10(1–2): 87–92.\n  [doi:10.1016/0165-1765(82)90121-5](https://doi.org/10.1016/0165-1765(82)90121-5). The\n  original result that demand rotations identify the conduct parameter; foundation of the\n  \"new empirical IO.\"\n- **[F]** Nevo, A. (1998), \"Identification of the Oligopoly Solution Concept in a\n  Differentiated-Products Industry,\" *Economics Letters* 59(3): 391–395.\n  [doi:10.1016/s0165-1765(98)00061-5](https://doi.org/10.1016/s0165-1765(98)00061-5).\n  Extends conduct identification to differentiated products; the bridge from Bresnahan to\n  BLP-style supply.\n- **[F]** Nevo, A. (2001), *Econometrica* 69(2): 307–342.\n  [doi:10.1111/1468-0262.00194](https://doi.org/10.1111/1468-0262.00194). (Re-used)\n  recovers cereal markups and decomposes them into cost, markup, and portfolio effects.\n\n**Debate:** Can conduct be credibly tested, or must it be assumed? (the \"testing vs.\ncalibrating conduct\" problem)\n\n### Week 7 — Counterfactuals & merger / policy simulation {#sec-io-week07}\n\n**Topic:** Using estimated demand and supply to recompute equilibria under mergers, new\ngoods, and policy changes.\n\n**Subtopics:** Recomputing equilibrium prices under new ownership (mergers), new goods,\ntaxes/regulation; welfare and consumer surplus from logit/BLP; passthrough; the role of\nsupply-side assumptions in counterfactuals.\n\n**Methods:** Solving for post-merger equilibrium; computing compensating variation;\nsensitivity of counterfactuals to conduct.\n\n**Key readings:**\n\n- **[F]** Nevo, A. (2000), *J. Econ. & Mgmt. Strategy* 9(4): 513–548.\n  [doi:10.1162/105864000567954](https://doi.org/10.1162/105864000567954). (Re-used) lays\n  out the merger-simulation mechanics that follow directly from estimated demand and FOCs.\n- **[F]** @petrin2002minivan — Petrin, A. (2002), \"Quantifying the Benefits of New\n  Products: The Case of the Minivan,\" *Journal of Political Economy* 110(4): 705–729.\n  [doi:10.1086/340779](https://doi.org/10.1086/340779). The canonical \"value of a new good\"\n  counterfactual; shows how micro-data discipline the welfare numbers.\n\n**Debate:** How much do counterfactuals depend on un-tested supply assumptions and\nout-of-sample extrapolation?\n\n### Week 8 — Dynamic demand: durable and storable goods {#sec-io-week08}\n\n**Topic:** Forward-looking consumers and the bias from ignoring durability or\nstockpiling.\n\n**Subtopics:** Forward-looking consumers; the durable-goods problem (Coase) and\nintertemporal price discrimination; stockpiling and storable goods; dynamic demand\nestimation.\n\n**Methods:** Solving consumer dynamic programs; integrating dynamics into BLP-style\ndemand; managing the state space.\n\n**Key readings:**\n\n- **[R]** Gowrisankaran, G. & Rysman, M. (2012), \"Dynamics of Consumer Demand for New\n  Durable Goods,\" *Journal of Political Economy* 120(6): 1173–1219.\n  [doi:10.1086/669540](https://doi.org/10.1086/669540). The workhorse framework for\n  estimating dynamic demand for durables (digital camcorders); falling prices and\n  forward-looking buyers.\n- **[R]** Hendel, I. & Nevo, A. (2006), \"Measuring the Implications of Sales and Consumer\n  Inventory Behavior,\" *Econometrica* 74(6): 1637–1673.\n  [doi:10.1111/j.1468-0262.2006.00721.x](https://doi.org/10.1111/j.1468-0262.2006.00721.x).\n  Shows how ignoring consumer stockpiling biases demand elasticities; the canonical\n  storable-goods paper.\n- **[R]** Nair, H. (2007), \"Intertemporal Price Discrimination with Forward-Looking\n  Consumers: Application to the US Market for Console Video-Games,\" *Quantitative Marketing\n  and Economics* 5(3): 239–292.\n  [doi:10.1007/s11129-007-9026-4](https://doi.org/10.1007/s11129-007-9026-4). The\n  marketing-canon dynamic-demand application; links forward-looking demand to optimal\n  dynamic pricing.\n\n**Debate:** How to handle expectations about future prices/products without overfitting\nthe dynamics?\n\n### Week 9 — Dynamic discrete choice: Rust and CCP {#sec-io-week09}\n\n**Topic:** Single-agent dynamic programming and the two-step shortcut that makes it\nestimable.\n\n**Subtopics:** Single-agent dynamic programming; the nested fixed-point (Rust) estimator;\nconditional-choice-probability (Hotz–Miller) inversion; finite dependence; the curse of\ndimensionality.\n\n**Methods:** Value-function iteration; CCP estimation; simulation of dynamic programs.\n\n**Key readings:**\n\n- **[F]** Rust, J. (1987), \"Optimal Replacement of GMC Bus Engines: An Empirical Model of\n  Harold Zurcher,\" *Econometrica* 55(5): 999–1033.\n  [doi:10.2307/1911259](https://doi.org/10.2307/1911259). The foundational single-agent\n  dynamic discrete-choice model and nested fixed-point estimator.\n- **[F]** Hotz, V. J. & Miller, R. A. (1993), \"Conditional Choice Probabilities and the\n  Estimation of Dynamic Models,\" *Review of Economic Studies* 60(3): 497–529.\n  [doi:10.2307/2298122](https://doi.org/10.2307/2298122). The CCP inversion that avoids the\n  full dynamic-programming solution; the basis for all modern two-step dynamic estimators.\n- **[R]** Aguirregabiria, V. & Mira, P. (2010), \"Dynamic Discrete Choice Structural\n  Models: A Survey,\" *Journal of Econometrics* 156(1): 38–67.\n  [doi:10.1016/j.jeconom.2009.09.007](https://doi.org/10.1016/j.jeconom.2009.09.007). The\n  standard survey tying NFP, CCP, and two-step methods together; the module's roadmap.\n\n**Debate:** NFP (full solution) vs. CCP (two-step)—efficiency vs. tractability and\nrobustness.\n\n### Week 10 — Dynamic games: entry, exit, and investment {#sec-io-week10}\n\n**Topic:** Extending dynamic discrete choice to oligopoly games with strategic\ninteraction.\n\n**Subtopics:** Markov-perfect equilibrium; the Ericson–Pakes framework; two-step\nestimators for dynamic games; multiplicity of equilibria.\n\n**Methods:** Estimating policy functions; forward simulation; handling equilibrium\nmultiplicity.\n\n**Key readings:**\n\n- **[R]** Bajari, P., Benkard, C. L., & Levin, J. (2007), \"Estimating Dynamic Models of\n  Imperfect Competition,\" *Econometrica* 75(5): 1331–1370.\n  [doi:10.1111/j.1468-0262.2007.00796.x](https://doi.org/10.1111/j.1468-0262.2007.00796.x).\n  The general two-step (BBL) estimator for dynamic oligopoly games; a foundational frontier\n  method.\n- **[R]** Pakes, A., Ostrovsky, M., & Berry, S. (2007), \"Simple Estimators for the\n  Parameters of Discrete Dynamic Games (with Entry/Exit Examples),\" *RAND Journal of\n  Economics* 38(2): 373–399.\n  [doi:10.1111/j.1756-2171.2007.tb00073.x](https://doi.org/10.1111/j.1756-2171.2007.tb00073.x).\n  A tractable moment-based estimator for entry/exit games; widely taught alongside BBL.\n- **[R]** Aguirregabiria, V. & Mira, P. (2007), \"Sequential Estimation of Dynamic Discrete\n  Games,\" *Econometrica* 75(1): 1–53.\n  [doi:10.1111/j.1468-0262.2007.00731.x](https://doi.org/10.1111/j.1468-0262.2007.00731.x).\n  The nested pseudo-likelihood (NPL) estimator for dynamic games; the third pillar of the\n  estimation toolkit.\n\n**Debate:** How to estimate games with multiple equilibria, and how credible are the\nMarkov/MPE assumptions?\n\n### Week 11 — Static entry and market structure {#sec-io-week11}\n\n**Topic:** What entry patterns alone reveal about competition when prices and quantities\nare unobserved.\n\n**Subtopics:** Entry as a revealed-preference inequality; ordered/sequential entry; what\nentry thresholds reveal about competition and fixed costs; market structure without\nprice/quantity data.\n\n**Methods:** Estimating entry models from count/threshold data; inequality-based\ninference; identifying fixed costs.\n\n**Key readings:**\n\n- **[F]** Bresnahan, T. F. & Reiss, P. C. (1991), \"Entry and Competition in Concentrated\n  Markets,\" *Journal of Political Economy* 99(5): 977–1009.\n  [doi:10.1086/261786](https://doi.org/10.1086/261786). The foundational entry-threshold\n  approach: how the number of firms a market supports reveals competitive conduct.\n- **[F]** Bresnahan, T. F. & Reiss, P. C. (1990), \"Entry in Monopoly Markets,\" *Review of\n  Economic Studies* 57(4): 531–553.\n  [doi:10.2307/2298085](https://doi.org/10.2307/2298085). The companion paper formalizing\n  entry decisions in small isolated markets; the empirical setup students replicate.\n\n**Debate:** What can entry patterns identify about competition when prices and quantities\nare unobserved?\n\n### Week 12 — Auctions {#sec-io-week12}\n\n**Topic:** Structural inversion from observed bids to the underlying distribution of\nbidder valuations.\n\n**Subtopics:** First-price sealed-bid auctions and the equilibrium bid function;\nstructural inversion from bids to valuations; nonparametric identification; private vs.\ncommon values; risk aversion.\n\n**Methods:** Inverting the bid function; kernel estimation of bid densities; testing for\ncommon values.\n\n**Key readings:**\n\n- **[F]** Guerre, E., Perrigne, I., & Vuong, Q. (2000), \"Optimal Nonparametric Estimation\n  of First-Price Auctions,\" *Econometrica* 68(3): 525–574.\n  [doi:10.1111/1468-0262.00123](https://doi.org/10.1111/1468-0262.00123). The GPV two-step\n  nonparametric estimator that recovers the value distribution from observed bids; the\n  canonical structural-auctions paper.\n- **[R]** Campo, S., Guerre, E., Perrigne, I., & Vuong, Q. (2011), \"Semiparametric\n  Estimation of First-Price Auctions with Risk-Averse Bidders,\" *Review of Economic\n  Studies* 78(1): 112–147.\n  [doi:10.1093/restud/rdq001](https://doi.org/10.1093/restud/rdq001). Extends GPV to\n  risk-averse bidders and the identification of preferences; the frontier reading for the\n  module.\n\n**Debate:** Private vs. common values and the limits of identification from bid data\nalone.\n\n### Week 13 — Two-sided markets and platforms {#sec-io-week13}\n\n**Topic:** Structural estimation of indirect network effects and platform pricing across\ntwo customer groups.\n\n**Subtopics:** Network effects across two customer groups; platform pricing and the\n\"see-saw\"; vertical integration and exclusivity; structural estimation of indirect\nnetwork effects.\n\n**Methods:** Estimating cross-side externalities; modeling adoption on both sides;\nplatform counterfactuals.\n\n**Key readings:**\n\n- **[F]** Rysman, M. (2004), \"Competition Between Networks: A Study of the Market for\n  Yellow Pages,\" *Review of Economic Studies* 71(2): 483–512.\n  [doi:10.1111/0034-6527.00512](https://doi.org/10.1111/0034-6527.00512). The foundational\n  structural estimation of a two-sided market with indirect network effects.\n- **[R]** Lee, R. S. (2013), \"Vertical Integration and Exclusivity in Platform and\n  Two-Sided Markets,\" *American Economic Review* 103(7): 2960–3000.\n  [doi:10.1257/aer.103.7.2960](https://doi.org/10.1257/aer.103.7.2960). A structural model\n  of platform competition (video-game consoles) with exclusive content; the modern\n  platform-IO template.\n\n**Debate:** Identifying network effects vs. unobserved quality, and the welfare effects of\nplatform exclusivity.\n\n### Week 14 — Consumer search & consideration; ML + structural; synthesis {#sec-io-week14}\n\n**Topic:** Limited demand from search and inattention, and where machine learning\ncomplements or substitutes for economic structure.\n\n**Subtopics:** Sequential vs. simultaneous search; consideration sets vs. full-information\ndemand; search/switching costs; machine learning for high-dimensional demand,\nheterogeneity, and unstructured data; the structural-vs-design-based debate revisited.\n\n**Methods:** Estimating search models; consideration-set inference; integrating ML\npredictors and heterogeneity into structural objectives.\n\n**Key readings:**\n\n- **[R]** De los Santos, B., Hortaçsu, A., & Wildenbeest, M. R. (2012), \"Testing Models of\n  Consumer Search Using Data on Web Browsing and Purchasing Behavior,\" *American Economic\n  Review* 102(6): 2955–2980.\n  [doi:10.1257/aer.102.6.2955](https://doi.org/10.1257/aer.102.6.2955). Uses clickstream\n  data to discriminate between sequential and fixed-sample search; the canonical empirical\n  search paper.\n- **[R]** Honka, E. (2014), \"Quantifying Search and Switching Costs in the US Auto\n  Insurance Industry,\" *RAND Journal of Economics* 45(4): 847–884.\n  [doi:10.1111/1756-2171.12073](https://doi.org/10.1111/1756-2171.12073). A marketing-canon\n  structural search-and-consideration model separating search costs from switching costs.\n- **[R]** Gentzkow, M., Kelly, B., & Taddy, M. (2019), \"Text as Data,\" *Journal of Economic\n  Literature* 57(3): 535–574.\n  [doi:10.1257/jel.20181020](https://doi.org/10.1257/jel.20181020). The reference survey for\n  bringing unstructured text into structural/empirical work; anchors the ML-meets-structural\n  discussion.\n- **[R]** Wager, S. & Athey, S. (2018), \"Estimation and Inference of Heterogeneous\n  Treatment Effects Using Random Forests,\" *Journal of the American Statistical Association*\n  113(523): 1228–1242.\n  [doi:10.1080/01621459.2017.1319839](https://doi.org/10.1080/01621459.2017.1319839).\n  Causal/generalized forests for flexible heterogeneity; the entry point for ML-based\n  heterogeneity in demand and policy.\n\n**Debate:** Search vs. preferences vs. inattention as competing explanations for \"limited\"\ndemand; and where ML complements vs. substitutes for structure.\n\n### Foundational vs. frontier at a glance {#sec-io-foundational-vs-frontier}\n\n**Foundational [F] — the canon every student must master.** Berry 1994 (the share\ninversion); BLP 1995 (random coefficients); Nevo 2000/2001 (applied BLP, markups, merger\nsimulation); Bresnahan 1982 and Nevo 1998 (conduct identification); Rust 1987 (single-\nagent DDC) and Hotz–Miller 1993 (CCP); Bresnahan–Reiss 1990/1991 (entry);\nGuerre–Perrigne–Vuong 2000 (auctions); Rysman 2004 (two-sided markets); with Nevo's 2000\npractitioner's guide and Petrin 2002 (counterfactuals / new goods) as the teaching and\napplied backbone.\n\n**Frontier [R] — methods still moving and actively contested.** Berry–Haile 2014\n(nonparametric identification, which reframes what BLP identifies); Dubé–Fox–Su 2012\n(MPEC) and Conlon–Gortmaker 2020 (PyBLP best practices), as computation keeps evolving;\nBajari–Benkard–Levin 2007, Pakes–Ostrovsky–Berry 2007, and Aguirregabiria–Mira 2007/2010\n(dynamic games and two-step estimation); Gowrisankaran–Rysman 2012, Hendel–Nevo 2006, and\nNair 2007 (dynamic demand); Lee 2013 (platforms, bundling, vertical integration);\nDe los Santos–Hortaçsu–Wildenbeest 2012 and Honka 2014 (search/consideration); and\nGentzkow–Kelly–Taddy 2019 together with Wager–Athey 2018 (text-as-data and generalized\nrandom forests) at the ML + structural frontier.\n\n### How this reading map expands {#sec-io-reading-map-expansion}\n\nThe arc above is meant to deepen within modules rather than sprawl into disconnected\ntopics; the demand → supply/conduct → counterfactual spine, taught static-then-dynamic,\nstays fixed. The most productive directions to extend it are:\n\n1. **Demand frontier.** Add micro-BLP with consumer-level data and the newer PyBLP\n   micro-moment workflow, plus nonparametric and \"demand for characteristics\" approaches\n   building on Berry–Haile.\n2. **Conduct-testing renaissance.** The post-2020 literature on testing firm conduct with\n   instruments deserves its own subsection (paired with Bresnahan 1982 as the historical\n   anchor) once those version-of-record DOIs are confirmed.\n3. **Dynamic games at scale.** Add moment-inequality and machine-learning approaches to\n   large state spaces, and reinforcement-learning solution methods for dynamic oligopoly.\n4. **Platforms / digital markets.** Expand Week 13 into two weeks as the platform-IO and\n   digital-advertising auction literatures mature (sponsored search, ad auctions,\n   recommendation systems).\n5. **Search & inattention.** Track the growing marketing literature on consideration sets,\n   rational inattention, and search with rich clickstream/CRM data.\n6. **ML + structural.** The fastest-moving module: double machine learning, causal forests,\n   deep learning for demand, and LLM/text-as-data for product attributes and reviews, with\n   the methodological debate about combining flexible prediction with economic structure.\n7. **Marketing-specific counterfactuals.** Deepen managerial counterfactuals—dynamic\n   pricing, advertising and targeting, product-line and assortment, and CRM/\n   personalization—each tied back to the estimated structural model.\n\nEvery new reading added here should carry a Crossref-verified version-of-record DOI before\ninclusion, and should attach to an existing module rather than open a new front.\n",
    "supporting": [
      "35-industrial-organization_files\\figure-epub"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}