{
  "hash": "2660cef8391e5bfe539e499f9035bc1b",
  "result": {
    "engine": "knitr",
    "markdown": "# Customer Lifetime Value {#sec-clv}\n\n*Customer lifetime value* (CLV), often called *lifetime value* (LTV) in practice, is\nthe present value of the future cash flows a firm expects to earn from a customer\nrelationship over its remaining duration. It reframes the customer from a\ntransaction into an asset: the question is no longer \"what did this person buy\ntoday?\" but \"what is this relationship worth, net of the cost of sustaining it, for\nas long as it lasts?\" That shift in unit of analysis is the conceptual core of\ncustomer-centric marketing. Once customers are assets, acquisition becomes a capital\nbudgeting decision, retention becomes asset maintenance, and the firm's total\ncustomer base aggregates into *customer equity*, a balance-sheet-style summary of the\ndemand side of the business [@rustLemonZeithaml2004; @gupta2006modeling].\n\nCLV matters for two reasons that map onto the book's two audiences. Scientifically,\nit forces an explicit stochastic model of three primitives (how long a customer stays\n(retention or survival), how often and how much they buy (transaction flow and\nspend), and how those translate into margin net of marketing cost) each of which is a\nlatent process observed only through noisy transaction data. Commercially, CLV is\nthe metric that allocates acquisition budget, prioritizes service, sizes loyalty\nprograms, and, when aggregated, has been shown to track shareholder value\n[@gupta2006modeling; @kumar2010; @kumarshah2009]. A practitioner heuristic captures the\nstakes: a single year's projected business typically recovers only about half of a\ncustomer's full lifetime value, a ratio that varies widely by industry. Truncating\nthe horizon at one year therefore discards roughly half the asset.\n\nThis chapter builds CLV from both ends. It leads with the way value is computed in\nproduction (the unit-economics formulas, the company-type playbooks, and the pipeline\nthat turns a data warehouse into a per-customer number) and grounds that practice in\nthe classical models that explain when the production shortcuts are safe and when they\nare biased. It defines the construct formally, lays out the contractual versus\nnon-contractual taxonomy that decides which model class is even admissible, and then\ndevelops, with reproducible code, the four modeling traditions in turn: the\nprobabilistic \"buy-till-you-die\" family, the econometric and hierarchical-Bayes\nextensions, the machine-learning and deep-learning frontier, and the\ncausal/decision-focused layer that asks not what CLV *is* but how to *act* on it. It\ncovers the full set of adjacent constructs (customer equity, CAC, the LTV:CAC ratio\nand payback, net and gross revenue retention, RFM, churn, share of wallet, customer\nreferral value, customer-based corporate valuation, and negative CLV) and closes on\nthe identification problems that make CLV easy to compute and hard to compute\n*correctly*.\n\n## The Construct and Its Assumptions {#sec-clv-construct}\n\nFix a customer $i$ and let periods be indexed by $j$ (annual or semiannual). Three\nlatent quantities drive value: the probability $p(\\text{Buy}_{ij}=1)$ that the\ncustomer is active and transacts in period $j$; the contribution margin\n$\\text{CM}_{ij}$ the customer generates conditional on transacting; and the\nmarketing cost $\\text{MC}_{ij}$ the firm directs at the customer to keep the\nrelationship alive. Future cash flows are discounted at a per-period rate $r$.\nWriting $T$ for the end of the observation (calibration) window and $N$ for the\nnumber of periods projected forward, the discounted-margin definition of CLV is\n\n$$\n\\text{CLV}_i \\;=\\; \\sum_{j=T+1}^{T+N}\n   \\frac{p(\\text{Buy}_{ij}=1)\\,\\widehat{\\text{CM}}_{ij}}{(1+r)^{\\,j-T}}\n   \\;-\\; \\sum_{j=T+1}^{T+N} \\frac{\\widehat{\\text{MC}}_{ij}}{(1+r)^{\\,j-T}} .\n$$ {#eq-clv-general}\n\n@eq-clv-general is the formulation popularized in the customer-equity program of\nKumar and colleagues [@Kumar_2008; @kumar2010]. Several features deserve emphasis\nbecause they are routinely elided in practice. The summation starts at $j=T+1$: CLV\nis a *forward-looking* quantity, the value of the relationship from today onward, not\nthe historical revenue already booked.[^historic] The purchase probability,\ncontribution margin, and marketing cost are all *predicted* ($\\widehat{\\,\\cdot\\,}$),\nso CLV inherits the sampling error of three separate forecasting models. And the\ndiscount factor must be expressed at the period frequency of the data: a 15% annual\nrate corresponds to a semiannual factor of $r \\approx 0.07238$, since\n$(1.07238)^2 \\approx 1.15$ [@Kumar_2008].\n\n[^historic]: A common conflation is between CLV and *historic customer value* (the\nrealized margin already earned). The two answer different questions: historic value\nscores past contribution; CLV is the basis for forward-looking decisions such as how\nmuch to spend acquiring a *similar* prospect. Only the latter belongs in a capital\nbudgeting calculation.\n\n> **Customer lifetime value.** The present value of all future cash flows\n> attributable to the relationship with a customer (margin from the customer's own\n> purchases, net of the marketing cost of serving and retaining them) over the\n> expected remaining lifetime of that relationship.\n\nA useful special case exposes the economics. Suppose margin per active period is a\nconstant $m = \\text{CM} - \\text{MC}$ and the customer is retained from one period to\nthe next with constant probability $\\rho$ (the *retention rate*). Then the expected\ndiscounted value of an infinite-horizon relationship collapses to a geometric series,\n\n$$\n\\text{CLV} \\;=\\; m \\sum_{t=0}^{\\infty} \\left(\\frac{\\rho}{1+r}\\right)^{t}\n            \\;=\\; m \\,\\frac{1+r}{\\,1+r-\\rho\\,},\n$$ {#eq-clv-geometric}\n\nvalid whenever $\\rho < 1+r$. The factor $(1+r)/(1+r-\\rho)$ is the *margin\nmultiple*: at $\\rho = 0.8$ and $r = 0.1$ it equals $1.1/0.3 \\approx 3.67$, so a\nloyal customer is worth roughly three and two-thirds years of current margin. Two\nmodeling decisions are buried in @eq-clv-geometric and matter enormously: the\nconstancy of $\\rho$ (real retention curves are not memoryless, as later sections\nshow) and the choice of horizon (the infinite sum versus a finite $N$). Both are\nwhere naive CLV estimates go wrong. The closed-form CLV expressions of the managerial\ntradition, of which @eq-clv-geometric is the simplest, descend from\n@bergernasr1998.\n\n### Two Traditions and a Taxonomy {#sec-clv-traditions}\n\nThe literature splits into complementary approaches to operationalizing\n@eq-clv-general, summarized in @tbl-clv-approaches. The *managerial* tradition\npredicts the components (purchase incidence, margin, marketing cost) with separate\nregression or machine-learning models, typically on a contractual or\npanel-with-covariates dataset, and is the workhorse of the customer-equity\nliterature [@Kumar_2008; @kumar2010; @gupta2006modeling; @venkatesankumar2004]. The\n*probabilistic* tradition instead posits a small generative model for the latent\npurchase and dropout processes and derives expected value in closed form; its\ncanonical members are the Pareto/NBD and BG/NBD \"buy-till-you-die\" models for\nnon-contractual settings [@paretonbd1987; @fader2005bgnbd] and the\nshifted-beta-geometric (sBG) model for discrete-time contractual settings\n[@faderhardie2007sbg]. A third, structural strand models the customer's underlying\nutility and budget constraint and derives CLV as an implication of choices\n[@sunder2016measuring], trading tractability for behavioral fidelity.\n\n| Dimension | Managerial / component models | Probabilistic models |\n|---|---|---|\n| What is modeled | Each cash-flow component separately | Latent purchase + dropout processes |\n| Typical data | Contractual or covariate-rich panel | Recency-frequency transaction logs |\n| Covariates | Rich (demographics, marketing) | Few or none |\n| Output | Per-customer point forecast | Posterior expected value |\n| Strengths | Targeting, what-if on marketing | Parsimony, honest uncertainty |\n| Weakness | Many models to maintain and validate | Hard to attach drivers/covariates |\n\n: Two traditions for operationalizing customer lifetime value. {#tbl-clv-approaches}\n\nWhich tradition is even *admissible* is decided by a single two-by-two taxonomy,\nshown in @tbl-clv-taxonomy, that organizes the entire field. The first axis is\nwhether the setting is *contractual* (the firm observes exactly when a customer\nleaves: subscriptions, insurance, B2B SaaS) or *non-contractual* (the customer can\nlapse silently and churn is never directly observed: retail, e-commerce, direct-to-\nconsumer). The second axis is whether purchase opportunities arrive in *discrete*\nperiods or in *continuous* time [@faderhardie2009tutorial]. The chapter's sBG model\noccupies the contractual-discrete cell; the buy-till-you-die models occupy the\nnon-contractual cells.\n\n| | Discrete time | Continuous time |\n|---|---|---|\n| Contractual (churn observed) | shifted-beta-geometric (sBG) for retention; BG/BB for transactions | survival models (exponential, Weibull, Cox) on time-to-churn |\n| Non-contractual (churn latent) | BG/BB | Pareto/NBD, BG/NBD, Gamma-Gamma |\n\n: The organizing taxonomy of customer-base analysis. The cell decides which model class is admissible. {#tbl-clv-taxonomy}\n\n@fig-clv-model-choice recasts the same taxonomy as the sequence of questions an\nanalyst answers before any estimation begins.\n\n```{mermaid}\n%%| label: fig-clv-model-choice\n%%| fig-cap: \"Choosing a customer-base model. The contractual versus non-contractual distinction (is churn observed?) and the discrete versus continuous timing of purchase opportunities jointly decide which model class is admissible.\"\nflowchart TD\n  Q1{\"Is churn observed?<br/>(contractual setting)\"}\n  Q1 -->|\"yes: subscriptions,<br/>insurance, B2B SaaS\"| Q2{\"Purchase opportunities<br/>in discrete periods?\"}\n  Q1 -->|\"no: retail, e-commerce,<br/>direct-to-consumer\"| Q3{\"Purchase opportunities<br/>in discrete periods?\"}\n  Q2 -->|\"discrete\"| M1[\"sBG for retention;<br/>BG/BB for transactions\"]\n  Q2 -->|\"continuous\"| M2[\"Survival models on time-to-churn<br/>(exponential, Weibull, Cox)\"]\n  Q3 -->|\"discrete\"| M3[\"BG/BB\"]\n  Q3 -->|\"continuous\"| M4[\"Pareto/NBD, BG/NBD,<br/>Gamma-Gamma\"]\n```\n\n@fig-clv-pipeline shows how the pieces compose, from raw transactions through a\nlatent survival process to a discounted, aggregated customer-equity figure.\n\n```{mermaid}\n%%| label: fig-clv-pipeline\n%%| fig-cap: \"From transaction data to customer lifetime value. A latent retention or survival process is estimated, projected forward, combined with a margin process, discounted, and aggregated across customers into customer equity.\"\nflowchart LR\n  A[Transaction /<br/>retention data] --> B[Estimate latent<br/>survival process]\n  B --> C[Project retention<br/>over horizon N]\n  M[Margin & cost<br/>process] --> D\n  C --> D[Discount expected<br/>per-period cash flows]\n  D --> E[CLV per customer]\n  E --> F[Aggregate:<br/>customer equity]\n```\n\n## CLV in Industry Practice {#sec-clv-production}\n\nAcademic CLV and operational LTV diverge sharply. In production, the formula a company\nuses is dictated by its business model and its data, and most LTV is computed with far\ncruder tools than the journals describe, which is exactly why the production pitfalls\ncatalogued below recur. We lead with practice because it motivates everything that\nfollows: each classical model in the later sections exists to repair a specific\nfailure of the naive production formula.\n\n### The Formulas Practitioners Actually Use {#sec-clv-formulas}\n\nThe single most widely used LTV formula, ubiquitous in SaaS and subscription\nbusinesses, is\n\n$$\n\\text{LTV} \\;=\\; \\frac{\\text{ARPA} \\times \\text{gross margin \\%}}{\\text{churn rate}},\n$$ {#eq-clv-naive}\n\nwhere ARPA is average revenue per account per period and $1/\\text{churn}$ is the\nimplied (geometric) expected lifetime. @eq-clv-naive is exactly the chapter's\n@eq-clv-geometric with $r=0$ and constant retention $\\rho = 1 - \\text{churn}$. Its\nappeal is that it needs only two numbers off a dashboard. Its dangers are four. First,\nit assumes a single constant churn rate, but real retention curves flatten with tenure\n(the sorting effect formalized by the sBG model in @sec-clv-sbg), so it *underestimates*\nthe value of survivors. Second, it divides by churn, so as churn approaches zero the\nestimate explodes: a firm that improves monthly churn from 2% to 1% sees its headline\nLTV double, an artifact of the functional form rather than a real doubling of value.\nThird, it ignores discounting. Fourth, it ignores expansion revenue, so for any\nbusiness with net revenue retention above 100% (defined in @sec-clv-saas-metrics) it\nunderstates value badly.\n\nThe correct version is the discounted, cohort-based form, identical to the\n@eq-clv-from-survivor derived later: sum the per-period margin weighted by the survivor\nfunction $S(t)$ and discounted at the period rate. Most companies should use this and\ndo not.\n\nAbove the customer level sit the board-room *unit-economics ratios* that govern\nwhether a growth model is solvent:\n\n- *CAC* (customer acquisition cost) is total sales-and-marketing spend in a period\n  divided by new customers acquired.\n- The *LTV:CAC ratio* compares the value of an acquired customer to the cost of\n  acquiring them. A common venture heuristic treats $\\geq 3{:}1$ as healthy, below\n  $1{:}1$ as losing money on every customer, and much above $5{:}1$ as a sign of\n  *under*-investment in growth.\n- The *CAC payback period* is CAC divided by monthly margin per customer, the number\n  of months to recoup acquisition cost; under twelve months is a frequent SaaS target.\n\nThese ratios carry no academic DOI; they are practitioner and venture-capital\nheuristics, but they are how acquisition budgets are actually defended. @sec-clv-unit-econ\ncomputes them from simulated cohorts.\n\n### SaaS Retention Metrics: Logo versus Dollar, Gross versus Net {#sec-clv-saas-metrics}\n\nSubscription businesses report retention at the cohort level along two crossed\ndistinctions. The first is *logo* (customer count) retention versus *dollar* retention:\na firm can lose many small logos yet grow dollars if its surviving accounts expand, or\nthe reverse. The second is *gross* versus *net*. Gross revenue retention (GRR) is\n\n$$\n\\text{GRR} \\;=\\; \\frac{\\text{start MRR} - \\text{churn} - \\text{contraction}}{\\text{start MRR}},\n$$ {#eq-grr}\n\nwhich measures pure leakage and is capped at 100%. Net revenue retention (NRR, also\nnet dollar retention) adds expansion (upsell, seat growth, cross-sell) back in:\n\n$$\n\\text{NRR} \\;=\\; \\frac{\\text{start MRR} - \\text{churn} - \\text{contraction} + \\text{expansion}}{\\text{start MRR}},\n$$ {#eq-nrr}\n\nand can exceed 100%. NRR above 100% means the existing customer base grows *without any\nnew logos*, which is why it is the single most-watched metric in subscription software.\nA firm with NRR of 120% needs no new customers to grow 20% a year; a firm with NRR of\n85% is on a treadmill, replacing a churning base just to stand still. @fig-clv-nrr\nrenders the expansion-versus-churn waterfall that produces an NRR above 100%.\n\n### A Company-Type Playbook {#sec-clv-playbook}\n\nThe admissible model and the operating metric both depend on the business model.\n@tbl-clv-playbook is the cross-industry map.\n\n| Company type | Contract? | Data | How CLV is computed in production | Typical tooling |\n|---|---|---|---|---|\n| SaaS / B2B subscription | Contractual | Billing/CRM, MRR by cohort | Cohort retention curves plus NRR/GRR; LTV:CAC and payback; sometimes sBG or survival on logo churn. Boards see unit economics, not per-customer CLV. | dbt/SQL cohorts; `lifelines`; spreadsheets |\n| E-commerce / DTC | Non-contractual | Order logs (id, date, amount) | BTYD: BG/NBD for transactions plus Gamma-Gamma for spend yields per-customer pLTV, feeding segmentation and paid-acquisition bids. | R `CLVTools`/`BTYD`; Python `lifetimes`; two-stage ML |\n| Retail / CPG | Non-contractual | Loyalty-card panels, basket data | Panel or loyalty BTYD, or structural CLV [@sunder2016measuring]; share of wallet; category CLV. Hard without identified customers. | Panel econometrics; hierarchical Bayes; warehouse |\n| Telecom / insurance / banking | Contractual | Tenure, usage, claims | Survival or churn models (Cox, gradient boosting, survival forests) yield a retention curve, then discounted CLV; uplift for save-desk targeting. | `survival`/`lifelines`; XGBoost; SAS |\n| Mobile gaming / apps | Non-contractual, freemium | Event telemetry | Early-LTV/pLTV with ML from the first hours or days of play; whale identification; ZILN or two-stage heads; ad-LTV for user-acquisition bidding. | TensorFlow; gradient boosting; feature stores |\n| Media / streaming | Contractual subs plus ad tiers | Viewing plus subscription | Cohort retention with content-engagement covariates; survival on subscription; ad-supported tiers blend ARPU models. | Warehouse cohorts; survival; ML |\n\n: How CLV is computed across company types. {#tbl-clv-playbook}\n\n### The Production Stack and Its Recurring Pitfalls {#sec-clv-pitfalls}\n\nThe standard pipeline runs event and transaction data in a warehouse (BigQuery,\nSnowflake, Redshift) into feature engineering in dbt or SQL, then into a CLV model\n(R `CLVTools`/`BTYD`, or Python `lifetimes`/`lifelines` plus a gradient-boosting or\ndeep model), and writes predictions back for segmentation, value-based paid-media\nbidding (Google and Meta both consume per-user pLTV), CRM suppression and targeting,\nand finance (customer-based corporate valuation, @sec-clv-adjacent). The pitfalls that\nrecur in essentially every such system are worth stating as named failure modes:\n\n1. *The naive constant-churn formula* (@eq-clv-naive) biases LTV and explodes as churn\n   approaches zero.\n2. *Survivorship bias.* Fitting a retention curve only on customers who survived to the\n   present inflates retention; the censored and churned customers must be included.\n3. *Look-ahead, or target, leakage.* Using information from inside the prediction window\n   to build features inflates offline metrics and collapses in production. Strict\n   temporal train/validation splits are mandatory.\n4. *Ignoring discounting.* Undiscounted multi-year LTV overstates present value; pick\n   $r$ at the data's period frequency.\n5. *Cohort blending.* Mixing acquisition cohorts of different channels and vintages\n   hides that paid cohorts usually churn faster than organic ones; always analyze by\n   cohort.\n6. *Treating predicted CLV or churn as a targeting policy.* The level of predicted churn\n   is not the same as the *persuadability* of a customer (@sec-clv-causal).\n7. *Extrapolating a short calibration window*, the warning made visual in\n   @fig-retention-projected.\n8. *Endogenous marketing spend.* Observed retention is partly a response to targeted\n   spend, so the spend-retention correlation is not a causal return.\n\nSeveral of these are not fixable by better data hygiene alone; they require the\nclassical models the rest of the chapter develops. We turn to those, starting with the\ncontractual-discrete benchmark.\n\n## Retention, Survival, and the Shifted-Beta-Geometric Model {#sec-clv-sbg}\n\nThe single most consequential primitive in @eq-clv-general is the path of the\npurchase probability over time. In a *contractual* setting (subscriptions,\nmemberships, insurance) the firm observes exactly when each customer churns, and the\nobject of interest is the survivor function $S(t)=\\Pr(\\text{still active at }t)$.\nThe naive approach assumes a constant retention rate $\\rho$ and sets\n$S(t)=\\rho^{t}$, the memoryless geometric curve underlying @eq-clv-geometric and the\nproduction formula @eq-clv-naive. This is almost always wrong in a specific and\npredictable direction: observed aggregate retention rates rise with tenure.\nCustomers who have stayed many periods are disproportionately the intrinsically loyal\nones; the churn-prone have already left. Aggregate retention climbs not because any\nindividual becomes more loyal but because the surviving population is increasingly\nself-selected toward loyalty, a pure *sorting* (heterogeneity) effect, not a\nduration-dependence effect.\n\nThe shifted-beta-geometric model formalizes exactly this intuition and is the\ndiscrete-time benchmark for contractual CLV [@faderhardie2007sbg]. Each customer has\na fixed but unobserved per-period churn probability $\\theta$. Conditional on\n$\\theta$, the period of churn follows a (shifted) geometric distribution: the\ncustomer survives each period with probability $1-\\theta$ and churns with probability\n$\\theta$, so\n\n$$\nP(T = t \\mid \\theta) = \\theta\\,(1-\\theta)^{\\,t-1}, \\qquad t = 1, 2, \\dots\n$$ {#eq-sbg-geometric}\n\nHeterogeneity across customers is captured by mixing $\\theta$ over the population\nwith a Beta prior, $\\theta \\sim \\text{Beta}(\\alpha,\\beta)$, whose density is\n$f(\\theta)=\\theta^{\\alpha-1}(1-\\theta)^{\\beta-1}/B(\\alpha,\\beta)$. Integrating the\nindividual churn probability over this prior yields closed-form aggregate churn and\nsurvivor functions that depend only on the two parameters $(\\alpha,\\beta)$:\n\n$$\nP(T = t) = \\frac{B(\\alpha+1,\\;\\beta+t-1)}{B(\\alpha,\\beta)}, \\qquad\nS(t) = \\frac{B(\\alpha,\\;\\beta+t)}{B(\\alpha,\\beta)} .\n$$ {#eq-sbg-survivor}\n\nThese satisfy the convenient forward recursions\n$P(1)=\\alpha/(\\alpha+\\beta)$, $P(t)=P(t-1)\\,(\\beta+t-2)/(\\alpha+\\beta+t-1)$, and\n$S(t)=S(t-1)-P(t)$, which is exactly how the estimation code below evaluates them.\nThe model's key qualitative property, rising aggregate retention from fixed\nindividual propensities, emerges purely from the Beta mixture; no individual's\n$\\theta$ ever changes.\n\n**Estimation.** With cohort data giving the number of customers $n_t$ surviving at\neach tenure $t$ (equivalently, the number churning, $d_t = n_{t-1}-n_t$), the\nparameters are estimated by maximum likelihood. The log-likelihood for a cohort\nobserved through period $\\tau$ sums the log-probability of each observed churn over\nits churn period plus the log-survivor probability for those still active at the end\nof the window:\n\n$$\n\\ell(\\alpha,\\beta) = \\sum_{t=1}^{\\tau} d_t \\,\\log P(T=t)\n   \\;+\\; n_{\\tau}\\,\\log S(\\tau).\n$$ {#eq-sbg-loglik}\n\nThe last term is the right-censoring contribution: customers still active at $\\tau$\ncontribute the probability of surviving *at least* that long. Identification is weak\nwhen the window is short relative to the heterogeneity ($\\alpha$ and $\\beta$ are\nseparately identified only once the curvature of the survival curve is visible),\nwhich is why the projections below stabilize as more months of history are used.\n\nThe following example reconstructs the analysis of a subscription business: four\ncohorts (\"cases\") with markedly different retention dynamics, each observed for eight\nmonths. The goal is to fit the sBG model and project retention forward. We first\nvisualize the raw curves in @fig-retention-observed.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nset.seed(13)\n\n# Observed retention rate by months since signup (month 0 = 100%)\ndf_ret <- tibble(\n  month_lt = 0:7,\n  case01 = c(1, .531, .452, .423, .394, .375, .356, .346),\n  case02 = c(1, .869, .743, .653, .593, .551, .517, .491),\n  case03 = c(1, .677, .562, .486, .412, .359, .332, .310),\n  case04 = c(1, .631, .468, .382, .326, .289, .262, .241)\n) |>\n  pivot_longer(-month_lt, names_to = \"example\", values_to = \"retention_rate\")\n\nggplot(df_ret, aes(month_lt, retention_rate, colour = example)) +\n  geom_line() + geom_point() +\n  facet_wrap(~ example) +\n  scale_colour_manual(values = c(\"#4e79a7\", \"#f28e2b\", \"#e15759\", \"#76b7b2\")) +\n  labs(x = \"Months since signup\", y = \"Retention rate\") +\n  theme_minimal() +\n  theme(legend.position = \"none\", strip.text = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![Observed monthly retention curves for four subscription cohorts. All decline, but at different rates and with different curvature.](13-clv_files/figure-html/fig-retention-observed-1.png){#fig-retention-observed fig-align='center' width=85%}\n:::\n:::\n\n\nWe next implement the sBG churn, survivor, and (negative) log-likelihood functions\nfollowing @eq-sbg-survivor and @eq-sbg-loglik, then optimize.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Aggregate churn probability P(T = t) via the forward recursion implied by\n# the Beta-geometric mixture (equation @eq-sbg-survivor).\nchurn_bg <- Vectorize(function(alpha, beta, period) {\n  p <- alpha / (alpha + beta)\n  if (period > 1)\n    p <- churn_bg(alpha, beta, period - 1) *\n         (beta + period - 2) / (alpha + beta + period - 1)\n  p\n}, vectorize.args = \"period\")\n\n# Survivor function S(t) = S(t-1) - P(t), with S(1) = 1 - P(1).\nsurvival_bg <- Vectorize(function(alpha, beta, period) {\n  s <- 1 - churn_bg(alpha, beta, 1)\n  if (period > 1)\n    s <- survival_bg(alpha, beta, period - 1) - churn_bg(alpha, beta, period)\n  s\n}, vectorize.args = \"period\")\n\n# Negative log-likelihood (equation @eq-sbg-loglik): churners contribute\n# log P(T = t); the still-active at the end contribute log S(tau).\nneg_loglik <- function(par, active, lost) {\n  alpha <- par[1]; beta <- par[2]\n  tau <- length(active)\n  -( sum(lost * log(churn_bg(alpha, beta, 1:tau))) +\n       active[tau] * log(survival_bg(alpha, beta, tau)) )\n}\n\n# Convert retention rates into active/lost counts for a notional 1,000-customer\n# cohort (the likelihood depends only on the shape, not the cohort size).\ndf_ret <- df_ret |>\n  group_by(example) |>\n  mutate(active = 1000 * retention_rate,\n         lost   = replace_na(lag(active) - active, 0)) |>\n  ungroup()\n```\n:::\n\n\nThe instructive exercise is to ask how the *projected* retention curve evolves as\nthe firm accumulates more months of actual data. With only one or two months\nobserved, identification is weak and the projection is unreliable; as the window\nlengthens, the fitted curve locks onto the truth. We refit the model for each cohort\nusing the first $i$ months only, for $i = 1, \\dots, 7$, and overlay every projection\non the observed curve.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nproject_cohort <- function(d) {\n  map_dfr(1:7, function(i) {\n    fit <- d |> filter(month_lt >= 1, month_lt <= i)\n    opt <- optim(c(1, 1), neg_loglik,\n                 active = fit$active, lost = fit$lost)\n    tibble(month_lt   = 0:7,\n           fact_months = i,\n           retention_pred = round(\n             c(1, survival_bg(opt$par[1], opt$par[2], 1:7)), 3))\n  })\n}\n\nret_preds <- df_ret |>\n  group_by(example) |>\n  group_modify(~ project_cohort(.x)) |>\n  ungroup()\n\ndf_plot <- df_ret |>\n  select(month_lt, example, retention_rate) |>\n  left_join(ret_preds, by = c(\"month_lt\", \"example\"))\n\nggplot(df_plot, aes(month_lt, retention_rate, colour = example)) +\n  geom_line(aes(y = retention_pred, group = fact_months), alpha = 0.4) +\n  geom_line(linewidth = 1.2) + geom_point(size = 1.2) +\n  facet_wrap(~ example) +\n  scale_colour_manual(values = c(\"#4e79a7\", \"#f28e2b\", \"#e15759\", \"#76b7b2\")) +\n  labs(x = \"Months since signup\", y = \"Retention rate\") +\n  theme_minimal() +\n  theme(legend.position = \"none\", strip.text = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![Observed retention (bold) with sBG projections fit on the first i months only, for i = 1..7 (faint lines). Projections stabilize toward the observed curve as the calibration window lengthens.](13-clv_files/figure-html/fig-retention-projected-1.png){#fig-retention-projected fig-align='center' width=85%}\n:::\n:::\n\n\nThe faint projection lines fan out wildly when fit on one month and converge onto\nthe observed curve as the calibration window grows, a visual diagnostic of the\nidentification problem in @eq-sbg-loglik. In practice this argues against committing\nto a CLV figure from a single early cohort snapshot. The same identification problem,\naddressed by borrowing strength across cohorts with limited information, is the subject\nof @schweidel2008retention.\n\n### From Retention to Value {#sec-clv-retention-to-value}\n\nWith a fitted survivor function, lifetime value follows directly. For a contractual\nproduct with constant per-period margin $m$ (here a \\$1 subscription) and discount\nfactor $r$, expected discounted value over a horizon of $N$ periods is\n\n$$\n\\widehat{\\text{CLV}} \\;=\\; m \\sum_{t=0}^{N} \\frac{\\widehat{S}(t)}{(1+r)^{\\,t}},\n$$ {#eq-clv-from-survivor}\n\nwith $\\widehat{S}(t)$ taken from observed data where available and from the sBG\nprojection beyond the calibration window. Setting $r=0$ for transparency (the firm\nwants undiscounted expected revenue per signup), we compute average LTV for cohort 3\nfrom only two months of history, projected over a 24-month horizon.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit3 <- df_ret |> filter(example == \"case03\", month_lt >= 1, month_lt <= 2)\nopt3 <- optim(c(1, 1), neg_loglik, active = fit3$active, lost = fit3$lost)\n\nprojected <- tibble(\n  month_lt       = 3:24,\n  retention_pred = round(survival_bg(opt3$par[1], opt3$par[2], 3:24), 3))\n\nltv3 <- df_ret |>\n  filter(example == \"case03\", month_lt <= 2) |>\n  select(month_lt, retention_rate) |>\n  bind_rows(projected) |>\n  mutate(retention = coalesce(retention_rate, retention_pred),\n         ltv_monthly = retention * 1,          # $1 subscription price\n         ltv_cum     = round(cumsum(ltv_monthly), 2))\n\ntail(ltv3, 3)\n#> # A tibble: 3 × 6\n#>   month_lt retention_rate retention_pred retention ltv_monthly ltv_cum\n#>      <int>          <dbl>          <dbl>     <dbl>       <dbl>   <dbl>\n#> 1       22             NA          0.254     0.254       0.254    8.83\n#> 2       23             NA          0.25      0.25        0.25     9.08\n#> 3       24             NA          0.246     0.246       0.246    9.33\ncat(\"Average 24-month LTV for cohort 3: $\", tail(ltv3$ltv_cum, 1), \"\\n\", sep = \"\")\n#> Average 24-month LTV for cohort 3: $9.33\n```\n:::\n\n\nThe cumulative figure, roughly \\$9.33 per subscriber over 24 months, blends two months\nof *observed* retention with twenty-two months of *projected* retention from a\ntwo-parameter model estimated on those same two months. That this is even possible is\nthe practical appeal of the probabilistic approach; that it rests on extrapolating a\nheterogeneity model far beyond its calibration window is its central caveat, and\n@fig-retention-projected is the warning label.\n\n## Probabilistic Models for Customer-Base Analysis {#sec-clv-btyd}\n\nIn *non-contractual* settings, churn is never observed: a customer who has not bought\nrecently may have defected or may simply be between trips. The buy-till-you-die (BTYD)\nfamily solves this by positing two latent processes, a *purchase* process active while\nthe customer is \"alive\" and a *dropout* (death) process that ends the relationship at\nan unobserved time, and deriving expected future transactions and value in closed form\nfrom each customer's *recency* (time of last purchase) and *frequency* (number of\nrepeat purchases). These statistics carry exactly the information needed to infer the\nprobability a customer is still alive.\n\n### Pareto/NBD and BG/NBD {#sec-clv-pnbd}\n\nThe origin model is the *Pareto/NBD* [@paretonbd1987]. While alive, customer $i$\npurchases according to a Poisson process with rate $\\lambda_i$, and the rate varies\nacross the population as $\\lambda \\sim \\text{Gamma}(r,\\alpha)$ (the negative-binomial,\nor NBD, half). The customer's lifetime is exponential with dropout rate $\\mu_i$, and\n$\\mu \\sim \\text{Gamma}(s,\\beta)$ across customers (the Pareto half). The expected number\nof transactions in a future interval, and the probability that a customer is still\nalive given recency and frequency, both have closed forms. The model's one\ninconvenience is computational: the likelihood involves Gaussian hypergeometric\nfunctions and can be fragile to optimize.\n\nThe *BG/NBD* model, \"counting your customers the easy way,\" replaces the\nanalytically awkward Pareto death process with a beta-geometric one\n[@fader2005bgnbd]. After each purchase, the customer flips a coin and, with\nprobability $p$, becomes inactive; $p$ varies across customers as $\\text{Beta}(a,b)$.\nThis swap makes estimation far easier with almost identical fit, and BG/NBD is now the\nsingle most-used BTYD model. The *Gamma-Gamma* monetary model [@fader2005rfmclv]\nsupplies the spend dimension: average transaction value varies within a customer\naround a latent mean, and that mean is Gamma-distributed across the population, with\nspend assumed independent of transaction frequency. Multiplying expected future\ntransactions by expected spend (and a margin rate) gives a monetary pLTV.\n\nA unifying observation closes the loop with practice: RFM scoring and the BTYD models\nare two views of the same object. @fader2005rfmclv show this with *iso-value curves*,\ncontours in the recency-frequency plane that group customers with different histories\nbut equal predicted future value.\n\n### A Worked Non-Contractual Pipeline {#sec-clv-btyd-code}\n\nWe simulate a transaction log from the Pareto/NBD data-generating process, then fit\nBG/NBD plus Gamma-Gamma with the maintained `CLVTools` package and cross-check the\ntransaction model against the original `BTYD` package. The simulation draws each\ncustomer's purchase rate and lifetime from Gamma priors, runs a Poisson process up to\nthe (possibly censored) lifetime, and attaches Gamma-distributed spend.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\n\nn_cust  <- 1500\nT_total <- 78                       # weeks of potential observation\n\nlambda    <- rgamma(n_cust, shape = 0.55, rate = 10)  # weekly purchase rate\nmu        <- rgamma(n_cust, shape = 0.40, rate = 30)  # dropout rate\ncust_mean <- rgamma(n_cust, shape = 4,   rate = 0.08) # latent mean spend (~ $50)\n\nsim_one <- function(i) {\n  end <- min(rexp(1, mu[i]), T_total)   # exponential lifetime, censored at T_total\n  ts <- 0; t <- 0                       # initial purchase at t = 0\n  repeat {\n    t <- t + rexp(1, lambda[i])         # Poisson interarrival while alive\n    if (t > end) break\n    ts <- c(ts, t)\n  }\n  tibble(cust = i, t = ts)\n}\n\nlog_df <- map_dfr(seq_len(n_cust), sim_one) |>\n  mutate(amount = rgamma(n(), shape = 6, rate = 6 / cust_mean[cust]),\n         date   = as.Date(\"2020-01-01\") + round(t * 7)) |>\n  transmute(cust_id = paste0(\"C\", cust), date, amount = round(amount, 2))\n\ncat(\"rows:\", nrow(log_df),\n    \" customers:\", n_distinct(log_df$cust_id),\n    \" span:\", as.character(min(log_df$date)), \"to\",\n    as.character(max(log_df$date)), \"\\n\")\n#> rows: 6048  customers: 1500  span: 2020-01-01 to 2021-06-30\n```\n:::\n\n\nWe hand the log to `CLVTools`, fit the Pareto/NBD transaction model and the\nGamma-Gamma spend model on the full history, and predict a discounted per-customer CLV\n52 weeks forward. We use Pareto/NBD here because `CLVTools` derives a closed-form\ndiscounted expected residual transaction count (DERT), and hence a discounted CLV,\ndirectly from it.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(CLVTools)\n\nclv_dat <- clvdata(log_df, date.format = \"ymd\", time.unit = \"week\",\n                   name.id = \"cust_id\", name.date = \"date\", name.price = \"amount\")\n\nfit_pnbd <- pnbd(clv_dat, verbose = FALSE)   # Pareto/NBD transaction model\nfit_gg   <- gg(clv_dat,   verbose = FALSE)   # Gamma-Gamma spend model\n\nround(coef(fit_pnbd), 3)\n#>      r  alpha      s   beta \n#>  0.560 10.802  0.545 45.883\n\n# Predict 52 weeks ahead; continuous.discount.factor is the per-week rate.\npred <- predict(fit_pnbd, predict.spending = fit_gg,\n                prediction.end = 52,\n                continuous.discount.factor = 0.0029,  # ~ 15% per year\n                verbose = FALSE) |>\n  as.data.frame()\n\npred |>\n  transmute(Id, PAlive = round(PAlive, 3), CET = round(CET, 2),\n            spend = round(predicted.mean.spending, 1),\n            DERT  = round(DERT, 2),\n            pLTV  = round(predicted.CLV, 2)) |>\n  head(6)\n#>      Id PAlive  CET spend  DERT    pLTV\n#> 1    C1  0.978 5.48  68.2 23.26 1585.99\n#> 2   C10  0.774 0.64  65.2  2.72  177.33\n#> 3  C100  0.435 0.13  52.3  0.55   28.71\n#> 4 C1000  0.435 0.13  52.3  0.55   28.71\n#> 5 C1001  0.435 0.13  52.3  0.55   28.71\n#> 6 C1002  0.435 0.13  52.3  0.55   28.71\n\ncat(\"Mean predicted 1-year CLV: $\", round(mean(pred$predicted.CLV), 2), \"\\n\", sep = \"\")\n#> Mean predicted 1-year CLV: $310.81\n```\n:::\n\n\n`PAlive` is the inferred probability a customer is still active, `CET` the conditional\nexpected transactions over the horizon, `DERT` the discounted expected residual\ntransactions, and `predicted.CLV` the monetary lifetime value. For independent\nconfirmation, we re-estimate the BG/NBD transaction model with the original `BTYD`\npackage on the same log and compare the implied expected transactions.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(BTYD)\n\nend_cal <- as.Date(\"2020-01-01\") + 39 * 7   # split calibration / holdout\n\nelog <- log_df |>\n  transmute(cust = cust_id, date = as.Date(date), sales = amount) |>\n  as.data.frame()\n\nelog_m  <- dc.MergeTransactionsOnSameDate(elog)\ncbs_cbt <- dc.ElogToCbsCbt(elog_m, per = \"week\", T.cal = end_cal)\ncal_cbs <- cbs_cbt$cal$cbs\n\nparams_bg <- bgnbd.EstimateParameters(cal_cbs)\ncet_btyd  <- bgnbd.ConditionalExpectedTransactions(\n  params_bg, T.star = 13,\n  x = cal_cbs[, \"x\"], t.x = cal_cbs[, \"t.x\"], T.cal = cal_cbs[, \"T.cal\"])\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"BTYD BG/NBD params (r, alpha, a, b):\", round(params_bg, 3), \"\\n\")\n#> BTYD BG/NBD params (r, alpha, a, b): 0.404 7.849 0.339 3.664\ncat(\"Mean 13-week expected transactions (BTYD BG/NBD):\",\n    round(mean(cet_btyd), 3), \"\\n\")\n#> Mean 13-week expected transactions (BTYD BG/NBD): 0.482\n```\n:::\n\n\nThe two packages, two model variants, and two estimation routines deliver coherent\nparameters and forecasts from the same simulated log, which is the trust-building step\nbefore any of these numbers reaches a paid-media bid. We visualize the BTYD intuition\ndirectly in @fig-clv-palive: the probability a customer is alive as a function of how\nmany times they have bought and how long ago they last appeared.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngrid <- expand_grid(x = 0:10, t.x = seq(0, 39, by = 3)) |>\n  mutate(palive = bgnbd.PAlive(params_bg, x = x, t.x = t.x, T.cal = 39))\n\nggplot(grid, aes(t.x, x, fill = palive)) +\n  geom_tile() +\n  scale_fill_viridis_c(name = \"P(alive)\", limits = c(0, 1)) +\n  labs(x = \"Recency: time of last purchase (weeks)\",\n       y = \"Frequency: number of repeat purchases\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Probability a customer is still alive under the fitted BG/NBD model, over the recency-frequency grid. Many purchases with a recent last visit imply near-certain life; a long silence after few purchases implies likely dropout.](13-clv_files/figure-html/fig-clv-palive-1.png){#fig-clv-palive fig-align='center' width=85%}\n:::\n:::\n\n\nThe contours in @fig-clv-palive are the iso-value intuition of @fader2005rfmclv made\nconcrete: customers with very different recency-frequency histories can share the same\nP(alive), and therefore the same future value.\n\n## Econometric and Hierarchical-Bayes CLV {#sec-clv-econometric}\n\nWhere BTYD models are deliberately covariate-light, the econometric tradition predicts\nthe *components* of @eq-clv-general (incidence, frequency, spend, churn) with\nregression and hierarchical-Bayes machinery and rich covariates such as demographics,\nmarketing touches, channel, and macro conditions. Its strength is targeting and\nwhat-if analysis on marketing levers; its weakness is the number of models to maintain\nand validate.\n\nThe bridge between the two traditions is @abe2009, which recasts the Pareto/NBD as a\nhierarchical Bayes model. This yields individual-level posteriors, honest uncertainty,\nand, crucially, the ability to let covariates shift the purchase and dropout rates,\nsomething the closed-form Pareto/NBD cannot do. On the pure component-modeling side,\n@venkatesankumar2004 build a covariate-rich CLV used to rank and select customers and\nto allocate contact across channels, and @reinartzkumar2003 model *profitable* lifetime\nduration with a hazard specification, the econometric face of retention.\n\nTwo themes from this literature carry practical weight. First, acquisition and retention\nare not independent: @schweidel2008bivariate model jointly *when* a customer is acquired\nand *how long* they then stay, and show that ignoring the correlation biases CLV.\nSecond, elaboration does not always pay. @donkers2007clv run a model tournament in\ninsurance and find that simple status-quo and Markov-chain models often match or beat\nfar more elaborate ones out of sample, an empirical-humility check on the impulse to\nadd structure.\n\nThe Markov-chain formulation [@pfeifercarraway2000] is worth stating in full because it\nlinks CLV to the decision-theoretic view. Define a small set of states (for example,\nactive, lapsed, lost), a transition matrix $P$, and a per-period reward vector $\\mathbf{r}$\ngiving the margin earned in each state. With discount factor $\\gamma = 1/(1+r)$, the\nvector of state-conditional lifetime values solves the linear system\n\n$$\n\\mathbf{V} \\;=\\; (\\mathbf{I} - \\gamma P)^{-1}\\,\\mathbf{r},\n$$ {#eq-clv-markov}\n\nthe discounted expected reward of a customer currently in each state. @tbl-clv-markov\ncomputes it for a three-state migration model; @fig-clv-states draws the transition\nstructure the code encodes.\n\n```{mermaid}\n%%| label: fig-clv-states\n%%| fig-cap: \"The three-state customer-migration process behind the Markov-chain CLV. Only the active state earns margin; the lapsed state can be reactivated but leaks heavily into the absorbing lost state.\"\nflowchart LR\n  ACT[\"Active<br/>(reward 100)\"]\n  LAP[\"Lapsed<br/>(reward 0)\"]\n  LST[\"Lost<br/>(reward 0, absorbing)\"]\n  ACT -->|\"0.70\"| ACT\n  ACT -->|\"0.20\"| LAP\n  ACT -->|\"0.10\"| LST\n  LAP -->|\"0.30\"| ACT\n  LAP -->|\"0.40\"| LAP\n  LAP -->|\"0.30\"| LST\n  LST -->|\"1.00\"| LST\n```\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstates <- c(\"active\", \"lapsed\", \"lost\")\nP <- matrix(c(0.70, 0.20, 0.10,\n              0.30, 0.40, 0.30,\n              0.00, 0.00, 1.00),\n            nrow = 3, byrow = TRUE, dimnames = list(states, states))\nreward <- c(active = 100, lapsed = 0, lost = 0)\ngamma  <- 1 / 1.10                                   # 10% per-period discount\nV <- solve(diag(3) - gamma * P) %*% reward           # equation @eq-clv-markov\n```\n:::\n\n\n\n::: {#tbl-clv-markov .cell layout-align=\"center\" tbl-cap='Markov-chain migration CLV by current state. An active customer is worth far more than a lapsed one because the lapsed state carries a high probability of transitioning to the absorbing lost state.'}\n::: {.cell-output-display}\n\n\n|Current state | CLV ($)|\n|:-------------|-------:|\n|active        |     350|\n|lapsed        |     150|\n|lost          |       0|\n\n\n:::\n:::\n\n\n@tbl-clv-markov shows the absorbing structure at work: an active customer is worth\n\\$350 because they earn margin now and are likely to keep earning, a lapsed customer\nonly \\$150 because the lapsed state leaks heavily into the absorbing lost state, and a\nlost customer nothing. This is the same discounting logic as @eq-clv-from-survivor,\nexpressed as a controllable Markov reward process, and it is the conceptual link to the\ndecision models of @sec-clv-causal.\n\n## The Machine-Learning and Deep-Learning Frontier {#sec-clv-ml}\n\nThe production frontier has moved from closed-form probability models to supervised\nmachine learning and deep learning on rich feature sets and raw event sequences.\nSeveral recurring design patterns organize the space.\n\nThe dominant production pattern is the *two-stage churn-times-spend* (or\npropensity-times-value) decomposition. A first-stage classifier (logistic regression,\ngradient boosting, random forest) predicts the probability a customer is active or\nrepeat-purchasing over the horizon; a second-stage regressor predicts conditional\nspend; their product, times margin and discounted, is pLTV. This mirrors the BTYD\nfrequency-times-monetary split but adds covariates and nonlinearity. The benchmark for\n*whether the modeling effort pays off* is the churn-model tournament of\n@neslin2006churn, whose central finding (\"methods matter\") is that modest gains in\npredictive accuracy translate into six-figure swings in campaign profit.\n\nWe demonstrate the two-stage pattern on simulated customer features, using a random\nforest for the active/inactive classifier and an elastic-net (`glmnet`) regression for\nlog-spend among actives, then combine the two heads.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(glmnet)\nlibrary(randomForest)\n\nset.seed(11)\nN <- 5000\nfeat <- tibble(\n  recency   = runif(N, 0, 52),\n  frequency = rpois(N, 3),\n  monetary  = rgamma(N, 4, 0.08),\n  tenure    = runif(N, 1, 104),\n  promo     = rbinom(N, 1, 0.4))\n\neta      <- -1 + 0.03 * feat$frequency - 0.02 * feat$recency + 0.4 * feat$promo\nactive   <- rbinom(N, 1, plogis(eta))\nspend    <- active * rgamma(N, shape = 3, rate = 3 / (feat$monetary * 0.5))\ndf_ml    <- feat |> mutate(active = factor(active), spend = spend)\n\ntr <- sample(N, 0.7 * N); te <- setdiff(seq_len(N), tr)\n\n# Stage 1: random-forest active/inactive classifier.\nrf <- randomForest(active ~ recency + frequency + monetary + tenure + promo,\n                   data = df_ml[tr, ], ntree = 200)\np_active_hat <- predict(rf, df_ml[te, ], type = \"prob\")[, \"1\"]\n\n# Stage 2: elastic-net log-spend regression among training actives.\nact_tr <- tr[df_ml$active[tr] == \"1\"]\nxtr <- model.matrix(~ recency + frequency + monetary + tenure + promo,\n                    df_ml[act_tr, ])[, -1]\nytr <- log(df_ml$spend[act_tr])\ncvfit <- cv.glmnet(xtr, ytr, alpha = 0.5)\n\nxte <- model.matrix(~ recency + frequency + monetary + tenure + promo,\n                    df_ml[te, ])[, -1]\nresid_var <- as.numeric(var(ytr - predict(cvfit, xtr, s = \"lambda.min\")))\nspend_hat <- exp(as.numeric(predict(cvfit, xte, s = \"lambda.min\")) + 0.5 * resid_var)\n\npltv_ml <- p_active_hat * spend_hat * 0.6   # 60% margin\ncat(\"Mean two-stage pLTV: $\", round(mean(pltv_ml), 2), \"\\n\", sep = \"\")\n#> Mean two-stage pLTV: $3.23\ncat(\"Correlation with realized margin:\",\n    round(cor(pltv_ml, df_ml$spend[te] * 0.6), 3), \"\\n\")\n#> Correlation with realized margin: 0.226\n```\n:::\n\n\nThe lognormal back-transform includes the variance correction $\\exp(0.5\\sigma^2)$,\nwithout which expected spend on the raw scale is systematically understated, a common\nproduction bug. The positive correlation between predicted pLTV and realized margin on\nthe held-out customers confirms the two heads compose sensibly.\n\nA more integrated approach uses a single probabilistic head that models the spike at\nzero (non-buyers) and the heavy right tail (a few high spenders) jointly. The\n*zero-inflated lognormal* (ZILN) loss, popularized by a Google deep-learning model\n[@wang2019ziln], does exactly this: one model outputs a churn logit, a lognormal mean,\nand a lognormal scale, and is trained on the combined likelihood. We fit a small ZILN\nmodel by maximum likelihood (no neural network required to make the point) and recover\nboth the structure and a calibrated expected value. @fig-clv-ml-heads contrasts the\njoint ZILN head with the two-stage decomposition.\n\n```{mermaid}\n%%| label: fig-clv-ml-heads\n%%| fig-cap: \"Two production architectures for machine-learning pLTV. The two-stage pattern multiplies a first-stage activity classifier by a second-stage conditional-spend regressor; the zero-inflated lognormal alternative trains one model on the combined likelihood of the zero spike and the heavy right tail.\"\nflowchart TB\n  FT[\"Customer features and event history\"]\n  subgraph TS[\"Two-stage: churn-times-spend\"]\n    C1[\"Stage 1 classifier:<br/>probability active over the horizon\"]\n    R1[\"Stage 2 regressor:<br/>conditional spend among actives\"]\n    PD[\"Product, times margin,<br/>discounted: pLTV\"]\n    C1 --> PD\n    R1 --> PD\n  end\n  subgraph ZS[\"Joint head: zero-inflated lognormal\"]\n    ZH[\"One model outputs a churn logit,<br/>a lognormal mean, and a<br/>lognormal scale\"]\n    ZE[\"Trained on the combined likelihood:<br/>spike at zero plus heavy right tail\"]\n    ZH --> ZE\n  end\n  FT --> C1\n  FT --> R1\n  FT --> ZH\n```\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(21)\nM <- 6000\nx      <- runif(M, -2, 2)\np_buy  <- plogis(-0.5 + 0.9 * x)\nbuy    <- rbinom(M, 1, p_buy)\nspend2 <- buy * rlnorm(M, meanlog = 3 + 0.5 * x, sdlog = 0.6)\n\n# ZILN negative log-likelihood: a churn (zero-inflation) head and a lognormal\n# value head, each linear in x here for transparency.\nziln_nll <- function(par) {\n  p  <- plogis(par[1] + par[2] * x)         # P(buy)\n  ml <- par[3] + par[4] * x                 # lognormal mean (log scale)\n  s  <- exp(par[5])                         # lognormal scale\n  ll <- ifelse(spend2 == 0,\n               log1p(-p),\n               log(p) + dlnorm(pmax(spend2, 1e-8), ml, s, log = TRUE))\n  -sum(ll)\n}\n\nfit_ziln <- optim(c(0, 0, 3, 0, log(0.6)), ziln_nll, method = \"BFGS\")\np_hat  <- plogis(fit_ziln$par[1] + fit_ziln$par[2] * x)\nE_buy  <- p_hat * exp((fit_ziln$par[3] + fit_ziln$par[4] * x) +\n                        exp(fit_ziln$par[5])^2 / 2)\ncat(\"ZILN params (b0, b1, m0, m1, log-sigma):\",\n    round(fit_ziln$par, 3), \"\\n\")\n#> ZILN params (b0, b1, m0, m1, log-sigma): -0.512 0.912 3.008 0.511 -0.503\ncat(\"Mean predicted E[spend]: $\", round(mean(E_buy), 2),\n    \"  vs actual: $\", round(mean(spend2), 2), \"\\n\", sep = \"\")\n#> Mean predicted E[spend]: $15.57  vs actual: $15.6\n```\n:::\n\n\nThe fitted ZILN expected value matches the simulated mean closely because the model\nrespects the data-generating structure: it does not try to force a single distribution\nonto a population that is half non-buyers and half a right-skewed spending tail.\n\nBeyond these patterns, the frontier includes *sequence models* (RNN, LSTM, seq2seq,\ntransformers) that consume the raw chronological event stream and learn temporal\npatterns hand-built RFM features miss [@bauerjannach2021seq2seq]; *customer embeddings*\nthat learn dense vector representations from product and event co-occurrence and\ntransfer information across sparse customers, as in the ASOS production system\n[@chamberlain2017embeddings]; graph neural networks for marketplace and advertising\nLTV; and *early-LTV* models that predict a mobile game player's lifetime value (and\nidentify \"whales\") from the first hours of play [@sifa2015games]. A caveat is in order:\nmost of this work lives in KDD, RecSys, AAAI, and arXiv rather than the top marketing\njournals, and the marketing-journal contribution is concentrated on the *decision* side,\nto which we now turn.\n\n## Causal and Decision-Focused CLV {#sec-clv-causal}\n\nPredicting CLV is not the same as acting on it, and the top-journal frontier here is\nabout *incremental* value and resource allocation rather than point prediction. This is\nwhere the \"endogenous marketing\" pitfall of @sec-clv-pitfalls becomes a research program.\n\nThe landmark result is *retention futility* [@ascarza2018futility]: the\nhighest-churn-risk customers are often not the most *persuadable*, so targeting\nretention spend on predicted churn (or predicted CLV) wastes money on customers who\nwould either leave regardless or stay regardless. The correct target is the *uplift*,\nthe individual treatment effect of the intervention, validated by Ascarza in two field\nexperiments. We make the point concrete by simulating a retention treatment whose effect\nis uncorrelated with churn risk and comparing a risk-targeting policy against an\nuplift-targeting policy.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(3)\nM2     <- 8000\nrisk   <- runif(M2)                       # churn risk\nuplift <- rnorm(M2, 0.04, 0.03)           # treatment effect, ~independent of risk\nmargin <- 200\n\ntop_quintile <- function(v) v >= quantile(v, 0.8)\ngain_risk   <- mean(uplift[top_quintile(risk)])   * margin\ngain_uplift <- mean(uplift[top_quintile(uplift)]) * margin\n\ncat(sprintf(\"cor(risk, uplift) = %.3f\\n\", cor(risk, uplift)))\n#> cor(risk, uplift) = -0.011\ncat(sprintf(\"Per-target retained margin: risk-targeting $%.2f vs uplift-targeting $%.2f\\n\",\n            gain_risk, gain_uplift))\n#> Per-target retained margin: risk-targeting $7.79 vs uplift-targeting $16.39\n```\n:::\n\n\nWith risk and uplift essentially uncorrelated, the uplift-targeting policy roughly\ndoubles the retained margin per treated customer relative to the intuitive\ntarget-the-high-risk policy, which is Ascarza's point in miniature. The complementary\nmethodological advance is off-policy evaluation: @simester2020policy show how to assign\ncustomers to *actions* and then evaluate *any* targeting policy, including a\nCLV-maximizing one, without re-running an experiment for each candidate policy. At the\nbudget level, @reinartzthomaskumar2005 jointly optimize acquisition and retention spend\nagainst a CLV objective, the canonical resource-allocation-to-CLV result. The throughline\nis that the decision-relevant quantity is the *derivative* of CLV with respect to a\nmarketing action, not its level, and recovering that derivative requires experimental or\nquasi-experimental variation rather than the historical correlation between spend and\nvalue.\n\n## Adjacent and Related Constructs {#sec-clv-adjacent}\n\nCLV sits at the center of a constellation of constructs, summarized in\n@tbl-clv-constructs, that extend, aggregate, or operationalize it.\n\n| Construct | One-line definition | Anchor reference |\n|---|---|---|\n| Customer equity (CE) | Sum of all customers' CLV; the demand-side asset on a quasi-balance-sheet | @rustLemonZeithaml2004 |\n| Valuing customers to value firms | CE drives firm value; lets one value high-growth, negative-earnings firms | @guptaLehmannStuart2004 |\n| CLV modeling synthesis | The review defining and surveying implementable CLV | @gupta2006modeling |\n| CE to market capitalization | Aggregated CLV tracks shareholder value | @kumarshah2009 |\n| CBCV, contractual | Value a public subscription firm from disclosed customer metrics | @mccarthy2017 |\n| CBCV, non-contractual | Same, for non-subscription firms, from a BTYD model on disclosed data | @mccarthyfader2018 |\n| Customer referral value (CRV) | Value a customer creates by referring others | @kumarCRV2010 |\n| Customer engagement value (CEV) | CLV plus CRV plus influencer and knowledge value | @kumar2010cev |\n| Negative CLV | Loyal is not the same as profitable; some long-tenured customers destroy value | @reinartzkumar2002hbr |\n| RFM | The classic scoring heuristic, equivalent to a BTYD view | @fader2005rfmclv |\n| Churn / retention prediction | The predictive substrate of CLV | @neslin2006churn |\n| Structural CLV (CPG) | CLV from a utility and budget model with brand switching | @sunder2016measuring |\n\n: The constructs adjacent to customer lifetime value. {#tbl-clv-constructs}\n\n*Customer equity* is the headline aggregate: the sum of every customer's CLV, treated\nas the demand-side asset of the firm. @rustLemonZeithaml2004 build it into a \"return on\nmarketing\" framework that traces marketing actions through value, brand, and relationship\nequity to customer equity. The link to firm value is the bridge to the\nmarketing-finance interface: @guptaLehmannStuart2004 show that valuing customers lets one\nvalue the firm itself, which is decisive for high-growth, negative-earnings companies whose\nworth lives entirely in their customer base, and @kumarshah2009 demonstrate that aggregated\nCLV tracks market capitalization. The most direct realization of this idea is\n*customer-based corporate valuation* (CBCV), which values a public company from disclosed\ncustomer metrics: for contractual subscription firms [@mccarthy2017] and, using a BTYD\nmodel fit to disclosed transaction data, for non-contractual firms [@mccarthyfader2018].\n\nTwo constructs widen the definition of customer value beyond the focal customer's own\npurchases. *Customer referral value* extends it to the customers a person brings in,\ndeveloped in detail in @sec-clv-crv. *Customer engagement value* widens it further to\ninclude a customer's influencer value (social-media and word-of-mouth reach) and\nknowledge value (feedback and co-creation), so that the \"total\" engagement asset is CLV\nplus CRV plus influencer plus knowledge value [@kumar2010cev].\n\nA construct that runs the other way is *negative CLV*. Loyalty is not the same as\nprofitability: some long-tenured customers consume more service, discount, and support\nthan they generate in margin, and @reinartzkumar2002hbr document this \"mismanagement of\ncustomer loyalty\" directly. The practical corollary is that a firm should be willing to\n*demarket* to, or fire, its unprofitable customers, a recommendation that follows from\n@eq-clv-general the moment the marketing-cost term exceeds the margin term over the\nhorizon. Finally, *share of wallet*, the fraction of a customer's category spend the firm\ncaptures, complements CLV by indicating headroom: a high-CLV customer with low share of\nwallet is an expansion opportunity, the customer-level analogue of the net-revenue-retention\nexpansion in @sec-clv-saas-metrics.\n\n## Customer Referral Value {#sec-clv-crv}\n\nCLV as defined so far captures only the margin a customer generates through their\n*own* purchases. A customer also creates value by bringing in others, through\nword of mouth and formal referral programs, and this *customer referral value* (CRV)\nis empirically distinct from CLV: high-CLV customers are frequently not the best\nreferrers, so the two must be managed separately [@kumarCRV2010]. The managerial\nimplication is a two-by-two *customer value matrix* crossing CLV (low/high) with\nCRV (low/high): \"champions\" score high on both, \"affluents\" buy heavily but refer\nlittle, \"advocates\" refer well but buy little, and the remainder warrant minimal\ninvestment. The diagnostic point is that targeting on CLV alone leaves the referral\nasset unmanaged.\n\nMeasuring referral value requires separating two kinds of referred customer\n[@kumarCRV2010]. A *type-one* referral is incremental: the referred customer would\nnot have joined absent the referral, so their entire margin is attributable to the\nreferrer. A *type-two* referral would have joined anyway through other channels, so\nthe referrer's contribution is not the customer's margin but the *acquisition cost\nthe firm saved* by not having to recruit them through paid channels. Empirically the\nsplit is roughly even between the two types. Letting $n_1$ index the\nincremental (type-one) referrals and $n_1{+}1,\\dots,n_2$ index the would-have-joined\n(type-two) referrals,\n\n$$\n\\text{CRV}_i \\;=\\; \\sum_{t=1}^{T}\\sum_{y=1}^{n_1}\n   \\frac{A_{ty} - a_{ty} - M_{ty} + \\text{ACQ1}_{ty}}{(1+r)^{t}}\n   \\;+\\; \\sum_{t=1}^{T}\\sum_{y=n_1+1}^{n_2}\n   \\frac{\\text{ACQ2}_{ty}}{(1+r)^{t}},\n$$ {#eq-crv}\n\nwhere $A_{ty}$ is the gross margin from incremental customer $y$, $a_{ty}$ the cost\nof the referral incentive, $M_{ty}$ the marketing cost to retain the referred\ncustomer, $\\text{ACQ1}_{ty}$ the acquisition cost saved on incremental customers,\n$\\text{ACQ2}_{ty}$ the acquisition cost saved on would-have-joined customers, and $r$\nthe per-period discount factor (again $\\approx 0.07238$ semiannually for a 15% annual\nrate [@Kumar_2008]). The first sum books full net margin for incremental customers;\nthe second books *only* avoided acquisition cost for the rest. A practical detail\ngoverns the attribution window: referrals attributable to an incentive campaign\naccrue for about a year after it runs, so CRV is typically accumulated over a\none-year horizon and referrals beyond it are treated as organic [@kumarCRV2010].\n\n## Unit Economics and the Discounting of a CLV Stream {#sec-clv-unit-econ}\n\nWe close the production thread of @sec-clv-production with three quantitative\ndemonstrations: the LTV:CAC and payback dashboard, the net-revenue-retention waterfall,\nand a discounting and horizon sensitivity analysis that quantifies the chapter's opening\nclaim that roughly half the asset sits beyond the first year.\n\n@tbl-clv-unit-econ computes the board-level ratios per acquisition channel from simulated\nchannel economics, using the geometric LTV of @eq-clv-naive (here with $r=0$ for\ntransparency).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchannels <- tribble(\n  ~channel,       ~cac, ~m_month, ~churn,\n  \"Organic\",        20,       18,   0.03,\n  \"Paid Search\",    95,       20,   0.06,\n  \"Social\",        140,       16,   0.09,\n  \"Affiliate\",      60,       14,   0.05)\n\nunit <- channels |>\n  mutate(ltv        = m_month / churn,             # geometric LTV, r = 0\n         ltv_cac    = round(ltv / cac, 2),\n         payback_mo = round(cac / m_month, 1))\n```\n:::\n\n\n\n::: {#tbl-clv-unit-econ .cell layout-align=\"center\" tbl-cap='Unit economics by acquisition channel. Organic acquisition is wildly efficient; the Social channel, with an LTV:CAC near 1, barely recovers its acquisition cost and would be a candidate to cut or rework.'}\n::: {.cell-output-display}\n\n\n|Channel     | CAC| Margin/mo| Churn| LTV| LTV:CAC| Payback (mo)|\n|:-----------|---:|---------:|-----:|---:|-------:|------------:|\n|Organic     |  20|        18|  0.03| 600|   30.00|          1.1|\n|Paid Search |  95|        20|  0.06| 333|    3.51|          4.8|\n|Social      | 140|        16|  0.09| 178|    1.27|          8.8|\n|Affiliate   |  60|        14|  0.05| 280|    4.67|          4.3|\n\n\n:::\n:::\n\n\n@tbl-clv-unit-econ makes the resource-allocation logic immediate: the Social channel,\nwith an LTV:CAC ratio near $1{:}1$ and an payback of nearly nine months, barely earns\nback its acquisition cost and is the first candidate for rework, while Organic at $30{:}1$\nis so efficient it likely signals under-investment in scaling it.\n\nNext we render the gross- and net-revenue-retention decomposition of @sec-clv-saas-metrics\nas a waterfall in @fig-clv-nrr, showing how expansion revenue pushes net retention above\n100% even as gross retention leaks below it.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstart_mrr   <- 100\nchurn       <- -5\ncontraction <- -3\nexpansion   <- 15\ngrr <- (start_mrr + churn + contraction) / start_mrr\nnrr <- (start_mrr + churn + contraction + expansion) / start_mrr\n\nwf <- tibble(\n  step  = factor(c(\"Start MRR\", \"Churn\", \"Contraction\", \"Expansion\", \"End MRR\"),\n                 levels = c(\"Start MRR\", \"Churn\", \"Contraction\",\n                            \"Expansion\", \"End MRR\")),\n  delta = c(start_mrr, churn, contraction, expansion, NA)) |>\n  mutate(end   = c(start_mrr, cumsum(delta[1:4])[-1], NA),\n         end   = ifelse(step == \"End MRR\", cumsum(delta[1:4]), end),\n         start = lag(end, default = 0),\n         start = ifelse(step %in% c(\"Start MRR\", \"End MRR\"), 0, start),\n         end   = ifelse(step %in% c(\"Start MRR\", \"End MRR\"),\n                        ifelse(step == \"Start MRR\", start_mrr,\n                               start_mrr + churn + contraction + expansion), end),\n         fill  = case_when(step %in% c(\"Start MRR\", \"End MRR\") ~ \"total\",\n                           delta >= 0 ~ \"gain\", TRUE ~ \"loss\"))\n\nggplot(wf, aes(step, fill = fill)) +\n  geom_rect(aes(xmin = as.numeric(step) - 0.4, xmax = as.numeric(step) + 0.4,\n                ymin = pmin(start, end), ymax = pmax(start, end))) +\n  scale_fill_manual(values = c(total = \"#4e79a7\", gain = \"#59a14f\",\n                               loss = \"#e15759\"), guide = \"none\") +\n  labs(x = NULL, y = \"MRR ($000s)\",\n       subtitle = sprintf(\"GRR = %.0f%%   |   NRR = %.0f%%\",\n                          100 * grr, 100 * nrr)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Net revenue retention waterfall. Starting MRR loses churn and contraction (GRR falls below 100%) but gains expansion, lifting NRR above 100%: the base grows with no new logos.](13-clv_files/figure-html/fig-clv-nrr-1.png){#fig-clv-nrr fig-align='center' width=85%}\n:::\n:::\n\n\n@fig-clv-nrr shows GRR at 92% (pure leakage from churn and contraction) but NRR at 107%,\nbecause expansion of \\$15k outpaces the \\$8k of losses. A subscription business with this\nprofile grows 7% a year on its existing base alone.\n\nFinally, @tbl-clv-dcf tabulates discounted CLV across discount rates and horizons for a\nfixed retention curve, quantifying how much value lies beyond the first year and how much\ndiscounting and horizon choice move the number.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nS_curve <- 0.85^(0:60)   # monthly retention curve, 15% monthly churn\nm       <- 100           # monthly margin\n\ngrid <- expand_grid(r_annual = c(0, 0.05, 0.10, 0.15),\n                    N = c(12, 24, 60)) |>\n  rowwise() |>\n  mutate(clv = round(sum(m * S_curve[1:(N + 1)] /\n                           (1 + r_annual / 12)^(0:N)), 0)) |>\n  ungroup()\n\nfrac_beyond_y1 <- 1 - sum(m * S_curve[1:13]) / sum(m * S_curve)\n```\n:::\n\n\n\n::: {#tbl-clv-dcf .cell layout-align=\"center\" tbl-cap='Discounted CLV ($) by annual discount rate and horizon for a fixed monthly retention curve. The horizon matters more than the discount rate at these parameters; lengthening from 12 to 60 months adds more value than any plausible change in r removes.'}\n::: {.cell-output-display}\n\n\n| r (annual)| N=12| N=24| N=60|\n|----------:|----:|----:|----:|\n|       0.00|  586|  655|  667|\n|       0.05|  577|  641|  651|\n|       0.10|  568|  628|  637|\n|       0.15|  559|  615|  623|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Fraction of (undiscounted) lifetime value beyond month 12: \",\n    round(frac_beyond_y1, 3), \"\\n\", sep = \"\")\n#> Fraction of (undiscounted) lifetime value beyond month 12: 0.121\n```\n:::\n\n\n@tbl-clv-dcf separates the two levers. Moving the horizon from 12 to 60 months adds far\nmore value than any plausible discount rate removes, which is the quantitative form of the\nwarning against truncating the horizon at one year. At a steeper retention curve the\nfraction of value beyond year one would be larger still; the \"roughly half the asset\"\nheuristic in the chapter's opening corresponds to a flatter, more loyal customer base than\nthis illustrative 15%-monthly-churn curve.\n\n## Identification and What Breaks It {#sec-clv-identification}\n\nCLV is arithmetically simple and inferentially treacherous. Every term in\n@eq-clv-general is a forecast, and the headline number compounds their errors. The\nrecurring failure modes are worth stating as assumptions whose violation is\ndiagnostic, and each maps onto a production pitfall from @sec-clv-pitfalls.\n\n*Constant-retention bias.* Assuming a fixed $\\rho$ (@eq-clv-geometric, @eq-clv-naive)\nwhen the true process is heterogeneous understates the value of long-tenured customers\nand overstates churn for survivors, because it misreads population sorting as individual\nduration dependence. The sBG model (@sec-clv-sbg) exists precisely to correct this; the\nsymptom is a geometric model that systematically underpredicts late-tenure survival.\n\n*Horizon and discounting.* Because a large share of lifetime value sits beyond the\nfirst year (@tbl-clv-dcf), the choice of $N$ and $r$ is not a rounding decision. The\ninfinite-horizon shortcut in @eq-clv-geometric requires $\\rho < 1+r$ and a genuinely\nstationary margin; the Gordon-style terminal value used in valuation work is valid\nonly when the growth rate is strictly below the discount rate. A short horizon\ntruncates the asset; an over-long one extrapolates a calibration-window model past\nits evidence (@fig-retention-projected).\n\n*Endogenous marketing.* The marketing cost $\\text{MC}_{ij}$ is not exogenous: firms\ndirect more spend at customers they already believe are valuable. Treating observed\n$\\text{MC}$ and observed retention as if the latter were the causal response to the\nformer conflates targeting with treatment effect, biasing the implied return on\nretention spending. Clean estimates of how marketing *moves* CLV require experimental\nor quasi-experimental variation, not the historical correlation between spend and\nvalue, which is the program of @sec-clv-causal.\n\n*Aggregation and the non-contractual problem.* In non-contractual settings (retail,\ne-commerce) churn is never observed: a customer who has not purchased recently may\nhave defected or may simply be between trips. Disentangling \"dead\" from \"dormant\"\nrequires a latent-attrition model such as the Pareto/NBD [@paretonbd1987], whose\nrecency-frequency sufficient statistics carry exactly the information needed to infer\nthe probability a customer is still alive (@fig-clv-palive). Ignoring latent attrition\nand counting all lapsed customers as retained inflates customer equity.\n\n*Survivorship and leakage.* Two data-engineering errors mimic good news. Fitting a\nretention curve only on customers who survived to the present inflates retention\n(survivorship bias); building features from inside the prediction window inflates\noffline accuracy that then collapses in production (look-ahead leakage). Both are\ndefeated only by strict temporal discipline in constructing the training data.\n\n*Heterogeneous response and structural drivers.* Reduced-form component models give\nper-customer forecasts but say little about *why* value differs or how it responds to\nprices and competition. Structural approaches embed CLV in a model of consumer\nutility: @sunder2016measuring derive brand- and category-level CLV in consumer\npackaged goods by accounting for multiple-discreteness (consumers buy several brands),\nbrand-switching, and a latent budget constraint inferred from transaction data alone\nvia Bayesian estimation, and show that ignoring the budget constraint, as simpler\nheuristics do, mismeasures value and the response to asymmetric price changes. The\ngain in behavioral fidelity is bought with strong functional-form assumptions; the\ntrade-off between the two traditions in @tbl-clv-approaches has no free lunch.\n\nThe financial relevance of getting these right is direct: aggregated CLV is *customer\nequity*, and the demonstrated link from customer equity to firm value\n[@gupta2006modeling; @kumar2010; @kumarshah2009] is the bridge from this chapter to the\nmarketing-finance interface developed in @sec-marketing-finance.\n\n## Key Takeaways {#sec-clv-takeaways}\n\n- CLV (@eq-clv-general) treats a customer as a forward-looking asset: the discounted\n  present value of future margin from their purchases net of the marketing cost of\n  retaining them. Aggregated across customers it is *customer equity*, which tracks firm\n  value.\n- The contractual versus non-contractual and discrete versus continuous taxonomy\n  (@tbl-clv-taxonomy) decides which model class is admissible before any estimation begins.\n- The naive production formula (@eq-clv-naive), ARPA times margin over churn, is the\n  industry default and is biased in predictable ways: it understates survivor value,\n  explodes as churn approaches zero, and ignores discounting and expansion revenue.\n- The constant-retention shortcut is biased whenever customers are heterogeneous;\n  observed aggregate retention rises with tenure because of *sorting*, not increasing\n  individual loyalty. The shifted-beta-geometric model (@eq-sbg-survivor) captures this\n  with a two-parameter Beta mixture and estimates cleanly from sparse cohort data.\n- In non-contractual settings, buy-till-you-die models (Pareto/NBD, BG/NBD) plus the\n  Gamma-Gamma spend model infer a probability-alive and a monetary pLTV from\n  recency-frequency-monetary data alone (@fig-clv-palive), and agree across the\n  `CLVTools` and `BTYD` implementations.\n- The machine-learning frontier decomposes pLTV into a churn head and a spend head\n  (two-stage, or a joint ZILN loss), trading the parsimony of probability models for\n  covariates and nonlinearity; \"methods matter\" only insofar as accuracy gains move\n  campaign profit.\n- Acting on CLV requires *uplift*, not level: targeting the highest-risk or highest-value\n  customers can be futile (@ascarza2018futility) when risk and persuadability are\n  uncorrelated.\n- The hard part is identification, not arithmetic: constant-retention bias, horizon and\n  discounting choices, endogenous marketing spend, survivorship and leakage, and latent\n  attrition in non-contractual settings each bias the headline number in a predictable\n  direction.\n",
    "supporting": [
      "13-clv_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}